(case "ls1 a LIST-state snapshot crosses mid-growth — the held list is immutable while the state keeps growing, sum and final length both pinned"
  (input  (do
            (effect E (op push (-> Int64 Int64)) (op snap (-> (List Int64))) (op len (-> Int64)))
            (def (sum-at (: xs (List Int64)) (: i Int64) (: acc Int64))
              (match (List.at xs i)
                ((Some v) (sum-at xs (+ i 1) (+ acc v)))
                ((None) acc)))
            (def (main (: n Int64))
              (handle E (list n)
                ((push (v) xs (resume v (List.push xs v)))
                 (snap () xs (resume xs xs))
                 (len () xs (resume (List.len xs) xs)))
                (do (E.push 7)
                    (let ((s1 (E.snap)))
                      (do (E.push 9)
                          (+ (sum-at s1 0 0) (* 100 (E.len))))))))
            (export main)))
  (call   main (: 5 Int64)) (output (: 312 Int64))
  (call   main (: 0 Int64)) (output (: 307 Int64))
  (call   main (: -3 Int64)) (output (: 304 Int64)))
