(case "sn1 a snapshot op resumes the WHOLE tuple state as a value — the body destructures the live pair after mixed bumps"
  (input  (do
            (effect E (op bumpa (-> Int64)) (op bumpb (-> Int64)) (op snap (-> (Tuple Int64 Int64))))
            (def (main (: n Int64))
              (handle E (tuple n 10)
                ((bumpa () st (match st ((tuple a b) (resume a (tuple (+ a 1) b)))))
                 (bumpb () st (match st ((tuple a b) (resume b (tuple a (+ b 5))))))
                 (snap () st (resume st st)))
                (do (E.bumpa) (E.bumpa) (E.bumpb)
                    (match (E.snap)
                      ((tuple a b) (+ (* 100 a) b))))))
            (export main)))
  (call   main (: 5 Int64)) (output (: 715 Int64))
  (call   main (: 0 Int64)) (output (: 215 Int64))
  (call   main (: -3 Int64)) (output (: -85 Int64)))
