(case "sn3 the snapshot crosses to a DEF helper — the crossed state tuple is consumed by a function parameter, not a body match"
  (input  (do
            (effect E (op bumpa (-> Int64)) (op bumpb (-> Int64)) (op snap (-> (Tuple Int64 Int64))))
            (def (mix (: p (Tuple Int64 Int64)))
              (match p ((tuple a b) (+ (* 2 a) b))))
            (def (main (: n Int64))
              (handle E (tuple n 10)
                ((bumpa () st (match st ((tuple a b) (resume a (tuple (+ a 1) b)))))
                 (bumpb () st (match st ((tuple a b) (resume b (tuple a (+ b 5))))))
                 (snap () st (resume st st)))
                (do (E.bumpa) (E.bumpb) (mix (E.snap)))))
            (export main)))
  (call   main (: 5 Int64)) (output (: 27 Int64))
  (call   main (: 0 Int64)) (output (: 17 Int64))
  (call   main (: -4 Int64)) (output (: 9 Int64)))
