(case "pas1 PASCAL'S TRIANGLE row advanced through effect state — next rebuilds the row by a recursive pairwise-sum answering the row total (a power of two), coef reads the SEED-KEYED binomial coefficient mid-descent and after, and the out-of-range read answers -1"
  (input  (do
            (effect P
              (op next (-> Int64))
              (op coef (-> Int64 Int64)))
            (def (getat (: xs (List Int64)) (: i Int64))
              (match (List.at xs i) ((Some v) v) ((None u) 0)))
            (def (pairs (: xs (List Int64)) (: i Int64) (: acc (List Int64)))
              (if (< i (- (List.len xs) 1))
                  (pairs xs (+ i 1) (List.push acc (+ (getat xs i) (getat xs (+ i 1)))))
                  (List.push acc 1)))
            (def (sums (: xs (List Int64)) (: i Int64) (: acc Int64))
              (if (< i (List.len xs))
                  (sums xs (+ i 1) (+ acc (getat xs i)))
                  acc))
            (def (main (: n Int64))
              (handle P (: (list 1) (List Int64))
                ((next () st
                  (match (pairs st 0 (: (list 1) (List Int64)))
                    (r2 (resume (sums r2 0 0) r2))))
                 (coef (k) st
                  (if (< k (List.len st))
                      (resume (getat st k) st)
                      (resume -1 st))))
                (let ((a (P.next)))
                  (let ((b (P.next)))
                    (let ((c (P.coef (+ (% n 3) 1))))
                      (let ((d (P.next)))
                        (let ((e (P.next)))
                          (let ((f (P.coef (+ (% n 3) 1))))
                            (let ((g (P.coef 7)))
                              (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 a) b)) c)) d)) e)) f)) g))))))))))
            (export main)))
  (call   main (: 10 Int64)) (output (: 2040108160599 Int64))
  (call   main (: 0 Int64)) (output (: 2040208160399 Int64)))
