(case "gd2 pure guards on SUM-PAYLOAD binders — guarded and unguarded twins of each variant arm, five paths input-reachable"
  (input  (do
            (type Mode (A) (B Int64) (C Int64 Int64))
            (effect E (op mode (-> Mode)) (op probe (-> Int64)))
            (def (main (: n Int64))
              (handle E n
                ((mode () s (resume (match (% s 3)
                                      (0 (A))
                                      (1 (B s))
                                      (_ (C s s)))
                                    (+ s 1)))
                 (probe () s (resume s s)))
                (+ (* 10 (match (E.mode)
                           ((guard (B x) (> x 3)) (+ 100 x))
                           ((B x) (+ 200 x))
                           ((guard (C x y) (> (+ x y) 10)) (+ 300 (+ x y)))
                           ((C x y) (+ 400 (+ x y)))
                           ((A) 7)))
                   (- (E.probe) n))))
            (export main)))
  (call   main (: 7 Int64)) (output (: 1071 Int64))
  (call   main (: 1 Int64)) (output (: 2011 Int64))
  (call   main (: 8 Int64)) (output (: 3161 Int64))
  (call   main (: 2 Int64)) (output (: 4041 Int64))
  (call   main (: 0 Int64)) (output (: 71 Int64)))
