(case "rrl1 a REFILL-ON-READ rate limiter — every take first refills the bucket by the seed rate clamped at capacity ten then serves or answers the negated shortfall (tokens kept on refusal), and the faster drip keeps the refusals shallow while the slow one starves deeper on the same request stream"
  (input  (do
            (effect R (op take (-> Int64 Int64)))
            (def (main (: n Int64))
              (handle R (: 5 Int64)
                ((take (c) tokens
                  (if (< 10 (+ tokens (+ (% n 3) 1)))
                      (if (< 10 c)
                          (resume (- 10 c) 10)
                          (resume c (- 10 c)))
                      (if (< (+ tokens (+ (% n 3) 1)) c)
                          (resume (- (+ tokens (+ (% n 3) 1)) c) (+ tokens (+ (% n 3) 1)))
                          (resume c (- (+ tokens (+ (% n 3) 1)) c))))))
                (let ((a (R.take 4)))
                  (let ((b (R.take 8)))
                    (let ((c (R.take 3)))
                      (let ((d (R.take 9)))
                        (let ((e (R.take 2)))
                          (let ((f (R.take 0)))
                            (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 a) b)) c)) d)) e)) f)))))))))
            (export main)))
  (call   main (: 10 Int64)) (output (: 39702970200 Int64))
  (call   main (: 0 Int64)) (output (: 39502930200 Int64)))
