(case "iw1 an interleaved two-map build: alternating inserts leave both tries correct"
  (input  (do
            (def (weave (: i Int64) (: a (Map Int64 Int64)) (: b (Map Int64 Int64)))
              (if (= i 0) (tuple a b)
                (if (= (% i 2) 0)
                    (weave (- i 1) (Map.insert a i (* i 2)) b)
                    (weave (- i 1) a (Map.insert b i (* i 3))))))
            (def (main (: n Int64))
              (match (weave n Map.empty Map.empty)
                ((tuple a b)
                  (+ (* 1000 (Map.len a))
                     (+ (* 10 (Map.len b))
                        (+ (match (Map.lookup a 20) ((Some v) (if (= v 40) 1 0)) ((None _u) -1))
                           (match (Map.lookup b 21) ((Some v) (if (= v 63) 1 0)) ((None _u) -1))))))))
            (export main)))
  (call   main (: 40 Int64)) (output (: 20202 Int64)))
