//! A minimal reducer GUEST component — the host driver's end-to-end fixture (`design/cadenza-platform.md`
//! §3). It implements the `reducer-world`'s `guest` export and calls the `identity` host import, so
//! instantiating and driving it through the host proves the whole path: the host provides the imports, the
//! guest folds an event and returns a `step`, and the host decodes it.
//!
//! Behaviour is a deliberate echo, shaped so a single driven `on-message` verifies both directions at once:
//!   - it emits exactly one request on the SAME contract carrying the SAME payload (the event round-trips
//!     out through the conversion layer), and
//!   - it sets that request's correlation token to the reducer's OWN id, read from the `identity` import (so
//!     a value the HOST supplied flows through the guest and back — proof the import is wired, not stubbed).
//! `on-response` and `on-notification` are inert (`continue`, no requests): the fixture drives the message
//! path, and the other two entry points exist only to satisfy the export.
//!
//! `no_std` + `alloc` with talc as the allocator (same discipline as cdz-nfc / cdz-runtime) so the component
//! imports only the `cadenza:platform` interfaces of its world — no wasi — and instantiates against the
//! host's linker alone.
#![no_std]

extern crate alloc;

use alloc::vec;
use alloc::vec::Vec;

#[cfg(target_arch = "wasm32")]
mod allocator;

// Generated by `cargo component build` from the shared `../../wit/world.wit` (world `reducer-world`).
#[allow(warnings)]
mod bindings;

use bindings::cadenza::platform::identity;
// The event envelopes and the `step` are the guest export's types; `request`/`outcome` are the shared
// `reducer` interface's types that `step` is built from.
use bindings::cadenza::platform::reducer::{Outcome, Request};
use bindings::exports::cadenza::platform::guest::{Guest, Message, Notification, Response, Step};

struct Component;

impl Guest for Component {
    fn on_message(msg: Message) -> Step {
        // Echo the event straight back out — same contract, same payload — and stamp the request's token with
        // the reducer's own id (read from the host `identity` import), so driving this once proves the event
        // conversion round-trips AND the host import is wired.
        Step {
            requests: vec![Request {
                contract: msg.contract,
                payload: msg.payload,
                token: identity::id(),
                deadline_nanos: None,
            }],
            outcome: Outcome::Continue,
        }
    }

    fn on_response(_resp: Response) -> Step {
        Step {
            requests: Vec::new(),
            outcome: Outcome::Continue,
        }
    }

    fn on_notification(_note: Notification) -> Step {
        Step {
            requests: Vec::new(),
            outcome: Outcome::Continue,
        }
    }
}

bindings::export!(Component with_types_in bindings);
