(case "s1 split a multibyte rope into slice parts and REJOIN — content round-trips exactly"
  (input  (do
            (def (collect (: s String) (: i Int64) (: n Int64) (: start Int64) (: acc (List String)))
              (if (< i n)
                  (match (String.at s i)
                    ((Some c)
                      (if (= c ",")
                          (match (String.slice s start i)
                            ((Some piece) (collect s (+ i 1) n (+ i 1) (List.push acc piece)))
                            ((None _u) acc))
                          (collect s (+ i 1) n start acc)))
                    ((None _u) acc))
                  (match (String.slice s start n)
                    ((Some piece) (List.push acc piece))
                    ((None _u) acc))))
            (def (rejoin (: parts (List String)) (: i Int64) (: acc String))
              (if (< i (List.len parts))
                  (rejoin parts (+ i 1)
                    (String.concat acc (match (List.at parts i) ((Some p) p) ((None _u) ""))))
                  acc))
            (def (main (: k Int64))
              (let ((s (String.concat "aé,b" (String.concat ",🎵" ",z"))))
                (let ((parts (collect s 0 (String.scalar-len s) 0 (list))))
                  (let ((joined (rejoin parts 0 "")))
                    (+ (List.len parts)
                       (+ (* 10 (String.byte-len joined))
                          (* 1000 (if (= joined "aéb🎵z") 1 0))))))))
            (export main)))
  (call   main (: 0 Int64)) (output (: 1094 Int64)))
