(case "a try short-circuit inside a fused-match arm exits the enclosing Option function per-branch"
  (input  (do
            (type Sz (Hi Int64) (Lo Int64))
            (def (mk x) (if (> x 5) (Hi x) (Lo x)))
            (def (pick (: xs (List Int64)) (: k Int64))
              (match (mk k)
                ((Hi h) (Some (* (try (List.at xs h)) 10)))
                ((Lo w) (Some (+ (try (List.at xs w)) 100)))))
            (def (main (: k Int64))
              (match (pick (list 5 6 7) k)
                ((Some v) v)
                ((None u) -1)))
            (export main)))
  (call   main (: 2 Int64)) (output (: 107 Int64))
  (call   main (: 9 Int64)) (output (: -1 Int64)))
