(case "v62b1 record-face repro: two record-stored closures share ONE firing"
  (input  (do
            (effect io (op get (-> Unit Int64)))
            (def (mk)
              (host (io)
                (let ((v (io.get unit)))
                  (record (f (fn ((: x Int64)) (+ v x)))
                          (g (fn ((: x Int64)) (* v x)))))))
            (def (main (: k Int64))
              (let ((r (mk)))
                (+ ((. r f) 10) ((. r g) 100))))
            (export main)))
  (host-responses (respond io.get (: 21 Int64)))
  (host-calls (call io.get))
  (call   main (: 0 Int64)) (output (: 2131 Int64)))
