(case "v62b2 nested-record face: closures in an INNER record of an outer record share one firing"
  (input  (do
            (effect io (op get (-> Unit Int64)))
            (def (mk)
              (host (io)
                (let ((v (io.get unit)))
                  (record (tag 1)
                          (fns (record (f (fn ((: x Int64)) (+ v x)))
                                       (g (fn ((: x Int64)) (* v x)))))))))
            (def (main (: k Int64))
              (let ((r (mk)))
                (+ ((. (. r fns) f) 10) ((. (. r fns) g) 100))))
            (export main)))
  (host-responses (respond io.get (: 21 Int64)))
  (host-calls (call io.get))
  (call   main (: 0 Int64)) (output (: 2131 Int64)))
