(case "v62b3 mixed face: a record holding one closure AND a direct value, both read"
  (input  (do
            (effect io (op get (-> Unit Int64)))
            (def (mk)
              (host (io)
                (let ((v (io.get unit)))
                  (record (raw v)
                          (f (fn ((: x Int64)) (+ v x)))))))
            (def (main (: k Int64))
              (let ((r (mk)))
                (+ (. r raw) (* 100 ((. r f) 10)))))
            (export main)))
  (host-responses (respond io.get (: 21 Int64)))
  (host-calls (call io.get))
  (call   main (: 0 Int64)) (output (: 3121 Int64)))
