(case "un1 an UNDO stack: snapshots of an evolving trie restore any prior version intact"
  (input  (do
            (def (evolve (: i Int64) (: m (Map Int64 Int64)) (: hist (List (Map Int64 Int64))))
              (if (= i 0) (tuple m hist)
                (let ((m2 (Map.insert m i (* i 7))))
                  (evolve (- i 1) m2 (List.push hist m2)))))
            (def (main (: n Int64))
              (match (evolve n Map.empty (list))
                ((tuple final hist)
                  (+ (* 1000 (Map.len final))
                     (+ (* 10 (match (List.at hist 4) ((Some snap) (Map.len snap)) ((None _u) -1)))
                        (match (List.at hist 4)
                          ((Some snap) (match (Map.lookup snap 20) ((Some _v) 0) ((None _u) 1)))
                          ((None _u) -1)))))))
            (export main)))
  (call   main (: 25 Int64)) (output (: 25051 Int64)))
