(case "orq1 an ORDER-BOOK spread tracker — bid raises the best bid and ask lowers the best ask (both answering the spread or -1 while a side is empty), a CROSSED book resets both sides answering zero, and the seed only shifts the opening bid so the first spread differs while the tightening ladder and the cross land identically"
  (input  (do
            (effect O
              (op bid (-> Int64 Int64))
              (op ask (-> Int64 Int64)))
            (def (spread-of (: bb Int64) (: ba Int64))
              (if (= bb 0) -1 (if (= ba 0) -1 (- ba bb))))
            (def (main (: n Int64))
              (handle O (tuple (: 0 Int64) (: 0 Int64))
                ((bid (p) st
                  (match st
                    ((tuple bb ba)
                      (if (< bb p)
                          (if (= ba 0)
                              (resume (spread-of p ba) (tuple p ba))
                              (if (< p ba)
                                  (resume (spread-of p ba) (tuple p ba))
                                  (resume 0 (tuple 0 0))))
                          (resume (spread-of bb ba) (tuple bb ba))))))
                 (ask (p) st
                  (match st
                    ((tuple bb ba)
                      (if (= ba 0)
                          (if (< bb p)
                              (resume (spread-of bb p) (tuple bb p))
                              (resume 0 (tuple 0 0)))
                          (if (< p ba)
                              (if (< bb p)
                                  (resume (spread-of bb p) (tuple bb p))
                                  (resume 0 (tuple 0 0)))
                              (resume (spread-of bb ba) (tuple bb ba))))))))
                (let ((a (O.bid (+ (% n 4) 5))))
                  (let ((b (O.ask 12)))
                    (let ((c (O.bid 9)))
                      (let ((d (O.ask 10)))
                        (let ((e (O.bid 11)))
                          (let ((f (O.ask 15)))
                            (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 a) b)) c)) d)) e)) f)))))))))
            (export main)))
  (call   main (: 10 Int64)) (output (: -9496990001 Int64))
  (call   main (: 0 Int64)) (output (: -9296990001 Int64)))
