(case "ldg1 a LEADING-DIGIT counter — feed strips each value to its leading digit through a recursive divide-down callee, a hit on the seed-wanted digit answers digit*10 plus the running hit count while a miss answers the bare digit, and the two seeds hunt DIFFERENT digits through one shared stream"
  (input  (do
            (effect G
              (op feed (-> Int64 Int64))
              (op tally (-> Int64)))
            (def (lead (: v Int64))
              (if (< v 10) v (lead (/ v 10))))
            (def (main (: n Int64))
              (handle G (: 0 Int64)
                ((feed (v) hits
                  (if (= (lead v) (+ (% n 4) 1))
                      (resume (+ (* (lead v) 10) (+ hits 1)) (+ hits 1))
                      (resume (lead v) hits)))
                 (tally () hits (resume hits hits)))
                (let ((a (G.feed 347)))
                  (let ((b (G.feed 19)))
                    (let ((c (G.tally)))
                      (let ((d (G.feed 3)))
                        (let ((e (G.feed 3124)))
                          (let ((f (G.feed 88)))
                            (let ((g (G.tally)))
                              (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 a) b)) c)) d)) e)) f)) g))))))))))
            (export main)))
  (call   main (: 10 Int64)) (output (: 31010132330803 Int64))
  (call   main (: 0 Int64)) (output (: 3110103030801 Int64)))
