(case "ddp1 a FIRST-TIME dedup stream over a Map of seen-counts — a first observation echoes the value, a repeat answers the negated repeat count, and the seed COLLIDES a computed key with a literal so the two runs disagree on which draws are repeats at all"
  (input  (do
            (effect D
              (op obs (-> Int64 Int64))
              (op kinds (-> Int64)))
            (def (main (: n Int64))
              (handle D (: (map) (Map Int64 Int64))
                ((obs (v) m
                  (match (Map.lookup m v)
                    ((Some c)
                      (resume (- 0 (+ c 1)) (Map.insert m v (+ c 1))))
                    ((None)
                      (resume v (Map.insert m v 1)))))
                 (kinds () m (resume (Map.len m) m)))
                (let ((a (D.obs (+ n 3))))
                  (let ((b (D.obs 13)))
                    (let ((c (D.obs 7)))
                      (let ((d (D.obs (+ n 3))))
                        (let ((e (D.obs 13)))
                          (let ((f (D.obs 7)))
                            (let ((g (D.kinds)))
                              (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 a) b)) c)) d)) e)) f)) g))))))))))
            (export main)))
  (call   main (: 10 Int64)) (output (: 12980696959802 Int64))
  (call   main (: 0 Int64)) (output (: 3130697979803 Int64)))
