(case "sky1 SKYLINE visibility with demolition — feeds answer whether the building tops all before it, demolish removes EVERY copy of the max forcing the threshold to recompute from survivors"
  (input  (do
            (effect S
              (op feed (-> Int64 Int64))
              (op demolish (-> Int64)))
            (def (maxl (: xs (List Int64)) (: i Int64) (: best Int64))
              (match (List.at xs i)
                ((Some v) (maxl xs (+ i 1) (if (> v best) v best)))
                ((None u) best)))
            (def (drop-eq (: xs (List Int64)) (: i Int64) (: m Int64) (: acc (List Int64)))
              (match (List.at xs i)
                ((Some v) (drop-eq xs (+ i 1) m (if (= v m) acc (List.push acc v))))
                ((None u) acc)))
            (def (main (: n Int64))
              (handle S (: (list) (List Int64))
                ((feed (h) hs
                  (let ((vis (if (> h (maxl hs 0 -1)) 1 0)))
                    (let ((h2 (List.push hs h)))
                      (resume (+ (* vis 10) (List.len h2)) h2))))
                 (demolish () hs
                  (let ((m (maxl hs 0 -1)))
                    (let ((h2 (drop-eq hs 0 m (: (list) (List Int64)))))
                      (resume (maxl h2 0 0) h2)))))
                (let ((a (S.feed 3)))
                  (let ((b (S.feed n)))
                    (let ((c (S.feed 4)))
                      (let ((d (S.demolish)))
                        (let ((e (S.feed 5)))
                          (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 a) b)) c)) d)) e))))))))
            (export main)))
  (call   main (: 7 Int64)) (output (: 1112030413 Int64))
  (call   main (: 2 Int64)) (output (: 1102130313 Int64)))
