(case "dcy1 a FREQUENCY-DECAY tracker — every observe first HALVES all counts dropping the zeroed rows, then bumps the observed key by four; the whole-map transform and the single-key update compose in one arm"
  (input  (do
            (effect S (op obs (-> Int64 Int64)))
            (def (decay (: src (List (Tuple Int64 Int64))) (: i Int64) (: acc (Map Int64 Int64)))
              (match (List.at src i)
                ((Some p) (match p
                            ((tuple k v)
                              (decay src (+ i 1)
                                     (if (> (/ v 2) 0) (Map.insert acc k (/ v 2)) acc)))))
                ((None u) acc)))
            (def (main (: n Int64))
              (handle S (: Map.empty (Map Int64 Int64))
                ((obs (k) m
                  (let ((d (decay (Map.to-list m) 0 Map.empty)))
                    (let ((c2 (+ (match (Map.lookup d k) ((Some x) x) ((None u) 0)) 4)))
                      (let ((m2 (Map.insert d k c2)))
                        (resume (+ (* 100 (Map.len m2)) c2) m2))))))
                (let ((a (S.obs n)))
                  (let ((b (S.obs n)))
                    (let ((c (S.obs 2)))
                      (let ((d (S.obs n)))
                        (+ (* 1000 (+ (* 1000 (+ (* 1000 a) b)) c)) d)))))))
            (export main)))
  (call   main (: 1 Int64)) (output (: 104106204205 Int64))
  (call   main (: 2 Int64)) (output (: 104106107107 Int64)))
