(case "cbk1 a CIRCUIT-BREAKER state machine — two failures trip it open, open requests answer the -1 sentinel while a cooldown counts down to half-open, the half-open probe either restores closed on success or re-trips on failure, and the final draw reads the mode"
  (input  (do
            (effect C
              (op req (-> Int64 Int64))
              (op mode (-> Int64)))
            (def (main (: n Int64))
              (handle C (tuple (: 0 Int64) (: 0 Int64) (: 0 Int64))
                ((req (v) st
                  (match st
                    ((tuple m fails cd)
                      (if (= m 1)
                          (if (= cd 1)
                              (resume -1 (tuple 2 fails 0))
                              (resume -1 (tuple 1 fails (- cd 1))))
                          (if (= m 2)
                              (if (< v 0)
                                  (resume 0 (tuple 1 fails 2))
                                  (resume v (tuple 0 0 0)))
                              (if (< v 0)
                                  (if (< 0 fails)
                                      (resume 0 (tuple 1 (+ fails 1) 2))
                                      (resume 0 (tuple 0 (+ fails 1) 0)))
                                  (resume v (tuple 0 fails 0))))))))
                 (mode () st
                  (match st ((tuple m fails cd) (resume m st)))))
                (let ((a (C.req (- n 6))))
                  (let ((b (C.req -3)))
                    (let ((c (C.req -2)))
                      (let ((d (C.req 5)))
                        (let ((e (C.req (- n 1))))
                          (let ((f (C.req 7)))
                            (let ((g (C.mode)))
                              (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 a) b)) c)) d)) e)) f)) g))))))))))
            (export main)))
  (call   main (: 10 Int64)) (output (: 3999998990700 Int64))
  (call   main (: 0 Int64)) (output (: -101000099 Int64)))
