(case "med1 a RUNNING MEDIAN over a sorted-insert list — each add splices the value at its recursive-scan insertion point and answers the live median (middle element odd, floor-averaged pair even), and the seed shifts two of the five inserts across the median boundary"
  (input  (do
            (effect M (op add (-> Int64 Int64)))
            (def (getat (: xs (List Int64)) (: i Int64))
              (match (List.at xs i) ((Some v) v) ((None u) 0)))
            (def (inspos (: xs (List Int64)) (: v Int64) (: i Int64))
              (if (< i (List.len xs))
                  (if (< (getat xs i) v)
                      (inspos xs v (+ i 1))
                      i)
                  i))
            (def (splice (: xs (List Int64)) (: v Int64) (: at Int64) (: i Int64) (: acc (List Int64)))
              (if (= i at)
                  (splice xs v -1 i (List.push acc v))
                  (if (< i (List.len xs))
                      (splice xs v at (+ i 1) (List.push acc (getat xs i)))
                      acc)))
            (def (median (: xs (List Int64)))
              (let ((m (List.len xs)))
                (if (= (% m 2) 1)
                    (getat xs (/ m 2))
                    (/ (+ (getat xs (- (/ m 2) 1)) (getat xs (/ m 2))) 2))))
            (def (main (: n Int64))
              (handle M (: (list) (List Int64))
                ((add (v) st
                  (let ((s2 (splice st v (inspos st v 0) 0 (: (list) (List Int64)))))
                    (resume (median s2) s2))))
                (let ((a (M.add (+ n 4))))
                  (let ((b (M.add 2)))
                    (let ((c (M.add 9)))
                      (let ((d (M.add (+ n 1))))
                        (let ((e (M.add 6)))
                          (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 a) b)) c)) d)) e))))))))
            (export main)))
  (call   main (: 10 Int64)) (output (: 1408091009 Int64))
  (call   main (: 0 Int64)) (output (: 403040304 Int64)))
