(case "medA control — same arm shape, splice replaced by List.push"
  (input  (do
            (effect M (op add (-> Int64 Int64)))
            (def (getat (: xs (List Int64)) (: i Int64))
              (match (List.at xs i) ((Some v) v) ((None u) 0)))
            (def (median (: xs (List Int64)))
              (let ((m (List.len xs)))
                (if (= (% m 2) 1)
                    (getat xs (/ m 2))
                    (/ (+ (getat xs (- (/ m 2) 1)) (getat xs (/ m 2))) 2))))
            (def (main (: n Int64))
              (handle M (: (list) (List Int64))
                ((add (v) st
                  (let ((s2 (List.push st v)))
                    (resume (median s2) s2))))
                (let ((a (M.add (+ n 4))))
                  (let ((b (M.add 2)))
                    (let ((c (M.add 9)))
                      (let ((d (M.add (+ n 1))))
                        (let ((e (M.add 6)))
                          (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 a) b)) c)) d)) e))))))))
            (export main)))
  (call   main (: 10 Int64)) (output (: 1408090909 Int64))
  (call   main (: 0 Int64)) (output (: 402040404 Int64)))