(case "medB control — the callee's internal let removed, recursive max instead"
  (input  (do
            (effect M (op add (-> Int64 Int64)))
            (def (getat (: xs (List Int64)) (: i Int64))
              (match (List.at xs i) ((Some v) v) ((None u) 0)))
            (def (maxs (: xs (List Int64)) (: i Int64) (: best Int64))
              (if (< i (List.len xs))
                  (maxs xs (+ i 1) (if (< best (getat xs i)) (getat xs i) best))
                  best))
            (def (main (: n Int64))
              (handle M (: (list) (List Int64))
                ((add (v) st
                  (let ((s2 (List.push st v)))
                    (resume (maxs s2 0 -999) s2))))
                (let ((a (M.add (+ n 4))))
                  (let ((b (M.add 2)))
                    (let ((c (M.add 9)))
                      (let ((d (M.add (+ n 1))))
                        (let ((e (M.add 6)))
                          (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 a) b)) c)) d)) e))))))))
            (export main)))
  (call   main (: 10 Int64)) (output (: 1414141414 Int64))
  (call   main (: 0 Int64)) (output (: 404090909 Int64)))