(case "bp1 a BYTES payload inside an arm-built Result — even states Ok-wrap a one-byte frame, the body reads len and first byte"
  (input  (do
            (type BRes (Ok Bytes) (Err))
            (effect E (op step (-> BRes)))
            (def (main (: n Int64))
              (handle E (if (< n 0) (- 0 n) n)
                ((step () s
                  (resume (if (= (% s 2) 0)
                              (BRes.Ok (Bytes.of (list (UInt8.wrap s))))
                              (BRes.Err))
                          (+ s 1))))
                (match (E.step)
                  ((BRes.Ok b) (+ (* 100 (Bytes.len b))
                                  (match (Bytes.at b 0)
                                    ((Some v) (Int64.of v))
                                    ((None) -9))))
                  ((BRes.Err) -1))))
            (export main)))
  (call   main (: 4 Int64)) (output (: 104 Int64))
  (call   main (: 7 Int64)) (output (: -1 Int64)))
