(do
  (effect A (op a (-> Int64)))
  (effect B (op b (-> Int64)))
  (effect C (op c (-> Int64)))
  (effect D (op d (-> Int64)))
  (effect Bail (op bail (-> Int64 Int64)))
  (def (main (: n Int64))
    (handle Bail 0
      ((bail (v) s v))
      (handle A 1 ((a () s (resume s (+ s 1))))
        (handle B 10 ((b () s (resume s (+ s 1))))
          (handle C 100 ((c () s (resume s (+ s 1))))
            (handle D 1000 ((d () s (resume s (+ s 1))))
              (+ (A.a) (+ (B.b) (+ (C.c) (+ (D.d)
                 (if (> n 3) (Bail.bail 7) 50)))))))))))
  (export main))
