(case "mr1 THREE Map.remove GENERATIONS share structure — each ancestor still holds what its descendant removed"
  (input  (do
            (def (lk (: m (Map Int64 Int64)) (: k Int64))
              (match (Map.lookup m k) ((Some v) v) ((None _u) -1)))
            (def (main (: n Int64))
              (let ((a (Map.insert (Map.insert (Map.insert Map.empty 1 n) 2 20) 3 30)))
                (let ((b (Map.remove a 2)))
                  (let ((c (Map.remove b 3)))
                    (+ (* 1000000 (Map.len a))
                       (+ (* 100000 (Map.len b))
                          (+ (* 10000 (Map.len c))
                             (+ (* 1000 (lk a 2))
                                (+ (* 10 (lk b 3)) (lk c 1))))))))))
            (export main)))
  (call   main (: 5 Int64)) (output (: 3230305 Int64))
  (call   main (: 0 Int64)) (output (: 3230300 Int64)))
