//! The INTERIM hand-written Rust checker guest for the reducer-echo end-to-end run
//! (`design/cadenza-platform.md` §9). It implements the `reducer-world`'s `guest` export like reducer-echo,
//! but instead of echoing it CHECKS: the harness names it as a run's `checker`, spawns it after the main run,
//! and delivers the whole observation log as a `check` message. `on_message` proves the wasm-checker
//! plumbing — it verifies (by a byte-substring check, no log decode) that an emitted-request record is
//! present (reducer-echo having echoed => the serialized log contains `emitted`), and emits a `verdict`
//! request carrying a precomputed `Verdict.Verdict({pass, messages})` value; the itest binary exits 0 on
//! pass / nonzero on fail.
//!
//! DELIBERATELY MINIMAL (operator decision, 2026-08-23): a hand-written Rust checker ONLY to get the
//! wasm-checker plumbing green before the compiler can emit a reducer component. It does NOT do the rich
//! echo assertion (find Delivered(C,P)+Emitted(C,P), token==identity::id()) — that is the Cadenza `.cdz`
//! checker (v-platform-itest ports the closed #3021 logic) once v-rust-backend's `.cdz`→reducer-component
//! emit (record-path W4c-b) lands. At that point DELETE this crate (and reducer-echo), replacing both with
//! Cadenza programs. Constants + `on_message` body authored by v-platform-itest (checker/log-format domain).
//!
//! `no_std` + `alloc` with talc (same discipline + exactly the same deps as reducer-echo — no cadenza-ast).
#![no_std]

extern crate alloc;

use alloc::vec;
use alloc::vec::Vec;

#[cfg(target_arch = "wasm32")]
mod allocator;

// Generated by `cargo component build` from the shared `../../wit/world.wit` (world `reducer-world`).
#[allow(warnings)]
mod bindings;

use bindings::cadenza::platform::reducer::{Closed, Outcome, Request};
use bindings::exports::cadenza::platform::guest::{Guest, Message, Notification, Response, Step};

// Precomputed protocol constants (v-platform-itest; stable = hash-of-schema / canonical encoding).
// The 33-byte contract ids and the two encoded `Verdict.Verdict({pass, messages})` payloads — hand-encoded
// so the guest needs no in-guest value builder (no cadenza-ast).
const CHECK_CONTRACT_ID: &[u8] = b"\x01\xdf\xb7\xd5\xf6\x29\x5d\xf6\xb0\x70\xa5\xdf\x94\xb5\xef\xfa\x8f\x92\x80\x09\x6e\xb8\x86\x7e\xa9\xa1\x68\x80\xf1\x73\x12\x8f\x47";
const VERDICT_CONTRACT_ID: &[u8] = b"\x01\xf7\x56\x1b\x5e\xd8\xd2\x4c\x6d\xbe\xe0\x19\x7e\xbd\x99\x05\x2a\x0c\x15\x89\x14\xbb\xfd\xf1\x42\x44\x3b\x76\x09\x84\x3f\x78\x51";
const VERDICT_PASS: &[u8] = b"\x63\x64\x7a\x61\x73\x74\x00\x01\x08\x0a\x01\x2e\x0a\x07\x56\x65\x72\x64\x69\x63\x74\x07\x06\x72\x65\x63\x6f\x72\x64\x0a\x01\x3d\x0a\x04\x70\x61\x73\x73\x09\x0a\x08\x6d\x65\x73\x73\x61\x67\x65\x73\x07\x04\x6c\x69\x73\x74\x10\x00\x00\x00\x01\x00\x01\x01\x03\x00\x01\x02\x00\x02\x00\x03\x00\x04\x00\x05\x01\x03\x05\x06\x07\x00\x03\x00\x06\x00\x07\x01\x01\x0b\x01\x03\x09\x0a\x0c\x01\x03\x04\x08\x0d\x01\x02\x03\x0e\x0f";
const VERDICT_FAIL: &[u8] = b"\x63\x64\x7a\x61\x73\x74\x00\x01\x09\x0a\x01\x2e\x0a\x07\x56\x65\x72\x64\x69\x63\x74\x07\x06\x72\x65\x63\x6f\x72\x64\x0a\x01\x3d\x0a\x04\x70\x61\x73\x73\x08\x0a\x08\x6d\x65\x73\x73\x61\x67\x65\x73\x07\x04\x6c\x69\x73\x74\x07\x15\x65\x63\x68\x6f\x20\x6e\x6f\x74\x20\x66\x6f\x75\x6e\x64\x20\x69\x6e\x20\x6c\x6f\x67\x11\x00\x00\x00\x01\x00\x01\x01\x03\x00\x01\x02\x00\x02\x00\x03\x00\x04\x00\x05\x01\x03\x05\x06\x07\x00\x03\x00\x06\x00\x07\x00\x08\x01\x02\x0b\x0c\x01\x03\x09\x0a\x0d\x01\x03\x04\x08\x0e\x01\x02\x03\x0f\x10";

struct Component;

impl Guest for Component {
    // The check entry point: the harness delivers the whole observation log as this message's payload.
    fn on_message(msg: Message) -> Step {
        if msg.contract.as_slice() != CHECK_CONTRACT_ID {
            return Step {
                requests: Vec::new(),
                outcome: Outcome::Continue,
            };
        }
        // `serialize_log` tags every emitted-request record with "emitted"; reducer-echo having echoed =>
        // an Emitted record exists => the log bytes contain b"emitted". A byte-substring check proves the
        // plumbing without decoding the log (the rich Delivered/Emitted/token check is the Cadenza checker).
        let passed = msg.payload.windows(7).any(|w| w == b"emitted");
        let payload = if passed { VERDICT_PASS } else { VERDICT_FAIL };
        Step {
            requests: vec![Request {
                contract: VERDICT_CONTRACT_ID.to_vec(),
                payload: payload.to_vec(),
                token: Vec::new(),
                deadline_nanos: None,
            }],
            // The harness reads the verdict from the EMITTED request (it scans Emitted on the verdict
            // contract), so the Close schema/reason are unused — any valid bytes are fine.
            outcome: Outcome::Close(Closed {
                schema: VERDICT_CONTRACT_ID.to_vec(),
                reason: Vec::new(),
            }),
        }
    }

    fn on_response(_resp: Response) -> Step {
        Step {
            requests: Vec::new(),
            outcome: Outcome::Continue,
        }
    }

    fn on_notification(_note: Notification) -> Step {
        Step {
            requests: Vec::new(),
            outcome: Outcome::Continue,
        }
    }
}

bindings::export!(Component with_types_in bindings);
