(case "ug1 THREE update GENERATIONS share structure — a, update(a), update(update(a)) all readable with distinct views, the untouched slot threads to the newest"
  (input  (do
            (def (at-or (: xs (List Int64)) (: i Int64))
              (match (List.at xs i) ((Some v) v) ((None _u) -1)))
            (def (main (: n Int64))
              (let ((a (list n 20 30)))
                (let ((b (List.update a 1 99)))
                  (let ((c (List.update b 2 88)))
                    (+ (* 1000000 (at-or c 0))
                       (+ (* 100000 (at-or a 1))
                          (+ (* 10000 (at-or a 2))
                             (+ (* 1000 (at-or b 1))
                                (+ (* 100 (at-or b 2))
                                   (+ (* 10 (at-or c 1)) (at-or c 2)))))))))))
            (export main)))
  (call   main (: 5 Int64)) (output (: 7403078 Int64))
  (call   main (: 1 Int64)) (output (: 3403078 Int64)))
