(case "tpx1 CHAINED shared-lets through a three-way arm — the step arm binds the advanced column THEN a second binder derived from the first, routes on the second binder's residue mod three, and every branch resumes a different mix of the two binders as answer and next-state; the closing peek reads the threaded column, exercising the collapse gate on a multi-binder arm"
  (input  (do
            (effect X
              (op step (-> Int64 Int64))
              (op peek (-> Int64)))
            (def (main (: n Int64))
              (handle X (: 1 Int64)
                ((step (x) col
                  (let ((c2 (+ col (+ x (% n 3)))))
                    (let ((d2 (- (* c2 2) col)))
                      (if (= (% d2 3) 0)
                          (resume (* d2 10) c2)
                          (if (= (% d2 3) 1)
                              (resume (+ (* c2 10) 1) d2)
                              (resume (+ c2 d2) (+ c2 1)))))))
                 (peek () col (resume col col)))
                (let ((a (X.step (: 3 Int64))))
                  (let ((b (X.step (: 5 Int64))))
                    (let ((c (X.step (: 2 Int64))))
                      (let ((d (X.step (: 4 Int64))))
                        (let ((f (X.peek)))
                          (+ (* 1000 (+ (* 1000 (+ (* 1000 (+ (* 1000 a) b)) c)) d)) f))))))))
            (export main)))
  (call   main (: 10 Int64)) (output (: 90028180201025 Int64))
  (call   main (: 0 Int64)) (output (: 41029032240020 Int64)))
