(do
  (type W (Atom Int64) (Node (List Int64)))
  (def (one (: b Bytes) (: pos Int64))
    (if (= (Option.expect (Bytes.at b pos) "t") 0)
      ((. W Atom) (Option.expect (Bytes.at b (+ pos 1)) "v"))
      ((. W Atom) 99)))
  (def (loop (: b Bytes) (: pos Int64) (: n Int64) (: last W))
    (if (= n 0) last (loop b pos (- n 1) (one b pos))))
  (def (wval (: s W)) (match s (((. W Atom) li) li) (((. W Node) ids) 0)))
  (def (main (: pos Int64)) (wval (loop b"\x00\x05\x00\x07" pos 1 ((. W Atom) 0))))
  (export main))
