(case "pysh7 SIBLING SHADOW REGIONS SHARE ONE OUTER THREAD — two side-by-side handles over the same effect each self-perform to the shared outer arm, the outer state advances through the FIRST sibling into the SECOND so their answers carry consecutive rungs, and an outer thread that forks per region or resets between siblings collapses the rung gap"
  (input  (do
            (effect E (op tick (-> Int64)))
            (def (main (: n Int64))
              (handle E (% n 3)
                ((tick () s (resume (+ (* s 10) 1) (+ s 1))))
                (+ (handle E (: 50 Int64)
                     ((tick () s (resume (+ s (E.tick)) (+ s 1))))
                     (E.tick))
                   (* 1000 (handle E (: 800 Int64)
                             ((tick () s (resume (+ s (E.tick)) (+ s 2))))
                             (E.tick))))))
            (export main)))
  (call   main (: 10 Int64)) (output (: 821061 Int64))
  (call   main (: 0 Int64)) (output (: 811051 Int64)))
