(case "ms1 a MEMOIZED recursive computation: the memo trie loop-carries through fib"
  (input  (do
            (def (fib (: n Int64) (: memo (Map Int64 Int64)))
              (match (Map.lookup memo n)
                ((Some v) (tuple v memo))
                ((None _u)
                  (if (< n 2) (tuple n (Map.insert memo n n))
                    (match (fib (- n 1) memo)
                      ((tuple a m1)
                        (match (fib (- n 2) m1)
                          ((tuple b m2) (tuple (+ a b) (Map.insert m2 n (+ a b)))))))))))
            (def (main (: n Int64))
              (match (fib n Map.empty)
                ((tuple v memo) (+ (* 10 v) (Map.len memo)))))
            (export main)))
  (call   main (: 15 Int64)) (output (: 6116 Int64)))
