//! Build-time regeneration of the bundled verification-kernel binary.
//!
//! `verify_kernel.bin` is the binary-AST encoding of `src/verify_kernel.cdz`, embedded by
//! `compile.rs` (`bundled_verify_kernel_arena`). It USED to be a committed golden that went stale
//! on any codec/emit drift — a recurring fleet-red (regenerated by hand in #6236, #6460). It is now
//! regenerated HERE at build time from the `.cdz` source, so there is no committed golden to go
//! stale.
//!
//! Producer is the REAL `cadenza-syntax` crate — `codec::encode(sexpr::read(verify_kernel.cdz))` —
//! the SAME producer the golden always had (NOT rcdzc's copied `crate::codec`, which build.rs can't
//! use pre-build anyway). Acyclic: `cadenza-syntax` does not depend on `rcdzc`, so it is a valid
//! `[build-dependencies]`. rcdzc's own copied `codec::decode` still decodes these bytes at compile
//! time (`bundled_verify_kernel_arena`) — the "copy stays byte-identical to cadenza-syntax"
//! invariant, which this build step continuously exercises.
use std::path::Path;

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set");
    let cdz = Path::new(&manifest).join("src/verify_kernel.cdz");
    // Only re-run when the kernel SOURCE changes (the .cdz), not every build.
    println!("cargo:rerun-if-changed=src/verify_kernel.cdz");
    println!("cargo:rerun-if-changed=build.rs");

    let src =
        std::fs::read_to_string(&cdz).unwrap_or_else(|e| panic!("read {}: {e}", cdz.display()));
    let syntax = cadenza_syntax::sexpr::read(&src)
        .unwrap_or_else(|e| panic!("verify_kernel.cdz must read as s-expression: {e:?}"));
    let bytes = cadenza_syntax::codec::encode(&syntax);

    let out =
        Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR is set")).join("verify_kernel.bin");
    std::fs::write(&out, &bytes).unwrap_or_else(|e| panic!("write {}: {e}", out.display()));
}
