(case "lk1 a STRING-keyed lock — the arm compares the string payload against the stored key by equality; parity picks the key, a fail counter rides along"
  (input  (do
            (effect L (op try (-> String Int64)))
            (def (main (: n Int64))
              (handle L (tuple (if (= (% n 2) 0) "ab" "cd") 1 0)
                ((try (a) st (match st
                               ((tuple key locked fails)
                                (if (= locked 1)
                                    (if (= a key)
                                        (resume 1 (tuple key 0 fails))
                                        (resume 0 (tuple key 1 (+ fails 1))))
                                    (resume 2 st))))))
                (let ((r1 (L.try "cd")))
                  (let ((r2 (L.try "ab")))
                    (let ((r3 (L.try "cd")))
                      (match (L.try "zz")
                        (_last (+ (* 100 r1) (+ (* 10 r2) r3)))))))))
            (export main)))
  (call   main (: 2 Int64)) (output (: 12 Int64))
  (call   main (: 1 Int64)) (output (: 122 Int64))
  (call   main (: 0 Int64)) (output (: 12 Int64)))
