(case "lk2 a ROLLING-code lock — each successful match advances the key index through a list of string keys, |n mod 3| picks the start"
  (input  (do
            (effect L (op try (-> String Int64)))
            (def (main (: n Int64))
              (handle L (tuple (list "aa" "bb" "cc")
                               (let ((m (% n 3))) (if (< m 0) (- 0 m) m)))
                ((try (a) st (match st
                               ((tuple keys ki)
                                (match (List.at keys ki)
                                  ((Some key)
                                   (if (= a key)
                                       (resume 1 (tuple keys (% (+ ki 1) 3)))
                                       (resume 0 st)))
                                  ((None) (resume -1 st)))))))
                (+ (* 1000 (L.try "aa"))
                   (+ (* 100 (L.try "bb"))
                      (+ (* 10 (L.try "bb"))
                         (L.try "cc"))))))
            (export main)))
  (call   main (: 0 Int64)) (output (: 1101 Int64))
  (call   main (: 1 Int64)) (output (: 101 Int64))
  (call   main (: 2 Int64)) (output (: 1 Int64)))
