(case "lk3 LOCKOUT after two failures — the fail counter flips a dead flag that rejects even the correct key thereafter"
  (input  (do
            (effect L (op try (-> String Int64)))
            (def (main (: n Int64))
              (handle L (tuple 0 0)
                ((try (a) st (match st
                               ((tuple fails dead)
                                (if (= dead 1)
                                    (resume 9 st)
                                    (if (= a "ab")
                                        (resume 1 st)
                                        (resume 0 (tuple (+ fails 1)
                                                         (if (>= (+ fails 1) 2) 1 0)))))))))
                (if (> n 0)
                    (+ (* 100 (L.try "xx")) (+ (* 10 (L.try "xx")) (L.try "ab")))
                    (+ (* 100 (L.try "xx")) (+ (* 10 (L.try "ab")) (L.try "ab"))))))
            (export main)))
  (call   main (: 1 Int64)) (output (: 9 Int64))
  (call   main (: 0 Int64)) (output (: 11 Int64))
  (call   main (: -2 Int64)) (output (: 11 Int64)))
