(case "abm2 the ABORT ARM ITSELF PERFORMS ON AN OUTER HANDLER — the bail arm builds its aborting answer from a tenfold of the state its two resumed ticks accumulated PLUS an outer audit drawn while aborting, the audit advances the outer thread so the body's later audit reads five higher, and the abort's own foreign perform threads exactly once through the surviving outer state"
  (input  (do
            (effect T (op audit (-> Int64)))
            (effect E (op tick (-> Int64)) (op bail (-> Int64)))
            (def (main (: n Int64))
              (handle T (% n 3)
                ((audit () t (resume t (+ t 5))))
                (+ (* 100 (handle E (: 1 Int64)
                            ((tick () s (resume s (+ s 1)))
                             (bail () s (+ (* s 10) (T.audit))))
                            (+ (E.tick) (+ (* 10 (E.tick)) (E.bail)))))
                   (T.audit))))
            (export main)))
  (call   main (: 10 Int64)) (output (: 3106 Int64))
  (call   main (: 0 Int64)) (output (: 3005 Int64)))
