(case "md2 the arm DRAINS a Map entry per dispatch — Map.remove keyed by the op arg, a re-take of the same key routes to the miss path"
  (input  (do
            (effect E (op take (-> Int64 Int64)) (op size (-> Int64)))
            (def (main (: n Int64))
              (handle E (Map.insert (Map.insert (Map.insert Map.empty 1 (+ 10 n)) 2 20) 3 30)
                ((take (k) m (match (Map.lookup m k)
                               ((Some v) (resume v (Map.remove m k)))
                               ((None) (resume -1 m))))
                 (size () m (resume (Map.len m) m)))
                (+ (* 1000 (E.take 1))
                   (+ (* 100 (E.take 1))
                      (+ (* 10 (E.take 3))
                         (E.size))))))
            (export main)))
  (call   main (: 5 Int64)) (output (: 15201 Int64))
  (call   main (: 0 Int64)) (output (: 10201 Int64))
  (call   main (: -13 Int64)) (output (: -2799 Int64)))
