(case "md3 the drained value RE-FILES under a shifted key — the third take HITS the re-filed entry, the final take finds it moved on"
  (input  (do
            (effect E (op take (-> Int64 Int64)))
            (def (main (: n Int64))
              (handle E (Map.insert (Map.insert Map.empty 1 (+ 10 n)) 2 20)
                ((take (k) m (match (Map.lookup m k)
                               ((Some v) (resume v (Map.insert (Map.remove m k) (+ k 3) v)))
                               ((None) (resume -1 m)))))
                (+ (* 1000 (E.take 1))
                   (+ (* 100 (E.take 2))
                      (+ (* 10 (E.take 4))
                         (E.take 4))))))
            (export main)))
  (call   main (: 5 Int64)) (output (: 17149 Int64))
  (call   main (: 0 Int64)) (output (: 12099 Int64))
  (call   main (: -12 Int64)) (output (: -21 Int64)))
