(case "abm3 a SHADOWED ABORT IS REGION-SCOPED — both handlers over the effect carry bail arms but the inner region's bail routes to the INNER arm and aborts ONLY the inner handle, the outer body continues past the dead region and its later tick reads the outer state untouched by the aborted region's churn, and an abort escaping to the outer arm or killing the outer body shifts the ten-thousands"
  (input  (do
            (effect E (op tick (-> Int64)) (op bail (-> Int64)))
            (def (main (: n Int64))
              (handle E (% n 3)
                ((tick () s (resume (+ (* s 10) 1) (+ s 1)))
                 (bail () s (+ 9000 s)))
                (+ (handle E (: 50 Int64)
                     ((tick () s (resume (+ s 100) (+ s 1)))
                      (bail () s (+ 5000 s)))
                     (+ (E.tick) (E.bail)))
                   (* 10000 (E.tick)))))
            (export main)))
  (call   main (: 10 Int64)) (output (: 115051 Int64))
  (call   main (: 0 Int64)) (output (: 15051 Int64)))
