(case "oc5 TWO Option slots in one tuple state — independent put lifecycles, a SWAP op exchanges them, reads confirm the exchange"
  (input  (do
            (effect E (op puta (-> Int64 Int64)) (op putb (-> Int64 Int64))
                      (op swap (-> Int64)) (op reada (-> Int64)) (op readb (-> Int64)))
            (def (main (: n Int64))
              (handle E (tuple (None) (None))
                ((puta (v) st (match st ((tuple a b) (resume 0 (tuple (Some v) b)))))
                 (putb (v) st (match st ((tuple a b) (resume 0 (tuple a (Some v))))))
                 (swap () st (match st ((tuple a b) (resume 1 (tuple b a)))))
                 (reada () st (match st ((tuple a b) (resume (match a ((Some x) x) ((None) -1)) st))))
                 (readb () st (match st ((tuple a b) (resume (match b ((Some x) x) ((None) -1)) st)))))
                (do (E.puta n) (E.putb 7) (E.swap)
                    (+ (* 10 (E.reada)) (E.readb)))))
            (export main)))
  (call   main (: 5 Int64)) (output (: 75 Int64))
  (call   main (: 0 Int64)) (output (: 70 Int64))
  (call   main (: -3 Int64)) (output (: 67 Int64)))
