(case "as1 concat ASSOCIATIVITY — left-nested and right-nested three-way concats are structurally EQUAL and element-identical"
  (input  (do
            (def (main (: n Int64))
              (let ((a (list n 2)))
                (let ((b (list 3 4)))
                  (let ((c (list 5 6)))
                    (let ((lr (List.concat (List.concat a b) c)))
                      (let ((rl (List.concat a (List.concat b c))))
                        (+ (* 1000000 (if (= lr rl) 1 0))
                           (+ (* 10000 (List.len lr))
                              (+ (* 100 (match (List.at lr 4) ((Some v) v) ((None _u) -1)))
                                 (+ (* 10 (match (List.at rl 0) ((Some v) v) ((None _u) -1)))
                                    (match (List.at rl 5) ((Some v) v) ((None _u) -1))))))))))))
            (export main)))
  (call   main (: 1 Int64)) (output (: 1060516 Int64))
  (call   main (: 9 Int64)) (output (: 1060596 Int64)))
