(case "oe1 an Option-CHAIN over successive trie hops (the follow-the-pointer walk)"
  (input  (do
            (def (fill (: i Int64) (: m (Map Int64 Int64)))
              (if (= i 0) m (fill (- i 1) (Map.insert m i (+ i 10)))))
            (def (hop3 (: m (Map Int64 Int64)) (: k Int64))
              (match (Map.lookup m k)
                ((Some a) (match (Map.lookup m a)
                            ((Some b) (match (Map.lookup m b)
                                        ((Some c) c)
                                        ((None _u) -3)))
                            ((None _u) -2)))
                ((None _u) -1)))
            (def (main (: n Int64))
              (+ (* 10 (hop3 (fill n Map.empty) 5))
                 (if (= (hop3 (fill n Map.empty) 30) -2) 1 0)))
            (export main)))
  (call   main (: 38 Int64)) (output (: 351 Int64)))
