(do
  (effect ask (op ask (-> Unit Int64)))
  (effect A (op get (-> Unit Int64)))
  (effect B (op get (-> Unit Int64)))
  (def (main (: n Int64))
    (host (ask)
      (+ (* 100 (handle A (ask.ask)
                  ((get (u) s (resume s s)))
                  (A.get)))
         (handle B (ask.ask)
           ((get (u) t (resume t t)))
           (B.get)))))
  (export main))
