(case "hf2 two host-seeded SIBLING handlers — each region's seed consumes its response in evaluation order"
  (input  (do
            (effect ask (op ask (-> Unit Int64)))
            (effect A (op get (-> Unit Int64)))
            (effect B (op get (-> Unit Int64)))
            (def (main (: n Int64))
              (host (ask)
                (+ (* 100 (handle A (ask.ask)
                            ((get (u) s (resume s s)))
                            (A.get)))
                   (handle B (ask.ask)
                     ((get (u) t (resume t t)))
                     (B.get)))))
            (export main)))
  (call   main (: 0 Int64))
  (host-responses (respond ask.ask (: 7 Int64)) (respond ask.ask (: 9 Int64)))
  (host-calls (call ask.ask) (call ask.ask))
  (output (: 709 Int64)))
