(case "e1 TWO returned closures capturing the SAME let-bound host call share ONE firing"
  (input  (do
            (effect io (op get (-> Unit Int64)))
            (def (mk)
              (host (io)
                (let ((v (io.get unit)))
                  (tuple (fn ((: x Int64)) (+ v x))
                         (fn ((: x Int64)) (* v x))))))
            (def (main (: k Int64))
              (match (mk)
                ((tuple f g) (+ (f k) (* 100 (g k))))))
            (export main)))
  (host-responses (respond io.get (: 7 Int64)))
  (host-calls (call io.get))
  (call   main (: 3 Int64)) (output (: 2110 Int64)))
