(case "v62a THREE closures + a direct body read all share ONE firing"
  (input  (do
            (effect io (op get (-> Unit Int64)))
            (def (mk)
              (host (io)
                (let ((v (io.get unit)))
                  (tuple (+ v 1)
                         (tuple (fn ((: x Int64)) (+ v x))
                                (fn ((: x Int64)) (* v x))
                                (fn ((: x Int64)) (- v x)))))))
            (def (main (: k Int64))
              (match (mk)
                ((tuple direct fns)
                  (match fns
                    ((tuple f g h)
                      (+ direct (+ (f k) (+ (* 100 (g k)) (* 10000 (h k))))))))))
            (export main)))
  (host-responses (respond io.get (: 7 Int64)))
  (host-calls (call io.get))
  (call   main (: 3 Int64)) (output (: 42118 Int64)))
