(case "v62b TWO DISTINCT host calls each captured by their own closure fire once each, in order"
  (input  (do
            (effect io (op a (-> Unit Int64)) (op b (-> Unit Int64)))
            (def (mk)
              (host (io)
                (let ((x (io.a unit)))
                  (let ((y (io.b unit)))
                    (tuple (fn ((: n Int64)) (+ x n))
                           (fn ((: n Int64)) (+ y n)))))))
            (def (main (: k Int64))
              (match (mk)
                ((tuple f g) (+ (f k) (* 100 (g k))))))
            (export main)))
  (host-responses (respond io.a (: 10 Int64)) (respond io.b (: 20 Int64)))
  (host-calls (call io.a) (call io.b))
  (call   main (: 1 Int64)) (output (: 2111 Int64)))
