(case "mec1 sorted enumeration AFTER remove-churn — five keyed inserts (one seed-colliding overwrite), two removes, the surviving key walk pins order and count"
  (input  (do
            (effect S
              (op put (-> Int64 Int64 Int64))
              (op del (-> Int64 Int64))
              (op walk (-> Int64)))
            (def (fold-keys (: xs (List (Tuple Int64 Int64))) (: i Int64) (: acc Int64))
              (match (List.at xs i)
                ((Some e) (match e ((tuple k _v) (fold-keys xs (+ i 1) (+ (* 100 acc) k)))))
                ((None u) acc)))
            (def (main (: n Int64))
              (handle S Map.empty
                ((put (k v) m (resume (Map.len m) (Map.insert m k v)))
                 (del (k) m (resume (Map.len m) (Map.remove m k)))
                 (walk () m (resume (+ (* 10 (fold-keys (Map.to-list m) 0 0)) (Map.len m)) m)))
                (let ((_a (S.put n 0)))
                  (let ((_b (S.put (+ n 1) 1)))
                    (let ((_c (S.put 3 2)))
                      (let ((_d (S.put 9 3)))
                        (let ((_e (S.put (+ n 2) 4)))
                          (let ((_f (S.del (+ n 1))))
                            (let ((_g (S.del 9)))
                              (S.walk))))))))))
            (export main)))
  (call   main (: 4 Int64)) (output (: 304063 Int64))
  (call   main (: 1 Int64)) (output (: 1032 Int64)))
