//! The Cadenza NFC (Unicode Normalization Form C) component — FINDING#23, operator ruling (d).
//!
//! A self-contained wasm component exporting `cadenza:nfc/normalize`. The emitted PROGRAM imports this
//! interface BY HASH (a second content-addressed import beside `cadenza:runtime/heap`); v-agent-harness's
//! dep-compose host (cdz-kernel §23) composes it from CAS. It carries the heavy Unicode composition tables
//! (`unicode-normalization`) so the tagless value-heap runtime does NOT — the core stays light and
//! hash-stable (no +124KB per instance, no fleet-wide `REQUIRED_RUNTIME_HASH` flip).
//!
//! PURE, runtime-agnostic value transform: `nfc(list<u8>) -> list<u8>` over UTF-8 bytes. It knows nothing
//! about the value-heap handle ABI (fork B, decided with v-agent-harness), so it composes independently.
//! The rcdzc emit marshals a String leaf's bytes to `list<u8>`, calls `nfc`, and rebuilds a leaf — at
//! String-typed sites only, preserving the from-bytes DECODE NFC-exemption by construction.
//!
//! `no_std` + `alloc` (no `std`), matching cdz-runtime's deterministic cross-arch build (`.cargo/config.toml`
//! build-std = core+alloc, panic=immediate-abort) so the component's content hash is host-independent.
#![no_std]

extern crate alloc;

use alloc::string::String;
use alloc::vec::Vec;

// The embedded wasm allocator (talc), isolated so it is swappable in one file — same as cdz-runtime.
// Only present in the wasm build; a native build (if ever added for tests) keeps the system allocator.
#[cfg(target_arch = "wasm32")]
mod allocator;

// The component bindings are generated by `cargo component build` from `wit/nfc.wit` (world `nfc`).
#[allow(warnings)]
mod bindings;

use bindings::exports::cadenza::nfc::normalize::Guest;
use unicode_normalization::UnicodeNormalization;

/// The pure NFC transform, factored out of the `Guest` impl so it is unit-testable natively (the `Guest`
/// trait + wasm bindings are awkward to invoke off-wasm; this free fn is plain `alloc`). Normalize a UTF-8
/// byte sequence to Unicode Normalization Form C. INPUT is assumed well-formed UTF-8 (the compiler emits
/// this ONLY at String-typed sites, whose bytes are valid UTF-8 by construction). If the input were somehow
/// NOT valid UTF-8 (the compiler never emits that here), pass it through unchanged rather than trapping — a
/// total function. Idempotent: nfc_bytes(nfc_bytes(x)) == nfc_bytes(x).
fn nfc_bytes(utf8: &[u8]) -> Vec<u8> {
    match core::str::from_utf8(utf8) {
        Ok(s) => s.nfc().collect::<String>().into_bytes(),
        // Not reachable from the compiler's String-typed emit sites; pass through (total, no trap).
        Err(_) => utf8.to_vec(),
    }
}

struct Component;

impl Guest for Component {
    fn nfc(utf8: Vec<u8>) -> Vec<u8> {
        nfc_bytes(&utf8)
    }
}

bindings::export!(Component with_types_in bindings);

#[cfg(test)]
mod tests {
    use super::nfc_bytes;
    use alloc::vec::Vec;

    // FINDING#23 core case: "e" + COMBINING ACUTE ACCENT (U+0301, decomposed) normalizes to the COMPOSED
    // "é" (U+00E9). This is exactly the runtime String.concat bug the imported NFC component closes: the
    // decomposed concat must compare/hash equal to the composed literal after normalization.
    #[test]
    fn decomposed_e_plus_combining_acute_composes_to_precomposed_e_acute() {
        let decomposed = "e\u{0301}".as_bytes(); // 'e' + U+0301, 3 bytes
        let composed = "é".as_bytes(); // U+00E9, 2 bytes (the NFC form)
        assert_eq!(nfc_bytes(decomposed), composed.to_vec(), "NFC composes e + combining-acute → é");
        assert_ne!(decomposed.len(), composed.len(), "precondition: the two spellings have different byte lengths");
    }

    #[test]
    fn nfc_is_idempotent_on_the_composed_form() {
        let composed = "é".as_bytes().to_vec();
        assert_eq!(nfc_bytes(&composed), composed, "already-NFC input is unchanged");
        // Idempotency over the decomposed input: normalize twice == once.
        let once = nfc_bytes("e\u{0301}".as_bytes());
        assert_eq!(nfc_bytes(&once), once, "nfc(nfc(x)) == nfc(x)");
    }

    #[test]
    fn pure_ascii_is_unchanged() {
        let ascii = b"hello world 123";
        assert_eq!(nfc_bytes(ascii), ascii.to_vec(), "ASCII is already NFC — byte-identical passthrough");
        assert_eq!(nfc_bytes(&[]), Vec::<u8>::new(), "empty input → empty output");
    }

    #[test]
    fn invalid_utf8_passes_through_unchanged_no_trap() {
        // The compiler never emits this on non-UTF-8 (String leaves are valid UTF-8), but the fn must be
        // total — a lone 0x80 continuation byte is not valid UTF-8 and is returned verbatim, not a panic.
        let bad = [0x80u8, 0xFF, 0x00];
        assert_eq!(nfc_bytes(&bad), bad.to_vec(), "invalid UTF-8 → verbatim passthrough (total, no trap)");
    }

    #[test]
    fn a_multi_combining_sequence_composes() {
        // 'a' + combining ring above (U+030A) → 'å' (U+00E5); a second independent decomposed pair in one
        // string exercises the streaming NFC over multiple base+combiner runs.
        let decomposed = "a\u{030A}o\u{0301}".as_bytes(); // å + ó, both decomposed
        let composed = "åó".as_bytes();
        assert_eq!(nfc_bytes(decomposed), composed.to_vec(), "multiple base+combining runs each compose");
    }
}
