(case "swd1 a SLIDING-WINDOW dedup state — the last-three list slides via push-and-drop-head rebuilt in the arm, membership answers flip as elements age out"
  (input  (do
            (effect S (op feed (-> Int64 Int64)))
            (def (has (: xs (List Int64)) (: v Int64) (: i Int64))
              (match (List.at xs i)
                ((Some x) (if (= x v) 1 (has xs v (+ i 1))))
                ((None u) 0)))
            (def (slide (: xs (List Int64)) (: v Int64))
              (let ((g (List.push xs v)))
                (match g
                  ((list _h .. t) (if (> (List.len g) 3) t g))
                  (_ g))))
            (def (main (: n Int64))
              (handle S (: (list) (List Int64))
                ((feed (v) w
                  (resume (has w v 0) (slide w v))))
                (let ((a (S.feed n)))
                  (let ((b (S.feed (+ n 1))))
                    (let ((c (S.feed n)))
                      (let ((d (S.feed 5)))
                        (let ((e (S.feed n)))
                          (+ (* 10000 (+ a 1)) (+ (* 1000 (+ b 1)) (+ (* 100 (+ c 1)) (+ (* 10 (+ d 1)) (+ e 1))))))))))))
            (export main)))
  (call   main (: 3 Int64)) (output (: 11212 Int64))
  (call   main (: 5 Int64)) (output (: 11222 Int64)))
