(case "rr1 RECORD handler state updated by one arm, field-read by a SIBLING arm plus a third counter arm — the record twin of the collection cross-arm shape"
  (input  (do
            (effect E (op tick (-> Int64)) (op rd (-> Int64)) (op cur (-> Int64)))
            (def (main (: n Int64))
              (handle E (record (cnt n) (tot 0))
                ((tick () st (resume (. st cnt)
                                     (record (cnt (+ (. st cnt) 1))
                                             (tot (+ (. st tot) (* 10 (. st cnt)))))))
                 (rd () st (resume (. st tot) st))
                 (cur () st (resume (. st cnt) st)))
                (+ (E.tick) (+ (E.tick) (+ (E.rd) (E.cur))))))
            (export main)))
  (call   main (: 5 Int64)) (output (: 128 Int64))
  (call   main (: 0 Int64)) (output (: 13 Int64))
  (call   main (: -3 Int64)) (output (: -56 Int64)))
