(case "rq2 floor/ceil/numerator/denominator READ a rational state — canonicalization (8/4 to 2/1) and negative rounding both pinned"
  (input  (do
            (effect E (op fl (-> Int64)) (op ce (-> Int64)) (op nu (-> Int64)) (op de (-> Int64)))
            (def (main (: n Int64))
              (handle E (Rational.of n 4)
                ((fl () s (resume (Int64.of (Rational.floor s)) s))
                 (ce () s (resume (Int64.of (Rational.ceil s)) s))
                 (nu () s (resume (Int64.of (Rational.numerator s)) s))
                 (de () s (resume (Int64.of (Rational.denominator s)) s)))
                (+ (* 1000 (E.fl))
                   (+ (* 100 (E.ce))
                      (+ (* 10 (E.nu)) (E.de))))))
            (export main)))
  (call   main (: 5 Int64)) (output (: 1254 Int64))
  (call   main (: 8 Int64)) (output (: 2221 Int64))
  (call   main (: -3 Int64)) (output (: -1026 Int64)))
