// Throwaway fork1a bootstrap: convert the hand-authored src/playground/examples.ts EXAMPLES[] into the
// examples.sexp source-of-truth (operator seq-259: playground examples → .sexp → @generated examples.ts,
// everything canonical). One-time migration input; after the flip, examples.sexp is authored directly and
// examples.ts is @generated by `xtask-codegen-guide --playground-registry`. Node is fine for a one-time
// bootstrap (the operator's "no TS tooling" is about the PERMANENT codegen/shred, which are the Rust xtask).
//
// All 60 playground examples are sexpr-authored, so each `source` (a `(do …)` program) embeds VERBATIM as
// `(source (do …))` — the canonicalization happens on the codegen READ (print_pretty_from), not here. String
// fields (id/name/theme/expected) are sexpr-escaped. Usage: node scripts/examples-to-sexp.mjs > examples.sexp
import { EXAMPLES } from "../src/playground/examples.ts";

/// Escape a JS string as a sexpr double-quoted string atom (quotes + backslashes).
const s = (v) => `"${String(v).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;

if (!Array.isArray(EXAMPLES) || EXAMPLES.length === 0) {
  console.error("examples-to-sexp: EXAMPLES is empty/not an array — aborting (would emit a vacuous doc).");
  process.exit(1);
}

const forms = EXAMPLES.map((e) => {
  if (e.surface !== "sexpr") {
    // The embed-verbatim path assumes a sexpr source; an ML example would need conversion first.
    console.error(`examples-to-sexp: example "${e.id}" is surface="${e.surface}" — only sexpr is supported by this bootstrap.`);
    process.exit(1);
  }
  const attrs = [
    `(id ${s(e.id)})`,
    `(name ${s(e.name)})`,
    `(theme ${s(e.theme)})`,
    `(surface ${s(e.surface)})`,
    // source embeds the program AST verbatim (it is already sexpr); codegen canonicalizes on read.
    `(source ${e.source.trim()})`,
  ];
  if (e.expected != null) attrs.push(`(expected ${s(e.expected)})`);
  if (e.expectError) attrs.push(`(expect-error "true")`);
  return `  (example\n    ${attrs.join("\n    ")})`;
});

process.stdout.write(`(playground\n${forms.join("\n")})\n`);
