(case "mrg1 a TWO-POINTER MERGE across two handlers — each holds a sorted list, the body pulls whichever head is smaller each step, and the sentinel head lets one side drain"
  (input  (do
            (effect A
              (op head (-> Int64))
              (op pop (-> Int64)))
            (effect B
              (op head (-> Int64))
              (op pop (-> Int64)))
            (def (hd (: xs (List Int64)))
              (match (List.at xs 0) ((Some v) v) ((None u) 999)))
            (def (tl (: xs (List Int64)))
              (match xs ((list _h .. t) t) (_ xs)))
            (def (main (: n Int64))
              (handle A (list 1 4 9)
                ((head () xs (resume (hd xs) xs))
                 (pop () xs (resume (hd xs) (tl xs))))
                (handle B (list n 5 8)
                  ((head () ys (resume (hd ys) ys))
                   (pop () ys (resume (hd ys) (tl ys))))
                  (let ((m1 (if (<= (A.head) (B.head)) (A.pop) (B.pop))))
                    (let ((m2 (if (<= (A.head) (B.head)) (A.pop) (B.pop))))
                      (let ((m3 (if (<= (A.head) (B.head)) (A.pop) (B.pop))))
                        (let ((m4 (if (<= (A.head) (B.head)) (A.pop) (B.pop))))
                          (+ (* 1000 m1) (+ (* 100 m2) (+ (* 10 m3) m4))))))))))
            (export main)))
  (call   main (: 2 Int64)) (output (: 1245 Int64))
  (call   main (: 6 Int64)) (output (: 1465 Int64)))
