// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod cadenza {
        pub mod runtime {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod heap {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_box_int_cabi<T: Guest>(arg0: i64) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::box_int(arg0);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_int_cabi<T: Guest>(arg0: i32) -> i64 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_int(arg0 as u32);
                    _rt::as_i64(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_box_bool_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::box_bool(_rt::bool_lift(arg0 as u8));
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_bool_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_bool(arg0 as u32);
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_box_float_cabi<T: Guest>(arg0: f64) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::box_float(arg0);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_float_cabi<T: Guest>(arg0: i32) -> f64 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_float(arg0 as u32);
                    _rt::as_f64(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_arr_alloc_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::arr_alloc(arg0 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_arr_set_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::arr_set(arg0 as u32, arg1 as u32, arg2 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_arr_get_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::arr_get(arg0 as u32, arg1 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_arr_len_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::arr_len(arg0 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_sum_new_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::sum_new(arg0 as u32, arg1 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_sum_disc_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::sum_disc(arg0 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_sum_payload_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::sum_payload(arg0 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_bytes_alloc_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::bytes_alloc(arg0 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_bytes_set_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::bytes_set(arg0 as u32, arg1 as u32, arg2 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_bytes_get_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::bytes_get(arg0 as u32, arg1 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_bytes_len_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::bytes_len(arg0 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_str_new_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::str_new(_rt::string_lift(bytes0));
                    _rt::as_i32(result1)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_str_get_cabi<T: Guest>(arg0: i32) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::str_get(arg0 as u32);
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0.into_bytes()).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_str_get<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_dup_cabi<T: Guest>(arg0: i32) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::dup(arg0 as u32);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_drop_cabi<T: Guest>(arg0: i32) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::drop(arg0 as u32);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_map_alloc_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::map_alloc(arg0 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_map_set_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i32,
                    arg3: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::map_set(
                        arg0 as u32,
                        arg1 as u32,
                        arg2 as u32,
                        arg3 as u32,
                    );
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_map_key_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::map_key(arg0 as u32, arg1 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_map_val_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::map_val(arg0 as u32, arg1 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_map_len_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::map_len(arg0 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_reset_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::reset(arg0 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_arr_alloc_reuse_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::arr_alloc_reuse(arg0 as u32, arg1 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_sum_new_reuse_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::sum_new_reuse(
                        arg0 as u32,
                        arg1 as u32,
                        arg2 as u32,
                    );
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_vec_empty_cabi<T: Guest>() -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::vec_empty();
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_vec_len_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::vec_len(arg0 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_vec_get_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::vec_get(arg0 as u32, arg1 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_vec_push_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::vec_push(arg0 as u32, arg1 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_vec_update_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::vec_update(arg0 as u32, arg1 as u32, arg2 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_bytes_concat_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::bytes_concat(arg0 as u32, arg1 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_bytes_slice_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::bytes_slice(arg0 as u32, arg1 as u32, arg2 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_bytes_compact_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::bytes_compact(arg0 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_map_empty_cabi<T: Guest>() -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::map_empty();
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_map_insert_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::map_insert(arg0 as u32, arg1 as u32, arg2 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_map_lookup_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::map_lookup(arg0 as u32, arg1 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_map_remove_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::map_remove(arg0 as u32, arg1 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_map_size_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::map_size(arg0 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_map_iter_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::map_iter(arg0 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_map_iter_next_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::map_iter_next(arg0 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_map_iter_key_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::map_iter_key(arg0 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_map_iter_val_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::map_iter_val(arg0 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_set_empty_cabi<T: Guest>() -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::set_empty();
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_set_insert_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::set_insert(arg0 as u32, arg1 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_set_contains_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::set_contains(arg0 as u32, arg1 as u32);
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_set_remove_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::set_remove(arg0 as u32, arg1 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_set_size_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::set_size(arg0 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_set_iter_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::set_iter(arg0 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_set_iter_next_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::set_iter_next(arg0 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_set_iter_elem_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::set_iter_elem(arg0 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_live_objects_cabi<T: Guest>() -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::live_objects();
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_vec_concat_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::vec_concat(arg0 as u32, arg1 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_vec_split_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::vec_split(arg0 as u32, arg1 as u32);
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let (t2_0, t2_1) = result0;
                    *ptr1.add(0).cast::<i32>() = _rt::as_i32(t2_0);
                    *ptr1.add(4).cast::<i32>() = _rt::as_i32(t2_1);
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_set_union_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::set_union(arg0 as u32, arg1 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_set_intersection_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::set_intersection(arg0 as u32, arg1 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_set_difference_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::set_difference(arg0 as u32, arg1 as u32);
                    _rt::as_i32(result0)
                }
                pub trait Guest {
                    /// ── Scalar leaves (indices 0–5). Box a primitive, read it back. No type tag: `get-*` is only
                    ///    ever called where the compiler's static type already says which primitive this handle
                    ///    holds, so a mismatched read is a compiler bug, not a runtime-checked condition. ──
                    fn box_int(v: i64) -> u32;
                    /// 0
                    fn get_int(handle: u32) -> i64;
                    /// 1
                    fn box_bool(v: bool) -> u32;
                    /// 2
                    fn get_bool(handle: u32) -> bool;
                    /// 3
                    fn box_float(v: f64) -> u32;
                    /// 4
                    fn get_float(handle: u32) -> f64;
                    /// 5
                    /// ── Positional array (indices 6–9) — the fixed-arity product shape for TUPLE and RECORD.
                    ///    A record IS a tuple (field names are compile-time indices); the two differ only in their
                    ///    static type, which the compiler renders as `(tuple …)` vs `(record (k v)…)`. Elements are
                    ///    handles. `arr-set` returns the array handle for convenient threading. `arr-len` returns the
                    ///    element count. A LIST is NOT this array — a list is growable and runtime-length, so it is
                    ///    the persistent-sequence trie (`vec-*`, indices 24–28) instead; the flat array backs only a
                    ///    fixed-arity tuple/record. (Which representation is unobservable — a list renders `(list …)`
                    ///    regardless.) ──
                    fn arr_alloc(len: u32) -> u32;
                    /// 6
                    fn arr_set(arr: u32, index: u32, elem: u32) -> u32;
                    /// 7
                    fn arr_get(arr: u32, index: u32) -> u32;
                    /// 8
                    fn arr_len(arr: u32) -> u32;
                    /// 9
                    /// ── Sum (indices 10–12) — a discriminant (WHICH variant: a genuine runtime choice, a small
                    ///    per-sum-type index the compiler assigns 0,1,2,… over the variants in declaration order and
                    ///    `switch`es on when rendering/matching; NOT a universal type tag) plus a payload handle.
                    ///    A nullary variant carries the unit value (an arr of length 0) as its payload. The runtime
                    ///    stores the discriminant verbatim and hands it back; only the compiler knows which variant
                    ///    name a discriminant denotes. ──
                    fn sum_new(disc: u32, payload: u32) -> u32;
                    /// 10
                    fn sum_disc(handle: u32) -> u32;
                    /// 11
                    fn sum_payload(handle: u32) -> u32;
                    /// 12
                    /// ── Bytes (indices 13–16) — a packed immutable byte buffer (NOT an array of boxed ints; the
                    ///    values are 0–255 and packing matters). Canonical text is `(Bytes.of (list b0 b1 …))`, which
                    ///    the compiler's renderer produces by looping `bytes-get`. `bytes-set` returns the buffer
                    ///    handle for threading; a byte value MUST be 0–255 (the compiler guarantees this — an
                    ///    out-of-range byte is a compile-time trap on Cadenza's side). ──
                    fn bytes_alloc(len: u32) -> u32;
                    /// 13
                    fn bytes_set(buf: u32, index: u32, value: u32) -> u32;
                    /// 14
                    fn bytes_get(buf: u32, index: u32) -> u32;
                    /// 15
                    fn bytes_len(buf: u32) -> u32;
                    /// 16
                    /// ── String (indices 17–18) — a stored UTF-8 string leaf. The component model marshals the
                    ///    `string` across the boundary, so the runtime just stores/returns the bytes VERBATIM: it
                    ///    performs NO normalization or scalar-counting (those are language semantics the compiler
                    ///    owns; the compiler normalizes before `str-new` if a rule requires it). `str-new` stores a
                    ///    string and returns its handle; `str-get` returns the stored string (the compiler-emitted
                    ///    renderer pulls it back to quote/escape it into the output, matching the corpus `"…"` form).
                    ///    ──
                    fn str_new(s: _rt::String) -> u32;
                    /// 17
                    fn str_get(handle: u32) -> _rt::String;
                    /// 18
                    /// ── Reference-count calling convention (Perceus, indices 19–20). No-ops in Phase B/C; Phase D
                    ///    makes `drop` decrement-and-maybe-reclaim and `dup` increment. Emitting the calls now fixes
                    ///    the call sites so Phase D needs no re-emit. ──
                    fn dup(handle: u32) -> ();
                    /// 19
                    fn drop(handle: u32) -> ();
                    /// 20
                    /// ── Map (indices 21–25) — a key→value collection with DYNAMIC keys, a DISTINCT type from a
                    ///    record (whose field set is fixed and whose "keys" are compile-time indices). Both keys and
                    ///    values are handles. Stored as positional (key, value) pairs; the runtime stores them
                    ///    VERBATIM and does NOT sort or dedup — key ordering / order-independent equality are
                    ///    language semantics the compiler owns (a map's canonical rendering is not yet pinned by the
                    ///    corpus, so this API exists to construct/inspect maps that flow at runtime; rendering lands
                    ///    when the map value form is specified). `map-set` returns the map handle for threading. ──
                    fn map_alloc(len: u32) -> u32;
                    /// 21
                    fn map_set(m: u32, index: u32, key: u32, value: u32) -> u32;
                    /// 22
                    fn map_key(m: u32, index: u32) -> u32;
                    /// 23
                    fn map_val(m: u32, index: u32) -> u32;
                    /// 24
                    fn map_len(m: u32) -> u32;
                    /// 25
                    /// ── Reuse / FBIP (Perceus reset + reuse, indices 26–28). The in-place update story: when an
                    ///    `rc==1` value is consumed and a same-arity value is built in the same breath (`List.map`,
                    ///    record update, a functional cons rebuild), hand the dying node's shell straight to the new
                    ///    allocation instead of free→malloc. This is Koka/Lean's core perf win, made frame-limited by
                    ///    the P3/P4 rule below: reuse fires ONLY when the node is UNIQUE (`rc==1`), so peak heap can
                    ///    never grow — a reused shell is memory that was already live and is about to die.
                    ///
                    ///    `reset(node) -> u32` — the drop-to-token op. If `node` is UNIQUE (`rc==1`): drop the
                    ///    children it owns (a normal cascading drop of each child reference), then RETAIN the emptied
                    ///    shell and return it as a non-null REUSE TOKEN (the same handle, now childless, rc still 1).
                    ///    If `node` is SHARED (`rc>1`): decrement and return 0 (null token) — no reuse, the other
                    ///    owners keep the node intact. A null token is always safe to pass on: the reuse-constructors
                    ///    treat it as "no cell to reuse" and allocate fresh. So the compiler emits `reset` on the
                    ///    scrutinee/old value and threads the token into the constructor that rebuilds it.
                    ///
                    ///    `arr-alloc-reuse(len, token) -> u32` — like `arr-alloc(len)`, but if `token` is a non-null
                    ///    reuse token, refit that shell to `len` NULL slots and return it (no allocation); else
                    ///    allocate fresh. `sum-new-reuse(disc, payload, token)` — like `sum-new`, reusing `token`'s
                    ///    shell for the new `(disc, payload)` node when non-null. Passing token 0 makes both behave
                    ///    exactly as their non-reuse forms, so a reset that declined to yield a token is transparent.
                    fn reset(node: u32) -> u32;
                    /// 26
                    fn arr_alloc_reuse(len: u32, token: u32) -> u32;
                    /// 27
                    fn sum_new_reuse(disc: u32, payload: u32, token: u32) -> u32;
                    /// 28
                    /// ── List representation: a 32-way radix trie (indices 29–33) — an IMMUTABLE, structurally-shared
                    ///    growable sequence. This is the runtime representation of the language's LIST type: a list is
                    ///    runtime-length and grows/updates functionally (`List.push`/`List.update`) with O(log₃₂ N)
                    ///    push/get/update and path-copying sharing, which the flat `arr` (fixed-arity, for tuple/record)
                    ///    cannot do. There is NO separate `Vec` type in the language — a list built as a `(list …)`
                    ///    literal and a list grown by push are the SAME type over THIS representation; which structure
                    ///    backs a list is unobservable (a list renders `(list …)` regardless), so the runtime is free to
                    ///    use the flat array for a small/literal list or this trie for a grown one. The representation is
                    ///    a pure runtime concern (see lib.rs § "Persistent vector"): these five signatures are the frozen
                    ///    contract; a later switch to a tail-optimized trie or an RRB tree keeps them byte-identical.
                    ///
                    ///    Ownership (DESIGN-rc-calling-convention.md §1): `vec-empty` produces a new owned list.
                    ///    `vec-push`/`vec-update` are CONSTRUCTORS — they CONSUME the input list and the element and
                    ///    produce a NEW owned list; the old version is untouched (persistence), so a caller keeping
                    ///    both versions `dup`s the input first. `vec-get` BORROWS (rc unchanged; the list still owns
                    ///    the element). `vec-len` returns a `u32` by value. An out-of-bounds `vec-get`/`vec-update`
                    ///    index TRAPS (fail-fast, like `arr-get`; the compiler emits the bounds check on its side).
                    fn vec_empty() -> u32;
                    /// 29 — a new empty vector
                    fn vec_len(v: u32) -> u32;
                    /// 30 — element count
                    fn vec_get(v: u32, index: u32) -> u32;
                    /// 31 — element at index (borrowed)
                    fn vec_push(v: u32, elem: u32) -> u32;
                    /// 32 — v with elem appended (consumes both)
                    fn vec_update(v: u32, index: u32, elem: u32) -> u32;
                    /// 33 — v with index set (consumes both)
                    /// ── Bytes rope (indices 34–36) — O(1) concat/slice over SHARED byte leaves. A Bytes value becomes
                    ///    a rope: a tree of concat/slice nodes bottoming out in the existing byte leaves (13–16), so
                    ///    `bytes-concat`/`bytes-slice` allocate one node and copy NO bytes — killing the O(n²) copy
                    ///    cascade the self-hosting compiler hits assembling a wasm module by concatenating encoded
                    ///    sections (DESIGN-rope-bytes.md / RUNTIME-REQUESTS Request 1). The representation is a pure
                    ///    runtime concern: it reuses the existing tagless node (`handles.len()` ∈ {0,1,2} selects
                    ///    leaf/slice/concat — see lib.rs § "Bytes rope"), so 13–16 are byte-unchanged and a rope is
                    ///    INDISTINGUISHABLE from a flat buffer by `bytes-len`/`bytes-get`/equality (a rope node
                    ///    flattens to a leaf on first full read — unobservable per memory-and-resource-model.md
                    ///    #Sharing Is Not Observable). A later balancing/tail change keeps these three signatures
                    ///    byte-identical.
                    ///
                    ///    Ownership (DESIGN-rc-calling-convention.md §1): all three are CONSTRUCTORS — they CONSUME
                    ///    their Bytes operand(s) (stored in the new node's `handles` without dup, like `arr-set`) and
                    ///    produce a NEW owned Bytes; a caller keeping an operand `dup`s it first. `bytes-concat` is the
                    ///    bytes of `a` then `b` (empty is the identity). `bytes-slice(buf, start, len)` is `len` bytes
                    ///    from `start`, total-or-trap (`start + len > bytes-len(buf)` traps; `len == 0` is empty, never
                    ///    a trap). `bytes-compact(buf)` returns a Bytes equal by content whose storage is INDEPENDENT
                    ///    of any larger buffer `buf` was sliced from (memory-and-resource-model.md #Retained Storage) —
                    ///    a slice that pinned a huge parent releases it. `bytes-set` is unchanged: it targets only a
                    ///    freshly `bytes-alloc`'d leaf, never a rope node.
                    fn bytes_concat(a: u32, b: u32) -> u32;
                    /// 34 — bytes of a then b (consumes both)
                    fn bytes_slice(buf: u32, start: u32, len: u32) -> u32;
                    /// 35 — len bytes from start (consumes buf)
                    fn bytes_compact(buf: u32) -> u32;
                    /// 36 — content-equal, storage-independent
                    /// ── Map (CHAMP, indices 37–45) — the REAL persistent key→value map, replacing the positional
                    ///    stub (21–25, now vestigial). Internally a Compressed Hash-Array Mapped Prefix tree over the
                    ///    SAME tagless node (no new field): a node's `raw` holds [datamap:u32][nodemap:u32][size:u32]
                    ///    and its `handles` hold data entries (2/entry: k,v) then subnodes, in bit-position order. Keys
                    ///    cross as PLAIN handles; the runtime hashes + STRUCTURALLY compares them (tag-free — no
                    ///    serialization, no upcall, no reentrancy). Correct because keys within one map are homogeneous
                    ///    (one key type/map; cross-type = compile-time reject) and every value form is canonical modulo
                    ///    Bytes-rope compaction (the compiler emits `bytes-compact` on a Bytes key before these ops).
                    ///    Iteration is deterministic (hash order); the compiler owns the canonical byte-form sort.
                    fn map_empty() -> u32;
                    /// 37 — the canonical empty map
                    fn map_insert(m: u32, key: u32, val: u32) -> u32;
                    /// 38 — m with key↦val (consumes m, key, val)
                    fn map_lookup(m: u32, key: u32) -> u32;
                    /// 39 — val, or NULL if absent (borrows m + key)
                    fn map_remove(m: u32, key: u32) -> u32;
                    /// 40 — m without key (consumes m; borrows key)
                    fn map_size(m: u32) -> u32;
                    /// 41 — entry count (O(1), from the root's size)
                    /// ── Map cursor (indices 42–45) — non-allocating iteration (rendering, equality, folds). A cursor
                    ///    is a STATELESS value: `map-iter-next` CONSUMES the cursor and returns the advanced one — at
                    ///    rc==1 it refits in place (FBIP, zero steady-state alloc), at rc>1 it path-copies (forkable /
                    ///    peekable / tee for free). `map-iter` borrows m (dups its root to keep the tree live for the
                    ///    walk); the cursor OWNS its descent-path frames, so the existing iterative `op_drop` reclaims
                    ///    it with no special-casing. `map-iter-key` returns NULL when exhausted (a key is never NULL);
                    ///    the projections BORROW (a kept key/val escapes the loop via a compiler-emitted `dup`, like
                    ///    `arr-get`). Static dispatch: the compiler emits map- vs set-iter directly (no cursor tag).
                    fn map_iter(m: u32) -> u32;
                    /// 42 — cursor at the first entry (or exhausted)
                    fn map_iter_next(cur: u32) -> u32;
                    /// 43 — advance (consumes cur, returns new cursor)
                    fn map_iter_key(cur: u32) -> u32;
                    /// 44 — current key, or NULL if exhausted (borrows)
                    fn map_iter_val(cur: u32) -> u32;
                    /// 45 — current value (borrows)
                    /// ── Set (CHAMP, indices 46–53) — the CHAMP minus the value column: entries are 1 handle, not 2.
                    ///    Same trie core, hashing, structural comparison, and RC as the map (a shared Rust core behind
                    ///    the distinct `set-*` ops — the economy does not leak across the seam). A Set is a PRIMITIVE
                    ///    collection, not a Map<T,Unit>. `set-contains` is a TOTAL predicate (no positional access;
                    ///    sets are unordered). Mirrors the map ops; the cursor obeys the same stateless/FBIP contract.
                    fn set_empty() -> u32;
                    /// 46 — the canonical empty set
                    fn set_insert(s: u32, elem: u32) -> u32;
                    /// 47 — s with elem (consumes s, elem)
                    fn set_contains(s: u32, elem: u32) -> bool;
                    /// 48 — total membership test (borrows s + elem)
                    fn set_remove(s: u32, elem: u32) -> u32;
                    /// 49 — s without elem (consumes s; borrows elem)
                    fn set_size(s: u32) -> u32;
                    /// 50 — element count (O(1))
                    fn set_iter(s: u32) -> u32;
                    /// 51 — cursor at the first element (or exhausted)
                    fn set_iter_next(cur: u32) -> u32;
                    /// 52 — advance (consumes cur, returns new cursor)
                    fn set_iter_elem(cur: u32) -> u32;
                    /// 53 — current element, or NULL if exhausted
                    /// ── Debug leak oracle (index 54). Returns the number of live heap objects (allocated and not yet
                    ///    freed). This is a VERIFICATION AID, not part of the language: the compiler NEVER imports or
                    ///    emits a call to it (it is absent from the compiler's allow-list, so the envelope and every
                    ///    emitted program are unchanged), and it composes as an extra export the program ignores
                    ///    (component-model width subtyping). A leak-check harness reads it after `run()` and asserts it
                    ///    is 0 to prove the compiler's Perceus dup/drop discipline balances. The live counter is compiled
                    ///    ONLY under the `debug-counters` cargo feature; in the default (shipped) build the counter is
                    ///    absent and this returns 0 at zero cost, so the runtime stays effectively unchanged.
                    fn live_objects() -> u32;
                    /// 54 — live heap-object count (0 unless debug)
                    /// ── Vector concat (RRB relaxed radix, index 55) — O(log N) concatenation. Joining two persistent
                    ///    vectors marks the boundary node(s) RELAXED with a per-child cumulative size table (u32 LE in
                    ///    the tagless node's `raw`, one entry per child), so the radix↔RRB distinction is an INTERNAL
                    ///    representation concern: a concatenated vector is INDISTINGUISHABLE from a push-built one by
                    ///    `vec-len`/`vec-get` (and remains valid for further `vec-push`/`vec-update`). Ownership
                    ///    (DESIGN-rc-calling-convention.md §1): a CONSTRUCTOR — CONSUMES both operands and produces a NEW
                    ///    owned vector (a caller keeping either version `dup`s it first). An empty operand is the identity
                    ///    (`concat(empty, b) == b`, `concat(a, empty) == a`).
                    fn vec_concat(a: u32, b: u32) -> u32;
                    /// 55 — a then b (consumes both)
                    /// ── Vector split (RRB relaxed radix, index 56) — O(log N) split by index. `vec-split(v, index)`
                    ///    returns `(left, right)` where `left` is elements `[0, index)` and `right` is `[index, len)`.
                    ///    Trimming the boundary spine marks the affected interior nodes RELAXED (a per-child cumulative
                    ///    size table in `raw`), so both halves are valid persistent vectors indistinguishable from
                    ///    push-built ones by `vec-len`/`vec-get` and remain valid for further push/update/concat.
                    ///    Ownership (DESIGN-rc-calling-convention.md §1): a CONSTRUCTOR — CONSUMES `v` and produces TWO
                    ///    new owned vectors (a caller keeping `v` `dup`s it first). Boundary: `index == 0` → `(empty, v)`,
                    ///    `index >= len` → `(v, empty)`. The pair crosses as a WIT `tuple<u32, u32>` (flattened to two
                    ///    return values by the component ABI).
                    fn vec_split(v: u32, index: u32) -> (u32, u32);
                    /// 56 — (left, right) at index (consumes v)
                    /// ── Set algebra (CHAMP, indices 57–59) — structural union / intersection / difference over the
                    ///    persistent set. Correctness-first over insert+contains+iterate (a recursive CHAMP node-merge
                    ///    sharing whole shared subnodes is the eventual O(min) form, DESIGN-champ-map.md — deferred); the
                    ///    result is CANONICAL by construction (built via `set-insert`, so byte-identical `champ_eq`/
                    ///    `champ_hash` regardless of build order). Ownership (DESIGN-rc-calling-convention.md §1): all
                    ///    three are CONSTRUCTORS — they CONSUME both operands and produce a NEW owned set (a caller
                    ///    keeping an operand `dup`s it first). Identities: `union(empty,b)=b`, `union(a,empty)=a`,
                    ///    `intersection(_,empty)=empty`, `difference(a,empty)=a`, `difference(empty,_)=empty`.
                    fn set_union(a: u32, b: u32) -> u32;
                    /// 57 — elements in a OR b (consumes both)
                    fn set_intersection(a: u32, b: u32) -> u32;
                    /// 58 — elements in a AND b (consumes both)
                    fn set_difference(a: u32, b: u32) -> u32;
                }
                #[doc(hidden)]
                macro_rules! __export_cadenza_runtime_heap_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "cadenza:runtime/heap#box-int")] unsafe extern "C" fn
                        export_box_int(arg0 : i64,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_box_int_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name = "cadenza:runtime/heap#get-int")] unsafe
                        extern "C" fn export_get_int(arg0 : i32,) -> i64 { unsafe {
                        $($path_to_types)*:: _export_get_int_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name = "cadenza:runtime/heap#box-bool")] unsafe
                        extern "C" fn export_box_bool(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_box_bool_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name = "cadenza:runtime/heap#get-bool")] unsafe
                        extern "C" fn export_get_bool(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_get_bool_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name = "cadenza:runtime/heap#box-float")] unsafe
                        extern "C" fn export_box_float(arg0 : f64,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_box_float_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name = "cadenza:runtime/heap#get-float")] unsafe
                        extern "C" fn export_get_float(arg0 : i32,) -> f64 { unsafe {
                        $($path_to_types)*:: _export_get_float_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name = "cadenza:runtime/heap#arr-alloc")] unsafe
                        extern "C" fn export_arr_alloc(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_arr_alloc_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name = "cadenza:runtime/heap#arr-set")] unsafe
                        extern "C" fn export_arr_set(arg0 : i32, arg1 : i32, arg2 : i32,)
                        -> i32 { unsafe { $($path_to_types)*:: _export_arr_set_cabi::<$ty
                        > (arg0, arg1, arg2) } } #[unsafe (export_name =
                        "cadenza:runtime/heap#arr-get")] unsafe extern "C" fn
                        export_arr_get(arg0 : i32, arg1 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_arr_get_cabi::<$ty > (arg0, arg1) }
                        } #[unsafe (export_name = "cadenza:runtime/heap#arr-len")] unsafe
                        extern "C" fn export_arr_len(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_arr_len_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name = "cadenza:runtime/heap#sum-new")] unsafe
                        extern "C" fn export_sum_new(arg0 : i32, arg1 : i32,) -> i32 {
                        unsafe { $($path_to_types)*:: _export_sum_new_cabi::<$ty > (arg0,
                        arg1) } } #[unsafe (export_name =
                        "cadenza:runtime/heap#sum-disc")] unsafe extern "C" fn
                        export_sum_disc(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_sum_disc_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name = "cadenza:runtime/heap#sum-payload")]
                        unsafe extern "C" fn export_sum_payload(arg0 : i32,) -> i32 {
                        unsafe { $($path_to_types)*:: _export_sum_payload_cabi::<$ty >
                        (arg0) } } #[unsafe (export_name =
                        "cadenza:runtime/heap#bytes-alloc")] unsafe extern "C" fn
                        export_bytes_alloc(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_bytes_alloc_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name = "cadenza:runtime/heap#bytes-set")] unsafe
                        extern "C" fn export_bytes_set(arg0 : i32, arg1 : i32, arg2 :
                        i32,) -> i32 { unsafe { $($path_to_types)*::
                        _export_bytes_set_cabi::<$ty > (arg0, arg1, arg2) } } #[unsafe
                        (export_name = "cadenza:runtime/heap#bytes-get")] unsafe extern
                        "C" fn export_bytes_get(arg0 : i32, arg1 : i32,) -> i32 { unsafe
                        { $($path_to_types)*:: _export_bytes_get_cabi::<$ty > (arg0,
                        arg1) } } #[unsafe (export_name =
                        "cadenza:runtime/heap#bytes-len")] unsafe extern "C" fn
                        export_bytes_len(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_bytes_len_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name = "cadenza:runtime/heap#str-new")] unsafe
                        extern "C" fn export_str_new(arg0 : * mut u8, arg1 : usize,) ->
                        i32 { unsafe { $($path_to_types)*:: _export_str_new_cabi::<$ty >
                        (arg0, arg1) } } #[unsafe (export_name =
                        "cadenza:runtime/heap#str-get")] unsafe extern "C" fn
                        export_str_get(arg0 : i32,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_str_get_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "cabi_post_cadenza:runtime/heap#str-get")] unsafe extern "C" fn
                        _post_return_str_get(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_str_get::<$ty > (arg0) } }
                        #[unsafe (export_name = "cadenza:runtime/heap#dup")] unsafe
                        extern "C" fn export_dup(arg0 : i32,) { unsafe {
                        $($path_to_types)*:: _export_dup_cabi::<$ty > (arg0) } } #[unsafe
                        (export_name = "cadenza:runtime/heap#drop")] unsafe extern "C" fn
                        export_drop(arg0 : i32,) { unsafe { $($path_to_types)*::
                        _export_drop_cabi::<$ty > (arg0) } } #[unsafe (export_name =
                        "cadenza:runtime/heap#map-alloc")] unsafe extern "C" fn
                        export_map_alloc(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_map_alloc_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name = "cadenza:runtime/heap#map-set")] unsafe
                        extern "C" fn export_map_set(arg0 : i32, arg1 : i32, arg2 : i32,
                        arg3 : i32,) -> i32 { unsafe { $($path_to_types)*::
                        _export_map_set_cabi::<$ty > (arg0, arg1, arg2, arg3) } }
                        #[unsafe (export_name = "cadenza:runtime/heap#map-key")] unsafe
                        extern "C" fn export_map_key(arg0 : i32, arg1 : i32,) -> i32 {
                        unsafe { $($path_to_types)*:: _export_map_key_cabi::<$ty > (arg0,
                        arg1) } } #[unsafe (export_name =
                        "cadenza:runtime/heap#map-val")] unsafe extern "C" fn
                        export_map_val(arg0 : i32, arg1 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_map_val_cabi::<$ty > (arg0, arg1) }
                        } #[unsafe (export_name = "cadenza:runtime/heap#map-len")] unsafe
                        extern "C" fn export_map_len(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_map_len_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name = "cadenza:runtime/heap#reset")] unsafe
                        extern "C" fn export_reset(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_reset_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name = "cadenza:runtime/heap#arr-alloc-reuse")]
                        unsafe extern "C" fn export_arr_alloc_reuse(arg0 : i32, arg1 :
                        i32,) -> i32 { unsafe { $($path_to_types)*::
                        _export_arr_alloc_reuse_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name = "cadenza:runtime/heap#sum-new-reuse")] unsafe
                        extern "C" fn export_sum_new_reuse(arg0 : i32, arg1 : i32, arg2 :
                        i32,) -> i32 { unsafe { $($path_to_types)*::
                        _export_sum_new_reuse_cabi::<$ty > (arg0, arg1, arg2) } }
                        #[unsafe (export_name = "cadenza:runtime/heap#vec-empty")] unsafe
                        extern "C" fn export_vec_empty() -> i32 { unsafe {
                        $($path_to_types)*:: _export_vec_empty_cabi::<$ty > () } }
                        #[unsafe (export_name = "cadenza:runtime/heap#vec-len")] unsafe
                        extern "C" fn export_vec_len(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_vec_len_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name = "cadenza:runtime/heap#vec-get")] unsafe
                        extern "C" fn export_vec_get(arg0 : i32, arg1 : i32,) -> i32 {
                        unsafe { $($path_to_types)*:: _export_vec_get_cabi::<$ty > (arg0,
                        arg1) } } #[unsafe (export_name =
                        "cadenza:runtime/heap#vec-push")] unsafe extern "C" fn
                        export_vec_push(arg0 : i32, arg1 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_vec_push_cabi::<$ty > (arg0, arg1) }
                        } #[unsafe (export_name = "cadenza:runtime/heap#vec-update")]
                        unsafe extern "C" fn export_vec_update(arg0 : i32, arg1 : i32,
                        arg2 : i32,) -> i32 { unsafe { $($path_to_types)*::
                        _export_vec_update_cabi::<$ty > (arg0, arg1, arg2) } } #[unsafe
                        (export_name = "cadenza:runtime/heap#bytes-concat")] unsafe
                        extern "C" fn export_bytes_concat(arg0 : i32, arg1 : i32,) -> i32
                        { unsafe { $($path_to_types)*:: _export_bytes_concat_cabi::<$ty >
                        (arg0, arg1) } } #[unsafe (export_name =
                        "cadenza:runtime/heap#bytes-slice")] unsafe extern "C" fn
                        export_bytes_slice(arg0 : i32, arg1 : i32, arg2 : i32,) -> i32 {
                        unsafe { $($path_to_types)*:: _export_bytes_slice_cabi::<$ty >
                        (arg0, arg1, arg2) } } #[unsafe (export_name =
                        "cadenza:runtime/heap#bytes-compact")] unsafe extern "C" fn
                        export_bytes_compact(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_bytes_compact_cabi::<$ty > (arg0) }
                        } #[unsafe (export_name = "cadenza:runtime/heap#map-empty")]
                        unsafe extern "C" fn export_map_empty() -> i32 { unsafe {
                        $($path_to_types)*:: _export_map_empty_cabi::<$ty > () } }
                        #[unsafe (export_name = "cadenza:runtime/heap#map-insert")]
                        unsafe extern "C" fn export_map_insert(arg0 : i32, arg1 : i32,
                        arg2 : i32,) -> i32 { unsafe { $($path_to_types)*::
                        _export_map_insert_cabi::<$ty > (arg0, arg1, arg2) } } #[unsafe
                        (export_name = "cadenza:runtime/heap#map-lookup")] unsafe extern
                        "C" fn export_map_lookup(arg0 : i32, arg1 : i32,) -> i32 { unsafe
                        { $($path_to_types)*:: _export_map_lookup_cabi::<$ty > (arg0,
                        arg1) } } #[unsafe (export_name =
                        "cadenza:runtime/heap#map-remove")] unsafe extern "C" fn
                        export_map_remove(arg0 : i32, arg1 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_map_remove_cabi::<$ty > (arg0, arg1)
                        } } #[unsafe (export_name = "cadenza:runtime/heap#map-size")]
                        unsafe extern "C" fn export_map_size(arg0 : i32,) -> i32 { unsafe
                        { $($path_to_types)*:: _export_map_size_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name = "cadenza:runtime/heap#map-iter")] unsafe
                        extern "C" fn export_map_iter(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_map_iter_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name = "cadenza:runtime/heap#map-iter-next")]
                        unsafe extern "C" fn export_map_iter_next(arg0 : i32,) -> i32 {
                        unsafe { $($path_to_types)*:: _export_map_iter_next_cabi::<$ty >
                        (arg0) } } #[unsafe (export_name =
                        "cadenza:runtime/heap#map-iter-key")] unsafe extern "C" fn
                        export_map_iter_key(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_map_iter_key_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name = "cadenza:runtime/heap#map-iter-val")]
                        unsafe extern "C" fn export_map_iter_val(arg0 : i32,) -> i32 {
                        unsafe { $($path_to_types)*:: _export_map_iter_val_cabi::<$ty >
                        (arg0) } } #[unsafe (export_name =
                        "cadenza:runtime/heap#set-empty")] unsafe extern "C" fn
                        export_set_empty() -> i32 { unsafe { $($path_to_types)*::
                        _export_set_empty_cabi::<$ty > () } } #[unsafe (export_name =
                        "cadenza:runtime/heap#set-insert")] unsafe extern "C" fn
                        export_set_insert(arg0 : i32, arg1 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_set_insert_cabi::<$ty > (arg0, arg1)
                        } } #[unsafe (export_name = "cadenza:runtime/heap#set-contains")]
                        unsafe extern "C" fn export_set_contains(arg0 : i32, arg1 : i32,)
                        -> i32 { unsafe { $($path_to_types)*::
                        _export_set_contains_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name = "cadenza:runtime/heap#set-remove")] unsafe extern
                        "C" fn export_set_remove(arg0 : i32, arg1 : i32,) -> i32 { unsafe
                        { $($path_to_types)*:: _export_set_remove_cabi::<$ty > (arg0,
                        arg1) } } #[unsafe (export_name =
                        "cadenza:runtime/heap#set-size")] unsafe extern "C" fn
                        export_set_size(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_set_size_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name = "cadenza:runtime/heap#set-iter")] unsafe
                        extern "C" fn export_set_iter(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_set_iter_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name = "cadenza:runtime/heap#set-iter-next")]
                        unsafe extern "C" fn export_set_iter_next(arg0 : i32,) -> i32 {
                        unsafe { $($path_to_types)*:: _export_set_iter_next_cabi::<$ty >
                        (arg0) } } #[unsafe (export_name =
                        "cadenza:runtime/heap#set-iter-elem")] unsafe extern "C" fn
                        export_set_iter_elem(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_set_iter_elem_cabi::<$ty > (arg0) }
                        } #[unsafe (export_name = "cadenza:runtime/heap#live-objects")]
                        unsafe extern "C" fn export_live_objects() -> i32 { unsafe {
                        $($path_to_types)*:: _export_live_objects_cabi::<$ty > () } }
                        #[unsafe (export_name = "cadenza:runtime/heap#vec-concat")]
                        unsafe extern "C" fn export_vec_concat(arg0 : i32, arg1 : i32,)
                        -> i32 { unsafe { $($path_to_types)*::
                        _export_vec_concat_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name = "cadenza:runtime/heap#vec-split")] unsafe extern
                        "C" fn export_vec_split(arg0 : i32, arg1 : i32,) -> * mut u8 {
                        unsafe { $($path_to_types)*:: _export_vec_split_cabi::<$ty >
                        (arg0, arg1) } } #[unsafe (export_name =
                        "cadenza:runtime/heap#set-union")] unsafe extern "C" fn
                        export_set_union(arg0 : i32, arg1 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_set_union_cabi::<$ty > (arg0, arg1)
                        } } #[unsafe (export_name =
                        "cadenza:runtime/heap#set-intersection")] unsafe extern "C" fn
                        export_set_intersection(arg0 : i32, arg1 : i32,) -> i32 { unsafe
                        { $($path_to_types)*:: _export_set_intersection_cabi::<$ty >
                        (arg0, arg1) } } #[unsafe (export_name =
                        "cadenza:runtime/heap#set-difference")] unsafe extern "C" fn
                        export_set_difference(arg0 : i32, arg1 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_set_difference_cabi::<$ty > (arg0,
                        arg1) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_cadenza_runtime_heap_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 2
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub use alloc_crate::string::String;
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_runtime_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::cadenza::runtime::heap::__export_cadenza_runtime_heap_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::cadenza::runtime::heap);
    };
}
#[doc(inline)]
pub(crate) use __export_runtime_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:cadenza:runtime:runtime:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1582] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xb0\x0b\x01A\x02\x01\
A\x02\x01Bc\x01@\x01\x01vx\0y\x04\0\x07box-int\x01\0\x01@\x01\x06handley\0x\x04\0\
\x07get-int\x01\x01\x01@\x01\x01v\x7f\0y\x04\0\x08box-bool\x01\x02\x01@\x01\x06h\
andley\0\x7f\x04\0\x08get-bool\x01\x03\x01@\x01\x01vu\0y\x04\0\x09box-float\x01\x04\
\x01@\x01\x06handley\0u\x04\0\x09get-float\x01\x05\x01@\x01\x03leny\0y\x04\0\x09\
arr-alloc\x01\x06\x01@\x03\x03arry\x05indexy\x04elemy\0y\x04\0\x07arr-set\x01\x07\
\x01@\x02\x03arry\x05indexy\0y\x04\0\x07arr-get\x01\x08\x01@\x01\x03arry\0y\x04\0\
\x07arr-len\x01\x09\x01@\x02\x04discy\x07payloady\0y\x04\0\x07sum-new\x01\x0a\x01\
@\x01\x06handley\0y\x04\0\x08sum-disc\x01\x0b\x04\0\x0bsum-payload\x01\x0b\x04\0\
\x0bbytes-alloc\x01\x06\x01@\x03\x03bufy\x05indexy\x05valuey\0y\x04\0\x09bytes-s\
et\x01\x0c\x01@\x02\x03bufy\x05indexy\0y\x04\0\x09bytes-get\x01\x0d\x01@\x01\x03\
bufy\0y\x04\0\x09bytes-len\x01\x0e\x01@\x01\x01ss\0y\x04\0\x07str-new\x01\x0f\x01\
@\x01\x06handley\0s\x04\0\x07str-get\x01\x10\x01@\x01\x06handley\x01\0\x04\0\x03\
dup\x01\x11\x04\0\x04drop\x01\x11\x04\0\x09map-alloc\x01\x06\x01@\x04\x01my\x05i\
ndexy\x03keyy\x05valuey\0y\x04\0\x07map-set\x01\x12\x01@\x02\x01my\x05indexy\0y\x04\
\0\x07map-key\x01\x13\x04\0\x07map-val\x01\x13\x01@\x01\x01my\0y\x04\0\x07map-le\
n\x01\x14\x01@\x01\x04nodey\0y\x04\0\x05reset\x01\x15\x01@\x02\x03leny\x05tokeny\
\0y\x04\0\x0farr-alloc-reuse\x01\x16\x01@\x03\x04discy\x07payloady\x05tokeny\0y\x04\
\0\x0dsum-new-reuse\x01\x17\x01@\0\0y\x04\0\x09vec-empty\x01\x18\x01@\x01\x01vy\0\
y\x04\0\x07vec-len\x01\x19\x01@\x02\x01vy\x05indexy\0y\x04\0\x07vec-get\x01\x1a\x01\
@\x02\x01vy\x04elemy\0y\x04\0\x08vec-push\x01\x1b\x01@\x03\x01vy\x05indexy\x04el\
emy\0y\x04\0\x0avec-update\x01\x1c\x01@\x02\x01ay\x01by\0y\x04\0\x0cbytes-concat\
\x01\x1d\x01@\x03\x03bufy\x05starty\x03leny\0y\x04\0\x0bbytes-slice\x01\x1e\x04\0\
\x0dbytes-compact\x01\x0e\x04\0\x09map-empty\x01\x18\x01@\x03\x01my\x03keyy\x03v\
aly\0y\x04\0\x0amap-insert\x01\x1f\x01@\x02\x01my\x03keyy\0y\x04\0\x0amap-lookup\
\x01\x20\x04\0\x0amap-remove\x01\x20\x04\0\x08map-size\x01\x14\x04\0\x08map-iter\
\x01\x14\x01@\x01\x03cury\0y\x04\0\x0dmap-iter-next\x01!\x04\0\x0cmap-iter-key\x01\
!\x04\0\x0cmap-iter-val\x01!\x04\0\x09set-empty\x01\x18\x01@\x02\x01sy\x04elemy\0\
y\x04\0\x0aset-insert\x01\"\x01@\x02\x01sy\x04elemy\0\x7f\x04\0\x0cset-contains\x01\
#\x04\0\x0aset-remove\x01\"\x01@\x01\x01sy\0y\x04\0\x08set-size\x01$\x04\0\x08se\
t-iter\x01$\x04\0\x0dset-iter-next\x01!\x04\0\x0dset-iter-elem\x01!\x04\0\x0cliv\
e-objects\x01\x18\x04\0\x0avec-concat\x01\x1d\x01o\x02yy\x01@\x02\x01vy\x05index\
y\0%\x04\0\x09vec-split\x01&\x04\0\x09set-union\x01\x1d\x04\0\x10set-intersectio\
n\x01\x1d\x04\0\x0eset-difference\x01\x1d\x04\0\x14cadenza:runtime/heap\x05\0\x04\
\0\x17cadenza:runtime/runtime\x04\0\x0b\x0d\x01\0\x07runtime\x03\0\0\0G\x09produ\
cers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x06\
0.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
