(case "tmb2 a SILENT POST-RESUME LEVY — each inner arm replays the tail then levies the outer handler DISCARDING the levy's value and answers a tombstone, the levies are observable ONLY through the outer audit read after the inner handle completes, and a dead-code elision that drops the valueless levy (its answer feeds nothing) shifts the audit by ten while leaving the inner result untouched"
  (input  (do
            (effect T (op levy (-> Int64)) (op audit (-> Int64)))
            (effect E (op tick (-> Int64)))
            (def (main (: n Int64))
              (handle T (% n 3)
                ((levy () t (resume t (+ t 5)))
                 (audit () t (resume t t)))
                (+ (* 100 (handle E (: 1 Int64)
                            ((tick () s
                              (do (resume s (+ s 1))
                                  (T.levy)
                                  (+ s 40))))
                            (let ((a (E.tick)))
                              (let ((b (E.tick)))
                                (+ a (* 10 b))))))
                   (T.audit))))
            (export main)))
  (call   main (: 10 Int64)) (output (: 4111 Int64))
  (call   main (: 0 Int64)) (output (: 4110 Int64)))
