(case "swm1 a SLIDING-WINDOW maximum of width 3 — each push appends and evicts the oldest element once the window is full, answering the max scanned from the LIVE window, and the seeds disagree on which pushes set new maxima"
  (input  (do
            (effect W (op push (-> Int64 Int64)))
            (def (dropf (: xs (List Int64)) (: i Int64) (: acc (List Int64)))
              (if (< i (List.len xs))
                  (dropf xs (+ i 1) (List.push acc (match (List.at xs i) ((Some v) v) ((None u) 0))))
                  acc))
            (def (maxs (: xs (List Int64)) (: i Int64) (: best Int64))
              (if (< i (List.len xs))
                  (maxs xs (+ i 1)
                        (match (List.at xs i)
                          ((Some v) (if (< best v) v best))
                          ((None u) best)))
                  best))
            (def (main (: n Int64))
              (handle W (: (list) (List Int64))
                ((push (v) st
                  (let ((grown (List.push st v)))
                    (if (< 3 (List.len grown))
                        (let ((trimmed (dropf grown 1 (: (list) (List Int64)))))
                          (resume (maxs trimmed 0 -999) trimmed))
                        (resume (maxs grown 0 -999) grown)))))
                (let ((a (W.push (+ n 2))))
                  (let ((b (W.push 5)))
                    (let ((c (W.push (- n 1))))
                      (let ((d (W.push 8)))
                        (let ((e (W.push 3)))
                          (let ((f (W.push (+ n 6))))
                            (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 a) b)) c)) d)) e)) f)))))))))
            (export main)))
  (call   main (: 10 Int64)) (output (: 121212090916 Int64))
  (call   main (: 0 Int64)) (output (: 20505080808 Int64)))
