(case "pysd1 probe: a SET-STATE handler enforces DEDUP across the seam — add(k) threads Set.insert and answers the new size, so re-adding an already-present key does not grow the set; a has(k) op reads membership, confirming the CHAMP set's dedup and contains both survive the resume threading"
  (input (do
  (effect E (op add (-> Int64 Int64)) (op has (-> Int64 Int64)))
  (def (main (: n Int64))
    (handle E (Set.of (list (% n 3)))
      ((add (k) s (resume (Set.len (Set.insert s k)) (Set.insert s k)))
       (has (k) s (resume (if (Set.contains s k) (: 1 Int64) (: 0 Int64)) s)))
      (do (E.add (% n 3))
          (do (E.add (: 7 Int64))
              (+ (* 1000 (E.add (% n 3)))
                 (+ (* 100 (E.has (% n 3)))
                    (+ (* 10 (E.has (: 7 Int64)))
                       (E.has (: 99 Int64)))))))))
  (export main)))
  (call   main (: 10 Int64)) (output (: 2110 Int64))
  (call   main (: 5 Int64)) (output (: 2110 Int64)))
