(do
  (effect A (op tick (-> Int64)) (op beat (-> Int64)))
  (def (drive (: d Int64))
    (if (<= d 0) 0 (+ (A.tick) (drive (- d 1)))))
  (def (main (: n Int64))
    (handle A (% n 3)
      ((tick () s (let ((k (A.beat))) (resume (+ s 1) (+ s k))))
       (beat () s (resume (+ s 1) (+ s 1))))
      (drive n)))
  (export main))
