(do
  (effect A (op tick (-> Int64)))
  (effect B (op beat (-> Int64)))
  (def (drive (: d Int64))
    (if (<= d 0) 0 (+ (A.tick) (drive (- d 1)))))
  (def (main (: n Int64))
    (handle B (: 0 Int64)
      ((beat () bs (resume (+ bs 1) (+ bs 1))))
      (handle A (% n 3)
        ((tick () s (let ((k (B.beat))) (resume (+ s 1) (+ s k)))))
        (drive n))))
  (export main))
