//! GENERATED by `xtask-codegen-declines` from `data/unsupported.sexp` — DO NOT EDIT.
//! Edit the sexpr source + run `cargo run -p xtask-codegen-declines` (a `cdzDeclines` drift-check
//! reds if this committed file is stale). The unsupported-error tracker's `DeclineId` catalog:
//! a stable, enumerable referent for every construct rcdzc declines to compile (operator seq-286).
use crate::diag::Code;
/// The stable, enumerable catalog of every construct rcdzc declines to compile. A `DeclineId` names
/// a REASON (a capability the compiler does not realize), not a call site; `DeclineId::ALL` is a
/// complete, by-construction list. Generated from `data/unsupported.sexp` (the source of truth).
#[derive(Copy, Clone, PartialEq, Eq, Debug, Hash)]
pub enum DeclineId {
    ///A host effect and a peer effect both composed with a resource-escaping entrypoint (#6163).
    WasmHostPeerResourceFusion,
    ///An export that both receives and returns a closure — a closure transformer (#6216).
    WasmClosureTransformer,
    ///A compound result alongside a closure (plain or round-trip) export (#6216).
    WasmCompoundResultWithClosureExport,
    ///A recursive-sum / runtime-collection value rendered as a host-boundary result (#6216).
    WasmValueFormWalkerRecursive,
    ///A bytes-crossing host op whose signature has no host-boundary form (#6216).
    WasmBytesCrossingHostOpNoBoundaryForm,
    ///Matching a map-pattern payload against a runtime map (#6216, select/dispatch).
    WasmMapPatternRuntimeMap,
    ///A built-in operation used as a runtime value (would need a synthesized runtime closure). Coded CDZ0900 at its emit site (lower/compute.rs) by #6349.
    PrimAsValueNeedsClosure,
    ///An effect handler in a form the tail-resumptive fold does not specialize (cross-function / non-tail resume) — v-effects #6219.
    TailResumptiveFoldUnhandledForm,
    ///Matching over a heap-backed Set/Map scrutinee — even a whole-value binder — needs a heap walk the compiler does not yet emit; surfaced by the dedup self-suppression fix (#6417).
    MatchOverHeapCollectionScrutinee,
    ///A recursive function applied where it would need runtime specialization (the eval beta-reduction recursion guard, eval.rs); reworded off deferral wording to "which is not supported" by v-core-opt #6565.
    RecursiveFunctionRuntimeSpecialization,
    ///A deeper compound sub-pattern below a record field — a record match pattern (resolve.rs match_arm_record_binds), a tuple/list/constructor-nested record match (resolve.rs, reclassified CDZ0201->CDZ0900 by #6850), or a record binding pattern (resolve.rs + lower/match_tree.rs, #6800/#6838). v-ast-compound is building PathStep::Field (name-keyed record-field descent) to make most such cases BIND; whatever still declines is tagged declined(id) in that build PR.
    NestedRecordFieldPatternDescent,
    ///A closure crossing the host boundary whose parameter, result, or capture type has no machine representation — one family over the 3 sibling diag.rs declines CLOSURE_PARAM/RESULT/CAPTURE_NO_REPR. A fully-typed closure crosses via the host-closure resource; these are the un-built frontier (e.g. a bare `(fn (v1) v1)` in a list whose v1 solves to Any — infer recovers the param type from an enclosing higher-order arrow when it can, this face cannot). Fuzzer-surfaced (v-cdz-smith reachability sweep #6878, faces #1/#6); classified feature-gap by v-rust-backend. NUANCE: the pure-Any param subcase borders the CDZ0203 annotate-it undetermined-type reject — kept as a closure-boundary family tag; the operator may reclassify the pure-Any face to a coded CDZ0203 reject later.
    WasmClosureBoundaryNoRepr,
    ///A parameterized heap-return export (the make(a…)->own<t> resource-escape path) forwards scalar and fixed-shape scalar tuple/record params only; a String/Bytes/list param has no boundary representation on this path. The mem-leaf param lift that would forward it exists for the typed-interface member route (#6624/#6639) but is not wired on the bare resource-escape path. Fuzzer-surfaced (#6878 face #3); classified feature-gap (buildable-next) by v-rust-backend. Emit site backend/wasm/mod.rs:9277.
    WasmHeapReturnParamNoBoundaryRep,
}
impl DeclineId {
    /// The complete catalog (declared order — byte-deterministic).
    pub const ALL: &'static [DeclineId] = &[
        DeclineId::WasmHostPeerResourceFusion,
        DeclineId::WasmClosureTransformer,
        DeclineId::WasmCompoundResultWithClosureExport,
        DeclineId::WasmValueFormWalkerRecursive,
        DeclineId::WasmBytesCrossingHostOpNoBoundaryForm,
        DeclineId::WasmMapPatternRuntimeMap,
        DeclineId::PrimAsValueNeedsClosure,
        DeclineId::TailResumptiveFoldUnhandledForm,
        DeclineId::MatchOverHeapCollectionScrutinee,
        DeclineId::RecursiveFunctionRuntimeSpecialization,
        DeclineId::NestedRecordFieldPatternDescent,
        DeclineId::WasmClosureBoundaryNoRepr,
        DeclineId::WasmHeapReturnParamNoBoundaryRep,
    ];
    /// The stable kebab-case registry key (the durable referent `data/unsupported.sexp` pins).
    pub fn key(self) -> &'static str {
        match self {
            DeclineId::WasmHostPeerResourceFusion => "wasm-host-peer-resource-fusion",
            DeclineId::WasmClosureTransformer => "wasm-closure-transformer",
            DeclineId::WasmCompoundResultWithClosureExport => {
                "wasm-compound-result-with-closure-export"
            }
            DeclineId::WasmValueFormWalkerRecursive => "wasm-value-form-walker-recursive",
            DeclineId::WasmBytesCrossingHostOpNoBoundaryForm => {
                "wasm-bytes-crossing-host-op-no-boundary-form"
            }
            DeclineId::WasmMapPatternRuntimeMap => "wasm-map-pattern-runtime-map",
            DeclineId::PrimAsValueNeedsClosure => "prim-as-value-needs-closure",
            DeclineId::TailResumptiveFoldUnhandledForm => "tail-resumptive-fold-unhandled-form",
            DeclineId::MatchOverHeapCollectionScrutinee => "match-over-heap-collection-scrutinee",
            DeclineId::RecursiveFunctionRuntimeSpecialization => {
                "recursive-function-runtime-specialization"
            }
            DeclineId::NestedRecordFieldPatternDescent => "nested-record-field-pattern-descent",
            DeclineId::WasmClosureBoundaryNoRepr => "wasm-closure-boundary-no-repr",
            DeclineId::WasmHeapReturnParamNoBoundaryRep => "wasm-heap-return-param-no-boundary-rep",
        }
    }
    /// The umbrella code this decline carries (`Some(CDZ0900)` = coded; `None` = still codeless).
    pub fn code(self) -> Option<Code> {
        match self {
            DeclineId::WasmHostPeerResourceFusion => Some(Code::UnsupportedConstruct),
            DeclineId::WasmClosureTransformer => Some(Code::UnsupportedConstruct),
            DeclineId::WasmCompoundResultWithClosureExport => Some(Code::UnsupportedConstruct),
            DeclineId::WasmValueFormWalkerRecursive => Some(Code::UnsupportedConstruct),
            DeclineId::WasmBytesCrossingHostOpNoBoundaryForm => Some(Code::UnsupportedConstruct),
            DeclineId::WasmMapPatternRuntimeMap => Some(Code::UnsupportedConstruct),
            DeclineId::PrimAsValueNeedsClosure => Some(Code::UnsupportedConstruct),
            DeclineId::TailResumptiveFoldUnhandledForm => Some(Code::UnsupportedConstruct),
            DeclineId::MatchOverHeapCollectionScrutinee => Some(Code::UnsupportedConstruct),
            DeclineId::RecursiveFunctionRuntimeSpecialization => Some(Code::UnsupportedConstruct),
            DeclineId::NestedRecordFieldPatternDescent => Some(Code::UnsupportedConstruct),
            DeclineId::WasmClosureBoundaryNoRepr => Some(Code::UnsupportedConstruct),
            DeclineId::WasmHeapReturnParamNoBoundaryRep => Some(Code::UnsupportedConstruct),
        }
    }
    /// A canonical one-line reason, independent of the runtime `format!` message's specifics.
    pub fn reason(self) -> &'static str {
        match self {
            DeclineId::WasmHostPeerResourceFusion => {
                "a host effect and a peer effect composed with a resource-escaping entrypoint"
            }
            DeclineId::WasmClosureTransformer => {
                "an export that both receives and returns a closure"
            }
            DeclineId::WasmCompoundResultWithClosureExport => {
                "a compound result alongside a closure export"
            }
            DeclineId::WasmValueFormWalkerRecursive => {
                "a recursive-sum or runtime-collection value as a host-boundary result"
            }
            DeclineId::WasmBytesCrossingHostOpNoBoundaryForm => {
                "a host op whose signature has no host-boundary form"
            }
            DeclineId::WasmMapPatternRuntimeMap => {
                "matching a map-pattern payload against a runtime map"
            }
            DeclineId::PrimAsValueNeedsClosure => "a built-in operation used as a runtime value",
            DeclineId::TailResumptiveFoldUnhandledForm => {
                "an effect handler in a form the tail-resumptive fold does not specialize"
            }
            DeclineId::MatchOverHeapCollectionScrutinee => {
                "matching over a heap-backed Set or Map scrutinee"
            }
            DeclineId::RecursiveFunctionRuntimeSpecialization => {
                "a recursive function needs runtime specialization"
            }
            DeclineId::NestedRecordFieldPatternDescent => {
                "a nested compound sub-pattern below a record field"
            }
            DeclineId::WasmClosureBoundaryNoRepr => {
                "a closure's param, result, or capture type has no machine representation"
            }
            DeclineId::WasmHeapReturnParamNoBoundaryRep => {
                "a parameterized heap-return export forwards scalar params only; this param type has no boundary representation"
            }
        }
    }
}
