//! GENERATED by `xtask-codegen-declines` from `data/unsupported.sexp` — DO NOT EDIT.
//! Edit the sexpr source + run `cargo run -p xtask-codegen-declines` (a `cdzDeclines` drift-check
//! reds if this committed file is stale). The unsupported-error tracker's `DeclineId` catalog:
//! a stable, enumerable referent for every construct rcdzc declines to compile (operator seq-286).
use crate::diag::Code;
/// The stable, enumerable catalog of every construct rcdzc declines to compile. A `DeclineId` names
/// a REASON (a capability the compiler does not realize), not a call site; `DeclineId::ALL` is a
/// complete, by-construction list. Generated from `data/unsupported.sexp` (the source of truth).
#[derive(Copy, Clone, PartialEq, Eq, Debug, Hash)]
pub enum DeclineId {
    ///A host effect and a peer effect both composed with a resource-escaping entrypoint (#6163).
    WasmHostPeerResourceFusion,
    ///An export that both receives and returns a closure — a closure transformer (#6216).
    WasmClosureTransformer,
    ///A compound result alongside a closure (plain or round-trip) export (#6216).
    WasmCompoundResultWithClosureExport,
    ///A recursive-sum / runtime-collection value rendered as a host-boundary result (#6216).
    WasmValueFormWalkerRecursive,
    ///A bytes-crossing host op whose signature has no host-boundary form (#6216).
    WasmBytesCrossingHostOpNoBoundaryForm,
    ///Matching a map-pattern payload against a runtime map (#6216, select/dispatch).
    WasmMapPatternRuntimeMap,
    ///A built-in operation used as a runtime value (would need a synthesized runtime closure). Coded CDZ0900 at its emit site (lower/compute.rs) by #6349.
    PrimAsValueNeedsClosure,
    ///An effect handler in a form the tail-resumptive fold does not specialize (cross-function / non-tail resume) — v-effects #6219.
    TailResumptiveFoldUnhandledForm,
    ///Matching over a heap-backed Set/Map scrutinee — even a whole-value binder — needs a heap walk the compiler does not yet emit; surfaced by the dedup self-suppression fix (#6417).
    MatchOverHeapCollectionScrutinee,
    ///A recursive function applied where it would need runtime specialization (the eval beta-reduction recursion guard, eval.rs); reworded off deferral wording to "which is not supported" by v-core-opt #6565.
    RecursiveFunctionRuntimeSpecialization,
    ///A refutable VARIANT sub-pattern below a record field (#record((= x (Some c)))), in a match OR a binding pattern — the sole remaining residual. v-ast-compound BUILT everything else: the POSITIONAL Elem-reachable case (#6890 match + #6911 binding) AND the RECORD/tuple/list-below-a-field case (#6944, name-keyed RecordSubStep::Field, both faces) — those all BIND now. What STILL declines (this id): only a VARIANT below a record field, which is REFUTABLE and needs the match-arm switch-lowering path (a separate increment). Emit sites: binding — resolve.rs last_binder_named (has_variant→declined) + lower/match_tree.rs check_binding_pattern; match — resolve.rs match_arm_record_binds Unwireable + Case-6rec-nested skips Payload → Case-6rec-nested-decline.
    NestedRecordFieldPatternDescent,
    ///A closure crossing the host boundary whose parameter, result, or capture type has no machine representation — one family over the 3 sibling diag.rs declines CLOSURE_PARAM/RESULT/CAPTURE_NO_REPR. A fully-typed closure crosses via the host-closure resource; these are the un-built frontier (e.g. a bare `(fn (v1) v1)` in a list whose v1 solves to Any — infer recovers the param type from an enclosing higher-order arrow when it can, this face cannot). Fuzzer-surfaced (v-cdz-smith reachability sweep #6878, faces #1/#6); classified feature-gap by v-rust-backend. NUANCE: the pure-Any param subcase borders the CDZ0203 annotate-it undetermined-type reject — kept as a closure-boundary family tag; the operator may reclassify the pure-Any face to a coded CDZ0203 reject later.
    WasmClosureBoundaryNoRepr,
    ///A parameterized heap-return export (the make(a…)->own<t> resource-escape path) forwards scalar and fixed-shape scalar tuple/record params only; a String/Bytes/list param has no boundary representation on this path. The mem-leaf param lift that would forward it exists for the typed-interface member route (#6624/#6639) but is not wired on the bare resource-escape path. Fuzzer-surfaced (#6878 face #3); classified feature-gap (buildable-next) by v-rust-backend. Emit site backend/wasm/mod.rs:9277.
    WasmHeapReturnParamNoBoundaryRep,
    ///A parameterized (non-nullary) export whose scalar params are fine but whose heap RESULT (List/Option/Result/Tuple/Symbol/...) reached the boundary: the value form is emitted only for a nullary constant-bake export, and a runtime value-encode render for it is not available. The dominant reachable heap-return decline (v-cdz-smith #9183 reachability census; the ~18 return-type variants are one logical gap). Classified feature-gap by v-rust-backend. Emit site backend/wasm/mod.rs:1205.
    WasmParameterizedHeapReturnNoValueEncode,
    ///A bare (effect ...) host operation whose argument or result type has no component boundary form. On a bare effect, host results cross as a scalar/unit and arguments as a scalar/unit/string or a Bytes (list<u8>); a Bytes/option<list<u8>> RESULT crosses only on the WORLD-DRIVEN (wit-world) path, and a record/compound argument or a list<list<u8>>/list<tuple> result is not supported on a bare effect. THE dominant reachable decline (v-cdz-smith #9183 census: ~17.7k hits across the result and argument faces = one emit site backend/wasm/mod.rs:211, via host::first_unrepresentable_host_op). Distinct from WasmBytesCrossingHostOpNoBoundaryForm (the narrower bytes-crossing-member site). Classified feature-gap by v-rust-backend.
    WasmHostOpNoBoundaryFormOnBareEffect,
    ///An entrypoint delegating more than one distinct host effect. The host-delegation emit binds one component interface per envelope, so two distinct effect names cannot both be delegated. One logical gap over 6 emit sites in backend/wasm/mod.rs: the bare host-delegating path, four resource-escaping-entrypoint variants, and the closure-export variant. Reachable via the bare path (v-cdz-smith #9183 census, ~216 hits). Classified feature-gap by v-rust-backend.
    WasmMultiHostEffectDelegation,
}
impl DeclineId {
    /// The complete catalog (declared order — byte-deterministic).
    pub const ALL: &'static [DeclineId] = &[
        DeclineId::WasmHostPeerResourceFusion,
        DeclineId::WasmClosureTransformer,
        DeclineId::WasmCompoundResultWithClosureExport,
        DeclineId::WasmValueFormWalkerRecursive,
        DeclineId::WasmBytesCrossingHostOpNoBoundaryForm,
        DeclineId::WasmMapPatternRuntimeMap,
        DeclineId::PrimAsValueNeedsClosure,
        DeclineId::TailResumptiveFoldUnhandledForm,
        DeclineId::MatchOverHeapCollectionScrutinee,
        DeclineId::RecursiveFunctionRuntimeSpecialization,
        DeclineId::NestedRecordFieldPatternDescent,
        DeclineId::WasmClosureBoundaryNoRepr,
        DeclineId::WasmHeapReturnParamNoBoundaryRep,
        DeclineId::WasmParameterizedHeapReturnNoValueEncode,
        DeclineId::WasmHostOpNoBoundaryFormOnBareEffect,
        DeclineId::WasmMultiHostEffectDelegation,
    ];
    /// The stable kebab-case registry key (the durable referent `data/unsupported.sexp` pins).
    pub fn key(self) -> &'static str {
        match self {
            DeclineId::WasmHostPeerResourceFusion => "wasm-host-peer-resource-fusion",
            DeclineId::WasmClosureTransformer => "wasm-closure-transformer",
            DeclineId::WasmCompoundResultWithClosureExport => {
                "wasm-compound-result-with-closure-export"
            }
            DeclineId::WasmValueFormWalkerRecursive => "wasm-value-form-walker-recursive",
            DeclineId::WasmBytesCrossingHostOpNoBoundaryForm => {
                "wasm-bytes-crossing-host-op-no-boundary-form"
            }
            DeclineId::WasmMapPatternRuntimeMap => "wasm-map-pattern-runtime-map",
            DeclineId::PrimAsValueNeedsClosure => "prim-as-value-needs-closure",
            DeclineId::TailResumptiveFoldUnhandledForm => "tail-resumptive-fold-unhandled-form",
            DeclineId::MatchOverHeapCollectionScrutinee => "match-over-heap-collection-scrutinee",
            DeclineId::RecursiveFunctionRuntimeSpecialization => {
                "recursive-function-runtime-specialization"
            }
            DeclineId::NestedRecordFieldPatternDescent => "nested-record-field-pattern-descent",
            DeclineId::WasmClosureBoundaryNoRepr => "wasm-closure-boundary-no-repr",
            DeclineId::WasmHeapReturnParamNoBoundaryRep => "wasm-heap-return-param-no-boundary-rep",
            DeclineId::WasmParameterizedHeapReturnNoValueEncode => {
                "wasm-parameterized-heap-return-no-value-encode"
            }
            DeclineId::WasmHostOpNoBoundaryFormOnBareEffect => {
                "wasm-host-op-no-boundary-form-on-bare-effect"
            }
            DeclineId::WasmMultiHostEffectDelegation => "wasm-multi-host-effect-delegation",
        }
    }
    /// The umbrella code this decline carries (`Some(CDZ0900)` = coded; `None` = still codeless).
    pub fn code(self) -> Option<Code> {
        match self {
            DeclineId::WasmHostPeerResourceFusion => Some(Code::UnsupportedConstruct),
            DeclineId::WasmClosureTransformer => Some(Code::UnsupportedConstruct),
            DeclineId::WasmCompoundResultWithClosureExport => Some(Code::UnsupportedConstruct),
            DeclineId::WasmValueFormWalkerRecursive => Some(Code::UnsupportedConstruct),
            DeclineId::WasmBytesCrossingHostOpNoBoundaryForm => Some(Code::UnsupportedConstruct),
            DeclineId::WasmMapPatternRuntimeMap => Some(Code::UnsupportedConstruct),
            DeclineId::PrimAsValueNeedsClosure => Some(Code::UnsupportedConstruct),
            DeclineId::TailResumptiveFoldUnhandledForm => Some(Code::UnsupportedConstruct),
            DeclineId::MatchOverHeapCollectionScrutinee => Some(Code::UnsupportedConstruct),
            DeclineId::RecursiveFunctionRuntimeSpecialization => Some(Code::UnsupportedConstruct),
            DeclineId::NestedRecordFieldPatternDescent => Some(Code::UnsupportedConstruct),
            DeclineId::WasmClosureBoundaryNoRepr => Some(Code::UnsupportedConstruct),
            DeclineId::WasmHeapReturnParamNoBoundaryRep => Some(Code::UnsupportedConstruct),
            DeclineId::WasmParameterizedHeapReturnNoValueEncode => Some(Code::UnsupportedConstruct),
            DeclineId::WasmHostOpNoBoundaryFormOnBareEffect => Some(Code::UnsupportedConstruct),
            DeclineId::WasmMultiHostEffectDelegation => Some(Code::UnsupportedConstruct),
        }
    }
    /// A canonical one-line reason, independent of the runtime `format!` message's specifics.
    pub fn reason(self) -> &'static str {
        match self {
            DeclineId::WasmHostPeerResourceFusion => {
                "a host effect and a peer effect composed with a resource-escaping entrypoint"
            }
            DeclineId::WasmClosureTransformer => {
                "an export that both receives and returns a closure"
            }
            DeclineId::WasmCompoundResultWithClosureExport => {
                "a compound result alongside a closure export"
            }
            DeclineId::WasmValueFormWalkerRecursive => {
                "a recursive-sum or runtime-collection value as a host-boundary result"
            }
            DeclineId::WasmBytesCrossingHostOpNoBoundaryForm => {
                "a host op whose signature has no host-boundary form"
            }
            DeclineId::WasmMapPatternRuntimeMap => {
                "matching a map-pattern payload against a runtime map"
            }
            DeclineId::PrimAsValueNeedsClosure => "a built-in operation used as a runtime value",
            DeclineId::TailResumptiveFoldUnhandledForm => {
                "an effect handler in a form the tail-resumptive fold does not specialize"
            }
            DeclineId::MatchOverHeapCollectionScrutinee => {
                "matching over a heap-backed Set or Map scrutinee"
            }
            DeclineId::RecursiveFunctionRuntimeSpecialization => {
                "a recursive function needs runtime specialization"
            }
            DeclineId::NestedRecordFieldPatternDescent => {
                "a variant sub-pattern below a record field"
            }
            DeclineId::WasmClosureBoundaryNoRepr => {
                "a closure's param, result, or capture type has no machine representation"
            }
            DeclineId::WasmHeapReturnParamNoBoundaryRep => {
                "a parameterized heap-return export forwards scalar params only; this param type has no boundary representation"
            }
            DeclineId::WasmParameterizedHeapReturnNoValueEncode => {
                "a parameterized (non-nullary) export cannot return this heap type; its value form is emitted only for a nullary constant export and it has no runtime value-encode render"
            }
            DeclineId::WasmHostOpNoBoundaryFormOnBareEffect => {
                "a host operation whose argument or result type has no component boundary form on a bare effect"
            }
            DeclineId::WasmMultiHostEffectDelegation => {
                "delegating more than one host effect from one entrypoint (one interface per envelope)"
            }
        }
    }
}
