(case "pynd4 probe: THREE nested handlers (A/B/C) where each inner arm delegates OUTWARD — C.cc performs both B.bb and A.aa, B.bb performs A.aa, A.aa is the base; each perform must route past the intervening handlers to its own handler and thread that effect's state independently, so A's counter advances across ALL delegated performs (from C, from B, and directly) while B and C keep their own"
  (input (do
  (effect A (op aa (-> Int64)))
  (effect B (op bb (-> Int64)))
  (effect C (op cc (-> Int64)))
  (def (main (: n Int64))
    (handle A (% n 3)
      ((aa () s (resume (* s 10) (+ s 1))))
      (handle B (: 5 Int64)
        ((bb () s (resume (+ s (A.aa)) (+ s 1))))
        (handle C (: 0 Int64)
          ((cc () s (resume (+ (B.bb) (A.aa)) (+ s 1))))
          (+ (C.cc) (C.cc))))))
  (export main)))
  (call   main (: 10 Int64)) (output (: 111 Int64))
  (call   main (: 0 Int64)) (output (: 71 Int64)))
