(case "ra2 the race walk's exit value SEEDS a third effect's handle — two-thread termination feeding the position matrix"
  (input  (do
            (effect A (op next (-> Int64)))
            (effect B (op next (-> Int64)))
            (effect C (op g (-> Unit Int64)))
            (def (race (: steps Int64))
              (let ((a (A.next)))
                (let ((b (B.next)))
                  (if (< a b) (race (+ steps 1)) (+ (* 100 steps) (- a b))))))
            (def (main (: n Int64))
              (handle A n
                ((next () s (resume (+ s 5) (+ s 5))))
                (handle B (+ n (+ (* 2 (if (< (% n 5) 0) (- 0 (% n 5)) (% n 5))) 3))
                  ((next () t (resume (+ t 2) (+ t 2))))
                  (handle C (race 0)
                    ((g (u) w (resume w (+ w 1))))
                    (+ (C.g) (C.g))))))
            (export main)))
  (call   main (: 5 Int64)) (output (: 1 Int64))
  (call   main (: 1 Int64)) (output (: 203 Int64))
  (call   main (: -4 Int64)) (output (: 603 Int64)))
