(case "hoh3 the INNER HANDLE'S INIT PERFORMS ON THE LIVE OUTER HANDLER — the starting value packs two outer levies drawn while only the outer handler exists, the levies advance the outer state in order before the inner frame installs, and both inner draws then echo the levy-built seed one tick apart"
  (input  (do
            (effect T (op levy (-> Int64)))
            (effect E (op tick (-> Int64)))
            (def (main (: n Int64))
              (handle T (% n 3)
                ((levy () t (resume t (+ t 5))))
                (handle E (+ (T.levy) (* 10 (T.levy)))
                  ((tick () s (resume s (+ s 1))))
                  (let ((a (E.tick)))
                    (let ((b (E.tick)))
                      (+ a (* 100 b)))))))
            (export main)))
  (call   main (: 10 Int64)) (output (: 6261 Int64))
  (call   main (: 0 Int64)) (output (: 5150 Int64)))
