(case "lu1 List.update at a DRAWN index transitions the state — the poke answers the OLD cell, later reads see the write and its neighbor"
  (input  (do
            (effect S (op poke (-> Int64 Int64)) (op at (-> Int64 Int64)))
            (def (at-or (: xs (List Int64)) (: i Int64))
              (match (List.at xs i) ((Some v) v) ((None _u) -1)))
            (def (main (: n Int64))
              (handle S (list 10 20 30 40)
                ((poke (i) s (resume (at-or s i) (List.update s i 99)))
                 (at (i) s (resume (at-or s i) s)))
                (let ((a (S.poke n)))
                  (let ((b (S.at n)))
                    (let ((c (S.at (+ n 1))))
                      (+ (* 10000 a) (+ (* 100 b) c)))))))
            (export main)))
  (call   main (: 1 Int64)) (output (: 209930 Int64))
  (call   main (: 3 Int64)) (output (: 409899 Int64)))
