(case "hf1 a delegated effect performed in a closure RETURNED from a HOF then applied in-guest fires"
  (input  (do
            (effect io (op get (-> Unit Int64)))
            (def (make-adder (: base Int64))
              (fn ((: x Int64)) (+ (+ base x) (io.get))))
            (def (apply-twice (: f (-> Int64 Int64)) (: v Int64))
              (+ (f v) (f v)))
            (def (main (: k Int64))
              (host (io) (apply-twice (make-adder 100) k)))
            (export main)))
  (host-responses (respond io.get (: 7 Int64))
                  (respond io.get (: 9 Int64)))
  (host-calls (call io.get) (call io.get))
  (call   main (: 5 Int64))
  (output (: 226 Int64)))
