(case "lp1 a LIST handler state — each feed pushes and returns the pre-push length, a summing walk reads the final list"
  (input  (do
            (effect E (op push (-> Int64 Int64)) (op total (-> Int64)))
            (def (sum-list (: xs (List Int64)) (: i Int64) (: acc Int64))
              (match (List.at xs i)
                ((Some v) (sum-list xs (+ i 1) (+ acc v)))
                ((None) acc)))
            (def (main (: n Int64))
              (handle E (list)
                ((push (x) s (resume (List.len s) (List.push s x)))
                 (total () s (resume (sum-list s 0 0) s)))
                (let ((a (E.push n)))
                  (let ((b (E.push (* 2 n))))
                    (let ((c (E.push 7)))
                      (+ (* 1000 (E.total))
                         (+ (* 100 a) (+ (* 10 b) c))))))))
            (export main)))
  (call   main (: 3 Int64)) (output (: 16012 Int64))
  (call   main (: 0 Int64)) (output (: 7012 Int64))
  (call   main (: -2 Int64)) (output (: 1012 Int64)))
