(case "brk1 TYPED-BRACKET matching — opens push their code, a close must match the TOP of the expected stack (LIFO discipline), a wrong-type close flips the sticky invalid; the seed orders the closes right or wrong"
  (input  (do
            (effect S (op feed (-> Int64 Int64)))
            (def (topv (: xs (List Int64)))
              (match (List.at xs (- (List.len xs) 1)) ((Some v) v) ((None u) -1)))
            (def (dropl (: xs (List Int64)) (: i Int64) (: keep Int64) (: acc (List Int64)))
              (if (< i keep)
                  (dropl xs (+ i 1) keep (List.push acc (match (List.at xs i) ((Some v) v) ((None u) 0))))
                  acc))
            (def (main (: n Int64))
              (handle S (tuple (: (list) (List Int64)) 0)
                ((feed (c) st
                  (match st
                    ((tuple stack bad)
                      (if (= bad 1)
                          (resume -9 st)
                          (if (< c 10)
                              (let ((s2 (List.push stack c)))
                                (resume (List.len s2) (tuple s2 0)))
                              (if (= (topv stack) (- c 10))
                                  (let ((s2 (dropl stack 0 (- (List.len stack) 1) (: (list) (List Int64)))))
                                    (resume (List.len s2) (tuple s2 0)))
                                  (resume -9 (tuple stack 1)))))))))
                (let ((c3 (if (= n 0) 12 11)))
                  (let ((c4 (if (= n 0) 11 12)))
                    (let ((a (S.feed 1)))
                      (let ((b (S.feed 2)))
                        (let ((c (S.feed c3)))
                          (let ((d (S.feed c4)))
                            (+ (* 100 (+ (* 100 (+ (* 100 (+ a 10)) (+ b 10))) (+ c 10))) (+ d 10))))))))))
            (export main)))
  (call   main (: 0 Int64)) (output (: 11121110 Int64))
  (call   main (: 1 Int64)) (output (: 11120101 Int64)))
