// FROZEN source. This was generated by the `xtask` frame generator, which has been removed; it is
// now a hand-maintained committed file. Recover the generator from git history to re-derive it.
//
// Scalar-component frame byte segments, derived from wasm-encoder (the authoritative encoder of the
// wasm/component-model bytes). The SAME segments are emitted into `compiler/cdzc/40-frame.cdz` for the
// Cadenza compiler — one derivation feeds both, so the two implementations share every frame byte.
#![allow(dead_code)]

/// core module: \0asm v1 preamble
pub const FRAME_CORE_MAGIC: &[u8] = &[0, 97, 115, 109, 1, 0, 0, 0];
/// functype () -> i64
pub const FRAME_FUNCTYPE_RUN: &[u8] = &[96, 0, 1, 126];
/// the export name "run"
pub const FRAME_RUN_NAME: &[u8] = &[114, 117, 110];
/// component: preamble
pub const FRAME_COMP_MAGIC: &[u8] = &[0, 97, 115, 109, 13, 0, 1, 0];
/// section 2: core instance (instantiate module 0)
pub const FRAME_COMP_INSTANCE: &[u8] = &[2, 4, 1, 0, 0, 0];
/// section 7: component type () -> s64 (0x78)
pub const FRAME_COMP_TYPE_RUN: &[u8] = &[7, 5, 1, 64, 0, 0, 120];
/// section 6: canon lift of core run
pub const FRAME_COMP_CANON_LIFT: &[u8] = &[6, 9, 1, 0, 0, 1, 0, 3, 114, 117, 110];
/// section 8: component func alias
pub const FRAME_COMP_FUNC_ALIAS: &[u8] = &[8, 6, 1, 0, 0, 0, 0, 0];
/// section 11: export "run"
pub const FRAME_COMP_EXPORT_RUN: &[u8] = &[11, 9, 1, 0, 3, 114, 117, 110, 1, 0, 0];
