// FROZEN source. This was generated by the `xtask` opcode generator, which has been removed; it is
// now a hand-maintained committed file. Recover the generator from git history to re-derive it.
//
// WebAssembly opcode bytes, derived by ENCODING each `wasm_encoder::Instruction` and taking its
// leading byte — `wasm-encoder` is the authoritative source of the spec's opcode numbers, so this
// table cannot drift from the standard. The SAME opcodes are emitted into `compiler/op.cdz` for the
// Cadenza compiler. See spec/learnings/2026-07-06-the-envelope-blobs-are-generated-from-the-runtime-contract.md.

#![allow(dead_code)]

pub const UNREACHABLE: u8 = 0x00;
pub const CALL: u8 = 0x10;
pub const DROP: u8 = 0x1A;
pub const LOCAL_GET: u8 = 0x20;
pub const LOCAL_SET: u8 = 0x21;
pub const LOCAL_TEE: u8 = 0x22;
pub const I32_CONST: u8 = 0x41;
pub const I64_CONST: u8 = 0x42;
pub const F64_CONST: u8 = 0x44;
pub const IF: u8 = 0x04;
pub const ELSE: u8 = 0x05;
pub const END: u8 = 0x0B;
pub const BLOCK: u8 = 0x02;
pub const LOOP: u8 = 0x03;
pub const BR: u8 = 0x0C;
pub const BR_IF: u8 = 0x0D;
pub const RETURN: u8 = 0x0F;
pub const I64_ADD: u8 = 0x7C;
pub const I64_SUB: u8 = 0x7D;
pub const I64_MUL: u8 = 0x7E;
pub const I64_DIV_S: u8 = 0x7F;
pub const I64_REM_S: u8 = 0x81;
pub const I64_AND: u8 = 0x83;
pub const I64_OR: u8 = 0x84;
pub const I64_XOR: u8 = 0x85;
pub const I64_SHL: u8 = 0x86;
pub const I64_SHR_S: u8 = 0x87;
pub const I64_EQZ: u8 = 0x50;
pub const I64_EQ: u8 = 0x51;
pub const I64_NE: u8 = 0x52;
pub const I64_LT_S: u8 = 0x53;
pub const I64_GT_S: u8 = 0x55;
pub const I64_LE_S: u8 = 0x57;
pub const I64_GE_S: u8 = 0x59;
pub const I64_GE_U: u8 = 0x5A;
pub const I32_EQZ: u8 = 0x45;
pub const I32_EQ: u8 = 0x46;
pub const I32_LT_U: u8 = 0x49;
pub const I32_GT_U: u8 = 0x4B;
pub const I32_LE_U: u8 = 0x4D;
pub const I32_GE_U: u8 = 0x4F;
pub const I32_ADD: u8 = 0x6A;
pub const I32_SUB: u8 = 0x6B;
pub const I32_MUL: u8 = 0x6C;
pub const I32_LOAD: u8 = 0x28;
pub const I64_LOAD: u8 = 0x29;
pub const F64_LOAD: u8 = 0x2B;
pub const I32_LOAD8_U: u8 = 0x2D;
pub const I32_STORE: u8 = 0x36;
pub const I64_STORE: u8 = 0x37;
pub const F64_STORE: u8 = 0x39;
pub const I32_STORE8: u8 = 0x3A;
pub const GLOBAL_GET: u8 = 0x23;
pub const GLOBAL_SET: u8 = 0x24;
