(case "rc2 the arm updates ONE record-state field chosen by the fields' own parity — three snapshots pin the alternating writes"
  (input  (do
            (effect E (op snap (-> (Record (: a Int64) (: b Int64)))))
            (def (main (: n Int64))
              (handle E (record (a n) (b 100))
                ((snap () s (resume s (if (= (% (+ (. s a) (. s b)) 2) 0)
                                          (record (a (+ (. s a) 7)) (b (. s b)))
                                          (record (a (. s a)) (b (+ (. s b) 7)))))))
                (let ((r1 (E.snap)))
                  (let ((r2 (E.snap)))
                    (let ((r3 (E.snap)))
                      (+ (+ (. r1 a) (. r1 b))
                         (+ (* 10 (+ (. r2 a) (. r2 b)))
                            (* 100 (+ (. r3 a) (. r3 b))))))))))
            (export main)))
  (call   main (: 4 Int64)) (output (: 13014 Int64))
  (call   main (: 1 Int64)) (output (: 12681 Int64))
  (call   main (: -2 Int64)) (output (: 12348 Int64)))
