(case "rc3 a record state whose FIELD is a tuple — the counter ticks while the pair walks a Fibonacci step per dispatch"
  (input  (do
            (effect E (op snap (-> (Record (: ctr Int64) (: pair (Tuple Int64 Int64))))))
            (def (main (: n Int64))
              (handle E (record (ctr n) (pair (tuple 1 2)))
                ((snap () s (resume s (match (. s pair)
                                        ((tuple lo hi) (record (ctr (+ (. s ctr) 1))
                                                               (pair (tuple hi (+ lo hi)))))))))
                (let ((r1 (E.snap)))
                  (let ((r2 (E.snap)))
                    (let ((r3 (E.snap)))
                      (match (. r1 pair)
                        ((tuple a1 b1) (match (. r2 pair)
                          ((tuple a2 b2) (match (. r3 pair)
                            ((tuple a3 b3)
                              (+ (* 100 (+ (. r1 ctr) (+ a1 b1)))
                                 (+ (* 10 (+ (. r2 ctr) (+ a2 b2)))
                                    (+ (. r3 ctr) (+ a3 b3)))))))))))))))
            (export main)))
  (call   main (: 4 Int64)) (output (: 814 Int64))
  (call   main (: 0 Int64)) (output (: 370 Int64))
  (call   main (: -3 Int64)) (output (: 37 Int64)))
