//! `xtask-codegen-wasm-abi` — extract the backend's wasm / component-model byte table from `wasm-encoder`
//! (the core opcode table, core+component valtype bytes, section ids, magic headers, functype form bytes)
//! and render it as `wasm_abi.rs`. Carved out of `xtask/src/codegen.rs`'s `generate_wasm_abi` + its
//! `wasm_abi` module (v-xtask-decompose, the codegen→build-time-nix directive).
//!
//! Pure data extraction: it encodes a one-off value with `wasm-encoder` for each entry and reads the
//! emitted byte back — nothing hand-transcribed, no compiler dep, no cdz, no runtime store. The `wasm_abi`
//! module below is copied VERBATIM from codegen.rs (only the `use super::{…}` resolves to this crate's root
//! imports) so the emitted file is byte-identical to the committed `rcdzc/src/backend/wasm/wasm_abi.rs`.
//!
//! A `cdzWasmAbi` nix derivation runs this bin to produce the generated source at build time (a build-phase
//! overlay then copies it into rcdzc's src), so nothing generated is committed.
//!
//! Usage: `xtask-codegen-wasm-abi [<out-file>]` — `out-file` defaults to the committed
//! `rcdzc/src/backend/wasm/wasm_abi.rs` (for local parity); the derivation passes its target path. Repo
//! root from `CDZ_REPO_ROOT` (else cwd).

use proc_macro2::{Span, TokenStream};
use quote::quote;
use std::path::PathBuf;

fn main() {
    let repo = std::env::var_os("CDZ_REPO_ROOT")
        .map(PathBuf::from)
        .unwrap_or_else(|| std::env::current_dir().expect("current dir"));
    let out = std::env::args_os()
        .nth(1)
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            repo.join("implementation/seed/crates/rcdzc/src/backend/wasm/wasm_abi.rs")
        });

    let tables = wasm_abi::collect();
    let source = format!(
        "{}{}",
        wasm_abi_banner(),
        format_tokens(wasm_abi::render(&tables))
    );
    if let Some(parent) = out.parent() {
        std::fs::create_dir_all(parent).ok();
    }
    if let Err(e) = std::fs::write(&out, source) {
        eprintln!("xtask codegen: writing {}: {e}", out.display());
        std::process::exit(1);
    }
    println!("xtask codegen: wrote {}", out.display());
}

/// Pretty-print a generated token tree to formatted Rust source (prettyplease, then rustfmt if available).
fn format_tokens(tokens: proc_macro2::TokenStream) -> String {
    let file = syn::parse2::<syn::File>(tokens)
        .unwrap_or_else(|e| panic!("xtask codegen: generated tokens did not parse (a bug): {e}"));
    let pretty = prettyplease::unparse(&file);
    // rustfmt is REQUIRED for byte-identical output: prettyplease alone diverges from the committed
    // cargo-fmt'd line-wrapping, so a rustfmt-less run would silently emit MIS-FORMATTED source (v-nix
    // caught this wiring cdzPlatformContracts — byte-identity holds only with rustfmt on PATH). Hard-error
    // rather than fall back, so a rustfmt-less caller can never commit/overlay mis-formatted output.
    rustfmt_stdin(&pretty).unwrap_or_else(|| {
        eprintln!(
            "xtask codegen: `rustfmt` is required on PATH (prettyplease alone diverges from the committed \
             cargo-fmt'd form → mis-formatted output). Install the pinned toolchain's rustfmt."
        );
        std::process::exit(1);
    })
}

/// Run `src` through the `rustfmt` binary (stdin→stdout). `None` if rustfmt is unavailable or errors.
fn rustfmt_stdin(src: &str) -> Option<String> {
    use std::io::Write as _;
    use std::process::{Command, Stdio};
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2024"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .ok()?;
    child.stdin.take()?.write_all(src.as_bytes()).ok()?;
    let out = child.wait_with_output().ok()?;
    out.status
        .success()
        .then(|| String::from_utf8_lossy(&out.stdout).into_owned())
}

/// The `//!` banner prepended to `wasm_abi.rs` — the "do-not-edit / regenerate" notice.
fn wasm_abi_banner() -> String {
    "//! @generated by `cargo xtask codegen` from the `wasm-encoder` crate — DO NOT hand-edit.\n\
     //!\n\
     //! Every wasm / component-model byte the backend emits, EXTRACTED from `wasm-encoder` (the spec\n\
     //! byte encoder): the core opcode table, core + component valtype bytes, core + component section\n\
     //! ids, the two magic headers, and the functype form bytes. `codegen` encodes a one-off value\n\
     //! with `wasm-encoder` and reads the byte back, so nothing here is hand-transcribed. Regenerate\n\
     //! with `cargo xtask codegen`; `cargo xtask codegen --check` (a hard gate in `xtask check`) fails\n\
     //! if it drifts from the encoder. Plain data — no dependency, so it ships in the portable\n\
     //! compiler (the `wasm-encoder` oracle stays in xtask). The backend's serializer reads these\n\
     //! rather than baking a raw byte into the emit path.\n\n"
        .to_string()
}

mod wasm_abi {
    use super::{Span, TokenStream, quote};
    use wasm_encoder::{
        Component, ComponentSectionId, ComponentTypeSection, Encode, ExportKind, Instruction,
        Module, PrimitiveValType, SectionId, TypeSection, ValType,
    };

    /// One generated `op::<IDENT> = 0x..` opcode: the backend's Lir-instruction name and the single
    /// byte `wasm-encoder` emits for the matching `Instruction`.
    pub struct Opcode {
        /// The `SCREAMING_SNAKE` constant name the backend uses (`I32_ADD`, `LOCAL_GET`, …).
        pub ident: &'static str,
        /// The opcode byte, read back from encoding the `Instruction`.
        pub byte: u8,
    }

    /// One generated named single-byte constant — a valtype, section id, export-kind, or functype
    /// form byte. `doc` is the `///` line explaining what the byte is.
    pub struct Single {
        pub ident: &'static str,
        pub byte: u8,
        pub doc: &'static str,
    }

    /// One generated magic-header constant (`&[u8]`) — the 8-byte core-module / component preamble.
    pub struct Magic {
        pub ident: &'static str,
        pub bytes: [u8; 8],
        pub doc: &'static str,
    }

    /// The whole extracted table: the opcode list, the named single bytes, and the magic headers.
    pub struct Tables {
        pub opcodes: Vec<Opcode>,
        pub singles: Vec<Single>,
        pub magics: Vec<Magic>,
    }

    /// The single byte `wasm-encoder` emits for an `Instruction` — the opcode of an instruction whose
    /// operands (if any) follow. Every opcode the backend emits is a one-byte opcode, so byte 0 of the
    /// encoding IS the opcode; a longer encoding here would mean the instruction is multi-byte and the
    /// extraction is unsound, so that is asserted rather than silently truncated.
    fn opcode_of(name: &str, insn: Instruction) -> u8 {
        let mut buf = Vec::new();
        insn.encode(&mut buf);
        assert!(
            !buf.is_empty(),
            "wasm-encoder emitted no bytes for the {name} opcode"
        );
        // The operands follow the opcode byte; the backend emits them itself (LEB128), so only byte 0
        // is the opcode. (For operand-less instructions the encoding is exactly one byte.)
        buf[0]
    }

    /// The single byte `wasm-encoder` emits for a value that encodes to exactly one byte (a valtype,
    /// an export-kind). Asserts the one-byte shape so a spec change that widened it can't slip through.
    fn one_byte<T: Encode>(name: &str, v: T) -> u8 {
        let mut buf = Vec::new();
        v.encode(&mut buf);
        assert_eq!(
            buf.len(),
            1,
            "expected {name} to encode to a single byte, got {buf:?}"
        );
        buf[0]
    }

    /// The core FUNCTYPE FORM byte (`0x60`) — the tag that opens a core function type. It is only
    /// emitted inside a type section, so encode a one-function `TypeSection` and read the tag off the
    /// first (only) type entry — the byte `wasm-encoder` pushes before the param/result vectors.
    fn core_functype_form() -> u8 {
        let mut ts = TypeSection::new();
        ts.ty().function([], []);
        first_type_entry_tag("core functype", &ts)
    }

    /// The COMPONENT functype form byte (`0x40`) — the tag opening a component function type, likewise
    /// only emitted inside a component type section. Encode a one-function `ComponentTypeSection` and
    /// read the tag off its first entry.
    fn component_functype_form() -> u8 {
        let mut ts = ComponentTypeSection::new();
        // `params` must be encoded before `result` (the encoder asserts it); a nullary `() -> ()` is
        // enough — only the leading form tag is read.
        ts.function()
            .params(std::iter::empty::<(&str, wasm_encoder::ComponentValType)>())
            .result(None);
        first_type_entry_tag("component functype", &ts)
    }

    /// The leading tag byte of the FIRST entry in a one-entry type section. `wasm-encoder` frames a
    /// section as `<id:1> <byte-length:leb> <count:leb> <entries…>`; a section holding a single small
    /// function type has both the length and the count in one LEB byte each, so the entry — whose
    /// first byte is the functype form tag — starts at offset 3. (Asserted, so a framing change or a
    /// non-trivial length can't silently shift the read.)
    fn first_type_entry_tag<S: SectionBytes>(name: &str, sec: &S) -> u8 {
        let bytes = sec.section_bytes();
        // [0]=section id, [1]=section byte-length (1 LEB byte, the type is tiny), [2]=entry count.
        assert!(
            bytes.len() > 3,
            "{name} section unexpectedly short: {bytes:?}"
        );
        assert_eq!(
            bytes[2], 1,
            "{name} section should hold exactly one type entry, got count {}",
            bytes[2]
        );
        bytes[3]
    }

    /// A minimal shim over the two section flavors: emit the full `<id> <len> <contents>` bytes of a
    /// section. `wasm-encoder`'s `Section`/`ComponentSection` traits both expose exactly this via
    /// `append_to`, but they are distinct traits; this unifies them for `section_contents_first_byte`.
    trait SectionBytes {
        fn section_bytes(&self) -> Vec<u8>;
    }
    impl SectionBytes for TypeSection {
        fn section_bytes(&self) -> Vec<u8> {
            let mut m = Module::new();
            m.section(self);
            // A fresh `Module` is `[8-byte header][section…]`; the section is everything after it.
            m.finish()[Module::HEADER.len()..].to_vec()
        }
    }
    impl SectionBytes for ComponentTypeSection {
        fn section_bytes(&self) -> Vec<u8> {
            let mut c = Component::new();
            c.section(self);
            c.finish()[Component::HEADER.len()..].to_vec()
        }
    }

    /// Extract every backend byte from `wasm-encoder`. The opcode list is in the backend's own
    /// declaration order (matching the frozen `op` module for a readable, stable diff); the singles
    /// and magics follow.
    pub fn collect() -> Tables {
        // The opcode table: each backend `op::` constant paired with the `Instruction` whose encoding
        // yields its byte. One row per instruction the serializer emits (Lir → bytes).
        let opcodes = vec![
            op("I32_CONST", Instruction::I32Const(0)),
            op("I64_CONST", Instruction::I64Const(0)),
            op("F64_CONST", Instruction::F64Const(0.0f64.into())),
            op("F32_CONST", Instruction::F32Const(0.0f32.into())),
            // Float ARITHMETIC (f64/f32) — the machine ops a runtime `+.`/`-.`/`*.`/`/.` selects.
            // IEEE, never trapping (overflow → inf, x/0 → ±inf/NaN), so no overflow guard (unlike the
            // integer arith). Round-to-nearest-even is the hardware default the determinism contract pins.
            op("F64_ADD", Instruction::F64Add),
            op("F64_SUB", Instruction::F64Sub),
            op("F64_MUL", Instruction::F64Mul),
            op("F64_DIV", Instruction::F64Div),
            op("F32_ADD", Instruction::F32Add),
            op("F32_SUB", Instruction::F32Sub),
            op("F32_MUL", Instruction::F32Mul),
            op("F32_DIV", Instruction::F32Div),
            // Float EQUALITY (f64/f32) — a runtime float `=` (IEEE compare: -0.0 == 0.0, NaN ≠ NaN).
            op("F64_EQ", Instruction::F64Eq),
            op("F64_NE", Instruction::F64Ne),
            op("F32_EQ", Instruction::F32Eq),
            op("F32_NE", Instruction::F32Ne),
            // Float ORDERING (f64/f32) — runtime `< <= > >=` under IEEE PARTIAL order (operator ruling):
            // a NaN operand yields false (unordered — NaN is neither <, >, nor = anything), and -0.0
            // compares equal-under-ordering to +0.0 (`f64.le -0.0 0.0` = true). These are the RAW IEEE
            // compares, DISTINCT from the canonical-byte equality above (which the two relations disagree
            // with on NaN + signed zero — inherent to float).
            op("F64_LT", Instruction::F64Lt),
            op("F64_GT", Instruction::F64Gt),
            op("F64_LE", Instruction::F64Le),
            op("F64_GE", Instruction::F64Ge),
            op("F32_LT", Instruction::F32Lt),
            op("F32_GT", Instruction::F32Gt),
            op("F32_LE", Instruction::F32Le),
            op("F32_GE", Instruction::F32Ge),
            // Float width conversion (F5): `f32.demote_f64` narrows Float64→Float32 (rounds),
            // `f64.promote_f32` widens Float32→Float64 (exact). Int↔float conversions land with `of-int`.
            op("F32_DEMOTE_F64", Instruction::F32DemoteF64),
            op("F64_PROMOTE_F32", Instruction::F64PromoteF32),
            // INT→FLOAT conversion (`Float N.of-int`): signed i64 → f64/f32, round-to-nearest-even.
            op("F64_CONVERT_I64_S", Instruction::F64ConvertI64S),
            op("F32_CONVERT_I64_S", Instruction::F32ConvertI64S),
            // FLOAT→INT bit reinterpret (no value change) — the canonical-byte float `=` reinterprets
            // the bits to an integer to compare (NaN-canonicalizing bit compare, IEEE `f*.eq` won't do).
            op("I32_REINTERPRET_F32", Instruction::I32ReinterpretF32),
            op("I64_REINTERPRET_F64", Instruction::I64ReinterpretF64),
            op("IF", Instruction::If(wasm_encoder::BlockType::Empty)),
            op("ELSE", Instruction::Else),
            op("END", Instruction::End),
            op("SELECT", Instruction::Select),
            op("DROP", Instruction::Drop),
            op("BLOCK", Instruction::Block(wasm_encoder::BlockType::Empty)),
            op("LOOP", Instruction::Loop(wasm_encoder::BlockType::Empty)),
            op("BR", Instruction::Br(0)),
            op("BR_IF", Instruction::BrIf(0)),
            op(
                "BR_TABLE",
                Instruction::BrTable(std::borrow::Cow::Borrowed(&[]), 0),
            ),
            op("LOCAL_GET", Instruction::LocalGet(0)),
            op("LOCAL_SET", Instruction::LocalSet(0)),
            op("LOCAL_TEE", Instruction::LocalTee(0)),
            op("GLOBAL_GET", Instruction::GlobalGet(0)),
            op("GLOBAL_SET", Instruction::GlobalSet(0)),
            op("CALL", Instruction::Call(0)),
            op(
                "CALL_INDIRECT",
                Instruction::CallIndirect {
                    type_index: 0,
                    table_index: 0,
                },
            ),
            op("RETURN_CALL", Instruction::ReturnCall(0)),
            op("RETURN", Instruction::Return),
            op("UNREACHABLE", Instruction::Unreachable),
            op("I32_ADD", Instruction::I32Add),
            op("I32_SUB", Instruction::I32Sub),
            op("I32_MUL", Instruction::I32Mul),
            op("I32_DIV_S", Instruction::I32DivS),
            op("I32_DIV_U", Instruction::I32DivU),
            op("I32_REM_S", Instruction::I32RemS),
            op("I32_REM_U", Instruction::I32RemU),
            op("I32_AND", Instruction::I32And),
            op("I32_OR", Instruction::I32Or),
            op("I32_XOR", Instruction::I32Xor),
            op("I32_SHL", Instruction::I32Shl),
            op("I32_SHR_S", Instruction::I32ShrS),
            op("I32_SHR_U", Instruction::I32ShrU),
            op("I32_EQ", Instruction::I32Eq),
            op("I32_EQZ", Instruction::I32Eqz),
            op("I32_NE", Instruction::I32Ne),
            op("I32_LT_S", Instruction::I32LtS),
            op("I32_LT_U", Instruction::I32LtU),
            op("I32_GT_S", Instruction::I32GtS),
            op("I32_GT_U", Instruction::I32GtU),
            op("I32_LE_S", Instruction::I32LeS),
            op("I32_LE_U", Instruction::I32LeU),
            op("I32_GE_S", Instruction::I32GeS),
            op("I32_GE_U", Instruction::I32GeU),
            op("I64_ADD", Instruction::I64Add),
            op("I64_SUB", Instruction::I64Sub),
            op("I64_MUL", Instruction::I64Mul),
            op("I64_DIV_S", Instruction::I64DivS),
            op("I64_DIV_U", Instruction::I64DivU),
            op("I64_REM_S", Instruction::I64RemS),
            op("I64_REM_U", Instruction::I64RemU),
            op("I64_AND", Instruction::I64And),
            op("I64_OR", Instruction::I64Or),
            op("I64_XOR", Instruction::I64Xor),
            op("I64_SHL", Instruction::I64Shl),
            op("I64_SHR_S", Instruction::I64ShrS),
            op("I64_SHR_U", Instruction::I64ShrU),
            op("I64_EQ", Instruction::I64Eq),
            op("I64_EQZ", Instruction::I64Eqz),
            op("I64_NE", Instruction::I64Ne),
            op("I64_LT_S", Instruction::I64LtS),
            op("I64_LT_U", Instruction::I64LtU),
            op("I64_GT_S", Instruction::I64GtS),
            op("I64_GT_U", Instruction::I64GtU),
            op("I64_LE_S", Instruction::I64LeS),
            op("I64_LE_U", Instruction::I64LeU),
            op("I64_GE_S", Instruction::I64GeS),
            op("I64_GE_U", Instruction::I64GeU),
            op("I32_WRAP_I64", Instruction::I32WrapI64),
            op("I64_EXTEND_I32_S", Instruction::I64ExtendI32S),
            op("I64_EXTEND_I32_U", Instruction::I64ExtendI32U),
            // Memory stores — the `list<u8>`/`string` return path writes the payload bytes and the
            // canonical-ABI return area (`[data-ptr, data-len]`) into linear memory. `MemArg` is
            // irrelevant to the opcode byte (the extraction reads byte 0; the serializer emits the
            // align/offset LEB operands itself), so a zero memarg suffices to recover the opcode.
            op(
                "I32_STORE",
                Instruction::I32Store(wasm_encoder::MemArg {
                    offset: 0,
                    align: 0,
                    memory_index: 0,
                }),
            ),
            op(
                "I32_STORE8",
                Instruction::I32Store8(wasm_encoder::MemArg {
                    offset: 0,
                    align: 0,
                    memory_index: 0,
                }),
            ),
            // The wider stores the reducer RESULT-lower (W4c-b canonical writer) needs: an `i64`/`f64`/`f32`
            // scalar field, and the 2-byte `i32.store16` for a `u16`/`s16` slot. Same MemArg-irrelevant note.
            op(
                "I64_STORE",
                Instruction::I64Store(wasm_encoder::MemArg {
                    offset: 0,
                    align: 0,
                    memory_index: 0,
                }),
            ),
            op(
                "F32_STORE",
                Instruction::F32Store(wasm_encoder::MemArg {
                    offset: 0,
                    align: 0,
                    memory_index: 0,
                }),
            ),
            op(
                "F64_STORE",
                Instruction::F64Store(wasm_encoder::MemArg {
                    offset: 0,
                    align: 0,
                    memory_index: 0,
                }),
            ),
            op(
                "I32_STORE16",
                Instruction::I32Store16(wasm_encoder::MemArg {
                    offset: 0,
                    align: 0,
                    memory_index: 0,
                }),
            ),
            // Memory loads — the reducer byte-ABI `apply(event: list<u8>)` wrapper (B3) reads the incoming
            // event bytes out of linear memory (the canonical ABI delivers a `list<u8>` param as a
            // `(ptr, len)` pair with the bytes at `ptr`) to copy them into a heap `Bytes` before
            // `value-decode`. `I32_LOAD8_U` reads one unsigned byte; `I32_LOAD` reads the 4-byte
            // `(ptr, len)` fields where needed. Same `MemArg`-irrelevant-to-opcode-byte note as the stores.
            op(
                "I32_LOAD",
                Instruction::I32Load(wasm_encoder::MemArg {
                    offset: 0,
                    align: 0,
                    memory_index: 0,
                }),
            ),
            op(
                "I32_LOAD8_U",
                Instruction::I32Load8U(wasm_encoder::MemArg {
                    offset: 0,
                    align: 0,
                    memory_index: 0,
                }),
            ),
            // Width-specific loads for reading a scalar leaf a spilled compound result stored at its natural
            // width (the general result-lift's scalar-leaf boxing). MemArg is opcode-byte-irrelevant here too.
            op(
                "I64_LOAD",
                Instruction::I64Load(wasm_encoder::MemArg {
                    offset: 0,
                    align: 0,
                    memory_index: 0,
                }),
            ),
            op(
                "F32_LOAD",
                Instruction::F32Load(wasm_encoder::MemArg {
                    offset: 0,
                    align: 0,
                    memory_index: 0,
                }),
            ),
            op(
                "F64_LOAD",
                Instruction::F64Load(wasm_encoder::MemArg {
                    offset: 0,
                    align: 0,
                    memory_index: 0,
                }),
            ),
            op(
                "I32_LOAD8_S",
                Instruction::I32Load8S(wasm_encoder::MemArg {
                    offset: 0,
                    align: 0,
                    memory_index: 0,
                }),
            ),
            op(
                "I32_LOAD16_S",
                Instruction::I32Load16S(wasm_encoder::MemArg {
                    offset: 0,
                    align: 0,
                    memory_index: 0,
                }),
            ),
            op(
                "I32_LOAD16_U",
                Instruction::I32Load16U(wasm_encoder::MemArg {
                    offset: 0,
                    align: 0,
                    memory_index: 0,
                }),
            ),
        ];

        // The named single bytes: core valtypes, the empty block type, the component primitive
        // valtypes, the core + component section ids the envelope uses, the func export kind, and the
        // two functype form bytes.
        let singles = vec![
            valtype(
                "CORE_I32",
                "core valtype `i32` — a ≤32-bit scalar's machine slot.",
                ValType::I32,
            ),
            valtype(
                "CORE_I64",
                "core valtype `i64` — a 64-bit scalar's machine slot.",
                ValType::I64,
            ),
            valtype("CORE_F32", "core valtype `f32`.", ValType::F32),
            valtype("CORE_F64", "core valtype `f64`.", ValType::F64),
            Single {
                ident: "BLOCK_EMPTY",
                byte: one_byte("empty block type", wasm_encoder::BlockType::Empty),
                doc: "empty block type — a structured block (`if`/`block`) that leaves no value.",
            },
            prim("COMP_BOOL", "component `bool`.", PrimitiveValType::Bool),
            prim("COMP_S8", "component `s8`.", PrimitiveValType::S8),
            prim("COMP_U8", "component `u8`.", PrimitiveValType::U8),
            prim("COMP_S16", "component `s16`.", PrimitiveValType::S16),
            prim("COMP_U16", "component `u16`.", PrimitiveValType::U16),
            prim("COMP_S32", "component `s32`.", PrimitiveValType::S32),
            prim("COMP_U32", "component `u32`.", PrimitiveValType::U32),
            prim("COMP_S64", "component `s64`.", PrimitiveValType::S64),
            prim("COMP_U64", "component `u64`.", PrimitiveValType::U64),
            prim("COMP_F32", "component `f32`.", PrimitiveValType::F32),
            prim("COMP_F64", "component `f64`.", PrimitiveValType::F64),
            prim(
                "COMP_STRING",
                "component `string`.",
                PrimitiveValType::String,
            ),
            core_sec("CORE_SEC_TYPE", "core TYPE section id.", SectionId::Type),
            core_sec(
                "CORE_SEC_FUNCTION",
                "core FUNCTION section id.",
                SectionId::Function,
            ),
            core_sec(
                "CORE_SEC_TABLE",
                "core TABLE section id (the funcref table a closure's `call_indirect` dispatches through — one entry per lambda-lifted closure function).",
                SectionId::Table,
            ),
            core_sec(
                "CORE_SEC_ELEMENT",
                "core ELEMENT section id (the active segment filling the funcref table with the lifted closure functions' indices, so a closure's stored table slot names its code).",
                SectionId::Element,
            ),
            core_sec(
                "CORE_SEC_MEMORY",
                "core MEMORY section id (the linear memory a `list<u8>`/`string` return lifts through).",
                SectionId::Memory,
            ),
            core_sec(
                "CORE_SEC_GLOBAL",
                "core GLOBAL section id (a build-once static compound's handle global; the bump-allocator cursor).",
                SectionId::Global,
            ),
            core_sec(
                "CORE_SEC_EXPORT",
                "core EXPORT section id.",
                SectionId::Export,
            ),
            core_sec(
                "CORE_SEC_START",
                "core START section id (the init function that builds each static compound once).",
                SectionId::Start,
            ),
            core_sec("CORE_SEC_CODE", "core CODE section id.", SectionId::Code),
            core_sec(
                "CORE_SEC_DATA",
                "core DATA section id (an active segment initializing linear memory — the constant value form + return area of a resource escape).",
                SectionId::Data,
            ),
            comp_sec(
                "COMP_SEC_CORE_MODULE",
                "component CORE-MODULE section id.",
                ComponentSectionId::CoreModule,
            ),
            comp_sec(
                "COMP_SEC_CORE_INSTANCE",
                "component CORE-INSTANCE section id.",
                ComponentSectionId::CoreInstance,
            ),
            comp_sec(
                "COMP_SEC_ALIAS",
                "component ALIAS section id.",
                ComponentSectionId::Alias,
            ),
            comp_sec(
                "COMP_SEC_TYPE",
                "component TYPE section id.",
                ComponentSectionId::Type,
            ),
            comp_sec(
                "COMP_SEC_CANONICAL",
                "component CANONICAL-FUNCTION section id.",
                ComponentSectionId::CanonicalFunction,
            ),
            comp_sec(
                "COMP_SEC_IMPORT",
                "component IMPORT section id.",
                ComponentSectionId::Import,
            ),
            comp_sec(
                "COMP_SEC_EXPORT",
                "component EXPORT section id.",
                ComponentSectionId::Export,
            ),
            comp_sec(
                "COMP_SEC_COMPONENT",
                "component COMPONENT section id (a nested component definition).",
                ComponentSectionId::Component,
            ),
            comp_sec(
                "COMP_SEC_INSTANCE",
                "component INSTANCE section id (instantiate a component).",
                ComponentSectionId::Instance,
            ),
            Single {
                ident: "EXPORT_KIND_FUNC",
                byte: one_byte("export kind func", ExportKind::Func),
                doc: "core export kind `func` — the export-descriptor byte for a function export.",
            },
            Single {
                ident: "EXPORT_KIND_MEMORY",
                byte: one_byte("export kind memory", ExportKind::Memory),
                doc: "core export kind `memory` — the export-descriptor byte for a memory export (the resource escape's `memory`).",
            },
            Single {
                ident: "CORE_FUNCTYPE_FORM",
                byte: core_functype_form(),
                doc: "core functype form tag — opens a core `func` type before its param/result vecs.",
            },
            Single {
                ident: "COMP_FUNCTYPE_FORM",
                byte: component_functype_form(),
                doc: "component functype form tag — opens a component function type.",
            },
        ];

        let magics = vec![
            Magic {
                ident: "CORE_MAGIC",
                bytes: Module::HEADER,
                doc: "the `\\0asm` version-1 core-module preamble.",
            },
            Magic {
                ident: "COMPONENT_MAGIC",
                bytes: Component::HEADER,
                doc: "the `\\0asm` component-layer preamble (component-model version).",
            },
        ];

        Tables {
            opcodes,
            singles,
            magics,
        }
    }

    /// An opcode row: extract the byte from encoding `insn`.
    fn op(ident: &'static str, insn: Instruction) -> Opcode {
        Opcode {
            ident,
            byte: opcode_of(ident, insn),
        }
    }

    /// A core-valtype single: extract the byte from encoding the `ValType`.
    fn valtype(ident: &'static str, doc: &'static str, vt: ValType) -> Single {
        Single {
            ident,
            byte: one_byte(ident, vt),
            doc,
        }
    }

    /// A component-primitive single: extract the byte from encoding the `PrimitiveValType`.
    fn prim(ident: &'static str, doc: &'static str, p: PrimitiveValType) -> Single {
        Single {
            ident,
            byte: one_byte(ident, p),
            doc,
        }
    }

    /// A core-section-id single (the id is the enum's `u8` repr).
    fn core_sec(ident: &'static str, doc: &'static str, id: SectionId) -> Single {
        Single {
            ident,
            byte: u8::from(id),
            doc,
        }
    }

    /// A component-section-id single.
    fn comp_sec(ident: &'static str, doc: &'static str, id: ComponentSectionId) -> Single {
        Single {
            ident,
            byte: u8::from(id),
            doc,
        }
    }

    /// Render the extracted tables as the generated `wasm_abi.rs` body: the `op` opcode module, then
    /// the named single-byte constants, then the magic-header slices. Hex literals so the file reads
    /// like the spec (`pub const I32_ADD: u8 = 0x6a;`).
    pub fn render(t: &Tables) -> TokenStream {
        let op_consts = t.opcodes.iter().map(|o| {
            let ident = ident(o.ident);
            let byte = hex(o.byte);
            quote!(pub const #ident: u8 = #byte;)
        });

        let single_consts = t.singles.iter().map(|s| {
            let ident = ident(s.ident);
            let byte = hex(s.byte);
            let doc = format!(" {}", s.doc);
            quote! {
                #[doc = #doc]
                pub const #ident: u8 = #byte;
            }
        });

        let magic_consts = t.magics.iter().map(|m| {
            let ident = ident(m.ident);
            let bytes = m.bytes.iter().map(|b| hex(*b));
            let doc = format!(" {}", m.doc);
            quote! {
                #[doc = #doc]
                pub const #ident: &[u8] = &[#(#bytes),*];
            }
        });

        quote! {
            #[doc = " The core-wasm opcode bytes the serializer emits — one `pub const` per Lir"]
            #[doc = " instruction, the byte `wasm-encoder` encodes that instruction to. A one-byte opcode"]
            #[doc = " each (its operands follow, emitted by the serializer); the extraction asserts that."]
            pub mod op {
                #(#op_consts)*
            }

            #(#single_consts)*

            #(#magic_consts)*
        }
    }

    /// A hex `u8` literal token (`0x6a`) — matches the spec/wasm convention the frozen source used, so
    /// the generated file reads like an opcode table rather than decimal noise. The const's own `: u8`
    /// / `&[u8]` annotation types it, so the literal is unsuffixed; a raw token keeps the `0x` form
    /// through prettyplease/rustfmt (which would rewrite a `Literal`'s decimal print).
    fn hex(b: u8) -> TokenStream {
        format!("0x{b:02x}")
            .parse()
            .expect("a `0x..` hex literal parses as a token")
    }

    /// A `SCREAMING_SNAKE` const identifier token.
    fn ident(name: &str) -> proc_macro2::Ident {
        proc_macro2::Ident::new(name, Span::call_site())
    }
}
