//! @generated by `cargo xtask codegen` from cdz-platform/contracts/deliver.sexp — DO NOT hand-edit.
//!
//! The `deliver` contract's schema (`design/cadenza-platform.md` section 4) as Cadenza-AST builder
//! calls: `schema(b)` reconstructs the contract's named type declarations, which `deliver_contract`
//! hands to `Contract::new` (input `Deliver-Envelope`, output `Deliver-Outcome`). The source is real
//! Cadenza that codegen TYPECHECKS with the compiler before generating this file, so the schema is
//! provably valid Cadenza and a marshalled envelope value type-ascribes against it. Edit the schema
//! in `deliver.sexp`, then regenerate with `cargo xtask codegen`; `cargo xtask codegen --check` (a
//! hard gate in `xtask check`) fails if this file is stale. Plain builder calls — no dependency on
//! the compiler, so it ships in `cdz-platform` (the compiler stays a codegen-time dev-desk tool).

use cadenza_ast::ast::{Builder, StructId};
/// The `deliver` contract's schema: its named Cadenza type declarations, in source order.
/// Handed to `Contract::new` as the contract's types (input `Deliver-Envelope`, output
/// `Deliver-Outcome`). Generated from `contracts/deliver.sexp`, which the compiler
/// typechecks at codegen time, so this is provably a valid Cadenza schema.
pub fn schema(b: &mut Builder) -> Vec<StructId> {
    let v0 = b.name("type");
    let v1 = b.name("Error");
    let v2 = b.name("Timeout");
    let v3 = b.list(vec![v2]);
    let v4 = b.name("MissingHandler");
    let v5 = b.list(vec![v4]);
    let v6 = b.list(vec![v0, v1, v3, v5]);
    let v7 = b.name("type");
    let v8 = b.name("Result");
    let v9 = b.name("Ok");
    let v10 = b.name("Bytes");
    let v11 = b.list(vec![v9, v10]);
    let v12 = b.name("Err");
    let v13 = b.name("Error");
    let v14 = b.list(vec![v12, v13]);
    let v15 = b.list(vec![v7, v8, v11, v14]);
    let v16 = b.name("type");
    let v17 = b.name("Event");
    let v18 = b.name("Message");
    let v19 = b.name("Record");
    let v20 = b.name("id");
    let v21 = b.name("Bytes");
    let v22 = b.list(vec![v20, v21]);
    let v23 = b.name("reducer");
    let v24 = b.name("Bytes");
    let v25 = b.list(vec![v23, v24]);
    let v26 = b.name("host");
    let v27 = b.name("Bytes");
    let v28 = b.list(vec![v26, v27]);
    let v29 = b.name("payload");
    let v30 = b.name("Bytes");
    let v31 = b.list(vec![v29, v30]);
    let v32 = b.name("token");
    let v33 = b.name("Bytes");
    let v34 = b.list(vec![v32, v33]);
    let v35 = b.list(vec![v19, v22, v25, v28, v31, v34]);
    let v36 = b.list(vec![v18, v35]);
    let v37 = b.name("Response");
    let v38 = b.name("Record");
    let v39 = b.name("id");
    let v40 = b.name("Bytes");
    let v41 = b.list(vec![v39, v40]);
    let v42 = b.name("token");
    let v43 = b.name("Bytes");
    let v44 = b.list(vec![v42, v43]);
    let v45 = b.name("result");
    let v46 = b.name("Result");
    let v47 = b.list(vec![v45, v46]);
    let v48 = b.list(vec![v38, v41, v44, v47]);
    let v49 = b.list(vec![v37, v48]);
    let v50 = b.name("Notification");
    let v51 = b.name("Record");
    let v52 = b.name("id");
    let v53 = b.name("Bytes");
    let v54 = b.list(vec![v52, v53]);
    let v55 = b.name("payload");
    let v56 = b.name("Bytes");
    let v57 = b.list(vec![v55, v56]);
    let v58 = b.list(vec![v51, v54, v57]);
    let v59 = b.list(vec![v50, v58]);
    let v60 = b.list(vec![v16, v17, v36, v49, v59]);
    let v61 = b.name("type");
    let v62 = b.name("Deliver-Envelope");
    let v63 = b.name("Deliver");
    let v64 = b.name("Record");
    let v65 = b.name("target");
    let v66 = b.name("Bytes");
    let v67 = b.list(vec![v65, v66]);
    let v68 = b.name("event");
    let v69 = b.name("Event");
    let v70 = b.list(vec![v68, v69]);
    let v71 = b.list(vec![v64, v67, v70]);
    let v72 = b.list(vec![v63, v71]);
    let v73 = b.list(vec![v61, v62, v72]);
    let v74 = b.name("type");
    let v75 = b.name("Deliver-Outcome");
    let v76 = b.name("Delivered");
    let v77 = b.list(vec![v76]);
    let v78 = b.name("Failed");
    let v79 = b.name("Bytes");
    let v80 = b.list(vec![v78, v79]);
    let v81 = b.list(vec![v74, v75, v77, v80]);
    vec![v6, v15, v60, v73, v81]
}
