//! The forward primitive (`design/cadenza-platform.md` §4).
//!
//! `forward` is one of the two built-in effects a handler emits to act on an effect delivered to it (the
//! other is [`respond`](crate::respond)): it permits the effect and passes it to the next handler in the
//! chain, possibly rewritten — even re-contracted into a different contract. A handler emits it as an
//! ordinary [`Request`] against the [`forward_contract`], whose payload is a [`Forward`] envelope carrying
//! the (possibly new) request and the echoed correlation token. The event reducer decides the next hop from
//! the chain it assembled; forward names no target, only the request to pass on.
//!
//! The event reducer matches the forward to the open obligation by the handler's kernel-stamped `from` (§3)
//! and the `token` echoed in the envelope — the continuation-token the event reducer chose when it delivered
//! the effect. That token cannot ride on the emitted request's own continuation-token (which is the
//! handler's correlation for the forward effect's own answer), so it travels in the envelope. `contract` and
//! `payload` are the request to pass on: the same contract and bytes to forward transparently, or a new
//! contract-id and payload to transform.
//!
//! Like [`deliver`](crate::deliver), the schema is not hand-authored: it lives as real Cadenza in
//! `contracts/forward.cdz`, and `cargo xtask codegen` typechecks it with the `cdz` binary and generates
//! [`crate::contracts::forward`] (the schema builders and the [`contract`](crate::contracts::forward::contract)
//! constructor). The envelope is a Cadenza value encoded through the one canonical binary codec
//! ([`cadenza_ast::codec`]); [`Forward::decode`] is total, returning `None` on any input that is not a
//! well-formed forward value.

use crate::{Bytes, Contract, ContractId, Request};
use cadenza_ast::ast::{Builder, StructId};
use cadenza_ast::codec;
use std::sync::OnceLock;

/// The built-in contract a [`Request`](crate::Request) is emitted against to forward (§4). A real contract
/// whose id is the hash of its declared schema — generated by `cargo xtask codegen` from
/// `contracts/forward.cdz` into [`crate::contracts::forward::contract`]; built once and cached, so the id is
/// derived only once.
#[must_use]
pub fn forward_contract() -> ContractId {
    static FORWARD: OnceLock<Contract> = OnceLock::new();
    FORWARD
        .get_or_init(crate::contracts::forward::contract)
        .id()
}

/// A forward envelope: permit the obligation correlated by `token` and pass the request named by `contract`
/// with `payload` to the next handler (§4). This is what the payload of a forward [`Request`](crate::Request)
/// carries; the event reducer decodes it and delivers the request to the next hop in the chain.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Forward {
    /// The continuation-token the event reducer chose on delivery, echoed to name the obligation permitted.
    pub token: Bytes,
    /// The contract of the request to pass on — the same one to forward transparently, or a new one to
    /// re-contract.
    pub contract: ContractId,
    /// The request's payload — the same bytes to forward transparently, or rewritten to transform.
    pub payload: Bytes,
}

impl Forward {
    /// Encode the envelope as a Cadenza value in the canonical binary form ([`cadenza_ast::codec`]) — the
    /// inverse of [`decode`](Self::decode).
    #[must_use]
    pub fn encode(&self) -> Bytes {
        let mut b = Builder::new();
        let root = self.build(&mut b);
        let arenas = b.finish(root);
        Bytes::from(codec::encode(&arenas))
    }

    /// Build the envelope value into `b`, returning its root — a value of the schema type `Envelope`. The
    /// value SHAPE is entirely the generated builders' (`contracts::forward::*`); this only supplies the
    /// `Bytes` leaves (the contract-id's raw bytes and the payload).
    fn build(&self, b: &mut Builder) -> StructId {
        use crate::contract_value as v;
        use crate::contracts::forward as c;

        let token = v::bytes_leaf(b, &self.token);
        let contract = v::bytes_leaf(b, self.contract.hash().as_bytes());
        let payload = v::bytes_leaf(b, &self.payload);
        c::envelope_forward(
            b,
            c::EnvelopeForward {
                token,
                contract,
                payload,
            },
        )
    }

    /// The forward [`Request`](crate::Request) a handler emits to carry this out: against the
    /// [`forward_contract`], with the envelope as its payload. Its own continuation-token is the handler's to
    /// choose for correlating the forward effect's answer; this convenience leaves it empty and sets no
    /// deadline — the obligation it permits is named by the echoed `token` inside the envelope.
    #[must_use]
    pub fn into_request(self) -> Request {
        Request {
            id: forward_contract(),
            payload: self.encode(),
            continuation_token: Bytes::new(),
            deadline: None,
        }
    }

    /// Decode an envelope from a Cadenza value, or `None` if the bytes are not a well-formed forward value.
    /// Total, so a malformed envelope is a rejected forward, never a panic.
    #[must_use]
    pub fn decode(bytes: &[u8]) -> Option<Self> {
        use crate::contract_value as v;
        use crate::contracts::forward as c;

        let arenas = codec::decode(bytes)?;
        let env = c::as_envelope_forward(&arenas, arenas.root)?;
        let token = v::read_bytes(&arenas, env.token)?;
        let contract = ContractId::from_hash(v::read_hash(&arenas, env.contract)?);
        let payload = v::read_bytes(&arenas, env.payload)?;
        Some(Self {
            token,
            contract,
            payload,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::{Forward, forward_contract};
    use crate::{Bytes, ContractId};

    fn cid(tag: &[u8]) -> ContractId {
        ContractId::of(tag)
    }

    fn round_trips(f: &Forward) {
        assert_eq!(Forward::decode(&f.encode()), Some(f.clone()));
    }

    #[test]
    fn a_transparent_forward_round_trips() {
        round_trips(&Forward {
            token: Bytes::from_static(b"tok"),
            contract: cid(b"http.get"),
            payload: Bytes::from_static(b"a request body"),
        });
    }

    #[test]
    fn a_re_contracted_forward_round_trips() {
        // Re-contracting to a different contract with a rewritten payload — the transform case.
        round_trips(&Forward {
            token: Bytes::from_static(b"tok"),
            contract: cid(b"http.get.rate-limited"),
            payload: Bytes::from_static(b"a rewritten request"),
        });
    }

    #[test]
    fn decode_rejects_bytes_that_are_not_a_forward_value() {
        assert_eq!(Forward::decode(&[0xFF, 0x00, 0x13, 0x37]), None);
        assert_eq!(Forward::decode(&[]), None);
        // A well-formed Cadenza value of the wrong shape decodes cleanly but is not a forward.
        let mut b = cadenza_ast::ast::Builder::new();
        let root = b.name("not-a-forward");
        let wrong_shape = cadenza_ast::codec::encode(&b.finish(root));
        assert_eq!(Forward::decode(&wrong_shape), None);
    }

    #[test]
    fn the_forward_contract_id_is_a_real_contract_id_and_stable() {
        assert_eq!(forward_contract(), forward_contract());
        let rebuilt = crate::Contract::new(
            crate::Str::from_static("cdz-platform.forward"),
            crate::contracts::forward::schema,
            "Envelope",
            "Outcome",
        );
        assert_eq!(forward_contract(), rebuilt.id());
    }

    #[test]
    fn the_request_carries_the_forward_contract() {
        let req = Forward {
            token: Bytes::from_static(b"tok"),
            contract: cid(b"http.get"),
            payload: Bytes::from_static(b"body"),
        }
        .into_request();
        assert_eq!(req.id, forward_contract());
    }

    #[test]
    fn forward_and_respond_are_distinct_contracts() {
        assert_ne!(forward_contract(), crate::respond_contract());
        assert_ne!(forward_contract(), crate::deliver_contract());
    }
}
