//! The Cadenza platform runtime (`design/cadenza-platform.md`).
//!
//! A single unified crate, built bottom-up. The foundation is the content hash ([`Hash`], §8) — the sole
//! identity in the system: a contract-id is the hash of a contract declaration, a blob is addressed by the
//! hash of its bytes, and the content-addressed store is unpermissioned because the hash *is* the
//! capability. Over it sit the value primitives ([`Str`], [`Bytes`], §12), the swappable async backends
//! (the [`BlobStore`] §8 and the [`KvStore`] §7), the [`Contract`] whose declaration hashes to its id (§1),
//! the ordinary [`Reducer`] interface and its event types (§3), and the [`HandlerRegistry`] of handler
//! chains the system reducer routes through (§3/§4). The system reducer, dispatch, and the request context
//! come next (§4).

mod blob_store;
mod contract;
mod deliver;
// The `deliver` contract's schema, generated by `cargo xtask codegen` from `contracts/deliver.sexp`
// (real Cadenza the compiler typechecks at codegen time). Plain Cadenza-AST builder calls — no compiler
// dependency ships. Regenerate after editing the source; `cargo xtask codegen --check` gates staleness.
mod deliver_schema;
mod event_registry;
mod hash;
mod hierarchy;
mod ids;
mod kv;
mod reducer;
mod registry;
mod runtime;
mod str;

pub use blob_store::{BlobStore, InMemoryBlobStore};
pub use contract::Contract;
pub use deliver::{Deliver, Delivered, deliver_contract};
pub use event_registry::EventRegistry;
pub use hash::{Hash, base64url};
pub use hierarchy::{Ancestors, Hierarchy};
pub use ids::{ContractId, HostId, ProgramHash, ReducerId};
pub use kv::{InMemoryKvStore, KeyRange, KvKeyScan, KvScan, KvStore, prefix_range};
pub use reducer::{Error, Message, Notification, Origin, Outcome, Reducer, Request, Response};
pub use registry::HandlerRegistry;
pub use runtime::Runtime;
pub use str::Str;

// Re-export the byte-buffer type the platform marshals through, so downstream code depends on the
// platform's chosen `Bytes` (spec §12: every byte buffer is `bytes::Bytes`, never `Vec<u8>`).
pub use bytes::Bytes;
