//! The Cadenza platform runtime (`design/cadenza-platform.md`).
//!
//! A single unified crate, built bottom-up. The foundation is the content hash ([`Hash`], §8) — the sole
//! identity in the system: a contract-id is the hash of a contract declaration, a blob is addressed by the
//! hash of its bytes, and the content-addressed store is unpermissioned because the hash *is* the
//! capability. Over it sit the value primitives ([`Str`], [`Bytes`], §12), the swappable async backends
//! (the [`BlobStore`] §8 and the [`KvStore`] §7), the [`Contract`] whose declaration hashes to its id (§1),
//! the ordinary [`Reducer`] interface and its event types (§3), and the [`ReducerGraph`] — the one routing
//! substrate holding the spawn tree, supervision links, and the handler chains the system reducer routes
//! through (§3/§4/§7). The system reducer, dispatch, and the request context come next (§4).

mod blob_store;
// A generic cancellation scope for spawned futures — wrap a future, run it, and cancel whatever is still
// running when the scope drops. Used by the reducer loop to cancel a reducer's pending timers on exit.
mod cancel;
mod contract;
// The canonical value-model primitives every generated contract value builder/reader defers to (the
// `(. T C)` / `("record" (= f v)…)` forms in one place).
mod contract_value;
// Each built-in contract's schema + value builders/readers, generated by `cargo xtask codegen` from
// `contracts/<name>.cdz` (real Cadenza validated by the `cdz` binary at codegen time). Plain Cadenza-AST
// builder calls — no compiler dependency ships. Regenerate after editing a source; `cargo xtask codegen
// --check` gates staleness.
mod contracts;
mod deliver;
mod event_registry;
mod genesis;
mod graph;
mod hash;
mod ids;
mod kv;
mod lifecycle;
mod program;
mod reducer;
mod runtime;
mod spawned;
mod str;
mod system;
mod timer;

pub use blob_store::{BlobStore, InMemoryBlobStore};
pub use contract::Contract;
pub use deliver::{Deliver, Delivered, deliver_contract};
pub use event_registry::{EventRegistry, InMemoryEventRegistry};
pub use genesis::Genesis;
pub use graph::{Dir, EdgeKind, InMemoryReducerGraph, ReducerGraph};
pub use hash::{Hash, HashTag, Hasher, base64url};
pub use ids::{ContractId, HostId, ProgramHash, ReducerId};
pub use kv::{InMemoryKvStore, KeyRange, KvKeyScan, KvScan, KvStore, prefix_range};
pub use lifecycle::{Lifecycle, lifecycle_contract};
pub use program::ProgramStore;
pub use reducer::{Error, Message, Notification, Origin, Outcome, Reducer, Request, Response};
#[cfg(any(test, feature = "testing"))]
pub use runtime::BachRuntime;
pub use runtime::{Runtime, TokioRuntime};
pub use spawned::{Spawned, spawned_contract};
pub use str::Str;
pub use system::{Links, ReducerKind, Spawn, System, SystemError, TaskSystem};
pub use timer::{FireAfter, Fired, timer_contract};

// Re-export the byte-buffer type the platform marshals through, so downstream code depends on the
// platform's chosen `Bytes` (spec §12: every byte buffer is `bytes::Bytes`, never `Vec<u8>`).
pub use bytes::Bytes;

/// Test-support: swappable pieces for exercising components in isolation, without standing up the full
/// system. Each component's test helpers are re-exported here under the component's name (so a component's
/// production surface stays free of test scaffolding). Behind the `testing` feature (on automatically under
/// `cfg(test)`); enable it to reach these from another crate's tests.
#[cfg(any(test, feature = "testing"))]
pub mod testing {
    /// The [`program`](crate::program) module's test helpers — `program::Store`, a program store backed by
    /// registered Rust factories instead of the content-addressed store.
    pub use crate::program::testing as program;
}
