//! The respond primitive (`design/cadenza-platform.md` §4).
//!
//! `respond` is one of the two built-in effects a handler emits to act on an effect delivered to it (the
//! other is [`forward`](crate::forward)): it answers or denies, and the event reducer routes the answer back
//! down the chain to the caller, discharging the handler's pending obligation. A handler emits it as an
//! ordinary [`Request`] against the [`respond_contract`], whose payload is a [`Respond`] envelope carrying
//! the answer and the echoed correlation token.
//!
//! The event reducer matches the response to the open obligation by the handler's kernel-stamped `from`
//! (§3) and the `token` echoed in the envelope — the continuation-token the event reducer chose when it
//! delivered the effect. That token cannot ride on the emitted request's own continuation-token (which is
//! the handler's correlation for the respond effect's own answer), so it travels in the envelope. The
//! `answer` is the contract's output value or a runtime failure, exactly as a [`Response`] carries it: a
//! handler's domain failure is still an `Ok` output (the output type encodes it), while `Err` is a runtime
//! [`Error`].
//!
//! Like [`deliver`](crate::deliver), the schema is not hand-authored: it lives as real Cadenza in
//! `contracts/respond.cdz`, whose module pragmas name the contract and its input/output types, and `cargo
//! xtask codegen` typechecks it with the `cdz` binary and generates [`crate::contracts::respond`] (the
//! schema builders and the [`contract`](crate::contracts::respond::contract) constructor). The envelope is a
//! Cadenza value encoded through the one canonical binary codec ([`cadenza_ast::codec`]); [`Respond::decode`]
//! is total, returning `None` on any input that is not a well-formed respond value.

use crate::{Bytes, Contract, ContractId, Error, Request};
use cadenza_ast::ast::{Builder, StructId};
use cadenza_ast::codec;
use std::sync::OnceLock;

/// The built-in contract a [`Request`](crate::Request) is emitted against to respond (§4). A real contract
/// whose id is the hash of its declared schema — generated by `cargo xtask codegen` from
/// `contracts/respond.cdz` into [`crate::contracts::respond::contract`]; built once and cached, so the id is
/// derived only once.
#[must_use]
pub fn respond_contract() -> ContractId {
    static RESPOND: OnceLock<Contract> = OnceLock::new();
    RESPOND
        .get_or_init(crate::contracts::respond::contract)
        .id()
}

/// A respond envelope: answer the obligation correlated by `token` with `answer` (§4). This is what the
/// payload of a respond [`Request`](crate::Request) carries; the event reducer decodes it and routes the
/// answer back down the chain.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Respond {
    /// The continuation-token the event reducer chose on delivery, echoed to name the obligation answered.
    pub token: Bytes,
    /// The answer: the contract's output value (`Ok`, a domain error included) or a runtime failure (`Err`).
    pub answer: Result<Bytes, Error>,
}

impl Respond {
    /// Encode the envelope as a Cadenza value in the canonical binary form ([`cadenza_ast::codec`]) — the
    /// inverse of [`decode`](Self::decode).
    #[must_use]
    pub fn encode(&self) -> Bytes {
        let mut b = Builder::new();
        let root = self.build(&mut b);
        let arenas = b.finish(root);
        Bytes::from(codec::encode(&arenas))
    }

    /// Build the envelope value into `b`, returning its root — a value of the schema type `Envelope`. The
    /// value SHAPE is entirely the generated builders' (`contracts::respond::*`); this only supplies the
    /// `Bytes` leaves and the prelude `Result` value (`Ok`/`Err` are prelude constructors, not in this
    /// contract's schema, so they use the generic [`v::bare_ctor`]).
    fn build(&self, b: &mut Builder) -> StructId {
        use crate::contract_value as v;
        use crate::contracts::respond as c;

        let token = v::bytes_leaf(b, &self.token);
        let answer = match &self.answer {
            Ok(value) => {
                let x = v::bytes_leaf(b, value);
                v::bare_ctor(b, "Ok", vec![x])
            }
            Err(error) => {
                let e = match error {
                    Error::Timeout => c::error_timeout(b),
                    Error::MissingHandler => c::error_missing_handler(b),
                    Error::SchemaViolation => c::error_schema_violation(b),
                    Error::Faulted => c::error_faulted(b),
                };
                v::bare_ctor(b, "Err", vec![e])
            }
        };
        c::envelope_respond(b, c::EnvelopeRespond { token, answer })
    }

    /// The respond [`Request`](crate::Request) a handler emits to carry this out: against the
    /// [`respond_contract`], with the envelope as its payload. Its own continuation-token is the handler's to
    /// choose for correlating the respond effect's answer; this convenience leaves it empty and sets no
    /// deadline — the obligation it discharges is named by the echoed `token` inside the envelope.
    #[must_use]
    pub fn into_request(self) -> Request {
        Request {
            id: respond_contract(),
            payload: self.encode(),
            continuation_token: Bytes::new(),
            deadline: None,
        }
    }

    /// Decode an envelope from a Cadenza value, or `None` if the bytes are not a well-formed respond value.
    /// Total, so a malformed envelope is a rejected respond, never a panic.
    #[must_use]
    pub fn decode(bytes: &[u8]) -> Option<Self> {
        use crate::contract_value as v;
        use crate::contracts::respond as c;

        let arenas = codec::decode(bytes)?;
        let env = c::as_envelope_respond(&arenas, arenas.root)?;
        let token = v::read_bytes(&arenas, env.token)?;
        let answer = decode_result(&arenas, env.answer)?;
        Some(Self { token, answer })
    }
}

/// Read a `Result(Bytes, Error)` value — the prelude `Ok`/`Err` constructors (via the generic bare-ctor
/// reader), the `Err` payload being a generated `Error` value.
fn decode_result(arenas: &cadenza_ast::ast::Arenas, id: StructId) -> Option<Result<Bytes, Error>> {
    use crate::contract_value as v;
    use crate::contracts::respond as c;

    if let Some([value]) = v::as_bare_ctor(arenas, id, "Ok").and_then(one) {
        return Some(Ok(v::read_bytes(arenas, value)?));
    }
    if let Some([err]) = v::as_bare_ctor(arenas, id, "Err").and_then(one) {
        return Some(Err(if c::is_error_timeout(arenas, err) {
            Error::Timeout
        } else if c::is_error_missing_handler(arenas, err) {
            Error::MissingHandler
        } else if c::is_error_schema_violation(arenas, err) {
            Error::SchemaViolation
        } else if c::is_error_faulted(arenas, err) {
            Error::Faulted
        } else {
            return None;
        }));
    }
    None
}

/// A slice of exactly `N` occurrences as a fixed array, or `None`.
fn one<const N: usize>(items: &[StructId]) -> Option<[StructId; N]> {
    <[StructId; N]>::try_from(items).ok()
}

#[cfg(test)]
mod tests {
    use super::{Respond, respond_contract};
    use crate::{Bytes, Error};

    fn round_trips(r: &Respond) {
        assert_eq!(Respond::decode(&r.encode()), Some(r.clone()));
    }

    #[test]
    fn a_respond_round_trips_for_ok_and_every_error() {
        for answer in [
            Ok(Bytes::from_static(b"the answer")),
            Err(Error::Timeout),
            Err(Error::MissingHandler),
            Err(Error::SchemaViolation),
            Err(Error::Faulted),
        ] {
            round_trips(&Respond {
                token: Bytes::from_static(b"tok"),
                answer,
            });
        }
    }

    #[test]
    fn decode_rejects_bytes_that_are_not_a_respond_value() {
        assert_eq!(Respond::decode(&[0xFF, 0x00, 0x13, 0x37]), None);
        assert_eq!(Respond::decode(&[]), None);
        // A well-formed Cadenza value of the wrong shape decodes cleanly but is not a respond.
        let mut b = cadenza_ast::ast::Builder::new();
        let root = b.name("not-a-respond");
        let wrong_shape = cadenza_ast::codec::encode(&b.finish(root));
        assert_eq!(Respond::decode(&wrong_shape), None);
    }

    #[test]
    fn the_respond_contract_id_is_a_real_contract_id_and_stable() {
        assert_eq!(respond_contract(), respond_contract());
        let rebuilt = crate::Contract::new(
            crate::Str::from_static("cdz-platform.respond"),
            crate::contracts::respond::schema,
            "Envelope",
            "Outcome",
        );
        assert_eq!(respond_contract(), rebuilt.id());
    }

    #[test]
    fn the_request_carries_the_respond_contract() {
        let req = Respond {
            token: Bytes::from_static(b"tok"),
            answer: Ok(Bytes::from_static(b"a")),
        }
        .into_request();
        assert_eq!(req.id, respond_contract());
    }
}
