(case "bf3 tagged-record round-trip — arms ENCODE (tag,val) u8 pairs into the frame state, the body decodes the REPLAYED frame"
  (input  (do
            (effect W (op rec (-> Int64 Int64 Int64)) (op replay (-> Bytes)))
            (def (main (: n Int64))
              (handle W (bin)
                ((rec (t v) fr (resume v (Bytes.concat fr (bin (u8 (UInt8.wrap t)) (u8 (UInt8.wrap v))))))
                 (replay () fr (resume fr fr)))
                (do (W.rec 1 (+ 10 n)) (W.rec 2 (+ 20 n))
                    (match (W.replay)
                      ((bin (u8 t1) (u8 v1) (u8 t2) (u8 v2))
                       (+ (* 1000 (+ (* 100 (Int64.of t1)) (Int64.of v1)))
                          (+ (* 100 (Int64.of t2)) (Int64.of v2))))
                      (_other -1)))))
            (export main)))
  (call   main (: 1 Int64)) (output (: 111221 Int64))
  (call   main (: 4 Int64)) (output (: 114224 Int64))
  (call   main (: 0 Int64)) (output (: 110220 Int64)))
