/// Curated starter programs for the playground's Examples dropdown. Each is a full program (the
/// playground buffer is compiled verbatim) authored in the s-expression surface as flat top-level
/// definitions grouped in a `(do …)` (no `module` wrapper — that's boilerplate unless an example's
/// point IS modules); the surface toggle re-renders them into idiomatic top-level ML `def`s. All are
/// verified to compile + run against the current compiler.
///
/// The EXAMPLES[] array below is @GENERATED from the sibling `examples.sexp` (the source-of-truth) by
/// `xtask-codegen-guide --playground-registry`. Do NOT hand-edit the generated region — edit
/// `examples.sexp` and regenerate. The `Example` interface + this header are hand-written.

import type { Surface } from "../compiler/client.ts";

export interface Example {
  /// Stable kebab-case identifier — the deep-link target (`/playground?example=<id>`) and the nav key.
  /// Distinct from `name` (the human label) so a rename of the label never breaks a deep-link.
  id: string;
  name: string;
  /// Which themed nav bucket this example sits under in the sidebar's "Examples" section. Drives the
  /// grouping v-guide-infra renders from data (no hardcoded nav list). Kept coarse (4 buckets) so 36
  /// examples stay scannable: basics (language fundamentals), algorithms (classic computations),
  /// data-and-collections (lists/maps/sets/records at work), numbers (numeric-model showcases).
  theme: "basics" | "algorithms" | "data-and-collections" | "numbers";
  surface: Surface;
  source: string;
  /// Optional pinned result, in the S-EXPR canonical render. When set, the check-examples gate asserts the
  /// program runs to exactly this value — turning the example into a regression test rather than a mere
  /// "it runs" check. BOTH scalars (bare number/bool) AND compound values are pinnable: a playground
  /// example has no in-browser Check (it's loaded and Run), so an s-expr-canonical compound like
  /// `(: (list 1 2 3) (List Int64))` is stable to pin. The value is compared on the s-expr pass, and the
  /// gate runs both surfaces — so a pin IS checked either way, but for an ML-authored example it's only
  /// asserted against the RENDERED s-expr toggle output (brittle: depends on a byte-stable ML→s-expr
  /// render, and the pin reads in a different surface than it's maintained in). So pins must be
  /// `surface: "sexpr"` — all playground examples are, and check-examples FAILS LOUDLY on a non-sexpr pin.
  /// (A graded chapter EXERCISE differs: it's compared in the reader's LIVE surface, where a compound
  /// renders differently in ML vs s-expr, so exercise pins stay scalar-only — see check-examples.)
  expected?: string;
  /// When `true`, this example is a teaching case authored to NOT compile (the "see the squiggle" type
  /// error). The check-examples gate then asserts it DECLINES rather than runs — an intentional negative
  /// case. Declared explicitly here (not sniffed from `source`) so re-authoring the example's body to a
  /// different type error can't silently flip it back to a value-example that then fails the sweep.
  expectError?: boolean;
}

export const EXAMPLES: Example[] = [
  // <generated:examples> — DO NOT EDIT; regenerated by `xtask-codegen-guide --playground-registry` (from examples.sexp)
  {
    id: "hello-arithmetic",
    name: "Hello, arithmetic",
    theme: "basics",
    surface: "sexpr",
    source: `(do
  (def (main) (+ 2 3))

  (export main))`,
    expected: "5",
  },
  {
    id: "recursive-sum",
    name: "A recursive sum",
    theme: "basics",
    surface: "sexpr",
    source: `(do
  (def (sm n) (if (= n 0) 0 (+ n (sm (- n 1)))))

  (def (main) (sm 5))

  (export main))`,
    expected: "15",
  },
  {
    id: "pattern-matching",
    name: "Pattern matching",
    theme: "basics",
    surface: "sexpr",
    source: `(do
  (def (main) (match 2 (1 10) (2 20) (_ 0)))

  (export main))`,
    expected: "20",
  },
  {
    id: "option-sum-types",
    name: "Option & sum types",
    theme: "basics",
    surface: "sexpr",
    source: `(do
  (type Opt (Some Int64) (None unit))

  (def (main) (match (Some 7) ((Some x) x) ((None _) 0)))

  (export main))`,
    expected: "7",
  },
  {
    id: "records",
    name: "Records",
    theme: "basics",
    surface: "sexpr",
    source: `(do
  (def (area r) (* r.w r.h))

  (def (main) (area #record((= w 4) (= h 5))))

  (export main))`,
    expected: "20",
  },
  {
    id: "record-patterns",
    name: "Record patterns (match on fields)",
    theme: "basics",
    surface: "sexpr",
    source: `(do
  (def
    (score p)
    (match p (#record((= x 0) (= y 0)) 0) (#record((= x xv) (= y yv)) (+ (* xv xv) (* yv yv)))))

  (def (main) (score #record((= x 3) (= y 4))))

  (export main))`,
    expected: "25",
  },
  {
    id: "nested-record-patterns",
    name: "Nested record patterns (destructure in place)",
    theme: "basics",
    surface: "sexpr",
    source: `(do
  (def
    (weigh pair)
    (match pair (#tuple(#record((= x px) (= y py)) w) (* w (+ (* px px) (* py py))))))

  (def (main) (weigh #tuple(#record((= x 3) (= y 4)) 2)))

  (export main))`,
    expected: "50",
  },
  {
    id: "variant-nested-record-patterns",
    name: "Variant-nested record patterns (match through a variant)",
    theme: "basics",
    surface: "sexpr",
    source: `(do
  (def
    (dist opt)
    (match opt ((Some #record((= x px) (= y py))) (+ (* px px) (* py py))) ((None) 0)))

  (def (main) (dist (Some #record((= x 3) (= y 4)))))

  (export main))`,
    expected: "25",
  },
  {
    id: "tuple",
    name: "A tuple",
    theme: "basics",
    surface: "sexpr",
    source: `(do
  (def (main) #tuple(1 2 3))

  (export main))`,
    expected: "(: #tuple(1 2 3) (Tuple Int64 Int64 Int64))",
  },
  {
    id: "tuple-split-concat",
    name: "Splitting & joining tuples",
    theme: "basics",
    surface: "sexpr",
    source: `(do
  (def
    (main)
    (let
      ((parts (Tuple.split-at #tuple(1 2 3 4 5) 2)))
      (match parts (#tuple(head tail) #tuple(head tail (Tuple.concat head tail))))))

  (export main))`,
    expected: "(: #tuple(#tuple(1 2) #tuple(3 4 5) #tuple(1 2 3 4 5)) (Tuple (Tuple Int64 Int64) (Tuple Int64 Int64 Int64) (Tuple Int64 Int64 Int64 Int64 Int64)))",
  },
  {
    id: "lists",
    name: "Lists",
    theme: "basics",
    surface: "sexpr",
    source: `(do
  (def (main) (List.concat #list(1 2) #list(3 4 5)))

  (export main))`,
    expected: "(: #list(1 2 3 4 5) (List Int64))",
  },
  {
    id: "list-update-functional",
    name: "Functional list update",
    theme: "basics",
    surface: "sexpr",
    source: `(do
  (def (set-at xs i v) (List.update xs i v))

  (def (main) (let ((xs #list(10 20 30 40 50))) #tuple((set-at xs 0 99) (set-at xs 4 99) xs)))

  (export main))`,
    expected: "(: #tuple(#list(99 20 30 40 50) #list(10 20 30 40 99) #list(10 20 30 40 50)) (Tuple (List Int64) (List Int64) (List Int64)))",
  },
  {
    id: "expression-interpreter",
    name: "Expression interpreter",
    theme: "algorithms",
    surface: "sexpr",
    source: `(do
  (type Expr (Lit Int64) (Add (Tuple Expr Expr)) (Mul (Tuple Expr Expr)) (Neg Expr))

  (def
    (eval e)
    (match
      e
      ((Lit n) n)
      ((Add p) (+ (eval (. p 0)) (eval (. p 1))))
      ((Mul p) (* (eval (. p 0)) (eval (. p 1))))
      ((Neg x) (Num.neg (eval x)))))

  (def (main) (eval (Mul #tuple((Add #tuple((Lit 2) (Lit 3))) (Neg (Lit 4))))))

  (export main))`,
    expected: "-20",
  },
  {
    id: "collatz-orbit",
    name: "Collatz orbit length",
    theme: "algorithms",
    surface: "sexpr",
    source: `(do
  (def
    (collatz n steps)
    (if
      (= n 1)
      steps
      (if (= (% n 2) 0) (collatz (/ n 2) (+ steps 1)) (collatz (+ (* 3 n) 1) (+ steps 1)))))

  (def (main) (collatz 27 0))

  (export main))`,
    expected: "111",
  },
  {
    id: "function-composition",
    name: "Function composition",
    theme: "basics",
    surface: "sexpr",
    source: `(do
  (def (compose f g) (fn (x) (f (g x))))

  (def (double x) (* x 2))

  (def (inc x) (+ x 1))

  (def (main) ((compose double inc) 20))

  (export main))`,
    expected: "42",
  },
  {
    id: "higher-order-apply-n",
    name: "Higher-order functions (apply n times)",
    theme: "basics",
    surface: "sexpr",
    source: `(do
  (def (apply-n-times f n x) (if (= n 0) x (apply-n-times f (- n 1) (f x))))

  (def (adder k) (fn (x) (+ x k)))

  (def (main) #tuple((apply-n-times (adder 3) 4 10) (apply-n-times (fn (x) (* x 2)) 5 1)))

  (export main))`,
    expected: "(: (tuple 22 32) (Tuple Int64 Int64))",
  },
  {
    id: "memoized-fibonacci",
    name: "Memoized Fibonacci (Map cache)",
    theme: "data-and-collections",
    surface: "sexpr",
    source: `(do
  (def
    (fib n mp)
    (match
      (Map.lookup mp n)
      ((Some v) #tuple(v mp))
      ((None)
        (if
          (< n 2)
          #tuple(n (Map.insert mp n n))
          (let
            ((a (fib (- n 1) mp)))
            (let
              ((b (fib (- n 2) (. a 1))))
              (let ((r (+ (. a 0) (. b 0)))) #tuple(r (Map.insert (. b 1) n r)))))))))

  (def (main) (. (fib 30 (Map.empty)) 0))

  (export main))`,
    expected: "832040",
  },
  {
    id: "frequency-count",
    name: "Frequency count (fold into a Map)",
    theme: "data-and-collections",
    surface: "sexpr",
    source: `(do
  (def
    (bump mp k)
    (match (Map.lookup mp k) ((Some c) (Map.insert mp k (+ c 1))) ((None) (Map.insert mp k 1))))

  (def
    (tally xs i n mp)
    (if (= i n) mp (match (List.at xs i) ((Some x) (tally xs (+ i 1) n (bump mp x))) ((None) mp))))

  (def (main) (let ((xs #list(3 1 3 3 1 2))) (Map.to-list (tally xs 0 (List.len xs) (Map.empty)))))

  (export main))`,
    expected: "(: #list(#tuple(1 2) #tuple(2 1) #tuple(3 3)) (List (Tuple Int64 Int64)))",
  },
  {
    id: "map-swap-take-inventory",
    name: "Map swap & take (inventory)",
    theme: "data-and-collections",
    surface: "sexpr",
    source: `(do
  (def
    (main)
    (let
      ((stock (Map.insert (Map.insert (Map.empty) 1 5) 2 2)))
      (match
        (Map.swap stock 1 9)
        (#tuple(old-apples restocked)
          (match
            (Map.take restocked 2)
            (#tuple(gone-pears final) #tuple(old-apples gone-pears (Map.to-list final))))))))

  (export main))`,
    expected: "(: #tuple((Some 5) (Some 2) #list(#tuple(1 9))) (Tuple (Option Int64) (Option Int64) (List (Tuple Int64 Int64))))",
  },
  {
    id: "bytes-map-key",
    name: "Bytes as a Map key",
    theme: "data-and-collections",
    surface: "sexpr",
    source: `(do
  (def
    (bump (: m (Map Bytes Int64)) (: k Bytes))
    (match (Map.lookup m k) ((Some c) (Map.insert m k (+ c 1))) ((None) (Map.insert m k 1))))

  (def
    (main)
    (let
      ((red (String.to-bytes "red")) (blue (String.to-bytes "blue")))
      (let
        ((m (bump (bump (bump (bump (Map.empty) red) blue) red) red)))
        #tuple((Map.lookup m red) (Map.lookup m blue)))))

  (export main))`,
    expected: "(: #tuple((Some 3) (Some 1)) (Tuple (Option Int64) (Option Int64)))",
  },
  {
    id: "symbol-keyed-map",
    name: "Symbols as Map keys",
    theme: "data-and-collections",
    surface: "sexpr",
    source: `(do
  (def
    (main)
    (let
      ((palette
          (Map.insert
            (Map.insert
              (Map.insert (Map.empty) (Symbol.of "red") 16711680)
              (Symbol.of "green")
              65280)
            (Symbol.of "blue")
            255)))
      #tuple((Map.lookup palette (Symbol.of "green"))
        (Map.lookup palette (Symbol.of "teal"))
        (= (Symbol.of "red") (Symbol.of "red")))))

  (export main))`,
    expected: "(: #tuple((Some 65280) (None unit) true) (Tuple (Option Int64) (Option Int64) Bool))",
  },
  {
    id: "byte-string-literal",
    name: "Byte-string literal",
    theme: "data-and-collections",
    surface: "sexpr",
    source: `(do
  (def
    (main)
    (let
      ((magic b"GIF89a"))
      (match
        (Bytes.at magic 0)
        ((Some first) #tuple((Bytes.len magic) first))
        ((None) (trap "byte-literal: unexpectedly empty")))))

  (export main))`,
    expected: "(: #tuple(6 71) (Tuple Int64 Int64))",
  },
  {
    id: "value-encode-canonical-bytes",
    name: "Canonical binary encoding (Value.encode)",
    theme: "data-and-collections",
    surface: "sexpr",
    source: `(do
  (def (size v) (Bytes.len (Value.encode v)))

  (def (main) #tuple((size #record((= x 3) (= y 4))) (size (Some 7)) (size #list(1 2 3))))

  (export main))`,
    expected: "(: (tuple 102 61 66) (Tuple Int64 Int64 Int64))",
  },
  {
    id: "value-encode-determinism",
    name: "Structural encoding is deterministic (Value.encode)",
    theme: "data-and-collections",
    surface: "sexpr",
    source: `(do
  (def
    (main)
    (let
      ((ba (Value.encode #record((= x 3) (= y 4))))
        (bb (Value.encode #record((= x 3) (= y 4))))
        (bc (Value.encode #record((= x 3) (= y 5)))))
      #tuple((Bytes.len ba) (= ba bb) (= ba bc))))

  (export main))`,
    expected: "(: (tuple 102 true false) (Tuple Int64 Bool Bool))",
  },
  {
    id: "value-encode-roundtrip",
    name: "Encode / decode round-trip (Value)",
    theme: "data-and-collections",
    surface: "sexpr",
    source: `(do
  (type Point (Mk (Record (: x Int64) (: y Int64))))

  (def
    (main)
    (let
      ((p (Point.Mk #record((= x 3) (= y 4)))))
      (let
        ((bytes (Value.encode p)))
        (match
          (: (Value.decode bytes) (Option Point))
          ((Some (Point.Mk r)) #tuple((Bytes.len bytes) (+ r.x r.y)))
          ((None) #tuple((Bytes.len bytes) 0))))))

  (export main))`,
    expected: "(: (tuple 73 7) (Tuple Int64 Int64))",
  },
  {
    id: "exact-rational-arithmetic",
    name: "Exact rational arithmetic",
    theme: "numbers",
    surface: "sexpr",
    source: `(do
  (pragma default-fraction Rational)

  (def (sum) (+ (+ (/ 1 2) (/ 1 3)) (/ 1 6)))

  (def (main) (sum))

  (export main))`,
    expected: "(: 1/1 Rational)",
  },
  {
    id: "rational-parts",
    name: "Rational numerator & denominator",
    theme: "numbers",
    surface: "sexpr",
    source: `(do
  (pragma default-fraction Rational)

  (def (total) (+ (+ (/ 1 2) (/ 1 3)) (/ 1 12)))

  (def (main) #tuple((Rational.numerator (total)) (Rational.denominator (total))))

  (export main))`,
    expected: "(: #tuple(11 12) (Tuple BigInt BigInt))",
  },
  {
    id: "rational-floor-ceil",
    name: "Rational floor & ceil",
    theme: "numbers",
    surface: "sexpr",
    source: `(do
  (pragma default-fraction Rational)

  (def
    (main)
    #tuple((Rational.floor (/ 7 2))
      (Rational.ceil (/ 7 2))
      (Rational.floor (/ -7 2))
      (Rational.ceil (/ -7 2))))

  (export main))`,
    expected: "(: #tuple(3 4 -4 -3) (Tuple Int64 Int64 Int64 Int64))",
  },
  {
    id: "float-rounding-drift",
    name: "Float rounding drift",
    theme: "numbers",
    surface: "sexpr",
    source: `(do
  (def (add-tenths (: n Int64) (: acc Float64)) (if (= n 0) acc (add-tenths (- n 1) (+ acc 0.1))))

  (def (main) (add-tenths 10 0.0))

  (export main))`,
    expected: "0.9999999999999999",
  },
  {
    id: "gcd-lcm-euclid",
    name: "GCD and LCM (Euclid)",
    theme: "algorithms",
    surface: "sexpr",
    source: `(do
  (def (gcd a b) (if (= b 0) a (gcd b (% a b))))

  (def (lcm a b) (/ (* a b) (gcd a b)))

  (def (main) (lcm 12 18))

  (export main))`,
    expected: "36",
  },
  {
    id: "set-algebra",
    name: "Set algebra (symmetric difference)",
    theme: "data-and-collections",
    surface: "sexpr",
    source: `(do
  (def (sym-diff a b) (Set.union (Set.difference a b) (Set.difference b a)))

  (def
    (main)
    (let ((a (Set.of #list(1 2 3 4))) (b (Set.of #list(3 4 5 6)))) (Set.to-list (sym-diff a b))))

  (export main))`,
    expected: "(: #list(1 2 5 6) (List Int64))",
  },
  {
    id: "set-intersection-mutual",
    name: "Mutual friends (set intersection)",
    theme: "data-and-collections",
    surface: "sexpr",
    source: `(do
  (def (mutual a b) (Set.to-list (Set.intersection (Set.of a) (Set.of b))))

  (def (main) (mutual #list(1 2 3 4 5) #list(3 4 5 6 7)))

  (export main))`,
    expected: "(: #list(3 4 5) (List Int64))",
  },
  {
    id: "rpn-calculator",
    name: "RPN calculator (stack machine)",
    theme: "algorithms",
    surface: "sexpr",
    source: `(do
  (type Stack (Empty unit) (Cons (Tuple Int64 Stack)))

  (def (push s x) (Cons #tuple(x s)))

  (type Tok (Num Int64) (Plus unit) (Times unit))

  (def
    (apply2 s f)
    (match
      s
      ((Cons top1)
        (match
          (. top1 1)
          ((Cons top2) (push (. top2 1) (f (. top2 0) (. top1 0))))
          ((Empty _) (trap "rpn: operator underflow (need two operands)"))))
      ((Empty _) (trap "rpn: operator underflow (empty stack)"))))

  (def
    (step s tok)
    (match tok ((Num n) (push s n)) ((Plus _) (apply2 s +)) ((Times _) (apply2 s *))))

  (def
    (run toks i n s)
    (if (= i n) s (match (List.at toks i) ((Some t) (run toks (+ i 1) n (step s t))) ((None) s))))

  (def (top s) (match s ((Cons t) (. t 0)) ((Empty _) (trap "rpn: empty result stack"))))

  (def
    (main)
    (let
      ((toks #list((Num 3) (Num 4) (Plus unit) (Num 5) (Times unit))))
      (top (run toks 0 (List.len toks) (Empty unit)))))

  (export main))`,
    expected: "35",
  },
  {
    id: "count-primes",
    name: "Count primes (trial division)",
    theme: "algorithms",
    surface: "sexpr",
    source: `(do
  (def (isprime-from d n) (if (> (* d d) n) true (if (= (% n d) 0) false (isprime-from (+ d 1) n))))

  (def (isprime n) (if (< n 2) false (isprime-from 2 n)))

  (def (count k n acc) (if (> k n) acc (count (+ k 1) n (if (isprime k) (+ acc 1) acc))))

  (def (main) (count 2 100 0))

  (export main))`,
    expected: "25",
  },
  {
    id: "rule-110",
    name: "Rule 110 cellular automaton",
    theme: "algorithms",
    surface: "sexpr",
    source: `(do
  (def (cell xs i) (match (List.at xs i) ((Some v) v) ((None) 0)))

  (def
    (rule l c r)
    (match (+ (+ (* l 4) (* c 2)) r) (0 0) (1 1) (2 1) (3 1) (4 0) (5 1) (6 1) (7 0) (_ 0)))

  (def
    (step-from xs i n acc)
    (if
      (= i n)
      acc
      (step-from
        xs
        (+ i 1)
        n
        (List.push acc (rule (cell xs (- i 1)) (cell xs i) (cell xs (+ i 1)))))))

  (def (step xs) (step-from xs 0 (List.len xs) #list()))

  (def (gens xs k) (if (= k 0) xs (gens (step xs) (- k 1))))

  (def (main) (gens #list(0 0 0 0 0 0 0 1) 4))

  (export main))`,
    expected: "(: #list(0 0 0 1 1 1 1 1) (List Int64))",
  },
  {
    id: "data-pipeline",
    name: "Data pipeline over records",
    theme: "data-and-collections",
    surface: "sexpr",
    source: `(do
  (def (age r) r.age)

  (def
    (ages xs i n acc)
    (if
      (= i n)
      acc
      (match (List.at xs i) ((Some r) (ages xs (+ i 1) n (List.push acc (age r)))) ((None) acc))))

  (def
    (sum-age xs i n acc)
    (if
      (= i n)
      acc
      (match (List.at xs i) ((Some r) (sum-age xs (+ i 1) n (+ acc (age r)))) ((None) acc))))

  (def
    (main)
    (let
      ((people
          #list(#record((= name "Ada") (= age 36))
            #record((= name "Alan") (= age 41))
            #record((= name "Grace") (= age 40)))))
      #tuple((ages people 0 (List.len people) (: #list() (List Int64)))
        (/ (sum-age people 0 (List.len people) 0) (List.len people)))))

  (export main))`,
    expected: "(: #tuple(#list(36 41 40) 39) (Tuple (List Int64) Int64))",
  },
  {
    id: "matrix-transpose",
    name: "Matrix transpose",
    theme: "data-and-collections",
    surface: "sexpr",
    source: `(do
  (def
    (elem (: m (List (List Int64))) (: i Int64) (: j Int64))
    (match
      (List.at m i)
      ((Some r)
        (match (List.at r j) ((Some v) v) ((None) (trap "transpose: column index out of range"))))
      ((None) (trap "transpose: row index out of range"))))

  (def (col m j i rows acc) (if (= i rows) acc (col m j (+ i 1) rows (List.push acc (elem m i j)))))

  (def
    (go m j cols rows acc)
    (if
      (= j cols)
      acc
      (go m (+ j 1) cols rows (List.push acc (col m j 0 rows (: #list() (List Int64)))))))

  (def
    (main)
    (let ((m #list(#list(1 2 3) #list(4 5 6)))) (go m 0 3 2 (: #list() (List (List Int64))))))

  (export main))`,
    expected: "(: #list(#list(1 4) #list(2 5) #list(3 6)) (List (List Int64)))",
  },
  {
    id: "tower-of-hanoi",
    name: "Tower of Hanoi (move count)",
    theme: "algorithms",
    surface: "sexpr",
    source: `(do
  (def (hanoi n) (if (= n 0) 0 (+ (+ (hanoi (- n 1)) 1) (hanoi (- n 1)))))

  (def (main) (hanoi 10))

  (export main))`,
    expected: "1023",
  },
  {
    id: "population-count",
    name: "Population count (bits)",
    theme: "algorithms",
    surface: "sexpr",
    source: `(do
  (def (popcount n acc) (if (= n 0) acc (popcount (/ n 2) (+ acc (% n 2)))))

  (def (main) (popcount 2730 0))

  (export main))`,
    expected: "6",
  },
  {
    id: "run-length-encoding",
    name: "Run-length encoding",
    theme: "algorithms",
    surface: "sexpr",
    source: `(do
  (def
    (at (: xs (List Int64)) (: i Int64))
    (match (List.at xs i) ((Some v) v) ((None) (trap "rle: index out of range"))))

  (def
    (go xs i n cur cnt acc)
    (if
      (= i n)
      (List.push acc #tuple(cur cnt))
      (let
        ((x (at xs i)))
        (if
          (= x cur)
          (go xs (+ i 1) n cur (+ cnt 1) acc)
          (go xs (+ i 1) n x 1 (List.push acc #tuple(cur cnt)))))))

  (def
    (main)
    (let
      ((xs #list(1 1 1 2 3 3)))
      (go xs 1 (List.len xs) (at xs 0) 1 (: #list() (List (Tuple Int64 Int64))))))

  (export main))`,
    expected: "(: #list(#tuple(1 3) #tuple(2 1) #tuple(3 2)) (List (Tuple Int64 Int64)))",
  },
  {
    id: "quicksort",
    name: "Quicksort",
    theme: "algorithms",
    surface: "sexpr",
    source: `(do
  (def
    (at (: xs (List Int64)) (: i Int64))
    (match (List.at xs i) ((Some v) v) ((None) (trap "qsort: index out of range"))))

  (def
    (part xs i n pivot lows highs)
    (if
      (= i n)
      #tuple(lows highs)
      (let
        ((x (at xs i)))
        (if
          (< x pivot)
          (part xs (+ i 1) n pivot (List.push lows x) highs)
          (part xs (+ i 1) n pivot lows (List.push highs x))))))

  (def
    (qsort (: xs (List Int64)))
    (if
      (< (List.len xs) 2)
      xs
      (let
        ((pivot (at xs 0)))
        (match
          (part xs 1 (List.len xs) pivot (: #list() (List Int64)) (: #list() (List Int64)))
          (#tuple(lows highs) (List.concat (List.concat (qsort lows) #list(pivot)) (qsort highs)))))))

  (def (main) (qsort #list(5 3 8 1 9 2 7 4 6)))

  (export main))`,
    expected: "(: #list(1 2 3 4 5 6 7 8 9) (List Int64))",
  },
  {
    id: "binary-search",
    name: "Binary search",
    theme: "algorithms",
    surface: "sexpr",
    source: `(do
  (def
    (at (: xs (List Int64)) (: i Int64))
    (match (List.at xs i) ((Some v) v) ((None) (trap "bsearch: index out of range"))))

  (def
    (go xs target lo hi)
    (if
      (> lo hi)
      (: (None) (Option Int64))
      (let
        ((mid (/ (+ lo hi) 2)) (v (at xs mid)))
        (if
          (= v target)
          (Some mid)
          (if (< v target) (go xs target (+ mid 1) hi) (go xs target lo (- mid 1)))))))

  (def (bsearch (: xs (List Int64)) (: target Int64)) (go xs target 0 (- (List.len xs) 1)))

  (def (main) (let ((xs #list(1 3 5 7 9 11 13 15 17 19))) #tuple((bsearch xs 11) (bsearch xs 8))))

  (export main))`,
    expected: "(: #tuple((Some 5) (None unit)) (Tuple (Option Int64) (Option Int64)))",
  },
  {
    id: "binary-search-tree",
    name: "Binary search tree",
    theme: "data-and-collections",
    surface: "sexpr",
    source: `(do
  (type Tree (Leaf Unit) (Node (Tuple Int64 Tree Tree)))

  (def
    (insert (: t Tree) (: x Int64))
    (match
      t
      ((Leaf _u) (Node #tuple(x (Leaf unit) (Leaf unit))))
      ((Node nd)
        (match
          nd
          (#tuple(v l r)
            (if
              (< x v)
              (Node #tuple(v (insert l x) r))
              (if (> x v) (Node #tuple(v l (insert r x))) (Node #tuple(v l r)))))))))

  (def
    (inorder (: t Tree))
    (match
      t
      ((Leaf _u) (: #list() (List Int64)))
      ((Node nd) (match nd (#tuple(v l r) (List.concat (List.push (inorder l) v) (inorder r)))))))

  (def
    (build (: xs (List Int64)) (: i Int64) (: t Tree))
    (if
      (= i (List.len xs))
      t
      (match
        (List.at xs i)
        ((Some x) (build xs (+ i 1) (insert t x)))
        ((None) (trap "build: index out of range")))))

  (def (main) (let ((xs #list(5 3 8 1 4 7 9 2 6))) (inorder (build xs 0 (Leaf unit)))))

  (export main))`,
    expected: "(: #list(1 2 3 4 5 6 7 8 9) (List Int64))",
  },
  {
    id: "palindrome-check",
    name: "Palindrome check",
    theme: "algorithms",
    surface: "sexpr",
    source: `(do
  (def
    (at bs i)
    (match (Bytes.at bs i) ((Some b) b) ((None) (trap "palindrome: byte index out of range"))))

  (def (pal bs i j) (if (>= i j) true (if (= (at bs i) (at bs j)) (pal bs (+ i 1) (- j 1)) false)))

  (def (main) (let ((bs (String.to-bytes "racecar"))) (pal bs 0 (- (Bytes.len bs) 1))))

  (export main))`,
    expected: "true",
  },
  {
    id: "count-vowels",
    name: "Count vowels",
    theme: "algorithms",
    surface: "sexpr",
    source: `(do
  (def
    (is-vowel b)
    (if
      (= b 97)
      true
      (if (= b 101) true (if (= b 105) true (if (= b 111) true (if (= b 117) true false))))))

  (def
    (byte-at bs i)
    (match (Bytes.at bs i) ((Some b) b) ((None) (trap "count-vowels: byte index out of range"))))

  (def
    (go bs i n acc)
    (if (= i n) acc (go bs (+ i 1) n (if (is-vowel (byte-at bs i)) (+ acc 1) acc))))

  (def (count-vowels s) (let ((bs (String.to-bytes s))) (go bs 0 (Bytes.len bs) 0)))

  (def (main) (count-vowels "education"))

  (export main))`,
    expected: "5",
  },
  {
    id: "caesar-cipher-char",
    name: "Caesar cipher (char arithmetic)",
    theme: "algorithms",
    surface: "sexpr",
    source: `(do
  (def (letter s) (match (String.scalar-at s 0) ((Some c) c) ((None) (trap "empty string"))))

  (def
    (shift c n)
    (let
      ((code (Char.to-int c)))
      (match
        (Char.from-int (+ 65 (% (+ (- code 65) n) 26)))
        ((Some r) r)
        ((None) (trap "caesar: bad code point")))))

  (def (main) #tuple((shift (letter "A") 3) (shift (letter "Y") 3)))

  (export main))`,
    expected: "(: #tuple(#\\D #\\B) (Tuple Char Char))",
  },
  {
    id: "unicode-nfc-normalization",
    name: "Unicode NFC normalization",
    theme: "data-and-collections",
    surface: "sexpr",
    source: `(do
  (def (accent) (String.from-bytes (Bytes.of #list(204 129))))

  (def
    (main)
    (match
      (accent)
      ((Some acc)
        (let
          ((composed (String.concat "e" acc)))
          #tuple((String.scalar-len composed) (String.byte-len composed))))
      ((None) (trap "nfc: invalid accent bytes"))))

  (export main))`,
    expected: "(: (tuple 1 2) (Tuple Int64 Int64))",
  },
  {
    id: "string-slice-date-fields",
    name: "Substring slicing (ISO date fields)",
    theme: "data-and-collections",
    surface: "sexpr",
    source: `(do
  (def (field s lo hi) (match (String.slice s lo hi) ((Some part) part) ((None) "")))

  (def (main) (let ((d "2026-08-14")) #tuple((field d 0 4) (field d 5 7) (field d 8 10))))

  (export main))`,
    expected: "(: #tuple(\"2026\" \"08\" \"14\") (Tuple String String String))",
  },
  {
    id: "integer-square-root",
    name: "Integer square root",
    theme: "algorithms",
    surface: "sexpr",
    source: `(do
  (def (isqrt-from n g) (if (> (* g g) n) (- g 1) (isqrt-from n (+ g 1))))

  (def (isqrt n) (isqrt-from n 1))

  (def (main) (isqrt 144))

  (export main))`,
    expected: "12",
  },
  {
    id: "mutual-recursion",
    name: "Mutual recursion (even & odd)",
    theme: "algorithms",
    surface: "sexpr",
    source: `(do
  (def (is-even n) (if (= n 0) true (is-odd (- n 1))))

  (def (is-odd n) (if (= n 0) false (is-even (- n 1))))

  (def
    (count-evens n i acc)
    (if (= i n) acc (count-evens n (+ i 1) (if (is-even i) (+ acc 1) acc))))

  (def (main) (count-evens 10 0 0))

  (export main))`,
    expected: "5",
  },
  {
    id: "ackermann",
    name: "Ackermann function",
    theme: "algorithms",
    surface: "sexpr",
    source: `(do
  (def (ack m n) (if (= m 0) (+ n 1) (if (= n 0) (ack (- m 1) 1) (ack (- m 1) (ack m (- n 1))))))

  (def (main) (ack 3 3))

  (export main))`,
    expected: "61",
  },
  {
    id: "n-queens",
    name: "N-queens (count solutions)",
    theme: "algorithms",
    surface: "sexpr",
    source: `(do
  (def
    (at (: xs (List Int64)) (: i Int64))
    (match (List.at xs i) ((Some v) v) ((None) (trap "queens: placed[i] out of range"))))

  (def (adiff a b) (if (> a b) (- a b) (- b a)))

  (def
    (safe placed col row i)
    (if
      (= i row)
      true
      (let
        ((pc (at placed i)))
        (if
          (= pc col)
          false
          (if (= (adiff pc col) (adiff i row)) false (safe placed col row (+ i 1)))))))

  (def
    (try-cols n placed row col acc)
    (if
      (= col n)
      acc
      (try-cols
        n
        placed
        row
        (+ col 1)
        (if (safe placed col row 0) (+ acc (solve n (List.push placed col) (+ row 1))) acc))))

  (def (solve n placed row) (if (= row n) 1 (try-cols n placed row 0 0)))

  (def (main) (solve 8 (: #list() (List Int64)) 0))

  (export main))`,
    expected: "92",
  },
  {
    id: "reverse-a-list",
    name: "Reverse a list",
    theme: "basics",
    surface: "sexpr",
    source: `(do
  (def
    (at (: xs (List Int64)) (: i Int64))
    (match (List.at xs i) ((Some v) v) ((None) (trap "reverse: index out of range"))))

  (def (rev xs i acc) (if (< i 0) acc (rev xs (- i 1) (List.push acc (at xs i)))))

  (def (main) (let ((xs #list(1 2 3 4 5))) (rev xs (- (List.len xs) 1) (: #list() (List Int64)))))

  (export main))`,
    expected: "(: #list(5 4 3 2 1) (List Int64))",
  },
  {
    id: "stack-via-prepend",
    name: "Stack (push via prepend)",
    theme: "basics",
    surface: "sexpr",
    source: `(do
  (def (push stack x) (List.prepend stack x))

  (def (main) (push (push (push (: #list() (List Int64)) 10) 20) 30))

  (export main))`,
    expected: "(: #list(30 20 10) (List Int64))",
  },
  {
    id: "metaprogramming-quote-eval",
    name: "Metaprogramming (quote & eval)",
    theme: "basics",
    surface: "sexpr",
    source: `(do
  (def (build base offset) (quasiquote (+ (* (unquote base) (unquote base)) (unquote offset))))

  (def (main) #tuple((build 6 5) (eval (quasiquote (+ (* (unquote 6) (unquote 6)) (unquote 5))))))

  (export main))`,
    expected: "(: #tuple(((. Ast List) #list(((. Ast Name) \"+\") ((. Ast List) #list(((. Ast Name) \"*\") ((. Ast Int) 6) ((. Ast Int) 6))) ((. Ast Int) 5))) 41) (Tuple Ast Int64))",
  },
  {
    id: "effects-handlers-stateful",
    name: "Effects & handlers (stateful)",
    theme: "basics",
    surface: "sexpr",
    source: `(do
  (effect Tick (op tick (-> Int64 Int64)))

  (def
    (main)
    (handle Tick 0 ((tick (n) s (resume (+ s n) (+ s n)))) (+ (Tick.tick 10) (Tick.tick 5))))

  (export main))`,
    expected: "25",
  },
  {
    id: "iterator-pipeline",
    name: "Iterator pipeline (filter → map → fold)",
    theme: "data-and-collections",
    surface: "sexpr",
    source: `(do
  (type Iter (Nil unit) (Cons (Tuple Int64 Iter)))

  (def
    (from-list xs)
    (match xs (#list() (Nil unit)) (#list(h (.. t)) (Cons #tuple(h (from-list t))))))

  (def
    (ifilter it p)
    (match
      it
      ((Nil _) (Nil unit))
      ((Cons c) (if (p (. c 0)) (Cons #tuple((. c 0) (ifilter (. c 1) p))) (ifilter (. c 1) p)))))

  (def
    (imap it f)
    (match it ((Nil _) (Nil unit)) ((Cons c) (Cons #tuple((f (. c 0)) (imap (. c 1) f))))))

  (def (ifold it acc f) (match it ((Nil _) acc) ((Cons c) (ifold (. c 1) (f acc (. c 0)) f))))

  (def
    (main)
    (ifold
      (imap (ifilter (from-list #list(1 2 3 4 5 6)) (fn (x) (= 0 (% x 2)))) (fn (x) (* x 3)))
      0
      (fn (a x) (+ a x))))

  (export main))`,
    expected: "36",
  },
  {
    id: "iterator-zip-dot-product",
    name: "Iterator zip: dot product",
    theme: "data-and-collections",
    surface: "sexpr",
    source: `(do
  (type Iter (Nil unit) (Cons (Tuple Int64 Iter)))

  (def
    (from-list xs)
    (match xs (#list() (Nil unit)) (#list(h (.. t)) (Cons #tuple(h (from-list t))))))

  (def
    (dot a b)
    (match
      a
      ((Nil _) 0)
      ((Cons pa)
        (match
          pa
          (#tuple(ha ra)
            (match b ((Nil _) 0) ((Cons pb) (match pb (#tuple(hb rb) (+ (* ha hb) (dot ra rb)))))))))))

  (def (main) (dot (from-list #list(1 2 3)) (from-list #list(4 5 6))))

  (export main))`,
    expected: "32",
  },
  {
    id: "a-type-error",
    name: "A type error (see the squiggle)",
    theme: "basics",
    surface: "sexpr",
    source: `(do
  (def (main) (+ 1 true))

  (export main))`,
    expectError: true,
  },
  {
    id: "try-operator",
    name: "Fallible unwrap with try",
    theme: "basics",
    surface: "sexpr",
    source: `(do
  (def (safe-add a b) (let ((s (try (Int64.checked-add a b)))) (Some s)))

  (def (main) (safe-add 40 2))

  (export main))`,
    expected: "(: (Some 42) (Option Int64))",
  },
  {
    id: "design-by-contract",
    name: "Design by contract",
    theme: "basics",
    surface: "sexpr",
    source: `(do
  (@ (requires (>= x 0)) (@ (ensures (>= ret 0)) (def (double (: x Int64)) (* x 2))))

  (def (main) (double 21))

  (export main))`,
    expected: "42",
  },
  {
    id: "units-of-measure",
    name: "Units of measure",
    theme: "numbers",
    surface: "sexpr",
    source: `(do
  (def (main) (Qty.of 5.0 (Unit.prefix kilo (Unit.base #"meter"))))

  (export main))`,
    expected: "(: (Qty.of 5000.0 (Unit.base #\"meter\")) (Qty Float64 (Unit.base #\"meter\")))",
  },
  {
    id: "unit-arithmetic",
    name: "Adding mixed units",
    theme: "numbers",
    surface: "sexpr",
    source: `(do
  (def (main) (Qty.value (+ (Qty.of 1.0 (Unit.of #"km")) (Qty.of 500.0 (Unit.of #"m")))))

  (export main))`,
    expected: "1500.0",
  },
  // </generated:examples>
];

export const DEFAULT_EXAMPLE = EXAMPLES[0];
