(case "lcs1 an LCS DP-ROW state — each fed character rebuilds the whole dynamic-programming row against the fixed pattern via a recursive fold reading the OLD row while writing the NEW"
  (input  (do
            (effect S (op feed (-> Int64 Int64)))
            (def (at0 (: xs (List Int64)) (: i Int64))
              (match (List.at xs i) ((Some v) v) ((None u) 0)))
            (def (imax (: a Int64) (: b Int64)) (if (> a b) a b))
            (def (build (: pat (List Int64)) (: old (List Int64)) (: new (List Int64)) (: j Int64) (: c Int64))
              (if (> j (List.len pat))
                  new
                  (let ((cell (if (= (at0 pat (- j 1)) c)
                                  (+ (at0 old (- j 1)) 1)
                                  (imax (at0 new (- j 1)) (at0 old j)))))
                    (build pat old (List.push new cell) (+ j 1) c))))
            (def (main (: n Int64))
              (handle S (list 0 0 0 0)
                ((feed (c) row
                  (let ((row2 (build (list 1 2 3) row (list 0) 1 c)))
                    (resume (at0 row2 3) row2))))
                (let ((a (S.feed 1)))
                  (let ((b (S.feed n)))
                    (let ((c (S.feed 3)))
                      (+ (* 10 (+ (* 10 a) b)) c))))))
            (export main)))
  (call   main (: 2 Int64)) (output (: 123 Int64))
  (call   main (: 9 Int64)) (output (: 112 Int64)))
