(case "se1 a simplifier pass applied TWICE equals one application (idempotence at the fixpoint)"
  (input  (do
            (type Exp (Lit Int64) (Add (Tuple Exp Exp)) (Mul (Tuple Exp Exp)))
            (def (is-lit e k) (match e ((Exp.Lit n) (= n k)) (_other false)))
            (def (simp e)
              (match e
                ((Exp.Lit n) (Exp.Lit n))
                ((Exp.Add (tuple a b))
                  (let ((x (simp a)))
                  (let ((y (simp b)))
                    (if (is-lit y 0) x (if (is-lit x 0) y (Exp.Add (tuple x y)))))))
                ((Exp.Mul (tuple a b))
                  (let ((x (simp a)))
                  (let ((y (simp b)))
                    (if (is-lit y 1) x (if (is-lit x 1) y (Exp.Mul (tuple x y)))))))))
            (def (main (: k Int64))
              (let ((e (Add (tuple (Mul (tuple (Lit k) (Lit 1))) (Lit 0)))))
                (let ((once (simp e)))
                  (+ (* 10 (if (= (simp once) once) 1 0))
                     (if (= once (Lit k)) 1 0)))))
            (export main)))
  (call   main (: 6 Int64)) (output (: 11 Int64)))
