(case "se2 TWO passes compose: constant-fold then simplify, order-observable"
  (input  (do
            (type Exp (Lit Int64) (Add (Tuple Exp Exp)) (Mul (Tuple Exp Exp)))
            (def (is-lit e k) (match e ((Exp.Lit n) (= n k)) (_other false)))
            (def (cfold e)
              (match e
                ((Exp.Lit n) (Exp.Lit n))
                ((Exp.Add (tuple a b))
                  (let ((x (cfold a)))
                  (let ((y (cfold b)))
                    (match x ((Exp.Lit p) (match y ((Exp.Lit q) (Exp.Lit (+ p q))) (_o1 (Exp.Add (tuple x y))))) (_o2 (Exp.Add (tuple x y)))))))
                ((Exp.Mul (tuple a b))
                  (let ((x (cfold a)))
                  (let ((y (cfold b)))
                    (match x ((Exp.Lit p) (match y ((Exp.Lit q) (Exp.Lit (* p q))) (_o3 (Exp.Mul (tuple x y))))) (_o4 (Exp.Mul (tuple x y)))))))))
            (def (simp e)
              (match e
                ((Exp.Lit n) (Exp.Lit n))
                ((Exp.Add (tuple a b))
                  (let ((x (simp a)))
                  (let ((y (simp b)))
                    (if (is-lit y 0) x (if (is-lit x 0) y (Exp.Add (tuple x y)))))))
                ((Exp.Mul (tuple a b))
                  (let ((x (simp a)))
                  (let ((y (simp b)))
                    (if (is-lit y 1) x (if (is-lit x 1) y (Exp.Mul (tuple x y)))))))))
            (def (main (: k Int64))
              (let ((e (Mul (tuple (Add (tuple (Lit 2) (Lit 3))) (Add (tuple (Lit k) (Lit 0)))))))
                (+ (* 100 (match (cfold (simp e)) ((Exp.Mul (tuple _a _b)) 1) ((Exp.Lit v) (* v 0)) (_o5 -1)))
                   (match (simp (cfold e)) ((Exp.Lit _v) 99) ((Exp.Mul (tuple _a2 _b2)) 2) (_o6 -1)))))
            (export main)))
  (call   main (: 7 Int64)) (output (: 99 Int64)))
