(case "rpn1 an RPN EVALUATOR — pushes stack operands, the operator ops pop two and push the result; the (n+3)*2 program evaluates through five dispatches with stack depths and intermediates exposed"
  (input  (do
            (effect S
              (op push (-> Int64 Int64))
              (op addop (-> Int64))
              (op mulop (-> Int64)))
            (def (top2 (: st (List Int64)))
              (let ((k (List.len st)))
                (tuple (match (List.at st (- k 2)) ((Some a) a) ((None u) 0))
                       (match (List.at st (- k 1)) ((Some b) b) ((None u) 0)))))
            (def (drop2 (: st (List Int64)) (: i Int64) (: keep Int64) (: acc (List Int64)))
              (if (< i keep)
                  (drop2 st (+ i 1) keep (List.push acc (match (List.at st i) ((Some v) v) ((None u) 0))))
                  acc))
            (def (main (: n Int64))
              (handle S (: (list) (List Int64))
                ((push (v) st
                  (let ((s2 (List.push st v)))
                    (resume (List.len s2) s2)))
                 (addop () st
                  (match (top2 st)
                    ((tuple a b)
                      (let ((s2 (List.push (drop2 st 0 (- (List.len st) 2) (: (list) (List Int64))) (+ a b))))
                        (resume (+ a b) s2)))))
                 (mulop () st
                  (match (top2 st)
                    ((tuple a b)
                      (let ((s2 (List.push (drop2 st 0 (- (List.len st) 2) (: (list) (List Int64))) (* a b))))
                        (resume (* a b) s2))))))
                (let ((a (S.push n)))
                  (let ((b (S.push 3)))
                    (let ((c (S.addop)))
                      (let ((d (S.push 2)))
                        (let ((e (S.mulop)))
                          (+ (* 100 (+ (* 10 (+ (* 100 (+ (* 10 a) b)) c)) d)) e))))))))
            (export main)))
  (call   main (: 4 Int64)) (output (: 1207214 Int64))
  (call   main (: 10 Int64)) (output (: 1213226 Int64)))
