(case "by2 a SLICE view (start,LEN) of the Bytes state read per dispatch — in-range bytes returned, out-of-range answers -1"
  (input  (do
            (effect B (op peek (-> Int64 Int64)))
            (def (main (: n Int64))
              (handle B (Bytes.of (list (UInt8.wrap 10) (UInt8.wrap 20) (UInt8.wrap 30) (UInt8.wrap 40)))
                ((peek (i) s (resume (match (Bytes.slice s 1 2)
                                       ((Some sl) (match (Bytes.at sl i)
                                                    ((Some b) (Int64.of b))
                                                    ((None) -1)))
                                       ((None) -99))
                                    s)))
                (+ (B.peek n) (+ (* 10 (B.peek 1)) (* 100 (B.peek 2))))))
            (export main)))
  (call   main (: 0 Int64)) (output (: 220 Int64))
  (call   main (: 1 Int64)) (output (: 230 Int64)))
