(chapter
  (slug "ad-hoc-polymorphism")
  (title "Ad-hoc polymorphism")
  (pillar "language")
  (section "What makes Cadenza different")
  (blurb "One name, a per-type meaning: operators dispatch on operand type, generics specialize per type, all at compile time.")
  (lede "One name, more than one meaning, chosen per type. Most languages bolt on a trait or typeclass system for this, but Cadenza doesn't need one, because a \"trait\" is just a " (em "record of functions you pass in") " and dispatch is choosing which record to pass. No new machinery: records and functions you already have.")
  (p "\"Polymorphism\" means one piece of code working over many types. The " (em "ad-hoc") " kind is where the behaviour genuinely differs per type, so " (c "show") " renders an integer one way and a boolean another. Other languages introduce typeclasses (Haskell), traits (Rust), or interfaces to carry those per-type implementations. The Cadenza insight: that bundle of per-type operations is just a " (strong "record whose fields are functions") ", and a polymorphic function is one that takes such a record as an argument and calls its fields.")
  (h2 "A trait is a record of functions")
  (p "Say you want a " (c "show") "-like operation that turns a value into a number, differently per type. The \"trait\" is a record with a " (c "describe") " field: " (c "{ describe: T -> Int64 }") ". An " (em "instance") " for a type is a record with that field filled in. A polymorphic function takes the record and calls " (c "(. dict describe)") ". Dispatch is picking which record to hand it:")
  (runnable
    (source (def (describe-int n) (+ n 100))
(def (describe-bool b) (if b 1 0))
(def (show-with dict x) ((. dict describe) x))
(def (int-show) #record((= describe describe-int)))
(def (bool-show) #record((= describe describe-bool)))
(def (main)
  (+ (show-with (int-show) 5)
     (show-with (bool-show) true)))))
  (p (c "show-with") " is the polymorphic function, and it doesn't know or care " (em "which") " describe it's calling. " (c "int-show") " and " (c "bool-show") " are the two instances (the \"trait implementations\"), each a plain record. " (c "main") " dispatches by passing the right one, so " (c "5") " becomes " (c "105") " and " (c "true") " becomes " (c "1") ", summing to " (c "106") ". That's the whole mechanism, with no trait keyword and no instance resolution, just a record argument. And it's deliberate: the spec says a trait instance is an " (em "explicitly-passed dictionary") ", never resolved from ambient scope, so you can always see exactly which implementation a call uses by reading the argument.")
  (h2 "Make the dictionary free: a const parameter")
  (p "Passing a record around sounds like it should cost something at run time, but it doesn't have to, because the " (c "const") " parameter you met in the previous chapter applies here: mark the dictionary parameter " (c "const") " and the compiler inlines it into a specialized copy and erases it, so the " (c "(. dict describe)") " lookup folds to the concrete function with no record passed and no field looked up at run time.")
  (runnable
    (source (def (describe-int n) (+ n 100))
(def (describe-bool b) (if b 999 0))
(def (show-with (const dict) x) ((. dict describe) x))
(def (main)
  (+ (show-with #record((= describe describe-int)) 5)
     (show-with #record((= describe describe-bool)) true)))))
  (p "The very same two instances as before, one for " (c "Int64") " and one for " (c "Bool") ", now dispatch through a " (c "const") " dictionary: " (c "describe-int") " turns " (c "5") " into " (c "105") ", " (c "describe-bool") " turns " (c "true") " into " (c "999") ", summing to " (c "1104") ". Because the parameter is " (c "const") " and left " (em "unannotated") ", " (c "show-with") " stays fully generic and works for " (em "any") " type whose dictionary carries a " (c "describe") ", yet the compiler still inlines each call into a specialized copy and erases the record. This is exactly what a typeclass system does internally by threading a dictionary to the use site, except here the dictionary is an ordinary record you can see, and the erasure is the general " (c "const") " mechanism rather than special trait plumbing.")
  (note "Left the dictionary " (em "unannotated") " on purpose: that's what keeps " (c "show-with") " generic over the element type. Cadenza has no " (c "∀") "-binder inside an annotation, so you can't write a generic type like " (cdz (Record (: describe (-> a Int64)))) " with a free " (c "a") ", so an unannotated parameter " (em "is") " the generic form. When you " (em "want") " the signature written out, there's a second way, below.")
  (h2 "Spelling out the generic: a type parameter")
  (p "The unannotated version is generic but silent about it. If you'd rather " (em "document") " the constraint that \"this works for some type " (c "t") ", given a dictionary of " (c "describe : t → Int64") "\", take the type as an explicit " (cdz (: t Type)) " parameter (the same first-class " (em "types as values") " idea) and annotate the rest in terms of it. The caller passes the concrete type at the front; both instances still dispatch through the one " (c "show-with") ":")
  (runnable
    (source (def (describe-int n) (+ n 100))
(def (describe-bool b) (if b 999 0))
(def (show-with (: t Type) (: dict (Record (: describe (-> t Int64)))) (: x t))
  ((. dict describe) x))
(def (main)
  (+ (show-with Int64 #record((= describe describe-int)) 5)
     (show-with Bool #record((= describe describe-bool)) true)))))
  (p "Same " (c "1104") ", now with a fully written-out signature: " (c "show-with") " declares that its element type is a parameter " (c "t") " and its dictionary must carry " (c "describe : t → Int64") ". Feed it " (c "Int64") " with an integer dictionary, or " (c "Bool") " with a boolean one, and each checks against that same shape. It's the more verbose of the two, but it says out loud what the unannotated form leaves to inference, so pick whichever fits how much you want the reader to see.")
  (h2 "The built-in instances: typed operators")
  (p "The prelude's operators are this same shape, pre-supplied. " (c "+") " is one surface name backed by a per-type implementation, choosing integer addition for integers, floating-point for floats, and exact for rationals by the operand type. Here the very same " (c "+") " and " (c "&lt;") " run over floats and over integers in one program:")
  (runnable
    (source (def (main)
  (if (< (+ 1.5 1.5) 4.0)
    (+ 1 2)
    99))))
  (p "The " (cdz (+ 1.5 1.5)) " is float addition and the " (cdz (+ 1 2)) " integer addition, the same symbol picking the right implementation per type and folding to " (c "3") ". You didn't pass a dictionary because the prelude already provides the instances; it's the record-of-operations idea with the record built in.")
  (h2 "And the implicit face: generic specialization")
  (p "One more form needs no dictionary at all: a generic function the compiler " (em "monomorphizes") ". Write " (c "len") " with no type annotations and it works for any list; the compiler emits a distinct specialized copy per concrete type it's actually called at:")
  (runnable
    (source (def (len xs)
  (match xs
    (#list() 0)
    (#list(h .. t) (+ 1 (len t)))))
(def (main)
  (+ (len #list(1 2 3)) (len #list("a" "b"))))))
  (p "That calls " (c "len") " at " (c "List Int64") " and " (c "List String") " for " (c "3 + 2 = 5") ", with a separate machine function for each and no runtime type tag. (" (c "cdz instantiations len some-file.cdz") " lists the concrete types it was compiled at; the editor shows the same as a CodeLens above the definition.) This is the " (em "parametric") " case, one algorithm reused, whereas the dictionary and the operators are the genuinely per-type-" (em "behaviour") " cases.")
  (note "What Cadenza deliberately does " (em "not") " have: implicit instance resolution. There's no trait keyword and no compiler search for \"the " (c "Show") " instance for this type\" from ambient scope, so you pass the dictionary yourself or use a prelude operator that already carries its instances. You also can't declare two functions with the same name and have argument types pick between them; that's rejected, not resolved. The upshot is that a call's meaning is always visible in its arguments, never conjured from a global table.")
  (why (tenet "Traits are records you pass in, not new machinery") "A typeclass or trait system is a second little language: instance declarations, resolution rules, coherence checks. Cadenza gets the same expressiveness from what it already has, since a record of functions is the dictionary, passing it is dispatch, and marking it " (c "const") " makes it free (inlined and erased, exactly what a typeclass compiler emits). Because the dictionary is explicit, there's no invisible resolution to reason about: you can always read which implementation a call uses. And the prelude's typed operators are just the pre-built instances of this shape, so the everyday " (c "+") " and the hand-rolled " (c "show-with") " are the same idea at two levels.")
  (h2 "Your turn")
  (exercise
    (id "ad-hoc-polymorphism:1")
    (prompt "A dictionary is a record of functions. " (c "apply-op") " calls the record's " (c "op") " field on " (c "x") ". Fill the function stored in the record so " (c "(apply-op … 5)") " triples its input, giving " (c "15") ".")
    (starter (def (triple n) (* 3 n))
(def (apply-op dict x) ((. dict op) x))
(def (main) (apply-op #record((= op ?)) 5)))
    (solution (def (triple n) (* 3 n))
(def (apply-op dict x) ((. dict op) x))
(def (main) (apply-op #record((= op triple)) 5)))
    (expected "15")
    (hint "The record's " (c "op") " field is the function to call, so put " (c "triple") " there and " (c "apply-op") " calls it on " (c "5") " for " (c "15") ". Dispatch is just choosing which function the record carries."))
  (exercise
    (id "ad-hoc-polymorphism:2")
    (prompt "The same " (c "+") " means integer or float addition depending on its operands. Fill the float so the comparison " (c "(&lt; (+ 2.0 ?) 5.0)") " is " (em "true") ", which selects the " (cdz (+ 10 20)) " integer branch and gives " (c "30") ".")
    (starter (def (main)
  (if (< (+ 2.0 ?) 5.0) (+ 10 20) 0)))
    (solution (def (main)
  (if (< (+ 2.0 1.0) 5.0) (+ 10 20) 0)))
    (expected "30")
    (hint "You need " (c "(+ 2.0 ?)") " to stay under " (c "5.0") ", so any float below " (c "3.0") " works, and " (c "1.0") " gives " (c "3.0 &lt; 5.0") ", true. The addition on " (c "2.0") " is float addition, while " (cdz (+ 10 20)) " is integer addition: one operator, its per-type instances.")))
