(chapter
  (slug "basics")
  (title "Values & functions")
  (pillar "language")
  (section "Fundamentals")
  (blurb "Literals, bindings, functions, and type inference.")
  (lede "Literals, bindings, and first-class functions, the vocabulary everything is built from.")
  (h2 "Bindings")
  (p "A " (c "let") " binds a name to a value for the rest of an expression. Bindings are lexical, and an inner binding may shadow an outer one.")
  (runnable
    (id "basics-let")
    (source (let ((x 10)) (+ x 5))))
  (p (c "x") " is " (c "10") " for the body " (cdz (+ x 5)) ", so this is " (result (of "basics-let") 15) ".")
  (p "Shadowing is just a second binding of the same name. The inner " (c "x") " is computed " (em "from") " the outer one, since the right-hand side still sees the old value, and only then takes over for the rest of the body:")
  (runnable
    (id "basics-shadow")
    (source (let ((x 10))
  (let ((x (* x 2)))
    (+ x 1)))))
  (p "The inner binding's " (cdz (* x 2)) " reads the outer " (c "x = 10") " to get " (c "20") "; the body then sees that inner " (c "x") ", so " (cdz (+ x 1)) " is " (result (of "basics-shadow") 21) ". Nothing was mutated, since the outer " (c "x") " is untouched, just out of view.")
  (h2 "Functions are values")
  (p "A function is written with " (c "fn") " and is an ordinary value, so you can bind it, pass it, and return it. Here we bind a function " (c "inc") " and call it.")
  (runnable
    (id "basics-inc")
    (source (let ((inc (fn (x) (+ x 1)))) (inc 4))))
  (p "Binding it to " (c "inc") " and calling " (cdz (inc 4)) " gives " (result (of "basics-inc") 5) ".")
  (p "Functions close over their environment. " (c "adder") " returns a function that remembers " (c "n") ":")
  (runnable
    (id "basics-adder")
    (source (let ((adder (fn (n) (fn (x) (+ x n)))))
  ((adder 3) 10))))
  (p (cdz (adder 3)) " captures " (c "n = 3") " and returns a function that adds 3; applying it to " (c "10") " gives " (result (of "basics-adder") 13) ".")
  (why (tenet "Uniformity over special cases") "Underneath, every function takes exactly " (em "one") " argument and returns one value, so a two-argument function is sugar for a function returning a function (that's why " (c "adder") " above works so naturally). Cadenza leans on this kind of uniformity everywhere, because fewer special cases means fewer places for the compiler, and your mental model, to disagree with itself.")
  (h2 "Higher-order functions")
  (p "Because functions are values, a function can take another function as an argument. " (c "apply-twice") " applies its argument function twice:")
  (runnable
    (source (let ((apply-twice (fn (f v) (f (f v)))))
  (apply-twice (fn (x) (+ x 1)) 5))))
  (p "The passed-in function adds 1, applied twice to " (c "5") ", so " (c "5 → 6 → 7") ".")
  (h2 "Types are inferred, and can be written")
  (p "Every value has a type, and so far the compiler has worked them out for you, since you never wrote " (c "Int64") " anywhere, yet the results came back typed. When you " (em "want") " to state a type, whether as documentation or to pin down something inference would otherwise leave open, you annotate a binding with its type. Toggle to the ML surface and this " (c "dbl") " reads " (c "def dbl(x: Int64)") ":")
  (runnable
    (source (def (dbl (: x Int64)) (* x 2))
(def (main) (dbl 21))))
  (p "An annotation isn't just a comment, because the compiler " (em "checks") " it against the type it inferred and refuses if they disagree. Claiming a plain number is a " (c "Bool") " is a contradiction it won't accept:")
  (note "This one is " (strong "meant to be refused") ". Run it and read the diagnostic, " (c "CDZ0203") ", \"annotation type Bool does not match value type Int64\": the annotation is held to the truth, not the other way around.")
  (runnable
    (source (: 5 Bool))
    (expect "error"))
  (p "Because inference already knows the types, annotations are optional almost everywhere, so write them where they clarify, and leave them off where they'd just be noise.")
  (h2 "Your turn")
  (p "Time to write some Cadenza. Fill in the blank, press Check, and the guide will grade it.")
  (exercise
    (id "basics:1")
    (prompt "Make this produce " (c "42") " by doubling 21.")
    (starter (* 21 ?))
    (solution (* 21 2))
    (expected "42")
    (hint "Replace the " (c "?") " with the number that doubles 21."))
  (exercise
    (id "basics:2")
    (prompt (c "make-scaler") " returns a function that multiplies by whatever " (c "factor") " it captured. Fill the hole so " (c "triple") " is a scaler that captures " (c "3") ", then " (cdz (triple 5)) " is " (c "15") ".")
    (starter (let ((make-scaler (fn (factor) (fn (x) (* x factor)))))
  (let ((triple (make-scaler ?)))
    (triple 5))))
    (solution (let ((make-scaler (fn (factor) (fn (x) (* x factor)))))
  (let ((triple (make-scaler 3)))
    (triple 5))))
    (expected "15")
    (hint "The hole is the " (c "factor") " that " (c "triple") " should capture. You want it to triple, so pass " (c "3") "; the returned function then remembers it, and " (cdz (triple 5)) " is " (c "5 × 3") ".")))
