(chapter
  (slug "bytes")
  (title "Bytes")
  (pillar "language")
  (section "Fundamentals")
  (blurb "Raw octet sequences, and the bridge from text.")
  (lede "A string is Unicode text, but when you need the raw octets underneath, whether for a file, a protocol, or a hash, that's a " (c "Bytes") " value.")
  (p "A " (c "Bytes") " is an immutable sequence of 8-bit values. You can write one as a byte-string literal " (c "b\"…\"") ", where the " (c "b") " prefix distinguishes it from a text string, or build one from a list of numbers with " (c "Bytes.of") ". Return one and you see it printed back as a " (c "b\"…\"") " literal with non-printable bytes shown as " (c "\\x") " escapes, so here the numbers " (c "10") ", " (c "20") ", " (c "30") " become the three octets " (c "b\"\\n\\x14\\x1e\"") ":")
  (runnable
    (source (Bytes.of #list(10 20 30))))
  (p (c "Bytes.len") " counts those octets, so " (c "b\"hi!\"") " is the three bytes " (c "h") ", " (c "i") ", " (c "!") ", and its length is " (c "3") ":")
  (runnable
    (source (Bytes.len b"hi!")))
  (h2 "Two ways to write the same bytes")
  (p "A literal and a built sequence are just two spellings of one value, and Cadenza compares them by value, so they're " (em "equal") " when their bytes match. " (c "b\"AB\"") " is the two bytes 65 and 66:")
  (runnable
    (source (= b"AB" (Bytes.of #list(65 66)))))
  (h2 "Reaching in safely")
  (p "Like " (c "List.at") ", " (c "Bytes.at") " can miss, because an out-of-range index has no byte to return, so it hands back an " (c "Option") " you take apart with " (c "match") ". Here index 1 holds " (c "20") ":")
  (runnable
    (source (def (main)
  (match (Bytes.at (Bytes.of #list(10 20 30)) 1)
    ((Some b) b)
    ((None _) -1)))))
  (p "Push the index past the end and the " (c "None") " arm fires, with no out-of-bounds crash.")
  (h2 "Joining and slicing")
  (p (c "Bytes.concat") " joins two byte sequences, while " (c "Bytes.slice") " takes a " (em "start") " index and a " (em "length") ", and because that window might run off the end it returns an " (c "Option") ". Both return new values, leaving the originals untouched:")
  (runnable
    (source (Bytes.concat (Bytes.of #list(1 2)) (Bytes.of #list(3 4 5)))))
  (p "Joining a 2-byte sequence with a 3-byte one gives the 5-byte " (c "b\"\\x01\\x02\\x03\\x04\\x05\"") ", the two originals laid end to end, both untouched.")
  (runnable
    (source (def (main)
  (Bytes.len
    (Option.expect (Bytes.slice (Bytes.of #list(1 2 3 4 5)) 1 3) "out of range")))))
  (p (cdz "(Bytes.slice bs 1 3)") " takes 3 bytes starting at index 1, so its length is " (c "3") ". Ask for more bytes than remain and you get the " (c "None") " arm instead.")
  (note "A small difference worth noting: " (c "Bytes.slice") " takes a start and a " (em "length") ", while " (c "String.slice") " from the previous chapter takes a start and an " (em "end") " index. So " (cdz "(Bytes.slice bs 1 3)") " is three bytes, but " (cdz "(String.slice s 1 3)") " is two characters (indices 1 and 2). Read the argument names and you won't be caught out.")
  (h2 "From text to bytes")
  (p (c "String.to-bytes") ", the crossing the " (em "Strings") " chapter covered, hands you a string's UTF-8 encoding as a " (c "Bytes") ", which lets us see what " (c "Bytes.len") " measures, namely octets rather than characters. Return the bytes for the 4-character " (c "\"café\"") " and the encoding is right there in " (c "b\"caf\\xc3\\xa9\"") ":")
  (runnable
    (source (String.to-bytes "café")))
  (p "You can see it directly: " (c "c") ", " (c "a") ", " (c "f") " are one byte each, and the " (c "é") " is the two bytes " (c "\\xc3\\xa9") ", which is five octets for four characters. So " (c "Bytes.len") " of this is " (c "5") ", counting the octets it's given whatever the character count of the text that produced them.")
  (why (tenet "Text and bytes are different types") "Many languages blur strings and byte arrays into one thing, and the encoding bugs follow. Cadenza keeps them apart: a " (c "String") " is a sequence of Unicode characters; a " (c "Bytes") " is a sequence of octets. You cross between them with a named, explicit operation (" (c "String.to-bytes") ") that says which encoding you mean, so \"how long is it?\" and \"what's at index 2?\" always have one unambiguous answer, and a byte-level concern can never silently corrupt text.")
  (note "Everything here is the same value discipline as lists and strings: " (c "Bytes") " is immutable (operations return new values), compared by content, and indexed through an " (c "Option") " so a bad offset is a value you handle, not a crash.")
  (p "Raw octets are a flat sequence, but real formats give them " (em "structure") ", such as a 2-byte length, a tag, and a payload. " (em "Binary matching") ", next, describes that layout as typed segments that build and destructure " (c "Bytes") " both ways.")
  (h2 "Your turn")
  (exercise
    (id "bytes:1")
    (prompt "Read the byte at index " (c "2") " of the literal " (c "b\"ABC\"") ". Indexing is safe, so it comes back as an " (c "Option") ", matched here, and the byte for " (c "C") " is " (c "67") ".")
    (starter (def (main)
  (match (Bytes.at b"ABC" ?)
    ((Some x) x)
    ((None _) -1))))
    (solution (def (main)
  (match (Bytes.at b"ABC" 2)
    ((Some x) x)
    ((None _) -1))))
    (expected "67")
    (hint "Bytes are indexed from 0, so the third byte (" (c "C") ") is index " (c "2") ". Its ASCII code is " (c "67") "."))
  (exercise
    (id "bytes:2")
    (prompt (c "Bytes.concat") " joins two byte sequences into a new one, and because " (c "Bytes") " compares by content, you can check the result against a literal. Fill the hole with the byte-string that completes " (c "b\"AB\"") " into " (c "b\"ABC\"") ", so the equality holds and the answer is " (c "true") ".")
    (starter (def (main)
  (= (Bytes.concat b"AB" ?) b"ABC")))
    (solution (def (main)
  (= (Bytes.concat b"AB" b"C") b"ABC")))
    (expected "true")
    (hint "Joining " (c "b\"AB\"") " with one more byte should give " (c "b\"ABC\"") ", so the missing piece is the single-byte literal " (c "b\"C\"") ". The join builds a fresh value, then " (c "=") " compares it to " (c "b\"ABC\"") " byte for byte.")))
