// @generated DO NOT EDIT — rendered from the chapter's .sexp by the guide sexp→TSX codegen (chapterModel.ts).
import { C, H1, H2, Lede, Note, P } from "../../components/Prose.tsx";
import { Ch } from "../../components/ChapterLink.tsx";
import { Why } from "../../components/Why.tsx";

export default function CdzToolchain() {
  return (
    <article>
      <H1>The cdz toolchain</H1>
      <Lede>Every example in this guide has run the real compiler in your browser. That same compiler is one binary on your <C>PATH</C>, called <C>cdz</C>, and it carries the whole loop from a fresh project to a running program.</Lede>
      <P>There is no separate toolchain to assemble, because <C>cdz</C> both compiles and runs Cadenza and also provides a project workflow and a set of code-understanding queries. You met the pieces interactively already, so this chapter is about reaching for them at a terminal.</P>
      <H2>Compile and run, in one binary</H2>
      <P>The smallest loop is a single file. <C>cdz compile</C> lowers a program to a WebAssembly component and <C>cdz run</C> executes one, and because a compiled component is just a value you can pipe the one straight into the other.</P>
      <Note><C>$ cdz compile foo.cdz -o - | cdz run -</C> <br /> <C>{"$ cdz run foo.wasm --call add --arg 2 --arg 40   # prints 42"}</C></Note>
      <P>A run is bounded so a mistake fails loudly rather than hanging: it stops at a wall-clock deadline (30 seconds by default) and traps, which you can raise or lower with <C>CDZ_RUN_TIMEOUT_SECS</C> or disable with <C>=0</C> when you're stepping through a debugger. The exit code tells a script what happened, since an operational failure or a trap exits <C>1</C> while a usage mistake exits <C>2</C>.</P>
      <H2>A project, the cargo way</H2>
      <P>Past a single file you work in a project, and the commands mirror the ones you'd reach for in Cargo. <C>cdz new</C> scaffolds one with a <C>Project.cdz</C> manifest, an entry file, and a passing starter <C>@test</C>, so the project is green from the very first command.</P>
      <Note><C>$ cdz new my-app</C> <br /> <C>$ cd my-app</C> <br /> <C>{"$ cdz build     # compile the whole project into one component"}</C> <br /> <C>{"$ cdz run       # run it"}</C> <br /> <C>{"$ cdz test      # run the project's tests"}</C></Note>
      <P>The manifest is itself Cadenza: <C>Project.cdz</C> starts with a <C>def name</C>, a <C>def entry</C>, and a <C>def tests</C>, and it grows a <C>def deps</C> once you take on a dependency. You add and drop path dependencies with <C>cdz add ../mathlib</C> and <C>cdz remove ../mathlib</C> rather than hand-editing the manifest, inspect the dependency graph with <C>cdz tree</C>, and re-run any command on every save with <C>cdz watch</C> for the same instant feedback you've had in this guide. When something looks off, <C>cdz doctor</C> checks the setup.</P>
      <H2>What goes in Project.cdz</H2>
      <P>The manifest is a handful of top-level definitions, most of them optional. A typical one reads:</P>
      <Note><C>def name = "my-app"</C> <br /> <C>def entry = "main.cdz"</C> <br /> <C>def modules = ["util.cdz", "helpers/*.cdz"]</C> <br /> <C>def tests = ["main.cdz"]</C> <br /> <C>def deps = ["../mathlib"]</C></Note>
      <P>Only <C>def entry</C> is required, since it names the file that becomes the component's boundary, and it must be a string (a non-string is a clear error rather than a silent misread). The <C>def name</C> must be kebab-case (lowercase letters, digits, and hyphens) because a dependency's name becomes its interface as <C>cadenza:&lt;name&gt;/api</C>, so <C>cdz new</C> warns you at creation if you pick something like <C>"My App"</C> that would break when another project depends on it. <C>def modules</C> lists the extra source files compiled into the component and <C>def tests</C> lists the files whose <C>@test</C> definitions <C>cdz test</C> runs, both accepting globs, while <C>def exclude</C> filters patterns back out of those sets. <C>def deps</C> holds path dependencies to sibling project directories, each built and peer-bound as its own interface, which is what <C>cdz add</C> and <C>cdz remove</C> edit for you. You can also set the build tier a project prefers with <C>def opt-level = "O2"</C>, which an explicit <C>--opt-level</C> on the command line overrides.</P>
      <H2>Designed for agents as much as for people</H2>
      <P>The <Ch to="/welcome">very first chapter</Ch> said Cadenza is written and read by AI agents as much as by humans, and the toolchain is where that shows. Alongside the build loop, <C>cdz</C> answers one-shot, structured questions about your code, so an agent (or you) can understand and modify a program without opening an editor at all.</P>
      <Note><C>{"$ cdz type add foo.cdz        # the inferred type of a definition"}</C> <br /> <C>{"$ cdz check foo.cdz           # diagnostics, without building"}</C> <br /> <C>{"$ cdz uses / def / scope      # where a name is used, defined, in scope"}</C> <br /> <C>{"$ cdz symbols / doc           # a file's definitions, and their docs"}</C> <br /> <C>{"$ cdz fix foo.cdz             # apply the compiler's verified repairs"}</C> <br /> <C>{"$ cdz fmt foo.cdz             # canonical layout, meaning untouched"}</C> <br /> <C>{"$ cdz normalize --match-to-let  # opt-in codemod: an irrefutable match becomes a let"}</C></Note>
      <P>The first few <em>read</em> your program; <C>fmt</C> and <C>normalize</C> <em>rewrite</em> it, still structure-aware: <C>fmt</C> canonicalizes layout without changing meaning, so your comments and structure survive intact, while <C>normalize</C> is opt-in because it does change shape (the <Ch to="/irrefutable-patterns">match-to-let</Ch> idiom, applied for you). These are the same facts the editor shows on hover and as squiggles, offered one query at a time so a script or an agent can consume them directly. For an editor that speaks the Language Server Protocol, <C>cdz lsp</C> serves all of it live over stdio, and <C>cdz calc</C> opens the same exact-arithmetic calculator you met earlier as a REPL. The point is that a human and an agent reach for the same tool and get the same compiler-backed answers, never a separate approximation that might drift.</P>
      <Why tenet="One compiler, everywhere you work">The browser guide, the command line, the editor, and an agent's query all run the one compiler, which is why what you saw in the playground is exactly what <C>cdz</C> does at your terminal. Because a single tool answers both "build this" and "tell me about this," there is no second implementation to disagree with the first, and the understanding an agent acts on is the same understanding that compiles the code.</Why>
      <P>That's the whole toolchain: one binary from a fresh <C>cdz new</C> to a running program, with the compiler's knowledge available as ordinary queries along the way. To recap the language itself and find where to go from here, head to <Ch to="/whats-next">Where to go next</Ch>.</P>
    </article>
  );
}
