(chapter
  (slug "const-parameters")
  (title "Const parameters")
  (pillar "language")
  (section "What makes Cadenza different")
  (blurb "Arguments known at compile time, inlined into a specialized copy and erased: a constant, a type, or a dictionary of behaviour.")
  (lede "Some arguments you know before the program ever runs, like a size, a type, or a table of behaviour. What if the compiler could bake those in and charge you nothing at run time? That's a " (c "const") " parameter: an argument the compiler must know at compile time, so it is " (em "inlined") " into a specialized copy of the function and then erased, which means a different const value produces a different specialization and nothing about it survives to run time.")
  (p "You mark a parameter " (c "const") " by wrapping its annotated binder: " (cdz (const (: name Type))) ". The " (c "const") " sits on the " (em "parameter") ", not the type. At the call site you pass an ordinary argument, and the only rule is that it must be a closed, compile-time-known value such as a constant, a type, or a record of functions, never something computed from runtime data.")
  (h2 "A constant, inlined and specialized")
  (p "The simplest const parameter is a constant scalar. Here " (c "scale") " takes a " (c "const") " factor " (c "k") " and a runtime " (c "x") ". Each call fixes " (c "k") " to a literal, so the compiler bakes that factor into a specialized " (c "scale") ", giving one copy with " (c "k = 3") " and another with " (c "k = 2") ":")
  (runnable
    (source (def (scale (const (: k Int64)) (: x Int64))
  (* k x))
(def (main)
  (+ (scale 3 5) (scale 2 3)))))
  (p "That's " (c "15 + 6 = 21") ". The two calls compile to two distinct functions with the factor already substituted, the same way a generic function is monomorphized per type. A const parameter is that idea for " (em "values") ": specialize per compile-time-known argument, then erase it.")
  (h2 "A dictionary of behaviour")
  (p "The const value doesn't have to be a scalar, since it can be a whole " (em "record of functions") ", a \"dictionary\" that tells the function how to behave. Here " (c "fold-n") " applies an operation " (c "n") " times, and the operation lives in a const dictionary " (c "d") ". Calling it with two different dictionaries, one that adds 10 and one that doubles, specializes each call with its operation inlined:")
  (runnable
    (id "fold-n")
    (source (def (fold-n (const (: d (Record (: op (-> Int64 Int64))))) (: n Int64) (: acc Int64))
  (if (= n 0) acc (fold-n d (- n 1) ((. d op) acc))))
(def (main)
  (+ (fold-n #record((= op (fn (x) (+ x 10)))) 3 0)
     (fold-n #record((= op (fn (x) (* x 2)))) 3 1)))))
  (p "The first fold adds 10 three times from " (c "0") " to reach " (c "30") ", the second doubles three times from " (c "1") " to reach " (c "8") ", and together they make " (result (of "fold-n") 38) ". Because " (c "d") " is const, the " (cdz (. d op)) " lookup folds to the concrete function in each specialized copy, so no record is passed at run time and no indirect call is emitted. You've hand-written the mechanism a typeclass or trait system would automate, handing the implementation to the function as a compile-time argument.")
  (h2 "A const type parameter")
  (p "The const argument can even be a " (em "type") ". A " (cdz (const (: t Type))) " parameter takes a type-value at compile time (types are ordinary values, as shown in " (em "Types as values") "), and the body can branch on it with " (c "Type.eq") ", folding to a constant per specialization. Here " (c "is-int") " asks whether the type it was handed is " (c "Int64") ":")
  (runnable
    (id "is-int")
    (source (def (is-int (const (: t Type)) (: x Int64))
  (Type.eq t Int64))
(def (main) (is-int Int64 5))))
  (p "Called with " (c "Int64") " it folds to " (result (of "is-int") true) ", and calling it with " (c "Bool") " folds the same code to " (c "false") ", because each call site is specialized for the type it named so the comparison is settled at compile time rather than run time. The caller hands the type in as an argument and the compiler bakes a dedicated copy for it.")
  (note "A " (c "const") " parameter can carry either a type or a dictionary, and both are the same idea seen from two angles. Passing a " (c "const") " " (em "type") " (a " (cdz (const (: t Type))) " parameter) lets the caller name the type the code specializes for, which is " (em "types as values") " made into an argument, while passing a " (c "const") " " (em "dictionary") " lets the caller name the behaviour the code runs. Both ride the same machinery, since a compile-time-known argument is inlined and specialized and then erased before the program runs.")
  (why (tenet "A compile-time argument costs nothing at run time") "A const parameter lets a function be " (em "parameterized") " by a size, a strategy, a type, or a table of operations without paying for that flexibility when it runs. The argument is resolved while the program is compiled, folded into a specialized copy, and erased, so the generated code is exactly what you'd have written by hand for that specific value. It's the same bargain as generic monomorphization and first-class types: express the abstraction at compile time, keep the machine code concrete. And the compiler enforces the honesty, because a const argument that isn't actually known at compile time is a clean error rather than a silent fallback to a runtime value.")
  (h2 "Your turn")
  (exercise
    (id "const-parameters:1")
    (prompt (c "scale") " bakes its " (c "const") " factor " (c "k") " into each specialized copy. Fill the factor so " (c "(scale ? 5)") " gives " (c "20") ".")
    (starter (def (scale (const (: k Int64)) (: x Int64))
  (* k x))
(def (main) (scale ? 5)))
    (solution (def (scale (const (: k Int64)) (: x Int64))
  (* k x))
(def (main) (scale 4 5)))
    (expected "20")
    (hint (c "k * 5 = 20") " needs " (c "k = 4") ". That " (c "4") " is inlined into the specialized " (c "scale") " at compile time, so being a const argument it must be a literal rather than a runtime value."))
  (exercise
    (id "const-parameters:2")
    (prompt "The const dictionary decides the operation. Fill the body of " (c "op") " so that folding it three times from " (c "0") ", adding the same amount each step, reaches " (c "15") ".")
    (starter (def (fold-n (const (: d (Record (: op (-> Int64 Int64))))) (: n Int64) (: acc Int64))
  (if (= n 0) acc (fold-n d (- n 1) ((. d op) acc))))
(def (main) (fold-n #record((= op (fn (x) (+ x ?)))) 3 0)))
    (solution (def (fold-n (const (: d (Record (: op (-> Int64 Int64))))) (: n Int64) (: acc Int64))
  (if (= n 0) acc (fold-n d (- n 1) ((. d op) acc))))
(def (main) (fold-n #record((= op (fn (x) (+ x 5)))) 3 0)))
    (expected "15")
    (hint "Three steps from " (c "0") ", each adding the same amount " (c "a") ", gives " (c "3 × a") ". For " (c "15") " that's " (c "a = 5") ", so " (c "op") " is " (cdz (fn (x) (+ x 5))) ". The dictionary is const, so this operation is inlined into the specialized " (c "fold-n") ".")))
