(chapter
  (slug "control-flow")
  (title "Control flow")
  (pillar "language")
  (section "Fundamentals")
  (blurb "if / then / else, sequencing, and short-circuit logic.")
  (lede "Choosing between values with " (c "if") ", combining conditions, and looping by recursion.")
  (h2 "Conditionals")
  (p "An " (c "if") " is an " (em "expression") ": it evaluates to one branch or the other and yields that value. It's a value choice, not a statement you run for its effect.")
  (runnable
    (source (if (< 3 5) 100 200))
    (id "if-branch"))
  (p (try-change (example "if-branch") (find "<") (replace ">") "Change " (c "&lt;") " to " (c "&gt;")) " and it runs again to take the other branch, giving " (c "200") ".")
  (p "Because an " (c "if") " produces a value and that value needs one type, both branches must agree. Ask for one branch that returns a number and another that returns a boolean, and the compiler refuses:")
  (note "This one is " (strong "meant to be refused") ". Run it and read the status bar: the branches can't have different types, because the " (c "if") " as a whole is a value.")
  (runnable
    (source (if (< 1 2) 100 true))
    (expect "error"))
  (why (tenet "if is an expression, so both branches share a type") "That single-type rule isn't fussiness, because it's what lets " (c "if") " be used anywhere a value is expected, whether as a function argument, a let binding, or the arm of another " (c "if") ". There's no separate \"statement if\" you run for effect and \"expression if\" that yields a value, so none of the \"one branch forgot to return\" bugs that split brings can happen here. One form is always a value and always well-typed, so the type checker can vet it wherever it appears.")
  (h2 "Nesting choices")
  (p "An " (c "if") " selects among more than two outcomes by nesting in the else position:")
  (runnable
    (source (let ((n 0))
  (if (< n 0) -1
      (if (= n 0) 0 1)))))
  (p "This is the sign of " (c "n") ", giving " (c "-1") " if negative, " (c "0") " if zero, and " (c "1") " if positive. With " (c "n = 0") " the first test fails and the inner " (cdz "(= n 0)") " fires, so the answer is " (c "0") ". Change " (c "n") " to " (c "-4") " or " (c "7") " and Run to take a different branch.")
  (h2 "Booleans compose and short-circuit")
  (p "Comparisons produce " (c "Bool") " values, and " (c "and") ", " (c "or") ", " (c "not") " combine them. They " (em "short-circuit") ", so a false " (c "and") " never evaluates its right side. That's what makes a guard-then-use pattern safe, because here " (c "safe") " checks " (c "n") " isn't zero " (em "before") " dividing by it, so the division never runs when it would trap:")
  (runnable
    (source (def (safe n)
  (and (not (= n 0)) (> (/ 100 n) 5)))
(def (main) (safe 0))))
  (p "With " (c "n = 0") " the first test is false, so " (cdz "(/ 100 0)") " is skipped entirely and the whole thing renders " (c "false") ". Were " (c "and") " not short-circuiting, that division would trap.")
  (h2 "Recursion")
  (p "A function can call itself, and that's how you loop in Cadenza. A base case stops the recursion, and each step reduces toward it. Here " (c "sm") " sums the integers from " (c "n") " down to 0:")
  (runnable
    (source (def (sm n)
  (if (= n 0) 0 (+ n (sm (- n 1)))))
(def (main) (sm 5))))
  (p (cdz "(sm 5)") " adds " (c "5 + 4 + 3 + 2 + 1") " down to the base case, giving " (c "15") ". Each call peels off " (c "n") " and recurses on " (c "n - 1") " until it reaches " (c "0") ".")
  (h2 "Your turn")
  (exercise
    (id "control-flow:1")
    (prompt "Write " (c "pow2") ", which computes 2 to the " (c "n") ". Here " (c "n") " is just a " (em "counter") " that says how many times to double, while the doubling itself is always the same. Fill in the step so " (cdz "(pow2 5)") " gives " (c "32") ".")
    (starter (def (pow2 n)
  (if (= n 0) 1 ?))
(def (main) (pow2 5)))
    (solution (def (pow2 n)
  (if (= n 0) 1 (* 2 (pow2 (- n 1)))))
(def (main) (pow2 5)))
    (expected "32")
    (hint "Unlike " (c "sm") " above, " (c "n") " doesn't appear in the step, since you just double the result of one fewer step with " (cdz "(* 2 (pow2 (- n 1)))") ". Writing " (c "(* n …)") " by habit would give factorial, " (c "120") ", not " (c "32") "."))
  (exercise
    (id "control-flow:2")
    (prompt (c "fare") " picks a ticket price by age tier: under 5 rides free (" (c "0") "), 65 and over pays " (c "5") ", everyone in between pays " (c "10") ". The free case is done; fill the hole with the " (em "nested") " " (c "if") " that decides between the adult and senior fares, so that " (cdz "(fare 70)") " gives " (c "5") ".")
    (starter (def (fare age)
  (if (< age 5) 0
      ?))
(def (main) (fare 70)))
    (solution (def (fare age)
  (if (< age 5) 0
      (if (< age 65) 10 5)))
(def (main) (fare 70)))
    (expected "5")
    (hint "The hole is a second " (c "if") " in the else position, like the sign-of-" (c "n") " example above. In " (cdz "(if (< age 65) 10 5)") ", under 65 is the adult fare " (c "10") " and otherwise the senior " (c "5") ".")))
