(chapter
  (slug "data")
  (title "Tuples & records")
  (pillar "language")
  (section "Fundamentals")
  (blurb "Bundling values together, by position or by name.")
  (lede "Bundling several values into one, positionally or by name.")
  (p "So far our programs have passed around single values. Real programs group values together: a point is an " (c "x") " and a " (c "y") ", a result is a value and a status. Cadenza has two ways to bundle values, namely " (strong "tuples") " (by position) and " (strong "records") " (by name).")
  (h2 "Tuples")
  (p "A tuple is a fixed positional product of values. When you Run this, look at the type the result carries, " (cdz (Tuple Int64 Bool)) ": the compiler tracks not just " (em "how many") " elements there are but the type of each one, in order. The two slots hold different types, and that's fine, because a tuple's shape is part of its type.")
  (runnable
    (source #tuple(7 true))
    (title "A tuple"))
  (h2 "Records")
  (p "A record has a fixed set of " (em "named") " fields. Reach a field with the " (c ".") " accessor, here the " (c "leap") " flag of a little \"year\" record:")
  (runnable
    (source (let ((y #record((= year 2026) (= leap true))))
  (. y leap))))
  (p "Return the whole record and, just like the tuple, it carries a structural type, one entry per field, each with its own type:")
  (runnable
    (source #record((= year 2026) (= leap true))))
  (why (tenet "Everything is a record") "Records aren't just one data type among many, since they're the mechanism the whole language is built from. A module is a record of its exports; a built-in like " (c "List") " is a record of its operations; a sum type is a record of its constructors. Because the special things are ordinary values reached the ordinary way, the compiler needs just " (em "one") " lookup rule instead of dozens of special cases, and a name you define simply shadows a built-in of the same name, with no magic.")
  (h2 "Compared by value")
  (p "Two tuples or two records are equal when their contents are, which is structural equality, not identity. A tuple matches position by position, so " (cdz #tuple(1 2)) " equals another " (cdz #tuple(1 2)) ":")
  (runnable
    (source (= #tuple(1 2) #tuple(1 2))))
  (p "A record matches by " (em "field name") ", not field order, so the same fields written in a different order are still the same record. That's the by-name nature showing through: a record is its set of named fields, however you list them.")
  (runnable
    (source (= #record((= x 1) (= y 2)) #record((= y 2) (= x 1)))))
  (h2 "Taking one apart with a let")
  (p "Beyond reaching a single field, you can bind " (em "all") " of a tuple's parts at once by destructuring it in a " (c "let") ". The pattern on the left of the binding names each part; here a two-tuple binds " (c "a") " and " (c "b") " in one step, then adds them:")
  (runnable
    (source (let ((#tuple(a b) #tuple(3 4)))
  (+ a b))))
  (p "A two-tuple always has exactly this shape, so the pattern can't fail to match: it's " (em "irrefutable") ", and that's exactly when a " (c "let") " binding is the right tool rather than a one-armed " (c "match") ". Destructuring is the subject of " (strong "Pattern matching") " and " (strong "Irrefutable patterns") "; the point here is that a tuple or record is an ordinary value a pattern can name and take apart.")
  (h2 "They compose")
  (p "A tuple can hold a record, a record field can hold a tuple, and so on, so the shapes nest freely, and the accessor chains to reach inside. Here a record has one field, " (c "pair") ", holding a tuple; we reach the field, then index into the tuple to pull out its second element:")
  (runnable
    (id "data-nested")
    (source (. (. #record((= pair #tuple(10 20))) pair) 1)))
  (p "Reaching " (c "pair") " gets the tuple, then index " (c "1") " pulls its second element, " (result (of "data-nested") 20) ". We'll lean on this in the next chapter, but for now the point is just that the two ways of bundling stack together, with no special rule for the combination.")
  (h2 "Functions inside data")
  (p "Since functions are values, they can live in tuples and records too. Here we pull a function out of a tuple and call it:")
  (runnable
    (id "data-tuple-fn")
    (source ((. #tuple((fn (x) (+ x 1)) 9) 0) 5)))
  (p "Element " (c "0") " of the tuple is the increment function; applying it to " (c "5") " gives " (result (of "data-tuple-fn") 6) ". The " (c "9") " in the other slot just rides along, since a tuple can mix a function and a plain value.")
  (h2 "Your turn")
  (exercise
    (id "data:1")
    (prompt "The record has three named fields. Reach the " (c "y") " field with the " (c ".") " accessor, so the answer is " (c "20") ".")
    (starter (. #record((= x 10) (= y 20) (= z 30)) ?))
    (solution (. #record((= x 10) (= y 20) (= z 30)) y))
    (expected "20")
    (hint "The accessor takes the field's " (em "name") ", not a number, because records are reached by name. Write " (c "y") "."))
  (exercise
    (id "data:2")
    (prompt "Now both ways at once, reaching into a nested shape. This record's " (c "point") " field holds a tuple; the field is already reached by name, so finish the chain with the " (em "index") " that pulls out the " (em "last") " element, " (c "9") ".")
    (starter (. (. #record((= point #tuple(7 8 9))) point) ?))
    (solution (. (. #record((= point #tuple(7 8 9))) point) 2))
    (expected "9")
    (hint "The field access " (c "point") " used a name; the tuple step uses a " (em "number") ". Indices start at " (c "0") ", so the last of three elements is index " (c "2") "."))
  (p "That's the vocabulary. Next we'll " (em "use") " it by passing records into functions, nesting them, and reaching in for the pieces, in " (strong "Working with records &amp; tuples") "."))
