(chapter
  (slug "contracts")
  (title "Design by contract")
  (pillar "language")
  (section "What makes Cadenza different")
  (blurb "@requires and @ensures turn an assumption into an enforced check at the function boundary.")
  (lede "A function usually carries assumptions, like \"this count is never negative\" or \"I always return something in range\". Cadenza lets you write those assumptions down as " (em "contracts") ", and turns them into checks it enforces every time the function runs.")
  (p "Two annotations do it. " (c "@requires") " states a " (em "precondition") ", what must hold when the function is called, while " (c "@ensures") " states a " (em "postcondition") ", what must hold about its result. Each becomes a check the compiler injects at the function's boundary: violate it and the program " (em "traps") " right there, instead of quietly computing on bad data.")
  (h2 "@requires: a precondition")
  (p "Here " (c "f") " promises to work only for non-negative inputs. Called with " (c "5") ", it returns " (c "6") ", so the check passes and doesn't change the value:")
  (runnable
    (source (def (main) (f 5))
(@ (requires (>= x 0))
  (def (f (: x Int64)) (+ x 1)))))
  (p "Feed it a value that breaks the promise and it stops at the boundary, so " (c "f(-5)") " traps, because " (c "-5") " is not " (c ">= 0") ":")
  (runnable
    (source (def (main) (f -5))
(@ (requires (>= x 0))
  (def (f (: x Int64)) (+ x 1))))
    (expect "error"))
  (note "The precondition is checked " (em "once, at entry") ", which is the Hoare-logic reading of " (c "{P} body {Q}") ". Because it lives on the function, not the call, it holds even for higher-order or indirect calls. Preconditions also " (em "stack") ": put several " (c "@requires") " on one function and all of them are enforced.")
  (h2 "@ensures: a postcondition")
  (p "A postcondition constrains the " (em "result") ". Inside " (c "@ensures") ", the name " (c "ret") " refers to the value the function returns. This " (c "f") " promises a non-negative result, so with " (c "200") " it returns " (c "100") ", honestly:")
  (runnable
    (source (def (main) (f 200))
(@ (ensures (>= ret 0))
  (def (f (: x Int64)) (- x 100)))))
  (p "But " (c "f(5)") " would compute " (c "-95") ", a broken promise, so it traps on the way out instead of returning a wrong answer:")
  (runnable
    (source (def (main) (f 5))
(@ (ensures (>= ret 0))
  (def (f (: x Int64)) (- x 100))))
    (expect "error"))
  (h2 "The full contract")
  (p "Combine them and you have design by contract in full: " (c "@requires") " guards the input at entry, " (c "@ensures") " guards the result at exit, and they compose. This " (c "f") " demands a non-negative input " (em "and") " promises a non-negative output:")
  (runnable
    (source (def (main) (f 200))
(@ (requires (>= x 0))
  (@ (ensures (>= ret 0))
    (def (f (: x Int64)) (- x 100))))))
  (p "Called with " (c "200") " both hold and it returns " (c "100") ". Call it with " (c "-5") " and it traps at " (em "entry") " (the precondition); call it with " (c "5") " and it traps at " (em "exit") " (the postcondition catches the " (c "-95") "). A caller can only ever see a result that satisfies the contract, or a clean trap at the exact boundary that broke it.")
  (note "Two things to know: a contract may reference only the function's parameters (and prelude/global names), so naming something out of scope is a compile error at the annotation. And a function whose parameter is named " (c "ret") " can't carry an " (c "@ensures") ": the result binder " (c "ret") " would shadow the parameter, so rather than silently ignore the postcondition, the compiler rejects it and asks you to rename the parameter.")
  (h2 "A contract is an ordinary boolean")
  (p "A contract's predicate is just a boolean expression in the def's scope, so it can say far more than " (c "&gt;= 0") ". It can relate two parameters (" (cdz "(requires (< lo hi))") "), compare the result to an input (" (cdz "(ensures (> ret x))") "), reach into a tuple or record, or even " (em "match") " a sum result. Here " (c "safe-dec") " returns an " (c "Option") ", and the postcondition matches it, promising that whenever there " (em "is") " a value it's non-negative:")
  (runnable
    (source (def (main) (safe-dec 5))
(@ (requires (>= x 0))
  (@ (ensures (match ret
                ((Some v) (>= v 0))
                ((None _u) true)))
    (def (safe-dec (: x Int64))
      (if (> x 0) (Some (- x 1)) (None unit)))))))
  (p "Called with " (c "5") " the result is " (cdz "(Some 4)") ", and the postcondition's " (c "Some") " arm checks " (c "4 &gt;= 0") ". Because the predicate is ordinary code, a contract is as expressive as any other boolean you could write, it just runs at the boundary instead of in the body.")
  (h2 "@invariant: guarding a type")
  (p (c "@requires") " guards a function's entry and " (c "@ensures") " its exit. The third contract, " (c "@invariant") ", guards a " (em "type") ". Put it on a value type and the compiler enforces the predicate at " (em "every") " point a value of that type is built, so a value that breaks it can never come into existence. The predicate is written over " (c "self") ", the value being constructed. Here a " (c "Percent") " must stay between " (c "0") " and " (c "100") ", and building one in range works:")
  (runnable
    (source (do
  (@ (invariant (and (>= self 0) (<= self 100)))
    (type Percent (Pct Int64)))
  (def (mk (: v Int64))
    (let (((Percent.Pct p) (Percent.Pct v))) p))
  (def (main) (mk 50))
  (export main)))
    (wrap "false"))
  (p (c "mk(50)") " constructs a " (c "Percent") " and reads back " (c "50") ". Try to build one out of range and it traps at the moment of construction, before the invalid value can exist, so " (c "mk(150)") " never returns a bad " (c "Percent") ":")
  (runnable
    (source (do
  (@ (invariant (and (>= self 0) (<= self 100)))
    (type Percent (Pct Int64)))
  (def (mk (: v Int64))
    (let (((Percent.Pct p) (Percent.Pct v))) p))
  (def (main) (mk 150))
  (export main)))
    (expect "error")
    (wrap "false"))
  (p "The same guards any type with an invariant, a non-empty list or a normalized vector just as much as a bounded number. Because the check fires at construction, downstream code never re-validates: a " (c "Percent") " in hand is " (em "always") " in range, so the illegal state is unrepresentable rather than merely discouraged.")
  (why (tenet "Make the assumption an enforced check, not a comment") "Every function, and every type, carries assumptions; usually they live in a comment or someone's head, and a violation surfaces far away as corrupted data. A contract puts the assumption where the compiler can enforce it, checked at the boundary, failing loudly and locally the instant it's broken. It's the same " (link (slug "errors") " Option and Result ") " instinct of making the failure a value you must confront, turned on a function's inputs and results and on a type's own values.")
  (p "These contracts are checked at run time today. They're also the first step of a larger story: the same " (c "@requires") " a compiler could one day " (em "prove") " and remove, the assumption verified once, statically, instead of on every call. For now, a contract turns something you already assumed into a checked guarantee, just by writing it down. Next, " (link (slug "modules") " Modules ") " gather related definitions, contracts and all, under a name."))
