(chapter
  (slug "effects")
  (title "Effects & handlers")
  (pillar "language")
  (section "What makes Cadenza different")
  (blurb "Perform an operation; a handler decides what it means.")
  (lede "An effect lets a function ask for something like a random choice or the current setting or a way to bail out while leaving how that request is answered to whoever runs it.")
  (p "Most languages bake the answer into the function itself, so one that needs a random number calls the global generator and one that needs to give up throws an exception. Cadenza splits those two apart, because a function performs an operation by naming what it needs while a " (c "handle") " around it decides what performing that operation means, and the performing code never knows or cares who is listening. We'll build up from a handler sitting right next to the performance toward the case that matters, where a function performs an operation that some other function further out decides how to answer.")
  (h2 "Declaring and performing an operation")
  (p "An " (c "effect") " declares a named operation and its type. Here " (c "Ask") " has one operation, " (c "ask") ", that produces an " (c "Int64") ". The body performs it with " (cdz (Ask.ask)) ", and the enclosing " (c "handle") " answers every performance by " (c "resume") "-ing with a value:")
  (runnable
    (source (effect Ask (op ask (-> Unit Int64)))
(def (main)
  (handle Ask unit
    ((ask () s (resume 42 s)))
    (Ask.ask)))))
  (p "The body is just " (cdz (Ask.ask)) ". There's no " (c "42") " in it; the value came entirely from the handler. Read the arm as: when " (c "ask") " is performed, " (c "resume") " the performing code with " (c "42") ". (The " (c "s") " is the handler's state; we'll get to it, for now it's along for the ride.)")
  (why (tenet "A function says what it needs, not how it's met") "Splitting " (em "performing") " from " (em "handling") " is the same move as returning an " (c "Option") " instead of crashing: it puts a decision into the open where it can be seen and changed. Code that performs " (c "Ask.ask") " works against any handler: one that returns a constant, one that reads a config, one that records every call for a test. The alternative, reaching out to a global or throwing an exception the caller can't see in the type, welds the answer to the question. An effect keeps them separable.")
  (h2 "The handler intercepts every performance")
  (p "A handler isn't a one-time value; it answers " (em "each") " time the operation is performed. Here the body performs " (c "Ask.ask") " twice, and each one resumes with " (c "20") ":")
  (runnable
    (source (effect Ask (op ask (-> Unit Int64)))
(def (main)
  (handle Ask unit
    ((ask () s (resume 20 s)))
    (+ (Ask.ask) (Ask.ask))))))
  (p "Two performances, each answered with " (c "20") ", summed to " (c "40") ".")
  (h2 "A handler with state")
  (p "That " (c "s") " is the handler's own state, threaded from one performance to the next. A " (c "handle") " seeds it (here " (c "0") "), each arm receives it, and " (c "resume") " takes both the value to hand back " (em "and") " the next state. So a counter that hands out " (c "0") ", then " (c "1") ", then " (c "2") "… is a three-line handler:")
  (runnable
    (id "counter")
    (source (effect Counter (op next (-> Unit Int64)))
(def (main)
  (handle Counter 0
    ((next (u) s (resume s (+ s 1))))
    (+ (Counter.next) (* 10 (Counter.next)))))))
  (p "The first " (c "next") " resumes with the state " (c "0") " and bumps it to " (c "1") "; the second resumes with " (c "1") ". So the body computes " (c "0 + 10 * 1") " = " (result (of "counter") 10) ". The state never leaks out of the handler; the performing code just sees a sequence of numbers.")
  (h2 "The performer and the handler can be far apart")
  (p "So far the " (c "handle") " has wrapped the performance directly. But nothing says they have to sit in the same function, and this is where effects earn their keep. A function can perform an operation it never handles; the handler is supplied by whoever " (em "calls") " it. Here " (c "gen") " just performs " (c "Bump.by") " (it has no handler at all) and " (c "main") " decides what performing means, wrapped around its " (em "call") " to " (c "gen") ":")
  (runnable
    (source (effect Bump (op by (-> Int64 Int64)))
(def (gen) (Bump.by 41))
(def (main)
  (handle Bump unit
    ((by (n) s (resume (+ n 1) s)))
    (gen)))))
  (p (c "gen") " reads as an ordinary function, yet it reaches out to a handler installed one level up the call stack. Resolution follows the " (em "calls") ", not the source layout: the performance in " (c "gen") " searches outward along the chain that led to it until it finds a " (c "Bump") " handler, " (c "main") "'s. That's what lets a leaf function deep in a program name what it needs and let the edge of the program decide how.")
  (why (tenet "A function says what it needs, not how it's met") "This is dependency injection without the plumbing. " (c "gen") " doesn't take the answer as a parameter, doesn't import a global, doesn't know a handler exists; it just performs. The same " (c "gen") ", unchanged, behaves differently under a different caller's handler: one caller resumes with " (c "n + 1") ", another could resume with " (c "0") " for a test, another could count the calls. The dependency is threaded implicitly along the call chain and resolved at the nearest handler, the useful half of a global variable with none of the \"who set this?\" mystery.")
  (h2 "A getter/setter, shared across functions")
  (p "Give an effect " (em "two") " operations and let the handler's state be real mutable state (a " (c "get") " and a " (c "set") ") and you have a store that any function can read and write, without a single one of them holding the data. Here " (c "deposit") " and " (c "balance") " are ordinary helpers; neither owns the balance. The " (c "State") " handler in " (c "main") " is the only thing that does, and it threads it through " (c "s") ":")
  (runnable
    (id "state")
    (source (effect State
  (op get (-> Unit Int64))
  (op set (-> Int64 Unit)))
(def (deposit (: n Int64))
  (State.set (+ (State.get) n)))
(def (balance) (State.get))
(def (main)
  (handle State 100
    ((get (u) s (resume s s))
     (set (v) s (resume unit v)))
    (do (deposit 20) (deposit 5) (balance))))))
  (p "The account starts at " (c "100") "; two deposits push it to " (result (of "state") 125) ". Read the arms as the store's implementation: " (c "get") " resumes with the current state and leaves it unchanged; " (c "set") " resumes with " (c "unit") " and makes its argument the new state. " (c "deposit") " and " (c "balance") " talk to that store through " (c "State.get") " / " (c "State.set") " as if it were ambient, but it isn't ambient at all. Swap in a handler that logs every " (c "set") ", or seeds a different opening balance, and not one line of " (c "deposit") " changes.")
  (h2 "Doing work after resume")
  (p "Every handler so far has " (c "resume") "d as its " (em "last") " act: it hands a value back and steps aside, and whatever the performing code computes flows straight out. But an arm can do work " (em "after") " the resumption returns. " (c "resume") " is an ordinary expression, so its result, the value the rest of the body eventually produces, is something the arm can keep computing with:")
  (runnable
    (source (effect Amb (op flip (-> Unit Int64)))
(def (main)
  (handle Amb 0
    ((flip (u) s (+ 1 (resume 10 s))))
    (Amb.flip)))))
  (p "The arm resumes the performer with " (c "10") ", and here the body " (em "is") " that performance, so it reduces to " (c "10") "; then the arm's own " (c "+ 1") " wraps that result, and the answer is " (c "11") ". The " (c "resume") " plugs a value into the hole where " (c "Amb.flip") " was, and the arm gets to act on what comes back.")
  (p "That hole can have work around it too. If the body is " (cdz (+ 100 (Amb.flip))) ", the resumption re-runs " (em "the whole rest of the body") " with " (c "10") " in the hole, giving " (c "110") ", and only then does the arm's " (c "+ 1") " apply:")
  (runnable
    (source (effect Amb (op flip (-> Unit Int64)))
(def (main)
  (handle Amb 0
    ((flip (u) s (+ 1 (resume 10 s))))
    (+ 100 (Amb.flip))))))
  (p "The result is " (c "111") ": " (c "100 + 10") " from re-reducing the body, then " (c "+ 1") " from the arm on the way out. This is what lets a handler " (em "post-process") " or " (em "aggregate") " a whole computation, logging a total, accumulating, transforming a result, rather than only feeding a value in. And it composes with state: each performance resumes with the advanced state, and the arm's surrounding work wraps every re-reduction:")
  (runnable
    (id "st-tick")
    (source (effect St (op tick (-> Unit Int64)))
(def (main)
  (handle St 0
    ((tick (u) s (+ 100 (resume s (+ s 1)))))
    (+ (St.tick) (St.tick))))))
  (p "The first " (c "tick") " reads the initial state " (c "0") " and the second reads the advanced " (c "1") "; each is wrapped by the arm's " (c "+ 100") ", so they add up to " (result (of "st-tick") 201) ". Tail resume answers and steps aside; non-tail resume answers, then acts on what came back.")
  (h2 "A handler that doesn't resume: bailing out")
  (p "A handler can also " (em "not") " resume at all. If an arm just returns a value, the whole " (c "handle") " expression becomes that value and the rest of the body is abandoned: an early exit, no exceptions required. Here " (c "Bail.bail") " hands its argument straight out, so the " (c "+ 100") " never runs:")
  (runnable
    (id "bail")
    (source (effect Bail (op bail (-> Int64 Int64)))
(def (main)
  (handle Bail 0
    ((bail (n) s n))
    (+ (Bail.bail 7) 100)))))
  (p "The result is " (result (of "bail") 7) ", not " (c "107") ": performing " (c "bail") " jumped out of the addition entirely. This is how you'd write \"stop and return this now\": the same shape as an exception, but it's just a handler choosing not to resume.")
  (p "The bail works even right beside another effect, not just a plain value. Here the body adds a resumptive " (cdz (E.other)) " and an abortive " (cdz (E.bail 5)) ", and performing " (c "bail") " still exits the whole " (c "handle") ":")
  (runnable
    (id "e-bail")
    (source (effect E (op other (-> Int64)) (op bail (-> Int64 Int64)))
(def (main)
  (handle E 0
    ((other () s (resume s (+ s 1))) (bail (v) s v))
    (+ (E.other) (E.bail 5))))))
  (p "The result is " (result (of "e-bail") 5) ". " (cdz (E.other)) " ran first and drew the seed " (c "0") ", then " (cdz (E.bail 5)) " bailed, so the pending " (c "+") " never finishes. The effect " (cdz (E.other)) " already performed isn't undone, though: a bail-out abandons the work still " (em "pending") ", not what already happened. And the bail need not sit at the top of the body; it exits from wherever it runs, even from inside a conditional like " (cdz (if c (E.bail 5) 0)) " that only some runs reach.")
  (note "These handlers are " (em "one-shot") ": each performance resumes at most once, so they compile down to ordinary control flow: no captured continuations, no runtime machinery. Handling something the program can't discharge itself (real input, the clock) is delegated to the host at the program's edge, and shows up in its manifest. That's how effects stay honest about what a program actually does.")
  (h2 "A guard must be side-effect-free")
  (p "There's one place a perform is " (em "not") " allowed: a " (link (slug "pattern-matching") " match-arm ") " " (em "guard") ". A guard is a boolean decision the pattern engine may evaluate " (em "speculatively or repeatedly") ", or skip entirely when an earlier arm wins, so it has no well-defined \"run exactly once, in this order\" the way an arm body does. Performing an effect there would mean an effect with no defined schedule, so the compiler rejects it outright. Here a guard performs " (c "Ask.ask") ", and the program declines:")
  (runnable
    (source (effect Ask (op ask (-> Unit Int64)))
(def (main)
  (handle Ask unit
    ((ask () s (resume 5 s)))
    (match 3
      ((guard x (< x (Ask.ask))) 1)
      (_ 0)))))
    (expect "error"))
  (p "The error is " (c "CDZ0407") ", and its message names the fix: " (c "a guard must be side-effect-free — an effect is performed in this guard, which the pattern engine may evaluate speculatively or repeatedly; lift it to a `let` evaluated once before the `match` and guard on the bound value") ". That is exactly the repair: perform the effect " (em "once") ", before the " (c "match") ", bind the result, and let the guard read the bound value, which is pure. Same logic, now with a defined evaluation:")
  (runnable
    (source (effect Ask (op ask (-> Unit Int64)))
(def (main)
  (handle Ask unit
    ((ask () s (resume 5 s)))
    (let ((limit (Ask.ask)))
      (match 3
        ((guard x (< x limit)) 1)
        (_ 0)))))))
  (p "Now the perform happens exactly once (" (c "limit") " is " (c "5") "), the guard compares against the bound value, and since " (c "3 &lt; 5") " the first arm fires and the result is " (c "1") ". The rule is narrow: an effect is welcome in a scrutinee, in an arm body, anywhere with a defined order, just not in the guard condition itself, where \"how many times, in what order\" isn't a question the pattern engine can answer.")
  (h2 "Why this matters: mock now, real later")
  (p "This is what makes effects useful in real programs. Because the performer doesn't know who answers, the " (em "same") " code runs against a test mock or a real external service just by choosing a different handler. Picture a step of an agent loop: " (c "turn") " performs " (c "Model.converse") ", a call to a language model. It names what it needs; it doesn't reach out itself. Run it under a " (em "mock") " handler that echoes the query back, and under a " (em "different") " handler that answers differently, and you get two behaviours from the same " (c "turn") ":")
  (runnable
    (id "model")
    (source (effect Model (op converse (-> Int64 Int64)))
(def (turn) (Model.converse 5))
(def (main)
  (+ (handle Model 0 ((converse (q) s (resume q s))) (turn))
     (handle Model 0 ((converse (q) s (resume (* q 10) s))) (turn))))))
  (p "The first handler resumes with the query unchanged (" (c "5") "), the second with ten times it (" (c "50") "), so the sum is " (result (of "model") 55) ", from one unchanged " (c "turn") ". In a real program the mock is your unit test and the \"different\" handler is the one wired to the actual model at the edge; the loop's logic never mentions either. That's effects as an I/O " (em "boundary") ": the body performs, and swapping the handler swaps the whole outside world, with no dependency injection, no mocking framework, just a different " (c "handle") ".")
  (p "And the whole " (em "loop") " is just this. A real agent runs turns until it's done: each turn asks the model (" (c "Model.converse") ") and dispatches a tool (" (c "Tools.dispatch") "), accumulating a result, bounded by a fuel counter so it terminates. Every one of those is a performed operation; the loop itself is ordinary recursion, and the handlers supply the outside world. Here a three-step run against mock handlers accumulates " (c "3 + 2 + 1 = 6") ":")
  (runnable
    (source (effect Model (op converse (-> Int64 Int64)))
(effect Tools (op dispatch (-> Int64 Int64)) (op done (-> Int64 Int64)))
(def (run (: fuel Int64) (: acc Int64))
  (if (= fuel 0) (Tools.done acc)
    (if (= (Model.converse fuel) 0) (Tools.done acc)
      (run (- fuel 1) (+ acc (Tools.dispatch fuel))))))
(def (main)
  (handle Model 0 ((converse (q) s (resume q s)))
    (handle Tools 0 ((dispatch (a) s (resume a s)) (done (a) s (resume a s)))
      (run 3 0))))))
  (p "The " (c "run") " loop is pure Cadenza: no HTTP, no SDK, no knowledge of what a model or a tool " (em "is") ". Point the two handlers at a real language model and a real tool dispatcher (the program does this at its edge, where the effects show up in its manifest) and the identical loop drives a live agent, so the logic you test with mocks is byte-for-byte the logic that runs in production, and the handler is the only thing that changed.")
  (p "The " (app-link (route "/notebook") " notebook ") " turns this idea into a live document: drag a slider and every dependent cell recomputes, the surrounding context deciding what a value means, made interactive.")
  (h2 "Your turn")
  (exercise
    (id "effects:1")
    (prompt "Make the handler resume " (c "ask") " with " (c "41") ", so " (cdz (+ (Ask.ask) 1)) " gives " (c "42") ".")
    (starter (effect Ask (op ask (-> Unit Int64)))
(def (main)
  (handle Ask unit
    ((ask () s (resume ? s)))
    (+ (Ask.ask) 1))))
    (solution (effect Ask (op ask (-> Unit Int64)))
(def (main)
  (handle Ask unit
    ((ask () s (resume 41 s)))
    (+ (Ask.ask) 1))))
    (expected "42")
    (hint "The handler decides the value " (c "ask") " produces: resume with " (c "41") "."))
  (exercise
    (id "effects:2")
    (prompt "Finish the " (c "bail") " arm so it hands its argument out, making the answer " (c "5") " (not " (c "15") ").")
    (starter (effect Bail (op bail (-> Int64 Int64)))
(def (main)
  (handle Bail 0
    ((bail (n) s ?))
    (+ (Bail.bail 5) 10))))
    (solution (effect Bail (op bail (-> Int64 Int64)))
(def (main)
  (handle Bail 0
    ((bail (n) s n))
    (+ (Bail.bail 5) 10))))
    (expected "5")
    (hint "Return " (c "n") " from the arm without " (c "resume") ": that bails out, skipping the " (c "+ 10") "."))
  (exercise
    (id "effects:3")
    (prompt "Now the state. This " (c "next") " hands each caller the current count, so summing three performances should give " (c "0 + 1 + 2 = 3") ". It only counts up if each arm resumes with the " (em "next") " state, so fill in the second " (c "resume") " argument to make the counter advance by one.")
    (starter (effect Counter (op next (-> Unit Int64)))
(def (main)
  (handle Counter 0
    ((next (u) s (resume s ?)))
    (+ (Counter.next) (+ (Counter.next) (Counter.next))))))
    (solution (effect Counter (op next (-> Unit Int64)))
(def (main)
  (handle Counter 0
    ((next (u) s (resume s (+ s 1))))
    (+ (Counter.next) (+ (Counter.next) (Counter.next))))))
    (expected "3")
    (hint (c "resume") " takes two things: the value handed back (here " (c "s") ", the current count) and the state the " (em "next") " performance will see. Advance it by one with " (cdz (+ s 1)) ". (Leave it as plain " (c "s") " and every call sees " (c "0") ", summing to " (c "0") ".)"))
  (p "An effect splits " (em "what") " a function needs from " (em "how") " that need is met: the caller supplies the handler. The next chapter constrains the other end: not what a function needs, but what it " (em "promises") ". With " (link (slug "contracts") " design by contract ") " you state a function's assumptions and guarantees as checks the compiler enforces at its boundary."))
