(chapter
  (slug "errors")
  (title "Errors & absence")
  (pillar "language")
  (section "Fundamentals")
  (blurb "Option, Result, safe indexing, and checked arithmetic.")
  (lede "What happens when there's no answer, and how Cadenza makes you deal with it.")
  (p "Not every operation has an answer, and a language has to do something when you look past the end of a list or look up a missing key or ask for a result that doesn't fit. Cadenza represents a value that might be missing with the " (c "Option") " type, which is either " (cdz (Some x)) " with a value or " (cdz (None unit)) " with nothing, so the type system makes a caller acknowledge both cases rather than return a bogus default. A genuinely undefined operation like dividing by zero is a different story that halts rather than inventing a value, as you saw in " (strong "The numeric model") ", so this chapter is about the kind of absence you can handle.")
  (h2 "Returning an Option")
  (p "Here's safe division: it returns " (c "None") " when the divisor is zero, and " (c "Some") " of the quotient otherwise. The caller " (c "match") "es on the result and can't forget the empty case.")
  (runnable
    (source (def (safe-div a b)
  (if (= b 0) (None unit) (Some (/ a b))))
(def (main)
  (match (safe-div 10 2)
    ((Some q) q)
    ((None _) -1)))))
  (p "Change the " (c "2") " to " (c "0") " and Run: the " (c "None") " arm fires and you get " (c "-1") ", no crash.")
  (why (tenet "Partiality is data, not a trap") "Reading past the end of a list and looking up a missing key are ordinary values your program handles in Cadenza rather than crashes it suffers, because absence has a type. Since that type is " (c "Option") ", the compiler can see whether you've dealt with it, whereas a special sentinel like " (c "-1") " would invite a caller to forget the edge case and a trap would take the decision out of their hands. An " (c "Option") " keeps the choice in the type where the caller must confront it.")
  (h2 "Safe indexing")
  (p "The same pattern shows up in the standard library. " (c "List.at") " returns an " (c "Option") ", so you never read past the end by accident:")
  (runnable
    (id "list-at")
    (source (def (main)
  (match (List.at #list(10 20 30) 1)
    ((Some x) x)
    ((None _) 0)))))
  (p "Index " (c "1") " holds " (c "20") ", so the " (c "Some") " arm binds it and you get " (result (of "list-at") 20) ". Change the index to " (c "9") " and the " (c "None") " arm's " (c "0") " comes back instead: a miss you handle, not a crash.")
  (h2 "When you're sure: " (c "expect"))
  (p "Sometimes you know an " (c "Option") " holds a value and want to get on with it. " (c "Option.expect") " unwraps a " (c "Some") ", or halts with your message if it's a " (c "None") ". The message is required, so the one place you turn absence into a crash is spelled out, right where it happens. Index 1 is present, so this just hands back " (result (of "option-expect") 20) ":")
  (runnable
    (id "option-expect")
    (source (Option.expect (List.at #list(10 20 30) 1) "index out of range")))
  (p "But ask for index " (c "9") ", off the end, and there's no value to unwrap. " (c "expect") " makes good on its name and halts, with the message you supplied:")
  (note "This one is " (strong "meant to halt") ". It compiles fine (the trap is a run-time event, not a compile error), so Run it and read the status bar: the program stops deliberately, at the exact spot you asked it to, rather than limping on with a bogus value.")
  (runnable
    (source (Option.expect (List.at #list(10 20 30) 9) "index out of range"))
    (expect "error"))
  (p "That's the trade " (c "expect") " makes explicit: you're promising the " (c "Option") " is a " (c "Some") ", and if you're wrong the program halts " (em "here") ", named, instead of a wrong answer leaking downstream. Contrast the " (c "match") " above, which forces you to write the " (c "None") " case. " (c "expect") " is the \"I've already checked, let me proceed\" shortcut, and the required message is the receipt.")
  (h2 "Arithmetic that can't answer")
  (p "Overflow is the same story. The ordinary " (c "*") " traps if it overflows; when you'd rather " (em "handle") " an overflow than crash, " (c "Int64.checked-mul") " (and " (c "checked-add") ") returns an " (c "Option") ", " (c "None") " exactly when the result wouldn't fit.")
  (runnable
    (source (def (main)
  (match (Int64.checked-mul 9223372036854775807 2)
    ((Some x) x)
    ((None _) -1)))))
  (p "That's " (c "Int64") "'s largest value times 2, which can't fit, so you get the " (c "None") " arm.")
  (h2 "Chaining fallible steps: the " (c "?") " operator")
  (p "Match on one " (c "Option") " and you write two arms. Chain several (add two checked results, each of which might overflow) and the nested matches pile up, burying the happy path. The " (c "?") " operator (written " (c "(try …)") ") collapses that: on a " (c "Some") " it unwraps the value and carries on; on a " (c "None") " it " (em "short-circuits") ", making the whole function's result that " (c "None") ". Here two checked-adds both succeed, so " (c "x") " and " (c "y") " unwrap and the function returns " (result (of "try-some") (: (Some 84) (Option Int64))) ":")
  (runnable
    (id "try-some")
    (source (def (main)
  (let ((x (try (Int64.checked-add 20 22))))
    (let ((y (try (Int64.checked-add 40 2))))
      (Some (+ x y)))))))
  (p "No match arms, no nesting, just the happy path, top to bottom. And when a step " (em "does") " fail, the short-circuit takes over: make the first add overflow and its " (c "None") " becomes the function's answer immediately, so the second " (c "try") " and the body never run:")
  (runnable
    (id "try-none")
    (source (def (main)
  (let ((x (try (Int64.checked-add Int64.max 1))))
    (let ((y (try (Int64.checked-add 40 2))))
      (Some (+ x y)))))))
  (p "The overflowing add is " (c "None") ", so " (c "main") " is " (result (of "try-none") (: (None unit) (Option Int64))) ". The enclosing function must itself return the matching kind (an " (c "Option") " here, or a " (c "Result") "): " (c "?") " needs a fallible boundary to short-circuit " (em "to") ", and it doesn't convert between " (c "Option") " and " (c "Result") ": the kinds have to line up.")
  (h2 "Matching on the value inside")
  (p "A pattern can look " (em "inside") " a variant, not just name it. Here the first arm only fires for exactly " (cdz (Some 0)) "; a different " (c "Some") " falls through to the binding arm.")
  (runnable
    (id "describe-some0")
    (source (def (describe o)
  (match o
    ((Some 0) 100)
    ((Some x) x)
    ((None _) -1)))
(def (main) (describe (Some 0)))))
  (p (cdz (Some 0)) " matches the literal-" (c "0") " arm, so this is " (result (of "describe-some0") 100) ". Feed it " (cdz (Some 7)) " instead and the second arm binds " (c "x") " and returns " (c "7") "; " (cdz (None unit)) " takes the last.")
  (h2 "Failing with a reason: " (c "Result"))
  (p "An " (c "Option") " says " (em "whether") " there's an answer; sometimes you also want to say " (em "why") " there isn't. " (c "Result") " is the sum for that: " (cdz (Ok value)) " when it worked, " (cdz (Err e)) " carrying a reason when it didn't, and you take it apart with " (c "match") " exactly like an " (c "Option") ". Here " (c "safe-div") " reports the offending divisor on failure:")
  (runnable
    (source (def (safe-div a b)
  (if (= b 0) (Err b) (Ok (/ a b))))
(def (main)
  (match (safe-div 20 4)
    ((Ok q) q)
    ((Err e) -1)))))
  (p "This takes the " (c "Ok") " arm for " (c "20 / 4 = 5") ". Change the " (c "4") " to " (c "0") " and Run: the " (c "Err") " arm fires instead, and " (c "e") " is bound to the reason (here the divisor, " (c "0") "): the same exhaustive " (c "match") ", now with a payload that explains the failure.")
  (h2 "Your turn")
  (exercise
    (id "errors:1")
    (prompt (c "check") " returns " (cdz (Err 8)) " for this input. Finish the " (c "Err") " arm to hand back the reason it carries, so the result is " (c "8") ".")
    (starter (def (check n)
  (if (= n 0) (Ok n) (Err n)))
(def (main)
  (match (check 8)
    ((Ok v) v)
    ((Err e) ?))))
    (solution (def (check n)
  (if (= n 0) (Ok n) (Err n)))
(def (main)
  (match (check 8)
    ((Ok v) v)
    ((Err e) e))))
    (expected "8")
    (hint "The " (c "Err") " arm binds its payload to " (c "e") ", so return that binding to surface the reason: just " (c "e") "."))
  (exercise
    (id "errors:2")
    (prompt (c "take-from") " subtracts " (c "n") " from a stock of " (c "stock") ", but only when there's enough; asking for more than you have has no answer. Fill the hole so the \"not enough\" branch " (em "returns absence") ". Here the stock is " (c "3") " and the request is " (c "10") ", so that branch fires and the " (c "None") " arm hands back " (c "-1") ".")
    (starter (def (take-from stock n)
  (if (< stock n) ? (Some (- stock n))))
(def (main)
  (match (take-from 3 10)
    ((Some left) left)
    ((None _) -1))))
    (solution (def (take-from stock n)
  (if (< stock n) (None unit) (Some (- stock n))))
(def (main)
  (match (take-from 3 10)
    ((Some left) left)
    ((None _) -1))))
    (expected "-1")
    (hint "The " (c "Some") " branch already carries a value; the empty branch carries nothing, which you write as " (cdz (None unit)) ", the same " (c "None") " the " (c "match") " below is waiting for."))
  (p (c "Option") ", " (c "Result") ", and " (c "?") " all answer the same question, what happens when a step might not deliver, by making the outcome a " (em "value the caller must handle") ". The next chapter turns that inside out: with " (em "effects &amp; handlers") ", a function " (em "performs") " an operation and lets whoever runs it decide what it means, so the caller answers instead of just inspecting a returned value. It's the pivot from the fundamentals into what makes Cadenza its own language."))
