// @generated DO NOT EDIT — rendered from the chapter's .sexp by the guide sexp→TSX codegen (chapterModel.ts).
import { C, H1, H2, Lede, P } from "../../components/Prose.tsx";
import { AppLink, Ch } from "../../components/ChapterLink.tsx";

export default function ExampleApps() {
  return (
    <article>
      <H1>Example applications</H1>
      <Lede>Everything you've learned isn't a toy language, since it compiles and runs in this very browser. These are full, interactive applications built in Cadenza, each showing a different part of the language doing real work. Open any of them; they're the differentiators you just met, running.</Lede>
      <P>Each app below is a live page, so click through and use it. This gallery is the curated index: what each one is, which Cadenza features it showcases, and where in the guide those features are taught. The set is growing, so expect more over time.</P>
      <H2>The playground</H2>
      <P>The <AppLink to="/playground">playground</AppLink> is the whole language in one editor: write a program, run it, and peek at the WebAssembly <em>and</em> Rust it compiles to, the same source targeting two backends, which is the point of a compiler that treats code as data. It ships a dropdown of worked example programs, from an AST interpreter to a Collatz walk, function composition, a memoized Fibonacci, exact-rational arithmetic, set algebra, an RPN stack machine, a stateful <Ch to="/effects">effect handler</Ch>, a lazy <Ch to="/iterators">iterator pipeline</Ch> (filter → map → fold), and more, each a small showcase of recursion, sum types, closures, effects, lazy sequences, or the collections. Two stand out: a Rule 110 cellular automaton, a Turing-complete system in a handful of lines; and a <em>code-as-data</em> example that quotes a program into an AST, splices a computed value into it, and <C>eval</C>s the result, Cadenza building and running Cadenza from within itself. It's where <Ch to="/metaprogramming">metaprogramming</Ch> and the target-neutral value model become tangible. (The <Ch to="/using-the-playground">playground chapter</Ch> tours its features in depth.)</P>
      <H2>The calculator</H2>
      <P>The <AppLink to="/calculator">calculator</AppLink> is a focused prompt for exact arithmetic, with the <Ch to="/rationals">exact fractions</Ch> and <Ch to="/units">units of measure</Ch> chapters made interactive. Fractions stay fractions (<C>1 / 3 + 1 / 3 + 1 / 3</C> is <C>1</C>, not <C>0.9999…</C>), dimensioned quantities carry their units, and big integers never overflow. Reach for it when you want a number now and don't want a floating-point surprise.</P>
      <H2>The CAD preview</H2>
      <P>The <AppLink to="/cad">CAD preview</AppLink> renders a 3D solid modelled in Cadenza, a shape built from <em>exact rational coordinates</em> in real <Ch to="/units">units</Ch> (the exact-CAD worked example from the Units chapter, made visible). Orbit and inspect it. The model stays exact where it matters; floating point appears only at the very end, in the mesh the renderer draws, so it's exact where it counts and approximate only at the geometry kernel.</P>
      <H2>The notebook</H2>
      <P>The <AppLink to="/notebook">notebook</AppLink> is a live, parametric document: prose interleaved with runnable Cadenza code cells and interactive widgets. Drag a slider and every dependent cell recomputes, so a compound-interest model or a data table stays live. It's the reactive, run-the-outside-world side of the language, the same "perform an operation, let the surrounding context decide what it means" idea you met in <Ch to="/effects">effects &amp; handlers</Ch>, turned into a document. A cell that computes a dimensioned quantity displays it in the same concise surface as the <Ch to="/units">units of measure</Ch> chapter, <C>5.0 meter</C> rather than the raw value form, so a table of results reads like a table of measurements.</P>
      <H2>Music theory</H2>
      <P>The <AppLink to="/music">music page</AppLink> builds a short chord progression the way a theory textbook would describe it, from intervals measured as exact fractions of an octave. A perfect fifth is seven twelfths of an octave, not an approximation in cents, so a chord transposed to any key stays exactly itself. From those rational intervals it stacks chords, lays out a I-V-vi-IV progression, and lowers the whole piece to a stream of timed MIDI events. The result is one you can run: every note that switches on is proven to switch off again, so the piece can be transposed, looped, or remapped and never hangs a key. The page ends where live coders start, writing a rhythm as a Euclidean pattern and rendering it live, so the same event stream that carries a composed piece also carries an improvised one.</P>
      <H2>The platform explorer</H2>
      <P>The <AppLink to="/explorer">platform explorer</AppLink> is a multi-file workspace: instead of one buffer it holds a set of files, one marked the <em>entry</em> (the program that runs) and the rest modules it can <C>import</C>. Edit any file, Run, and the whole set compiles together in the browser, the same link-merge that lets the guide's showcase pages preload a library, opened up so the modules are yours to write. It's the smallest look at Cadenza as a <em>platform</em>: programs composed from several content-addressed pieces rather than a single snippet. That composition is the same one the <Ch to="/platform-overview">platform pillar</Ch> builds on, where an agent is a reducer split across files, its events in one and the fold that consumes them in another, so the boundary you can see in the explorer is the boundary between an agent's history and its behavior.</P>
      <P>All six run the identical in-browser compiler that powers this guide's inline examples, so geometry, tables, charts, and values are just what Cadenza's results look like when an app renders them instead of printing a single number.</P>
      <P>That's the tour: the ideas, and the apps that prove them. To recap what you've learned and find where to go from here, head to <Ch to="/whats-next">Where to go next</Ch>.</P>
    </article>
  );
}
