(chapter
  (slug "lists")
  (title "Lists")
  (pillar "language")
  (section "Fundamentals")
  (blurb "Ordered, immutable sequences of values.")
  (lede "Ordered, immutable sequences, built and measured on the value heap.")
  (p "A list is written with " (c "#list") ". Lists are " (em "persistent") ": operations like " (c "List.push") " and " (c "List.concat") " return a new list and leave the original untouched. Ask a list its length with " (c "List.len") ".")
  (runnable
    (source (List.len #list(1 2 3))))
  (h2 "Building lists")
  (p (c "List.push") " adds an element to the end; " (c "List.concat") " joins two lists. Each returns a whole new list, so Run this and you'll see the result, " (cdz "#list(1 2 3)") ", not just a count:")
  (runnable
    (source (List.push #list(1 2) 3)))
  (p (c "List.prepend") " is the mirror of " (c "push") ": it adds an element to the " (em "front") " rather than the end. It takes the list first and the new element second, the same receiver-first order as " (c "push") ", so prepending " (c "1") " to " (cdz "#list(2 3)") " gives " (cdz "#list(1 2 3)") ", the new element leading:")
  (runnable
    (source (List.prepend #list(2 3) 1)))
  (p (c "List.concat") " joins two lists into a new one, so Run this and you see the whole joined list, " (cdz "#list(1 2 3 4 5)") ", the two inputs laid end to end:")
  (runnable
    (source (List.concat #list(1 2) #list(3 4 5))))
  (h2 "Reaching in safely")
  (p (c "List.at") " gets the element at an index. But what if the index is out of range? Rather than crash, " (c "List.at") " returns an " (c "Option") ", either " (cdz "(Some x)") " when the element exists or " (cdz "(None unit)") " when it doesn't, which you take apart with " (c "match") ". Here index 1 exists, so you get its value, " (c "20") ":")
  (runnable
    (source (def (main)
  (match (List.at #list(10 20 30) 1)
    ((Some x) x)
    ((None _) -1)))))
  (p "Change the index " (c "1") " to " (c "9") " and Run: the lookup misses, the " (c "None") " arm fires, and you get " (c "-1") ", no crash, just a value that says \"nothing there\".")
  (why (tenet "Partiality is data, not a trap") "Reading past the end of a list, looking up a missing key, decoding bad text: in Cadenza these yield an " (c "Option") " (or a result), never a crash or a garbage value. Absence is an ordinary value your program " (em "handles") ". If you ever do want \"crash on missing\", that's a single, explicit operation that demands a message, so the one place a program turns absence into a halt is visible right where it happens, not hidden inside every accessor.")
  (h2 "Updating a slot without touching the original")
  (p (c "List.update") " takes a list, an index, and a new value, and hands back a list with that one slot changed. The word \"update\" is doing something specific here: it does " (em "not") " reach into your list and overwrite a slot, since nothing in Cadenza does that. It builds a " (em "new") " list. The old one is still exactly what it was. This snippet proves it: bind a list, make a bumped version, then read the original back:")
  (runnable
    (source (let ((original #list(10 20 30))
      (bumped   (List.update original 1 99)))
  (match (List.at original 1)
    ((Some x) x)
    ((None _) 0)))))
  (p "The answer is " (c "20") ", not " (c "99") ": " (c "original") " never changed. The " (c "99") " lives only in " (c "bumped") ". Swap " (c "original") " for " (c "bumped") " in the " (c "List.at") " line and Run again to see " (c "99") ". Two lists, sharing most of their structure internally, each with its own value.")
  (p "Return the updated list itself and you can see the change in place, one slot different, " (cdz "#list(10 99 30)") ", and the input " (cdz "#list(10 20 30)") " still intact wherever else it's held:")
  (runnable
    (source (List.update #list(10 20 30) 1 99)))
  (why (tenet "Immutable, persistent values") "Every value in Cadenza is immutable; an \"update\" always produces a fresh value and leaves every existing reference untouched. That's not just tidiness; it's what makes the whole system tractable. Because values can never form a cycle, the runtime reclaims memory by simple reference counting, no garbage collector needed. Because a list you handed to a function can't change underneath you, there's a whole class of aliasing bug that simply cannot happen. And whether a list is stored as a flat array or a balanced tree is the runtime's business, not yours: one type, many representations, sharing structure between versions so " (c "update") " doesn't copy the whole thing.")
  (h2 "Lists through functions")
  (p "A function can take a list and compute over it, and the element type rides along, so " (c "count") " works on a list of any element type:")
  (runnable
    (source (def (count xs) (List.len xs))
(def (main) (count #list(10 20 30 40)))))
  (p "Four elements in, so " (c "4") " out, and you never wrote the element type: " (c "count") " works on a list of anything, because " (c "List.len") " doesn't care what the elements are.")
  (p "To visit " (em "every") " element, match the list by shape. A " (c "match") " on a list has two cases: the empty list " (cdz "#list()") ", and a non-empty one " (cdz "#list(x .. rest)") ", which binds the first element to " (c "x") " and the " (em "rest") " of the list to " (c "rest") ". Recurse on " (c "rest") " and you fold over the whole list. Here " (c "sum") " adds the elements:")
  (runnable
    (source (def (sum xs)
  (match xs
    (#list() 0)
    (#list(x .. rest) (+ x (sum rest)))))
(def (main) (sum #list(10 20 30)))))
  (p "The empty case is the base case, " (c "0") ", the sum of nothing, and each step peels off one element and sums the rest, so " (cdz "#list(10 20 30)") " is " (c "10 + (20 + (30 + 0))") " = " (c "60") ". You didn't declare the element type either: it flows from the " (c "+") ", so " (c "sum") " is inferred over a list of " (c "Int64") ".")
  (p "The " (c "rest") " after " (c "..") " is special: it binds the " (em "whole tail") " as one sublist, so it must be a plain name (or " (c "_") "), not another pattern. You can destructure the leading elements as deeply as you like, but you can't nest a pattern in the rest slot itself. This tries to, and the compiler stops you:")
  (note "This one is " (strong "meant to be rejected") ": " (cdz "#list(b .. r)") " in the rest position asks to match the tail against a shape, but the rest binder only ever names the tail. The fix is to bind it, then match it.")
  (runnable
    (source (match #list(1 2 3)
  (#list(a .. #list(b .. r)) a)
  (_ 0)))
    (expect "error"))
  (p "To reach the second element, bind the tail to a name and match " (em "that") ", a two-step you'll use whenever you need more than the head: peel one layer, then look again. Here " (c "rest") " is " (c "#list(20 30)") ", and matching it pulls out " (c "20") ":")
  (runnable
    (source (match #list(10 20 30)
  (#list(a .. rest)
   (match rest
     (#list(b .. r) b)
     (#list() 0)))
  (#list() 0))))
  (p "A leading element can still be any pattern, so " (cdz "#list(#tuple(x y) .. rest)") " is fine, only the rest slot is name-only. Reach for the tail by name and match it again when you need to see inside.")
  (p "A list holds every element at once. Sometimes you want the elements without ever building the whole sequence, even an endless one. That's an " (em "iterator") ", next.")
  (h2 "Your turn")
  (exercise
    (id "lists:1")
    (prompt "Use " (c "List.update") " to change index " (c "0") " of " (cdz "#list(5 6 7)") " to " (c "50") ", then read that slot back with " (c "List.at") ". The answer is " (c "50") ".")
    (starter (match (List.at (List.update #list(5 6 7) 0 ?) 0)
  ((Some x) x)
  ((None _) 0)))
    (solution (match (List.at (List.update #list(5 6 7) 0 50) 0)
  ((Some x) x)
  ((None _) 0)))
    (expected "50")
    (hint (c "List.update") " takes the list, the index (" (c "0") "), and the new value (" (c "50") "), in that order. Then " (c "List.at … 0") " reads the slot you just set."))
  (exercise
    (id "lists:2")
    (prompt "Add the single element " (c "99") " to the end of " (cdz "#list(10 20 30)") ", then ask its length, so a three-element list grows to " (c "4") ". Which operation appends " (em "one element") ", " (c "push") " or " (c "concat") "? Fill in the blank.")
    (starter (List.len (List.? #list(10 20 30) 99)))
    (solution (List.len (List.push #list(10 20 30) 99)))
    (expected "4")
    (hint (c "push") " adds a single element to the end; " (c "concat") " joins two " (em "lists") " (and would reject the bare " (c "99") "). Pushing one element onto three gives length " (c "4") "."))
  (exercise
    (id "lists:3")
    (prompt "Here's the same fold shape as " (c "sum") ", but " (em "multiplying") ", and this time the recursive step is written for you; the " (em "empty") " case is the hole. What should " (c "prod") " of the empty list be, so that folding " (c "#list(1 2 3 4)") " gives " (c "24") "? Fill in the base case.")
    (starter (def (prod xs)
  (match xs
    (#list() ?)
    (#list(x .. rest) (* x (prod rest)))))
(def (main) (prod #list(1 2 3 4))))
    (solution (def (prod xs)
  (match xs
    (#list() 1)
    (#list(x .. rest) (* x (prod rest)))))
(def (main) (prod #list(1 2 3 4))))
    (expected "24")
    (hint "The base case has to be the value that leaves a product unchanged, so multiplying by it does nothing. For " (c "+") " that identity was " (c "0") "; for " (c "*") " it's " (c "1") ". (Try " (c "0") " and watch the whole product collapse to " (c "0") ".)"))
  (exercise
    (id "lists:4")
    (prompt "Add " (c "0") " to the " (em "front") " of " (cdz "#list(1 2 3)") ", then read index " (c "0") " back with " (c "List.at") " for the answer " (c "0") ". Which operation adds to the front, " (c "push") " or " (c "prepend") "? Fill in the blank.")
    (starter (match (List.at (List.? #list(1 2 3) 0) 0)
  ((Some x) x)
  ((None _) -1)))
    (solution (match (List.at (List.prepend #list(1 2 3) 0) 0)
  ((Some x) x)
  ((None _) -1)))
    (expected "0")
    (hint (c "push") " adds to the end, so index " (c "0") " would stay " (c "1") "; " (c "prepend") " adds to the front, so the new " (c "0") " becomes the element at index " (c "0") ".")))
