(chapter
  (slug "opaque-types")
  (title "Opaque types")
  (pillar "language")
  (section "What makes Cadenza different")
  (blurb "Export a type's name but keep its constructor private: values flow only through the module's functions, so an invariant can't be broken.")
  (lede "How do you guarantee a value is " (em "always") " valid, so a percentage is never above 100 and a list is never empty, no matter what code touches it? Make the type " (em "opaque") " by having a module export the type's " (em "name") " while keeping its " (em "constructor") " private, which is an abstract data type. Code elsewhere can hold and pass its values and call the module's functions on them, but it can't build or take one apart, so an invariant established when the value is made holds " (em "everywhere") ", forever.")
  (p "Exporting a type and exporting its " (em "constructors") " are two independent decisions. A bare " (cdz (export Percent)) " publishes only the type's " (em "handle") ", enough to name it but not to construct it. Adding " (cdz (export Percent.*)) " (or naming a specific variant) publishes the constructors too, making the type " (em "concrete") ". So opacity is the " (em "default") " of exporting a type; concreteness is opt-in. Withholding the constructor is what makes a type opaque.")
  (h2 "A validated type: Percent")
  (p "Here's where it earns its keep. A " (em "percentage") " should always be between 0 and 100, since a discount of 150% or −20% is nonsense. Model it as an opaque " (c "Percent") " whose only maker, " (c "percent") ", " (em "validates") ": it clamps anything out of range into " (c "[0, 100]") ". Feed it a wild " (c "150") " and what comes back is a legitimate " (result (of "percent-clamp") 100) ":")
  (runnable
    (id "percent-clamp")
    (source (type Percent (Pct Int64))
(def (percent (: n Int64))
  (if (< n 0) (Percent.Pct 0)
    (if (> n 100) (Percent.Pct 100) (Percent.Pct n))))
(def (rate (: p Percent)) (let (((Percent.Pct v) p)) v))
(def (main) (rate (percent 150)))))
  (p "What this buys you isn't the clamping itself but what every " (em "downstream") " function can now assume. Because a " (c "Percent") " can only come from " (c "percent") ", any code that receives one " (em "knows") " it's in range, with no re-checking. Here " (c "apply-discount") " takes a price and a " (c "Percent") " and subtracts that fraction, so a 25% discount off 200 is 150:")
  (runnable
    (source (type Percent (Pct Int64))
(def (percent (: n Int64))
  (if (< n 0) (Percent.Pct 0)
    (if (> n 100) (Percent.Pct 100) (Percent.Pct n))))
(def (rate (: p Percent)) (let (((Percent.Pct v) p)) v))
(def (apply-discount (: price Int64) (: p Percent))
  (- price (/ (* price (rate p)) 100)))
(def (main) (apply-discount 200 (percent 25)))))
  (p "And the invariant is what makes " (c "apply-discount") " " (em "safe") ": a discount can never exceed 100%, so a price can never go negative. Try to discount by a nonsensical 150% and the " (c "percent") " maker has already clamped it to 100%, so the worst case is a free item (price " (result (of "discount-clamped") 0) "), never a negative one:")
  (runnable
    (source (type Percent (Pct Int64))
(def (percent (: n Int64))
  (if (< n 0) (Percent.Pct 0)
    (if (> n 100) (Percent.Pct 100) (Percent.Pct n))))
(def (rate (: p Percent)) (let (((Percent.Pct v) p)) v))
(def (apply-discount (: price Int64) (: p Percent))
  (- price (/ (* price (rate p)) 100)))
(def (main) (apply-discount 200 (percent 150))))
    (id "discount-clamped"))
  (p (c "apply-discount") " never validates its " (c "Percent") " because it doesn't have to. The type is a " (em "proof") " the value was checked once, at the only place it could be made. That's the difference between a bare " (c "Int64") " (which every consumer must defensively re-check) and an opaque " (c "Percent") " (checked once, trusted everywhere).")
  (h2 "The boundary is what enforces it")
  (p "These run in one file, where the constructor " (c "Pct") " is visible, so you can see the whole mechanism. The " (em "enforcement") " lives at the module boundary. When " (c "Percent") " is its own module exporting only its handle plus " (c "percent") ", " (c "rate") ", and " (c "apply-discount") ", another module may name " (c "Percent") ", hold one, and call those functions, but it may " (em "not") " reach the constructor to forge an out-of-range one. An attempt is a compile error:")
  (note (c "// module \"percent\" does (export Percent)  — the handle only, Pct stays private") " " (br) " " (c "// another module tries: (Percent.Pct 150)   — a 150% \"percentage\", skipping the validator") " " (br) " " (c "cdz") " reports " (c "CDZ0214") ": the constructor " (c "Pct") " is withheld, so a " (c "Percent") " can be built only through the module's exported functions.")
  (p "The same wall stops an importer from taking a value apart, since it can't match on " (c "Pct") ", strip it, or structurally compare two " (c "Percent") "s to reverse-engineer the representation. Every " (c "Percent") " that exists anywhere in the program came from " (c "percent") " and is therefore in range: the invariant is not a convention the caller must remember, it's a fact the type system guarantees. (The guide runs one module at a time, so the runnables above show the mechanism from " (em "inside") "; the " (c "CDZ0214") " rejection is what the compiler prints when the forge is attempted from " (em "outside") ".)")
  (why (tenet "Hide the representation, and the invariant can't be broken") "Data hiding here isn't a convention or a naming trick but something checked by the type system. Because a type's handle and its constructors export independently, a module can publish a fully usable type whose " (em "representation") " is genuinely unreachable: the only values that exist are the ones its own functions made. So an invariant established in a smart constructor, whether in range, non-empty, sorted, normalized, or validated, holds for " (em "every") " value of that type, everywhere, with zero trust in callers. Cadenza leans on this at the highest stakes: its machine-checked proof kernel makes a " (c "Thm") " (theorem) an opaque type whose constructor is private, so the " (em "only") " way to obtain a " (c "Thm") " is to call one of the kernel's sound inference rules, so a bug in a tactic literally cannot forge a false theorem, because it cannot construct a " (c "Thm") " at all. Same mechanism as " (c "Percent") ", protecting soundness itself.")
  (h2 "Your turn")
  (exercise
    (id "opaque-types:1")
    (prompt "The validator clamps out-of-range input into " (c "[0, 100]") ". Fill an input that's " (em "too large") " so that reading the rate back gives " (c "100") ", the ceiling the invariant enforces.")
    (starter (type Percent (Pct Int64))
(def (percent (: n Int64))
  (if (< n 0) (Percent.Pct 0)
    (if (> n 100) (Percent.Pct 100) (Percent.Pct n))))
(def (rate (: p Percent)) (let (((Percent.Pct v) p)) v))
(def (main) (rate (percent ?))))
    (solution (type Percent (Pct Int64))
(def (percent (: n Int64))
  (if (< n 0) (Percent.Pct 0)
    (if (> n 100) (Percent.Pct 100) (Percent.Pct n))))
(def (rate (: p Percent)) (let (((Percent.Pct v) p)) v))
(def (main) (rate (percent 250))))
    (expected "100")
    (hint "Any value above " (c "100") " clamps to " (c "100") ", so " (c "250") " does too. The maker is the one place the ceiling is enforced, so " (c "rate") " can never read more than " (c "100") "."))
  (exercise
    (id "opaque-types:2")
    (prompt "Because a " (c "Percent") " is always in range, " (c "apply-discount") " is safe. Fill the discount so that 300 becomes 210, a 30% discount off 300.")
    (starter (type Percent (Pct Int64))
(def (percent (: n Int64))
  (if (< n 0) (Percent.Pct 0)
    (if (> n 100) (Percent.Pct 100) (Percent.Pct n))))
(def (rate (: p Percent)) (let (((Percent.Pct v) p)) v))
(def (apply-discount (: price Int64) (: p Percent))
  (- price (/ (* price (rate p)) 100)))
(def (main) (apply-discount 300 (percent ?))))
    (solution (type Percent (Pct Int64))
(def (percent (: n Int64))
  (if (< n 0) (Percent.Pct 0)
    (if (> n 100) (Percent.Pct 100) (Percent.Pct n))))
(def (rate (: p Percent)) (let (((Percent.Pct v) p)) v))
(def (apply-discount (: price Int64) (: p Percent))
  (- price (/ (* price (rate p)) 100)))
(def (main) (apply-discount 300 (percent 30))))
    (expected "210")
    (hint "30% of 300 is 90, and 300 − 90 is 210, so the discount is " (c "30") ". Because the type guarantees the rate is at most 100, the discounted price is never negative.")))
