(chapter
  (slug "ordering")
  (title "Comparison & ordering")
  (pillar "language")
  (section "Fundamentals")
  (blurb "Comparisons, and the three-way shape of a total order.")
  (lede "Asking how two values relate, and the shape a total order takes.")
  (h2 "The comparison operators")
  (p "The six comparisons, " (c "=") ", " (c "&lt;") ", " (c "&lt;=") ", " (c "&gt;") ", " (c "&gt;=") ", and " (c "not") " for negation, each produce a " (c "Bool") ", so evaluating one gives you " (c "true") " or " (c "false") " directly:")
  (runnable
    (source (<= 5 5)))
  (p "Combine them with " (c "and") " / " (c "or") " to express a range check, as in \"is 5 between 1 and 10?\", which is again just a " (c "Bool") ":")
  (runnable
    (source (and (>= 5 1) (<= 5 10))))
  (h2 "Building on comparison")
  (p "Small decisions built from comparisons are a large part of everyday code. Here is " (c "min") ", and a " (c "clamp") " that keeps a value within a range:")
  (runnable
    (source (def (min a b) (if (< a b) a b))
(def (main) (min 8 3))))
  (runnable
    (source (def (clamp lo hi x)
  (if (< x lo) lo
      (if (> x hi) hi x)))
(def (main) (clamp 0 10 42))))
  (p (cdz (min 8 3)) " is " (c "3") ", the smaller of the two. And " (cdz (clamp 0 10 42)) " is " (c "10") ": 42 is past the upper bound, so " (c "clamp") " pulls it back to " (c "10") ", and feeding it a value already inside " (c "0") "–" (c "10") " gives that value back unchanged.")
  (h2 "Three answers, not two")
  (p "A single " (c "&lt;") " only tells you yes-or-no. But comparing two values really has " (em "three") " possible answers: less, equal, or greater. You " (em "could") " encode that as " (c "-1") " / " (c "0") " / " (c "1") " and nest a couple of " (c "if") "s:")
  (runnable
    (source (def (cmp a b)
  (if (< a b) -1
      (if (= a b) 0 1)))
(def (main) (cmp 3 9))))
  (p "That works, but those numbers are a convention you have to remember, and nothing stops a caller from forgetting the " (c "equal") " case or inventing a meaningless " (c "2") ". Cadenza gives you the three answers as a " (em "value") " instead.")
  (h2 "The " (c "Ordering") " value")
  (p (c "Ordering.of") " takes two values and returns an " (c "Ordering") ", a sum with exactly three variants, " (c "Less") ", " (c "Equal") ", and " (c "Greater") ". The value itself is the answer, a named case instead of a magic number. Here " (c "3") " is less than " (c "9") ", so you get " (c "Less") ":")
  (runnable
    (source (Ordering.of 3 9)))
  (p "You read an " (c "Ordering") " apart with " (c "match") " to act on each case, the same way you would any sum. Because it's a closed sum, the compiler holds you to all three variants: drop the " (c "Greater") " arm and Run, and instead of a value you get a compile-time error, " (c "non-exhaustive match: pattern `Greater` not covered") ":")
  (note "This one is " (strong "meant to be rejected") ". The point is that a forgotten case is caught when you write it, not discovered as a wrong answer in production.")
  (runnable
    (source (match (Ordering.of 3 9)
  ((Less _)  "less")
  ((Equal _) "equal")))
    (expect "error"))
  (p (c "Ordering.of") " is " (em "generic") ", so it works on any two values of the same type, not just numbers. Text compares in dictionary order, so " (c "\"apple\"") " comes before " (c "\"banana\"") ", giving " (c "Less") " again:")
  (runnable
    (source (Ordering.of "apple" "banana")))
  (h2 "Ordered types can be keys")
  (p (c "Bytes") " is ordered too, lexicographically over its " (em "unsigned") " byte values, the same way Text compares in dictionary order. So " (cdz (Bytes.of #list(1 2))) " comes before " (cdz (Bytes.of #list(1 3))) ", decided at the first byte that differs:")
  (runnable
    (source (< (Bytes.of #list(1 2)) (Bytes.of #list(1 3)))))
  (p "Watch the " (em "unsigned") " part: a byte holding " (c "128") " is " (em "greater") " than one holding " (c "127") ", not less, because the bytes are compared as 0–255, never as signed numbers:")
  (runnable
    (source (> (Bytes.of #list(128)) (Bytes.of #list(127)))))
  (p "A " (c "Map") " key or a " (c "Set") " element needs two things: the collection compares keys for " (em "equality") " to find an entry, and it uses a " (em "total order") " to enumerate its contents in a stable, canonical sequence (so " (c "Map.to-list") " always yields the same order). " (c "Bytes") " now has both, so a byte string can be a key directly, and iterating the collection reads back in sorted key order. Here a " (c "Map") " keyed by " (c "Bytes") " finds its entry:")
  (runnable
    (source (do (def (main)
      (Map.lookup
        (Map.insert (Map.empty) (Bytes.of #list(1 2)) 42)
        (Bytes.of #list(1 2))))
    (export main))))
  (p "The lookup returns " (cdz (Some 42)) ": the second " (c "Bytes") " value compares equal to the key that was inserted, so the " (c "Map") " finds it. A value you can order is a value you can organize.")
  (h2 "What can't be a key: a function")
  (p "The flip side of that rule draws a sharp line. Keying needs equality and a total order, and a " (em "function") " has neither: two closures can compute the same results yet be different values, and there's no canonical way to compare or order them. So a function can't be a " (c "Map") " key or a " (c "Set") " element, and the compiler says so rather than inventing an answer. A " (c "Set") " of functions is rejected:")
  (runnable
    (source (do (def (main)
      (Set.len (Set.of #list((fn (x) (+ x 1))))))
    (export main)))
    (expect "error"))
  (p "The error is " (c "CDZ0216") ": " (em "a value of function type … cannot be a map/set key") ", since a function " (em "has no canonical identity, so it is neither equatable nor orderable") ". The check walks the whole key, not just its outer shape, so a function buried inside a tuple key or a list element is caught the same way. The fix the message points to is to key by a " (em "value") " instead: a field the closure captures, an id you assign, a tag, anything with the equality and order that a function lacks.")
  (why (tenet "A total order is a three-way answer") "Returning " (c "-1 / 0 / 1") " works, but it leans on a convention and can't be enforced. Cadenza's " (c "Ordering.of") " yields the " (c "Ordering") " sum of " (em "less") ", " (em "equal") ", and " (em "greater") ", so the three cases have names and the compiler checks a caller handled " (em "all") " of them (you saw the missing-arm error above). There's no fourth nonsense value to guard against: what would " (c "2") ", or " (c "true,true") ", even mean? And it's one order for every type, whether numbers, text, or the rest, so sorting and lookup behave the same way everywhere, observed identically by every consumer.")
  (h2 "Your turn")
  (exercise
    (id "ordering:1")
    (prompt "Finish the predicate " (c "outside") " so it returns " (c "true") " when " (c "x") " is " (em "below 0 or above 10") ", and " (c "false") " in between. With " (cdz (outside 15)) " the answer is " (c "true") ".")
    (starter (def (outside x)
  (or (< x 0) ?))
(def (main) (outside 15)))
    (solution (def (outside x)
  (or (< x 0) (> x 10)))
(def (main) (outside 15)))
    (expected "true")
    (hint "The two ways to be outside are joined with " (c "or") "; the second is \"above 10\", namely " (cdz (> x 10)) ". " (c "15") " is above 10, so the result is " (c "true") "."))
  (exercise
    (id "ordering:2")
    (prompt "Write " (c "max") " using " (c "Ordering.of") " and " (c "match") ", picking " (c "a") " when it's greater or equal, and " (c "b") " when " (c "a") " is less. " (cdz (max 8 3)) " should give " (c "8") ".")
    (starter (def (max a b)
  (match (Ordering.of a b)
    ((Less _)    ?)
    ((Equal _)   a)
    ((Greater _) a)))
(def (main) (max 8 3)))
    (solution (def (max a b)
  (match (Ordering.of a b)
    ((Less _)    b)
    ((Equal _)   a)
    ((Greater _) a)))
(def (main) (max 8 3)))
    (expected "8")
    (hint "The " (c "Less") " arm is the one case where " (c "a") " is " (em "not") " the maximum, so return " (c "b") " there.")))
