(chapter
  (slug "pattern-matching")
  (title "Pattern matching")
  (pillar "language")
  (section "Fundamentals")
  (blurb "Deciding by shape; sum types and exhaustiveness.")
  (lede "Deciding by shape, and why " (c "match") " is a set of patterns the compiler can check, not a chain of " (c "if") "s.")
  (h2 "Matching literals")
  (p "A " (c "match") " chooses an arm by matching the scrutinee against each arm's " (em "pattern") ". The last arm here uses " (c "_") ", the wildcard, which matches anything:")
  (runnable
    (source (match 2
  (1 10)
  (2 20)
  (_ 0))))
  (p "Change the " (c "2") " being matched to " (c "1") " or " (c "7") " and Run to see a different arm fire.")
  (p "Literals aren't just numbers, since you can match a " (c "String") " the same way, and this is the everyday shape for dispatching on a keyword or command name. Here " (c "known-op") " reports whether a name is one of the operations it recognises, answering " (c "false") " for everything else:")
  (runnable
    (source (def (known-op name)
  (match name
    ("add" true)
    ("sub" true)
    (_ false)))
(def (main) (known-op "sub"))))
  (p (c "\"sub\"") " takes the second arm, " (c "true") ". Change it to " (c "\"add\"") " or something unknown like " (c "\"mul\"") " and Run again. Note the answer is an honest " (c "Bool") ", not a stand-in number: a recognised name is " (c "true") ", anything else is " (c "false") ". (When a lookup needs to hand back a " (em "result") " that might not exist, you reach for " (c "Option") " rather than a magic value like " (c "-1") ", which is exactly what the next section builds.) The " (c "_") " arm isn't optional here: " (c "String") " (like " (c "Int64") ") has infinitely many values, so the compiler can't see that you've covered them all: leave the wildcard off and it declines with a non-exhaustive-match error, the same guarantee you'll meet with sums below.")
  (p "The same shape works for characters. A " (c "Char") " literal is written " (c "#\\a") " (the " (strong "Strings &amp; text") " chapter covers characters), and a " (c "match") " dispatches on one by its Unicode code point. Here " (c "is-vowel") " answers whether a character is a lowercase vowel:")
  (runnable
    (source (def (is-vowel c)
  (match c
    (#\a true)
    (#\e true)
    (#\i true)
    (#\o true)
    (#\u true)
    (_ false)))
(def (main) (is-vowel #\e))))
  (p (c "#\\e") " takes its arm, so the answer is " (c "true") ". Change it to a consonant like " (c "#\\z") " and the wildcard arm answers " (c "false") ". As with numbers and strings, the " (c "_") " arm is required, since " (c "Char") " has far too many values for the compiler to see them all listed.")
  (h2 "Sum types")
  (p "A sum type is a set of tagged variants. You declare it with " (c "type") ", build a value with one of its constructors, and take it apart by matching each variant. Here " (c "Opt") " is either " (c "Some") " carrying an " (c "Int64") ", or " (c "None") ". The " (cdz "(Some x)") " arm " (em "binds") " the payload to " (c "x") ":")
  (runnable
    (source (type Opt (Some Int64) (None unit))
(def (main)
  (match (Some 7)
    ((Some x) x)
    ((None _) 0)))))
  (p "Swap " (cdz "(Some 7)") " for " (cdz "(None unit)") " and Run to take the other arm, which returns " (c "0") ".")
  (h2 "The compiler checks you covered every case")
  (p "Exhaustiveness is what this buys you. Drop the " (c "None") " arm and the compiler " (em "refuses") " to compile, because it can see, from the type, that a case is unhandled:")
  (note "This one is " (strong "meant to be refused") ". Run it and read the status bar: " (c "non-exhaustive match") ", the missing variant named for you, before the program ever runs.")
  (runnable
    (source (type Opt (Some Int64) (None unit))
(def (main)
  (match (Some 7)
    ((Some x) x))))
    (expect "error"))
  (why (tenet "match is patterns, not predicates") "Many languages let a branch head be any boolean test. Cadenza deliberately doesn't: a " (c "match") " arm is always a " (em "pattern") ", whether a constructor that destructures, a literal, a binding, or " (c "_") ". Why refuse the more flexible option? Because a head that could be an arbitrary predicate quietly demotes the real question, " (em "\"did you handle every variant?\"") ", down to " (em "\"is there an else?\"") ". Keeping arms as patterns is what lets the compiler check exhaustiveness against the type, and turn a whole class of \"forgot a case\" bugs into compile errors. Value conditions still have a home; it's just " (c "if") ", not " (c "match") ".")
  (h2 "Guards: a pattern plus a condition")
  (p "When you do want to test a value, not just its shape, an arm can carry a " (em "guard") ": a pattern with an " (c "if") " condition. The arm fires only when the pattern matches " (em "and") " the guard holds. Here a number is classified by sign:")
  (runnable
    (source (def (sign n)
  (match n
    ((guard x (< x 0)) -1)
    (0 0)
    (_ 1)))
(def (main) (sign -8))))
  (p (cdz "(guard x (< x 0))") " binds the value to " (c "x") " and fires only when " (cdz "(< x 0)") ", so " (c "-8") " returns " (c "-1") "; " (c "0") " takes the literal arm, and everything else the wildcard. A guard is the bridge between \"match on shape\" and \"decide on value\", without turning the whole arm back into an arbitrary predicate.")
  (h2 "More than two variants")
  (p "Sums aren't limited to " (c "Some") "/" (c "None") ". A traffic light is a three-variant sum, and a " (c "match") " over it must cover all three (or the compiler complains):")
  (runnable
    (source (type Light (Red unit) (Yellow unit) (Green unit))
(def (wait l)
  (match l
    ((Red _) 30)
    ((Yellow _) 5)
    ((Green _) 0)))
(def (main) (wait (Red unit)))))
  (note "This is the typed cousin of the symbol dispatch from the Symbols chapter. A symbol tag is checked with " (c "=") " and any typo compiles; a sum's variants are checked by the compiler, so a forgotten or misspelled case is caught. Reach for a sum when the set of cases is fixed and worth enforcing.")
  (h2 "Matching a map by key")
  (p "A " (c "match") " can also look " (em "inside a collection") ". A map pattern, " (cdz "#map((= key binder) (.. rest))") ", fires when the map contains that key, binding the associated value to " (c "binder") " (and the leftover entries to " (c "rest") "). It's the pattern-matching counterpart to a " (c "Map.lookup") ": here " (c "setting") " reads the " (c "\"width\"") " from a config map, returning " (cdz "(Some v)") " when the key is present and " (cdz "(None unit)") " when it's absent, because a missing key is an absence, not a magic number:")
  (runnable
    (source (def (setting m)
  (match m
    (#map((= "width" v) (.. rest)) (Some v))
    (_ (None unit))))
(def (main)
  (setting (Map.insert (Map.insert (Map.empty) "width" 80) "height" 50)))))
  (p "The map has a " (c "\"width\"") ", so the arm fires, binds " (c "v") " to " (c "80") ", and returns " (cdz "(Some 80)") ". Drop that key from the map and the pattern no longer matches, so it falls through to the wildcard and returns " (cdz "(None unit)") ". The " (strong "Maps &amp; sets") " chapter later builds out maps as values.")
  (h2 "Matching a tuple's shape")
  (p "A tuple pattern takes a value apart by " (em "position") ", and a trailing rest marker " (c "(.. rest)") " gathers the elements you didn't name into a smaller tuple, the positional twin of a list's " (c ".. rest") ". Here " (cdz "#tuple(a b (.. rest))") " binds " (c "a") " and " (c "b") " to the first two elements and " (c "rest") " to a tuple of whatever trails, so reading " (c "rest") " back with " (c ".0") " recovers the third element:")
  (runnable
    (source (match #tuple(3 4 5)
  (#tuple(a b (.. rest)) (+ (+ a b) (. rest 0)))
  (_ 0))))
  (p "So " (c "a") " is " (c "3") ", " (c "b") " is " (c "4") ", and " (c "rest") " is the one-element tuple " (cdz "#tuple(5)") ", whose " (c ".0") " is " (c "5") ", giving " (c "3 + 4 + 5 = 12") ". Two things to hold onto: " (c "rest") " is the trailing " (em "sub-tuple") ", not a flattened list, so a " (cdz "#tuple(1 2 3 4)") " matched by " (cdz "#tuple(x (.. rest))") " leaves " (c "rest") " as " (cdz "#tuple(2 3 4)") ", indexed " (c ".0") "/" (c ".1") "/" (c ".2") "; and the arity is fixed, so " (cdz "#tuple(a b (.. rest))") " needs at least two elements, and a shorter tuple simply doesn't match that arm.")
  (note "The example above binds a rest over a tuple " (em "constructed in place") ", which is what this pattern supports. A rest binder over a fully opaque runtime tuple is " (em "not supported") " on the backends, so the compiler declines it with a clear message rather than compute a wrong answer, the same honest refusal you've seen elsewhere.")
  (h2 "Matching a record's fields")
  (p "Records take a rest the same way, by " (em "name") " instead of position. A record pattern names the fields you care about and a trailing " (c "(.. rest)") " gathers the rest into a " (em "residual record") ", the record analogue of the tuple rest above. Here " (cdz "#record((= a x) (.. rest))") " binds " (c "x") " to field " (c "a") " and " (c "rest") " to a record of the remaining fields, whose own fields you read back by name:")
  (runnable
    (source (match #record((= a 1) (= b 2) (= c 3))
  (#record((= a x) (.. rest)) (+ (+ x (. rest b)) (. rest c)))
  (_ 0))))
  (p "So " (c "x") " is " (c "1") ", and " (c "rest") " is the residual record " (cdz "#record((= b 2) (= c 3))") ", so " (c "rest.b") " is " (c "2") " and " (c "rest.c") " is " (c "3") ", giving " (c "1 + 2 + 3 = 6") ". The key difference from the tuple case: " (c "rest") " here is a " (em "record") ", so you reach into it by field name (" (c "rest.b") ", " (c "rest.c") "), not by position.")
  (note "As with the tuple rest, this supports a record " (em "constructed in place") ". A rest binder over a fully opaque runtime record is " (em "not supported") " on the backends, so the compiler declines it with a clear message rather than a wrong answer.")
  (h2 "Matching a set's members")
  (p "A set has no fields or positions, so a set pattern asks a different question: " (em "containment") ". " (cdz "#set(1 (.. rest))") " names the members that must be " (em "present") " and matches any set that contains them, a subset test rather than an equality, exactly like a map pattern matching on the keys it names. The trailing " (c "(.. rest)") " then binds " (c "rest") " to the " (em "residual set") ", the scrutinee's members minus the ones you named. Here the set contains " (c "1") ", so the arm fires and " (c "rest") " is what's left:")
  (runnable
    (source (match #set(1 2 3)
  (#set(1 (.. rest)) (Some rest))
  (_ (None unit)))))
  (p "The scrutinee " (cdz "#set(1 2 3)") " contains the named " (c "1") ", so the arm matches and " (c "rest") " binds the residual " (cdz "#set(2 3)") ", making the whole expression " (cdz "(Some #set(2 3))") ", the leftover set, returned as an " (c "Option") " since a set that lacks the named member takes the " (c "None") " arm instead. Three things follow from its being a containment test: it matches a " (em "superset") " too (" (cdz "#set(1)") " matches " (cdz "#set(1 2 3)") "), naming a member the set " (em "lacks") " refutes the arm (it falls to the wildcard), and order and duplicates in the pattern are immaterial because a set is unordered. It's the membership-axis twin of the map and record rest: same " (c "(.. rest)") " residual, asking \"is this present?\" instead of \"what's at this field?\".")
  (h2 "Your turn")
  (exercise
    (id "pattern-matching:1")
    (prompt "Add the missing " (c "None") " arm so this compiles and returns " (c "0") ".")
    (starter (type Opt (Some Int64) (None unit))
(def (main)
  (match (None unit)
    ((Some x) x)
    ?)))
    (solution (type Opt (Some Int64) (None unit))
(def (main)
  (match (None unit)
    ((Some x) x)
    ((None _) 0))))
    (expected "0")
    (hint "The missing case is " (c "None") "; an arm is a " (c "(pattern body)") " pair: " (c "((None _) 0)") "."))
  (exercise
    (id "pattern-matching:2")
    (prompt "Write the " (em "guard condition") " so " (c "grade") " returns " (c "1") " for a passing score of " (c "60") " or more, and " (c "0") " otherwise. With " (cdz "(grade 75)") " the answer is " (c "1") ".")
    (starter (def (grade s)
  (match s
    ((guard x ?) 1)
    (_ 0)))
(def (main) (grade 75)))
    (solution (def (grade s)
  (match s
    ((guard x (>= x 60)) 1)
    (_ 0)))
(def (main) (grade 75)))
    (expected "1")
    (hint "The guard binds the score to " (c "x") "; the condition for passing is \"60 or more\", namely " (cdz "(>= x 60)") ". " (c "75") " clears it, so the first arm fires.")))
