(chapter
  (slug "property-testing")
  (title "Testing & properties")
  (pillar "language")
  (section "What makes Cadenza different")
  (blurb "@test marks a function as a test; give it parameters and the runner generates inputs and shrinks failures.")
  (lede "You could write a hundred example tests by hand, or state the rule that must always hold and let the machine hunt for counterexamples. Cadenza does both, with no testing framework to learn: a test is just a function you mark " (c "@test") ", and the runner finds every one, runs it, and reports a pass or a fail. The panels below run for real, right here, and each shows ✓ or ✗ per test.")
  (h2 "A test is a marked function")
  (p "Mark a zero-argument function " (c "@test") " and the runner calls it. It " (em "passes") " unless it " (em "traps") ", so you assert by trapping on the bad case. A tiny assert helper (" (c "assert") ", " (c "assert-eq") ", " (c "assert-ne") ", each just an " (c "if") " that traps on failure) is in scope in these panels. Here two tests, both passing; press Run and you'll see two ✓:")
  (runnable
    (source (@ test (def (two-plus-two-is-four)
  (assert-eq (+ 2 2) 4 "arithmetic is broken")))
(@ test (def (addition-commutes)
  (assert-eq (Int64.wrapping-add 3 7) (Int64.wrapping-add 7 3) "not commutative"))))
    (mode "test"))
  (p "No " (c "main") ", no wrapper: the source " (em "is") " the test defs, and the runner discovers and runs them exactly the way " (c "cdz test") " does on your machine. A pass means the function returned without trapping; that's the whole contract.")
  (h2 "A failing test shows why")
  (p "When a test traps, the runner reports it as a failure with the trap message. Here one test passes and one deliberately fails; Run it and you'll see a ✓ and a ✗ with its reason:")
  (runnable
    (source (@ test (def (four-is-under-five)
  (assert (< 4 5) "4 should be under 5")))
(@ test (def (five-is-under-five)
  (assert (< 5 5) "5 is not under 5 — this test is meant to fail"))))
    (expect "error")
    (mode "test"))
  (p "The second test's condition is false, so " (c "assert") " traps and the runner marks it ✗ with the message you gave. That message is what a good assert is for: when a test fails, it tells you " (em "what") " broke, not just that something did.")
  (h2 "Tests are ordinary code")
  (p "A " (c "@test") " is a normal function, so it can do anything a function can: build a list, call your own definitions, check a result. Here a test defines a helper and asserts a property of it:")
  (runnable
    (source (def (double x) (* 2 x))
(@ test (def (double-then-halve-round-trips)
  (assert-eq (/ (double 21) 2) 21 "double then halve should return the original")))
(@ test (def (list-length-is-nonneg)
  (assert (>= (List.len #list(1 2 3)) 0) "length can't be negative"))))
    (mode "test"))
  (p "There's nothing special about a test beyond the " (c "@test") " mark; it's a function the runner knows to call. That's all there is to testing here: no framework, no assertion library built into the language, just functions that trap when an expectation is violated.")
  (h2 "Parameters make it generative")
  (p "Give a " (c "@test") " " (em "parameters") " and it becomes a " (em "property") " test: the runner " (em "generates") " inputs for those parameters (the generator is synthesized from the parameter " (em "types") ", nothing to write), runs the test many times (100 by default), and passes only if every trial does. On failure it " (em "shrinks") " the counterexample to the smallest input that still fails and prints a seed to replay. A property is just a test that should hold for " (em "all") " inputs:")
  (p "Give this test two " (c "Int64") " parameters and it becomes a property; press Run and the runner generates a hundred pairs, checking commutativity on every one:")
  (runnable
    (source (@ test (def (add-comm (: a Int64) (: b Int64))
  (assert-eq (Int64.wrapping-add a b) (Int64.wrapping-add b a) "not commutative"))))
    (mode "test"))
  (p "You wrote the predicate; the runner wrote the generator. It reports " (c "PASS add-comm (100 trials)") ", a hundred generated pairs, all commuting. Scalars generate directly; compound types (a " (cdz (List Int64)) ", a record, a user sum) generate too, with the compiler deriving the generator from the type.")
  (p "And a deliberately-wrong property shows the " (em "shrink") ". This one claims every generated " (c "Int64") " is under 100, which is false, so Run it and watch the runner report the " (em "smallest") " failing input it can find, not whatever large value it first stumbled on:")
  (runnable
    (source (@ test (def (all-small (: n Int64))
  (assert (< n 100) "not every Int64 is under 100"))))
    (expect "error")
    (mode "test"))
  (p "The counterexample is " (c "all-small(100)") ": the runner found a failing draw, then shrank it toward zero to the boundary value, with a seed to reproduce the run. A property that holds passes silently over its trials; one that doesn't hands you the minimal witness.")
  (p "Shrinking isn't just for scalars; it minimizes " (em "compound") " values the same way. Here a property claims no generated list ever has exactly three elements, a deliberately-wrong claim. The parameter is a " (cdz (List Int64)) ", so the compiler synthesizes a " (em "list") " generator (a random length, then an element per slot); press Run and the runner finds a failing list and shrinks it:")
  (runnable
    (source (@ test (def (never-three (: xs (List Int64)))
  (if (= (List.len xs) 3) (trap "was three") unit))))
    (expect "error")
    (mode "test"))
  (p "It fails and hands back the shrunk witness. The runner found some failing list, then shrank it: it pinned the length at the failing " (c "3") " (a shorter list stops failing) while driving the elements toward zero, the smallest list of the failing shape, not the arbitrary " (c "[7, 42, 5]") " it may have stumbled on first. That's the shrink made visible on a " (em "structured") " value, and it runs right here in the browser: the same generator-and-shrink the command-line " (c "cdz test") " uses, driving a compound parameter live.")
  (h2 "Proving a small domain, and tagging")
  (p "Two refinements round out the surface. " (c "@exhaustive") ", on a test whose parameters are " (em "bounded") " (a " (c "Bool") ", a narrow integer), runs " (em "every") " combination instead of sampling, so a pass is a " (em "proof") " over that domain: " (c "@exhaustive def or_symmetric(a: Bool, b: Bool) = …") " checks all four " (c "Bool") " pairs. And " (c "@tag(\"slow\")") " labels a test so " (c "cdz test --tag slow") " runs just that subset. All three are ordinary annotations, no privileged testing layer, just functions the runner knows how to call.")
  (why (tenet "A test is a function; a property is a test with arguments") "Cadenza doesn't add a property-testing DSL with its own generators and combinators. A test is a function marked " (c "@test") "; a " (em "property") " is that same idea with parameters, and the compiler synthesizes the generator from the types you already wrote, so there's nothing extra to learn. The runner drives generation, shrinking, and a recorded seed internally, but the surface you touch is just this: write a function, assert what should hold, mark it, and if it takes arguments the runner tries to break it for you.")
  (p "That's the last of what makes Cadenza its own language: exact numbers, units, effects, types as values, metaprogramming, generative tests. You've met the ideas; now watch them do real work. The " (link (slug "example-apps") " example applications ") " are full, interactive programs built in Cadenza: the calculator, the CAD preview, the notebook, the playground, each one a differentiator you just learned, running in your browser.")
  (h2 "Your turn")
  (p "A test's core is the " (em "predicate") " it asserts. These exercises compute that predicate directly (returning " (c "1") " when it holds), the exact check a " (c "@test") " body performs each time the runner calls it.")
  (exercise
    (id "property-testing:1")
    (prompt "Doubling then halving should return the original, the property a round-trip test asserts. Fill the value so the check holds for " (c "21") ", giving " (c "true") ".")
    (starter (def (round-trips n) (= (/ (* n 2) 2) ?))
(def (main) (round-trips 21)))
    (solution (def (round-trips n) (= (/ (* n 2) 2) n))
(def (main) (round-trips 21)))
    (expected "true")
    (hint "Doubling then halving gets you back where you started, so " (cdz (/ (* n 2) 2)) " equals " (c "n") ". Fill the blank with " (c "n") "; a " (c "@test") " would " (c "assert-eq") " these two."))
  (exercise
    (id "property-testing:2")
    (prompt "The length of a three-element list is exactly " (c "3") ", the property a length test asserts. Fill the comparison value so the check gives " (c "true") ".")
    (starter (def (len-is xs n) (= (List.len xs) n))
(def (main) (len-is #list(10 20 30) ?)))
    (solution (def (len-is xs n) (= (List.len xs) n))
(def (main) (len-is #list(10 20 30) 3)))
    (expected "true")
    (hint "The list has three elements, so its length is " (c "3") ". Fill " (c "3") " and the check holds, the same equality a " (c "@test") " would " (c "assert-eq") ".")))
