(chapter
  (slug "records-tuples")
  (title "Working with records & tuples")
  (pillar "language")
  (section "Fundamentals")
  (blurb "Passing structured data around and reaching into it.")
  (lede "Passing structured data around, reaching into it, and nesting it.")
  (p "You met records and tuples in " (em "Data") ", and here we put them to work in the everyday rhythm of building a little bundle of values, handing it to a function, and reaching in for the pieces.")
  (h2 "Functions over records")
  (p "A record travels as one value, so a function can take a whole record and read its fields with the " (c ".") " accessor. Here " (c "area") " multiplies a rectangle's width and height:")
  (runnable
    (source (def (area r) (* (. r w) (. r h)))
(def (main) (area #record((= w 4) (= h 5))))))
  (p "Reaching in with " (c ".") " repeatedly gets noisy when a function wants several fields. You can instead name them up front with a " (em "record pattern") " that binds each field in one move, right in the parameter, which " (link (slug "irrefutable-patterns") "Irrefutable patterns") " covers in full alongside tuple destructuring.")
  (h2 "Updating a field")
  (p "Records are immutable, so you never " (em "change") " a field but instead produce a new record that differs in one place. " (c "Record.with") " does exactly that: give it a record, a " (c "#field") " selector naming which field, and the new value, and it hands back a copy with that field replaced. Here a price of " (c "2") " becomes " (c "9") ":")
  (runnable
    (source (. (Record.with #record((= item 1) (= price 2)) #"price" 9) price)))
  (note "The field is named with a " (c "#") " selector, written " (c "#\"price\"") " in the s-expr surface and " (c "#price") " in the ML surface (flip the syntax toggle to see it). It's a symbol picking the field by name, not a value; the record and the new value are the other two operands.")
  (p "\"Hands back a copy\" is the important part, because the original is untouched. Bind a record, make an updated version, then read the " (em "original") " back and you'll see it never moved:")
  (runnable
    (source (let ((base #record((= hp 5) (= mp 3))))
  (. (Record.with base #"hp" 99) hp))))
  (p "That reads " (c "99") ", but swap " (c "Record.with base #\"hp\" 99") " for plain " (c "base") " and Run again to get " (c "5") ", the original, still there. Two records, sharing everything but the one field.")
  (p (c "Record.with") " is for a field that already exists; to " (em "add") " a new one, use " (c "Record.extend") ". Keeping them separate is deliberate, because it means a typo'd field name can't silently create a new field where you meant to update an old one:")
  (runnable
    (source (. (Record.extend #record((= x 1) (= y 2)) #"z" 3) z)))
  (p "And the compiler holds the line: use " (c "Record.with") " on a field that isn't there and it won't guess, but tells you to reach for " (c "Record.extend") " instead.")
  (runnable
    (source (. (Record.with #record((= a 1)) #"z" 5) z))
    (expect "error"))
  (h2 "Combining two records")
  (p "Where " (c "extend") " adds one field, " (c "Record.merge") " combines two whole records into one whose fields are the " (em "union") " of both. Merge a record of sizes with a record of colours and you can reach any field of either side:")
  (runnable
    (source (. (Record.merge #record((= w 4) (= h 5)) #record((= r 255))) r)))
  (p "The result has all three fields " (c "w") ", " (c "h") ", and " (c "r") ", so " (c ".r") " reads " (c "255") ". And the same no-clobber discipline applies: the two records must have " (em "disjoint") " fields. Ask to merge two records that both define " (c "x") " and the compiler refuses rather than silently pick a winner:")
  (runnable
    (source (. (Record.merge #record((= x 1)) #record((= x 2))) x))
    (expect "error"))
  (h2 "Nesting")
  (p "Records and tuples nest freely, so a field can hold another record and a tuple can hold a record, and so on. Chain the accessor to reach inside:")
  (runnable
    (source (. (. #record((= pt #record((= x 3) (= y 4)))) pt) y)))
  (h2 "Tuples as lightweight pairs")
  (p "When you just need to carry a couple of values together without naming a record type, a tuple is the tool. Access elements by position with " (c ".") " and an index. Here " (c "swap") " flips a pair, and since a tuple is an ordinary value it can hand the whole flipped pair straight back:")
  (runnable
    (source (def (swap p) #tuple((. p 1) (. p 0)))
(def (main) (swap #tuple(3 7)))))
  (p "The result is " (cdz #tuple(7 3)) ", both elements in their new positions, returned as one value you could pass along or reach into further.")
  (p "And just as " (c "Record.merge") " combined two records, " (c "Tuple.concat") " joins two tuples end to end into one wider tuple. It's the positional version, so there's no disjointness rule, and the second tuple's elements simply follow the first, their indices shifting up. Cat a pair onto a triple and index " (c "3") " of the result is the first element of the second tuple, " (c "4") ":")
  (runnable
    (source (. (Tuple.concat #tuple(1 2) #tuple(3 4 5)) 3)))
  (why (tenet "Records are named, tuples are positional") "Why have both? A tuple is a fixed " (em "positional") " product you reach into by index, and it reads best when the pieces are obvious from context (a coordinate pair, a swap). A record has fixed " (em "named") " fields you reach into by name, and it reads best when the pieces deserve labels (a rectangle's " (c "w") " and " (c "h") "). Both are just values with a fixed shape the compiler knows, so it can check every field access against the actual structure, with no \"field not found\" surprises at run time.")
  (h2 "Putting it together")
  (p "A small taste of real code: compute the squared distance of a point from the origin, by squaring each coordinate and summing. It composes a helper (" (c "sq") ") with record access:")
  (runnable
    (source (def (sq x) (* x x))
(def (dist2 p) (+ (sq (. p x)) (sq (. p y))))
(def (main) (dist2 #record((= x 3) (= y 4))))))
  (h2 "Your turn")
  (exercise
    (id "records-tuples:1")
    (prompt "Finish " (c "perimeter") " so a 4×5 rectangle gives " (c "18") " (two widths plus two heights).")
    (starter (def (perimeter r)
  (+ (* 2 (. r w)) ?))
(def (main) (perimeter #record((= w 4) (= h 5)))))
    (solution (def (perimeter r)
  (+ (* 2 (. r w)) (* 2 (. r h))))
(def (main) (perimeter #record((= w 4) (= h 5)))))
    (expected "18")
    (hint "Mirror the width term for the height: " (cdz (* 2 (. r h))) "."))
  (exercise
    (id "records-tuples:2")
    (prompt "Concatenating shifts the second tuple's indices up by the first's length. Cat " (cdz #tuple(1 2)) " onto " (cdz #tuple(3 4 5)) " and reach the " (em "last") " element, " (c "5") ", by its index in the joined tuple. Which index is it?")
    (starter (. (Tuple.concat #tuple(1 2) #tuple(3 4 5)) ?))
    (solution (. (Tuple.concat #tuple(1 2) #tuple(3 4 5)) 4))
    (expected "5")
    (hint "The joined tuple is " (cdz #tuple(1 2 3 4 5)) ", five elements with indices " (c "0") " to " (c "4") ". The " (c "5") " is last, so its index is " (c "4") ", not " (c "2") ", because the first tuple pushed it two slots over."))
  (exercise
    (id "records-tuples:3")
    (prompt (cdz #record((= x 10) (= y 20))) " has no " (c "z") " field. Add one, " (c "z = 30") ", then read it back for the answer " (c "30") ". Which operation adds a " (em "new") " field, " (c "with") " or " (c "extend") "? Fill in the blank.")
    (starter (. (Record.? #record((= x 10) (= y 20)) #"z" 30) z))
    (solution (. (Record.extend #record((= x 10) (= y 20)) #"z" 30) z))
    (expected "30")
    (hint (c "with") " only updates a field that already exists; adding a brand-new one is " (c "Record.extend") ". (Try " (c "with") " and the compiler declines, since " (c "z") " isn't there to update.)")))
