(chapter
  (slug "sized-integers")
  (title "Sized integers")
  (pillar "language")
  (section "Fundamentals")
  (blurb "Fixed-width integers that never convert silently.")
  (lede (c "Int64") " is the everyday integer, but when a value has a fixed width, whether a byte, a 16-bit field, or a protocol number, Cadenza gives it a type that says so, and never converts one width to another behind your back.")
  (p "A sized integer type is named by its signedness and its bit width: " (c "UInt8") " (0–255), " (c "Int8") " (−128–127), " (c "UInt16") ", " (c "UInt32") ", and so on. You don't get one by writing a literal, since a bare " (c "200") " is an " (c "Int64") ". You " (em "convert into") " a sized type by name, with " (c ".of") ":")
  (runnable
    (source (UInt8.of 200)))
  (p (c "200") " fits in a byte, so this is the " (c "UInt8") " value 200. Different widths hold different ranges, so " (c "UInt16.of") " happily takes a number a byte couldn't:")
  (runnable
    (source (UInt16.of 300)))
  (h2 "Conversion is checked")
  (p "What if the number doesn't fit? " (c ".of") " is the " (em "checked") " conversion, so it verifies the value is in range and traps if it isn't, rather than silently keeping the wrong bits. Asking a byte to hold 300 is a range error:")
  (note "This one is " (strong "meant to trap") ". Run it and read the status bar, where the range check firing is the point, so you find out immediately, not via a corrupted value downstream.")
  (runnable
    (source (UInt8.of 300))
    (expect "error"))
  (h2 "When you want the low bits: " (c "wrap"))
  (p "Sometimes truncation is exactly what you mean, whether for a checksum, a rollover counter, or packing into a byte. That's a different, explicit operation, since " (c "wrap") " keeps the low bits and discards the rest. " (c "300") " wrapped to 8 bits is " (c "300 − 256 = 44") ":")
  (runnable
    (source (UInt8.wrap 300)))
  (p (c "of") " and " (c "wrap") " are the two honest choices for \"this doesn't fit\", either halting or taking the low bits, and you say which one you mean. Neither happens by accident.")
  (h2 "Widths are distinct types")
  (p "A " (c "UInt8") " and a " (c "UInt16") " are " (em "different types") ". Try to add them and the compiler refuses, because it won't quietly widen one to match the other:")
  (runnable
    (source (+ (UInt8.of 1) (UInt16.of 300)))
    (expect "error"))
  (p "The fix is to say which width you want and convert there, so the widening is a thing you write, not a thing that happens to you.")
  (h2 "Why isn't " (c "Int") " a type?")
  (p "A newcomer's first reflex is to annotate with a bare " (c "Int") ", the way most languages name their integer type. In Cadenza " (c "Int") ", " (c "UInt") ", and " (c "Float") " are not types at all: they're " (em "width constructors") " that " (em "build") " a sized type from a bit width. " (cdz (Int 64)) " is " (c "Int64") ", " (cdz (UInt 8)) " is " (c "UInt8") ", " (cdz (Float 32)) " is " (c "Float32") ". So writing a bare " (c "Int") " where a type belongs uses a value where a type is required, and the compiler says so:")
  (note "This one is " (strong "meant to be refused") ": " (c "Int") " is a width constructor, not a type, so the annotation has nothing to stand on. The diagnostic names the sized default " (c "Int64") " (and offers a one-click fix to it), and points you at the other widths if you meant one of those.")
  (runnable
    (source (def (f (: a Int)) a))
    (expect "error"))
  (p "The fix is to name a concrete width, so " (c "Int64") " for the everyday integer, or " (c "Int32") ", " (c "UInt8") ", and the rest for a fixed size. The compound form " (cdz (Int 64)) " is itself a perfectly good type, exactly equal to " (c "Int64") ", so this compiles and runs, and " (cdz (add1 41)) " is " (result (of "add1") 42) ":")
  (runnable
    (id "add1")
    (source (do (def (add1 (: n (Int 64))) (+ n 1))
    (def (main) (add1 41))
    (export main))))
  (p "Only the " (em "bare") " name is the mistake, since " (cdz (Int 64)) " and " (c "Int64") " are the same type written two ways. Reach for the width name and the reflex costs you nothing.")
  (h2 "Arithmetic stays inside the width")
  (p "The width isn't just checked at conversion, since it's enforced in arithmetic too. Two " (c "UInt8") "s add as a " (c "UInt8") ", and a sum that would exceed " (c "255") " is caught, exactly like " (c "Int64") " overflow. " (c "200 + 100") " can't fit a byte, so it's refused:")
  (note "This one is " (strong "meant to be refused") ": the " (c "UInt8") " sum overflows its width, so the compiler declines rather than wrapping, the same no-silent-wrap discipline, at 8 bits.")
  (runnable
    (source (+ (UInt8.of 200) (UInt8.of 100)))
    (expect "error"))
  (p "When you " (em "do") " want a wider result, widen first: " (c "Int64.of") " lifts a sized value back to the everyday integer, where the sum has room. The " (c "UInt8") " " (c "200") " becomes the " (c "Int64") " " (c "200") ", and adding " (c "100") " is fine:")
  (runnable
    (source (+ (Int64.of (UInt8.of 200)) 100)))
  (why (tenet "A width is part of the type, and never crossed silently") "Bugs love implicit integer conversion: a value that fit in the source width but not the destination, a sign that flipped on the way, a truncation nobody wrote. Cadenza makes the width part of the type, so two widths simply don't mix, and every crossing is one you asked for by name, choosing " (c "of") " (halt if it doesn't fit) or " (c "wrap") " (take the low bits). It's the same discipline as " (c "Int64") " refusing to blur with " (c "Bool") ", applied to the sizes: the compiler never makes the \"did you mean to lose data here?\" decision for you.")
  (note "Signed widths work the same way, so " (c "Int8.of") " takes −128 through 127, traps outside it, and " (c "Int8.wrap") " gives you the low 8 bits. Same two choices, at every width.")
  (p "Integers, checked and sized and never blurred, are only half the number line. Next comes the other half, the approximate, real-valued world of " (em "floating-point numbers") ", with its own operators and its own honest tradeoff.")
  (h2 "Your turn")
  (exercise
    (id "sized-integers:1")
    (prompt (c "258") " doesn't fit a byte, and you want it truncated to the low 8 bits, not a halt. Pick the operation that takes the low bits, so the result should be " (c "2") " (that's " (c "258 − 256") "). Which of " (c "of") " / " (c "wrap") " goes in the blank?")
    (starter (UInt8.? 258))
    (solution (UInt8.wrap 258))
    (expected "2")
    (hint (c "wrap") " keeps the low bits, whereas " (c "of") " would " (em "refuse") " " (c "258") " as out of range. You asked for truncation, so it's " (c "wrap") ", and " (c "258") " wraps to " (c "2") "."))
  (exercise
    (id "sized-integers:2")
    (prompt "This won't compile: " (cdz (+ (UInt8.of 1) (UInt16.of 300))) " mixes two widths. Fix it by making the first operand a " (c "UInt16") " too, so both sides match and the sum is " (c "301") ".")
    (starter (+ (UInt?.of 1) (UInt16.of 300)))
    (solution (+ (UInt16.of 1) (UInt16.of 300)))
    (expected "301")
    (hint "Widths don't mix, so convert the " (c "1") " at the same width as the other operand, namely " (c "UInt16") ". Then " (c "1 + 300 = 301") ".")))
