(chapter
  (slug "units")
  (title "Units of measure")
  (pillar "language")
  (section "What makes Cadenza different")
  (blurb "Carry a unit with a value; mix dimensions and it won't compile.")
  (lede "A number rarely means anything on its own. " (c "5.0") " is five " (em "what") "? Meters, seconds, dollars? Cadenza lets you carry the unit along with the value, checks that you never add a length to a time, and then erases the whole apparatus before the program runs. It costs nothing.")
  (p "A " (strong "quantity") " is a number paired with a unit. You build one with " (c "Qty.of") ", giving it a value and a unit, and the quantity " (em "carries that unit as part of its value") ". Run this and the result comes back tagged with its unit, " (c "5.0 meter") ". The " (c "meter") " travels with the " (c "5.0") ":")
  (runnable
    (source (Qty.of 5.0 (Unit.of #"meter"))))
  (p "When you want the bare number back, to hand it to something that doesn't speak units, " (c "Qty.value") " strips the unit off and gives you just the " (c "5.0") ":")
  (runnable
    (source (Qty.value (Qty.of 5.0 (Unit.of #"meter")))))
  (h2 "The same dimension converts on its own")
  (p "A kilometer and a meter are two units of the one dimension " (em "length") ". Combining them is well-formed even though they differ: each carries an exact scale to its dimension's reference, so Cadenza converts and adds them for you. One kilometer plus five hundred meters is fifteen hundred meters:")
  (runnable
    (source (+ (Qty.of 1.0 (Unit.of #"kilometer"))
   (Qty.of 500.0 (Unit.of #"meter")))))
  (p "The result is a quantity, " (c "1500.0 meter") ", carried with its unit and reported at the dimension's reference unit (meters), the kilometer scaled in on the way. This is the one place Cadenza converts a number for you without being asked, and it earns the exception by being " (em "exact") ": kilometer-to-meter is times a thousand, no rounding, no guess. A mix of different " (em "dimensions") " gets no such courtesy, as we'll see in a moment.")
  (p "Because the quantity surface is meant to read like English, common plurals resolve to their singular unit. " (c "#\"feet\"") " is just " (c "#\"foot\"") ", the same member of the length family. So one meter plus four feet is well-formed and converts exactly, to " (c "2.2192 meter") ":")
  (runnable
    (source (+ (Qty.of 1.0 (Unit.of #"meter"))
   (Qty.of 4.0 (Unit.of #"feet")))))
  (note "Toggle to the conventional surface and the second quantity reads " (c "4.0 feet") ". The plural survives in the surface even though it means the singular unit underneath. Write " (c "#\"foot\"") " instead and you'd get the identical result.")
  (h2 "Converting on purpose")
  (p "When you want a specific unit out, convert to it with " (c "Unit.in") ": name the target unit first, then the quantity. Two kilometers " (em "in meters") ":")
  (runnable
    (source (Unit.in (Unit.of #"meter")
         (Qty.of 2.0 (Unit.of #"kilometer")))))
  (p "The result is the bare number " (c "2000") ". Converting " (em "into") " a unit is the deliberate exit from the quantity world: you asked \"how many meters?\" and get the plain number of meters, ready for ordinary arithmetic. There's no " (c "Qty.value") " to strip because " (c "Unit.in") " already hands back the number. Toggle to the ML surface and it reads as a plain postfix, " (c "2.0 kilometer as meter") ". It runs both ways across a scale: two hundred fifty milliseconds in seconds is a quarter of a second (" (c "0.25") "):")
  (runnable
    (source (Unit.in (Unit.of #"second")
         (Qty.of 250.0 (Unit.of #"millisecond")))))
  (h2 "Different dimensions do not mix")
  (p "Here is where the safety shows up. A length and a time share nothing. There is no exact factor between meters and seconds, so adding them is a mistake, and the compiler says so " (em "before") " the program ever runs:")
  (note "This one is " (strong "meant to be rejected") ". Run it and read the diagnostic: it names both dimensions and refuses. That's the feature working: a units bug is a compile error, never a wrong answer at runtime.")
  (runnable
    (source (+ (Qty.of 1.0 (Unit.of #"meter"))
   (Qty.of 1.0 (Unit.of #"second"))))
    (expect "error"))
  (p "The same guard covers conversion: asking for a length " (c "Unit.in") " a time is the same category error, caught the same way.")
  (h2 "Dimensions compose")
  (p "Units aren't just labels you match; they combine. Divide a distance by a time and you get a speed, and the units divide right along with the numbers. Two hundred forty meters over eight seconds is thirty meters per second:")
  (runnable
    (source (/ (Qty.of 240.0 (Unit.of #"meter"))
   (Qty.of 8.0 (Unit.of #"second")))))
  (p "The result carries its derived unit, " (c "30.0 meter/second") ", a compound Cadenza built by dividing the two units right along with the numbers. You can spell such units directly, too: " (c "(Unit.* a b)") " for a product (an area is a length times a length), " (c "(Unit./ a b)") " for a quotient, " (c "(Unit.^ u n)") " for a power, and " (c "Unit.one") " for a plain dimensionless number.")
  (h2 "Raising a quantity to a power")
  (p (c "Qty.pow") " raises a whole quantity, value " (em "and") " unit, to a compile-time integer power. Square a length and you get an area: the unit becomes meters-squared while the value squares. A five-meter side gives twenty-five square meters, " (c "25.0 meter^2") ", the unit squared along with the value:")
  (runnable
    (source (Qty.pow (Qty.of 5.0 (Unit.of #"meter")) 2)))
  (p "The exponent can be " (em "negative") ", and that's where units earn their keep. A period is a time, and its " (em "reciprocal") " is a frequency, with the unit inverted to per-second. A four-second period is a frequency of " (c "0.25 1/second") ":")
  (runnable
    (source (Qty.pow (Qty.of 4.0 (Unit.of #"second")) -1)))
  (p "That " (c "-1") " didn't just divide the number; it flipped the dimension from " (em "time") " to " (em "per-time") ". Try to add the result to a plain length and you'll get the same CDZ0501 you saw above: a frequency and a length are different dimensions, and the compiler knows it.")
  (h2 "Prefixes: SI and binary")
  (p "Most scaled units already have a name: " (c "kilometer") ", " (c "millisecond") ", " (c "mebibyte") " are units of their families just like " (c "meter") " is, so you write them the same way and everything above (mixing, converting, comparing) just works. The names carry two prefix systems that matter and must not blur together: SI " (em "decimal") " prefixes step by powers of ten (" (c "kilobyte") " is 1000 bytes), while the IEC " (em "binary") " prefixes step by powers of two (" (c "mebibyte") " is 2²⁰). One mebibyte is exactly 1&nbsp;048&nbsp;576 bytes, not a million:")
  (runnable
    (source (Unit.in (Unit.of #"byte")
         (Qty.of 1.0 (Unit.of #"mebibyte")))))
  (p "That's the distinction a units layer is " (em "for") ": the kind that quietly turns a 1&nbsp;MiB buffer into a 1&nbsp;MB one in someone's head. " (c "kibibyte") " and " (c "kilobyte") " are different names with different exact factors, and the arithmetic can't blur them.")
  (note "Need a prefix on a unit that has no ready-made name? " (c "Unit.prefix") " applies one to any unit. " (c "(Unit.prefix milli (Unit.of #\"meter\"))") " is the millimeter and " (c "(Unit.prefix mebi …)") " the mebi- scale, the general mechanism the named units above are built from.")
  (h2 "Declaring your own units")
  (p "The built-in table doesn't have to be the end of it. " (c "Unit.define") " introduces a new named unit as an exact multiple of one you already have: a name, the unit to build on, and a ratio (numerator then denominator). A furlong is 660 feet, so once you've defined it, it converts like any other unit. One furlong is " (c "201.168") " meters:")
  (runnable
    (source (Unit.define #"furlong" (Unit.of #"foot") 660 1)
(def (main)
  (Unit.in (Unit.of #"meter") (Qty.of 1.0 (Unit.of #"furlong"))))))
  (p "The new name joins the same family, so it carries a dimension and obeys every rule you've seen: conversion, mixing, mismatch detection. Define a nautical mile as 1852 meters and two of them come to " (c "3704") " meters:")
  (runnable
    (source (Unit.define #"nautical-mile" (Unit.of #"meter") 1852 1)
(def (main)
  (Unit.in (Unit.of #"meter") (Qty.of 2.0 (Unit.of #"nautical-mile"))))))
  (p "A unit's name has to mean exactly one conversion. Redefining " (c "foot") " as 2 meters, a value it already isn't, is a contradiction, and the compiler rejects it rather than let two definitions fight:")
  (note "This one is " (strong "meant to be rejected") ". A redefinition that " (em "agrees") " with the existing conversion is fine; only a " (em "conflicting") " one is the error (CDZ0502) you'll see here.")
  (runnable
    (source (Unit.define #"foot" (Unit.of #"meter") 2 1)
(def (main) 0))
    (expect "error"))
  (h2 "Worked example: exact CAD")
  (p "Here's where units and " (em "exact") " numbers pay off together. Every quantity so far used a " (c "Float64") " value, but a " (c "Qty") " can carry a " (em "rational") " just as well, and then a conversion is " (em "exact") ", no rounding. This is exactly how Cadenza's CAD library models solids: rational coordinates in real units, so a metric body and imperial fasteners coexist with no float drift. A quarter-inch hole in a millimetre plate converts to precisely " (c "127/20") " mm, which is " (c "6.35") " mm, exactly, as a fraction:")
  (runnable
    (source (def (main)
  (= (Unit.in (Unit.of #"millimeter")
              (Qty.of (Rational.of 1 4) (Unit.of #"inch")))
     (Rational.of 127 20)))))
  (p "That reads " (c "true") ": the converted value is the exact rational " (c "127/20") ", not a float approximation of 6.35. The exactness comes from the " (em "value") " type: the same conversion with a rational never accumulates the drift a float would. Sum a third of a millimetre three times and you land back on exactly " (c "1") ", so the comparison against " (cdz "(Rational.of 1 1)") " is " (c "true") ", which floating point can't promise:")
  (runnable
    (source (def (main)
  (let ((t (Rational.of 1 3)))
    (= (+ (+ t t) t) (Rational.of 1 1))))))
  (p "This is the split that makes the CAD model trustworthy: the " (em "model") " (coordinates, dimensions, bolt positions) stays exact in rationals and units, so a bounding box reports true dimensions and a metric-plus-imperial assembly is precise to the fraction. Float only appears at the very end, in the " (em "mesh") " the renderer draws (an arbitrary-angle rotation needs sine and cosine, which aren't rational). Exact where it matters, float only at the geometry kernel, and the " (app-link (route "/cad") " CAD page ") " lets you see a model like this rendered. The " (app-link (route "/calculator") " calculator ") " works in dimensioned quantities too, if you'd rather just do unit arithmetic at a prompt.")
  (why (tenet "Dimensions are checked, then erased") "Units live entirely at compile time. " (cdz "(Qty.of 5.0 meter)") " and the bare " (c "5.0") " emit " (em "byte-identical") " code: the unit is a static claim the checker verifies and then throws away, so a dimensional mismatch is always a compile error (CDZ0501) and never a runtime trap. You get the discipline of dimensional analysis (a length never adds to a time, a velocity is length over time) with zero runtime cost. It's the same principle as the rest of the numeric model: Cadenza refuses to guess what you meant, and here it refuses at the moment you write it.")
  (h2 "A quantity is a value you can key by")
  (p "That erasure is also why a quantity works as a value in its own right: the unit is gone at run time, but the magnitude is a perfectly good map key. Build a map under a five-kilometre quantity, then look it up with a separately-constructed but equal key, and it hits, because quantities compare by content like every other value:")
  (runnable
    (source (def (main)
  (let ((m (Map.insert (Map.empty)
                       (Qty.of 5 (Unit.prefix kilo (Unit.base #"meter"))) 42)))
    (match (Map.lookup m (Qty.of 5 (Unit.prefix kilo (Unit.base #"meter"))))
      ((Some x) x)
      ((None) 0))))))
  (p "The lookup returns " (c "42") ": a quantity assembled twice is one key, not two. The same by-content rule holds from the set side, so two equal quantities in a " (c "Set") " collapse to one. And because units are checked then erased, " (c "5") " kilometres and " (c "5") " metres are different " (em "types") ", not just different values, so the compiler won't let them share a map at all; convert one with " (c "Unit.in") " first if you mean them to meet.")
  (h2 "Your turn")
  (exercise
    (id "units:1")
    (prompt "Convert " (c "3.0") " kilometers into meters with " (c "Unit.in") ". The target unit comes first, then the quantity, and the answer is " (c "3000") ".")
    (starter (Unit.in (Unit.of #"meter")
         (Qty.of 3.0 (Unit.of #"?"))))
    (solution (Unit.in (Unit.of #"meter")
         (Qty.of 3.0 (Unit.of #"kilometer"))))
    (expected "3000.0")
    (hint "A kilometer is a named unit of length, " (c "(Unit.of #\"kilometer\")") ". One kilometer is a thousand meters, so three become " (c "3000") "."))
  (exercise
    (id "units:2")
    (prompt "A distance divided by a time is a speed. Divide " (c "100.0") " meters by " (c "8.0") " seconds and recover the number. The answer is " (c "12.5") " (meters per second).")
    (starter (Qty.value
  (/ (Qty.of 100.0 (Unit.of #"meter"))
     (Qty.of ? (Unit.of #"second")))))
    (solution (Qty.value
  (/ (Qty.of 100.0 (Unit.of #"meter"))
     (Qty.of 8.0 (Unit.of #"second")))))
    (expected "12.5")
    (hint "The unit divides along with the number. You don't spell the " (c "meter/second") " yourself, the division builds it. " (c "100.0 / 8.0") " is " (c "12.5") "."))
  (exercise
    (id "units:3")
    (prompt "Cube a " (c "2.0") "-meter edge with " (c "Qty.pow") " to get a volume in cubic meters. Raising to the power " (c "3") " gives " (c "8") ".")
    (starter (Qty.value (Qty.pow (Qty.of 2.0 (Unit.of #"meter")) ?)))
    (solution (Qty.value (Qty.pow (Qty.of 2.0 (Unit.of #"meter")) 3)))
    (expected "8.0")
    (hint "The second argument to " (c "Qty.pow") " is the exponent. A cube is the third power, so it's " (c "3") ", and " (c "2.0") " cubed is " (c "8") "."))
  (exercise
    (id "units:4")
    (prompt "Define a " (c "span") " as " (c "3") " meters with " (c "Unit.define") ", then convert " (c "4.0") " spans to meters. Four spans is " (c "12") " meters.")
    (starter (Unit.define #"span" (Unit.of #"meter") ? 1)
(def (main)
  (Unit.in (Unit.of #"meter") (Qty.of 4.0 (Unit.of #"span")))))
    (solution (Unit.define #"span" (Unit.of #"meter") 3 1)
(def (main)
  (Unit.in (Unit.of #"meter") (Qty.of 4.0 (Unit.of #"span")))))
    (expected "12.0")
    (hint "The ratio is numerator then denominator, so a span is " (c "3 / 1") " meters. Then " (c "4.0") " spans convert to " (c "4 × 3 = 12") " meters."))
  (exercise
    (id "units:5")
    (prompt "Exact conversion, no rounding. A " (c "1/4") "-inch length is exactly " (c "127/20") " mm. Fill the numerator of the rational quarter-inch so the exactness check gives " (c "true") ".")
    (starter (def (main)
  (= (Unit.in (Unit.of #"millimeter")
              (Qty.of (Rational.of ? 4) (Unit.of #"inch")))
     (Rational.of 127 20))))
    (solution (def (main)
  (= (Unit.in (Unit.of #"millimeter")
              (Qty.of (Rational.of 1 4) (Unit.of #"inch")))
     (Rational.of 127 20))))
    (expected "true")
    (hint "A quarter inch is " (cdz "(Rational.of 1 4)") ", numerator " (c "1") ". One inch is " (c "25.4") " mm, so a quarter is " (c "6.35") " mm, which as an exact fraction is " (c "127/20") ". The check confirms the conversion landed on that rational exactly.")))
