(case "ll1 a LIST-OF-LISTS handler state — each dispatch appends a fresh row, the drain reads a middle row's middle element"
  (input  (do
            (effect Rows (op add (-> Int64 Int64)) (op pick (-> Int64 Int64 Int64)))
            (def (row-at (: xss (List (List Int64))) (: i Int64) (: j Int64))
              (match (List.at xss i)
                ((Some xs) (match (List.at xs j) ((Some v) v) ((None _u) -1)))
                ((None _u) -2)))
            (def (main (: n Int64))
              (handle Rows (list)
                ((add (v) s (resume (List.len s) (List.push s (list v (* v 10) (* v 100)))))
                 (pick (i j) s (resume (row-at s i j) s)))
                (let ((a (Rows.add n)))
                  (let ((b (Rows.add (+ n 1))))
                    (let ((c (Rows.add (+ n 2))))
                      (+ (* 10000 (Rows.pick 1 1))
                         (+ (* 100 (Rows.pick 2 0)) (Rows.pick 0 2))))))))
            (export main)))
  (call   main (: 3 Int64)) (output (: 400800 Int64))
  (call   main (: 0 Int64)) (output (: 100200 Int64)))
