(case "nfc2 a RUNTIME concat producing a decomposed sequence normalizes at construction"
  (input  (do
            (def (main (: k Int64))
              (match (String.from-bytes (Bytes.of (list (UInt8.wrap 101))))
                ((Some e)
                  (match (String.from-bytes (Bytes.of (list (UInt8.wrap 204) (UInt8.wrap 129))))
                    ((Some acc)
                      (let ((joined (String.concat e acc)))
                        (+ (String.byte-len joined)
                           (+ (* 10 (String.scalar-len joined))
                              (* 100 (if (= joined "é") 1 0))))))
                    ((None _u) -2)))
                ((None _u) -1)))
            (export main)))
  (call   main (: 0 Int64)) (output (: 112 Int64)))
