(case "nfd2 NFC reorders OUT-OF-ORDER combining marks to canonical class order before composing"
  (input  (do
            (def (main (: k Int64))
              (match (String.from-bytes (Bytes.of (list (UInt8.wrap 101))))
                ((Some e)
                  (match (String.from-bytes (Bytes.of (list (UInt8.wrap 204) (UInt8.wrap 136))))
                    ((Some diaeresis)
                      (match (String.from-bytes (Bytes.of (list (UInt8.wrap 204) (UInt8.wrap 129))))
                        ((Some acute)
                          (let ((ad (String.concat e (String.concat acute diaeresis)))
                                (da (String.concat e (String.concat diaeresis acute))))
                            (+ (if (= ad da) 1 0)
                               (+ (* 10 (String.scalar-len ad))
                                  (* 100 (String.scalar-len da))))))
                        ((None _u) -3)))
                    ((None _u) -2)))
                ((None _u) -1)))
            (export main)))
  (call   main (: 0 Int64)) (output (: 220 Int64)))
