(case "nfd5 NFC REORDERS different-ccc marks: ogonek(202) after acute(230) sorts ogonek first, composes ę́"
  (input  (do
            (def (main (: k Int64))
              (match (String.from-bytes (Bytes.of (list (UInt8.wrap 101))))
                ((Some e)
                  (match (String.from-bytes (Bytes.of (list (UInt8.wrap 204) (UInt8.wrap 129))))
                    ((Some acute)
                      (match (String.from-bytes (Bytes.of (list (UInt8.wrap 204) (UInt8.wrap 168))))
                        ((Some ogonek)
                          (let ((oa (String.concat e (String.concat ogonek acute)))
                                (ao (String.concat e (String.concat acute ogonek))))
                            (+ (if (= oa ao) 1 0)
                               (+ (* 10 (String.scalar-len oa))
                                  (* 100 (String.byte-len oa))))))
                        ((None _u) -3)))
                    ((None _u) -2)))
                ((None _u) -1)))
            (export main)))
  (call   main (: 0 Int64)) (output (: 421 Int64)))
