(case "dh2 value-cmp orders two SHARED-prefix lists and value-eq a map — borrows reclaim, originals stay readable"
  (input  (do
            (def (mk (: n Int64))
              (Map.insert (Map.insert Map.empty 1 n) 2 (* n 10)))
            (def (main (: n Int64))
              (let ((m (mk n)))
                (let ((xs (list n (+ n 1))))
                  (let ((ys (List.push xs 7)))
                    (+ (if (< xs ys) 100 200)
                       (+ (if (= m m) 10 20)
                          (+ (match (Map.lookup m 2) ((Some v) v) ((None _u) -7))
                             (match (List.at xs 1) ((Some w) (* 1000 w)) ((None _u) -9)))))))))
            (export main)))
  (call   main (: 4 Int64)) (output (: 5150 Int64))
  (call   main (: 0 Int64)) (output (: 1110 Int64)))
