(case "swp1 an ATOMIC slot swap — the swap dispatch exchanges both tuple fields in one transition, reads before and after pin the exchange"
  (input  (do
            (effect S (op geta (-> Int64)) (op getb (-> Int64)) (op swap (-> Int64)))
            (def (main (: n Int64))
              (handle S (tuple n 100)
                ((geta () st (match st ((tuple a b) (resume a st))))
                 (getb () st (match st ((tuple a b) (resume b st))))
                 (swap () st (match st ((tuple a b) (resume (+ a b) (tuple b a))))))
                (let ((a1 (S.geta)))
                  (let ((_s (S.swap)))
                    (let ((a2 (S.geta)))
                      (let ((b2 (S.getb)))
                        (+ (* 100000 a1) (+ (* 100 a2) b2))))))))
            (export main)))
  (call   main (: 7 Int64)) (output (: 710007 Int64))
  (call   main (: 0 Int64)) (output (: 10000 Int64)))
