//! @generated by `cargo xtask codegen` from cdz-runtime/wit/runtime.wit — DO NOT hand-edit.
//!
//! The value-heap runtime's ABI as STRUCTURED data: each op's name + core signature, a typed
//! `OPS` accessor, the interface name, and the runtime's content hash. The wasm backend builds a
//! program's per-program import section from this (importing only the ops it uses) — no opaque
//! envelope blob, no baked-in op index (imports resolve by name). Regenerate with `cargo xtask
//! codegen`; `cargo xtask codegen --check` (a hard gate in `xtask check`) fails if it drifts from
//! the runtime WIT or the built runtime's bytes. Plain data — no dependency, so it ships.

/// The LOGICAL value type of a runtime op's param/result, as the WIT declares it (the
/// runtime interface uses only these four). Kept logical, NOT collapsed to a core valtype,
/// because the two envelope surfaces need different projections that are not recoverable from
/// each other: a core `i32` is the lowering of `u32`, `bool` AND `s32` alike, so the COMPONENT
/// import instance-type (which must structurally match the runtime's exported type) cannot be
/// rebuilt from the core byte. `core_byte` is the core-module import functype's valtype;
/// `comp_byte` is the component instance-type's primitive valtype. Both are wasm-spec
/// constants (a TARGET concern) so they live here in the backend, not in the generated data.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum AbiValType {
    U32,
    S64,
    Bool,
    F64,
}
impl AbiValType {
    /// The CORE wasm valtype byte a lowered handle/scalar occupies (i32=0x7F, i64=0x7E,
    /// f64=0x7C) — a `u32` handle / `bool` both lower to i32.
    pub fn core_byte(self) -> u8 {
        match self {
            AbiValType::U32 | AbiValType::Bool => 0x7F,
            AbiValType::S64 => 0x7E,
            AbiValType::F64 => 0x7C,
        }
    }
    /// The COMPONENT-model primitive valtype byte (u32=0x79, s64=0x78, bool=0x7F, f64=0x75) —
    /// the faithful boundary type the import instance-type declares.
    pub fn comp_byte(self) -> u8 {
        match self {
            AbiValType::U32 => 0x79,
            AbiValType::S64 => 0x78,
            AbiValType::Bool => 0x7F,
            AbiValType::F64 => 0x75,
        }
    }
}
/// One value-heap runtime op the compiler may import: its WIT name and logical signature. A
/// non-`lowerable` op carries a non-scalar WIT type (string/tuple) the bare-core envelope
/// cannot import; it is listed for completeness but never selected.
pub struct RtOp {
    pub name: &'static str,
    pub params: &'static [AbiValType],
    pub result: Option<AbiValType>,
    pub lowerable: bool,
}
/// The runtime interface a program imports — the fixed ABI identity, prefix of the
/// versioned `<iface>@…+<hash>` import name (`component-abi.md` §The Value-Heap Runtime
/// Crosses By A Well-Known Import). The content-address suffix is `REQUIRED_RUNTIME_HASH`.
pub const RUNTIME_IFACE: &str = "cadenza:runtime/heap";
/// The SHA-256 content address of the value-heap runtime component this ABI was generated
/// against — the runtime a program built with this compiler requires. Regenerated from the
/// built runtime bytes, so it tracks a runtime-code change automatically.
pub const REQUIRED_RUNTIME_HASH: &str =
    "29ef75cb61ecce418eeb32d6653c6b23c31b5b2a734ee8497bfa5a26d4d610fc";
/// The SHA-256 content address of the DEBUG-COUNTERS runtime build — the same runtime code
/// with the `live-objects` leak counter compiled in (`--features debug-counters`). A shipped
/// program pins `REQUIRED_RUNTIME_HASH` (the release build); a Perceus leak-check harness
/// composes THIS build to assert `live-objects == 0` after a run. Recorded here so the harness
/// locates the debug runtime by content address (from the store), never by rebuilding it.
pub const DEBUG_RUNTIME_HASH: &str =
    "ccdba349236a09952117af252cc044bd20be48d8e051dd635541f0112ea3a5db";
/// Every op the runtime `heap` interface declares, as structured signature data (sorted).
pub const RUNTIME_OPS: &[RtOp] = &[
    RtOp {
        name: "arr-alloc",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "arr-alloc-reuse",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "arr-get",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "arr-len",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "arr-set",
        params: &[AbiValType::U32, AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "box-bool",
        params: &[AbiValType::Bool],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "box-float",
        params: &[AbiValType::F64],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "box-int",
        params: &[AbiValType::S64],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "bytes-alloc",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "bytes-compact",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "bytes-concat",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "bytes-get",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "bytes-len",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "bytes-set",
        params: &[AbiValType::U32, AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "bytes-slice",
        params: &[AbiValType::U32, AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "drop",
        params: &[AbiValType::U32],
        result: None,
        lowerable: true,
    },
    RtOp {
        name: "dup",
        params: &[AbiValType::U32],
        result: None,
        lowerable: true,
    },
    RtOp {
        name: "get-bool",
        params: &[AbiValType::U32],
        result: Some(AbiValType::Bool),
        lowerable: true,
    },
    RtOp {
        name: "get-float",
        params: &[AbiValType::U32],
        result: Some(AbiValType::F64),
        lowerable: true,
    },
    RtOp {
        name: "get-int",
        params: &[AbiValType::U32],
        result: Some(AbiValType::S64),
        lowerable: true,
    },
    RtOp {
        name: "live-objects",
        params: &[],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-alloc",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-empty",
        params: &[],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-insert",
        params: &[AbiValType::U32, AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-iter",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-iter-key",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-iter-next",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-iter-val",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-key",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-len",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-lookup",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-remove",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-set",
        params: &[
            AbiValType::U32,
            AbiValType::U32,
            AbiValType::U32,
            AbiValType::U32,
        ],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-size",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-val",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "reset",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "set-contains",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::Bool),
        lowerable: true,
    },
    RtOp {
        name: "set-difference",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "set-empty",
        params: &[],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "set-insert",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "set-intersection",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "set-iter",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "set-iter-elem",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "set-iter-next",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "set-remove",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "set-size",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "set-union",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "str-get",
        params: &[AbiValType::U32],
        result: None,
        lowerable: false,
    },
    RtOp {
        name: "str-new",
        params: &[],
        result: Some(AbiValType::U32),
        lowerable: false,
    },
    RtOp {
        name: "sum-disc",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "sum-new",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "sum-new-reuse",
        params: &[AbiValType::U32, AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "sum-payload",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "vec-concat",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "vec-empty",
        params: &[],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "vec-get",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "vec-len",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "vec-push",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "vec-split",
        params: &[AbiValType::U32, AbiValType::U32],
        result: None,
        lowerable: false,
    },
    RtOp {
        name: "vec-update",
        params: &[AbiValType::U32, AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
];
/// Typed access to each runtime op by name — `OPS.arr_get` borrows `&RUNTIME_OPS[i]`. A
/// field per op (kebab-case WIT name → snake_case field), so a rename in the WIT is a
/// compile error at every use rather than a silent stringly-typed miss.
pub struct RuntimeOps {
    pub arr_alloc: &'static RtOp,
    pub arr_alloc_reuse: &'static RtOp,
    pub arr_get: &'static RtOp,
    pub arr_len: &'static RtOp,
    pub arr_set: &'static RtOp,
    pub box_bool: &'static RtOp,
    pub box_float: &'static RtOp,
    pub box_int: &'static RtOp,
    pub bytes_alloc: &'static RtOp,
    pub bytes_compact: &'static RtOp,
    pub bytes_concat: &'static RtOp,
    pub bytes_get: &'static RtOp,
    pub bytes_len: &'static RtOp,
    pub bytes_set: &'static RtOp,
    pub bytes_slice: &'static RtOp,
    pub drop: &'static RtOp,
    pub dup: &'static RtOp,
    pub get_bool: &'static RtOp,
    pub get_float: &'static RtOp,
    pub get_int: &'static RtOp,
    pub live_objects: &'static RtOp,
    pub map_alloc: &'static RtOp,
    pub map_empty: &'static RtOp,
    pub map_insert: &'static RtOp,
    pub map_iter: &'static RtOp,
    pub map_iter_key: &'static RtOp,
    pub map_iter_next: &'static RtOp,
    pub map_iter_val: &'static RtOp,
    pub map_key: &'static RtOp,
    pub map_len: &'static RtOp,
    pub map_lookup: &'static RtOp,
    pub map_remove: &'static RtOp,
    pub map_set: &'static RtOp,
    pub map_size: &'static RtOp,
    pub map_val: &'static RtOp,
    pub reset: &'static RtOp,
    pub set_contains: &'static RtOp,
    pub set_difference: &'static RtOp,
    pub set_empty: &'static RtOp,
    pub set_insert: &'static RtOp,
    pub set_intersection: &'static RtOp,
    pub set_iter: &'static RtOp,
    pub set_iter_elem: &'static RtOp,
    pub set_iter_next: &'static RtOp,
    pub set_remove: &'static RtOp,
    pub set_size: &'static RtOp,
    pub set_union: &'static RtOp,
    pub str_get: &'static RtOp,
    pub str_new: &'static RtOp,
    pub sum_disc: &'static RtOp,
    pub sum_new: &'static RtOp,
    pub sum_new_reuse: &'static RtOp,
    pub sum_payload: &'static RtOp,
    pub vec_concat: &'static RtOp,
    pub vec_empty: &'static RtOp,
    pub vec_get: &'static RtOp,
    pub vec_len: &'static RtOp,
    pub vec_push: &'static RtOp,
    pub vec_split: &'static RtOp,
    pub vec_update: &'static RtOp,
}
/// The one `RuntimeOps` value — each field borrows its entry in `RUNTIME_OPS` by offset.
pub const OPS: RuntimeOps = RuntimeOps {
    arr_alloc: &RUNTIME_OPS[0],
    arr_alloc_reuse: &RUNTIME_OPS[1],
    arr_get: &RUNTIME_OPS[2],
    arr_len: &RUNTIME_OPS[3],
    arr_set: &RUNTIME_OPS[4],
    box_bool: &RUNTIME_OPS[5],
    box_float: &RUNTIME_OPS[6],
    box_int: &RUNTIME_OPS[7],
    bytes_alloc: &RUNTIME_OPS[8],
    bytes_compact: &RUNTIME_OPS[9],
    bytes_concat: &RUNTIME_OPS[10],
    bytes_get: &RUNTIME_OPS[11],
    bytes_len: &RUNTIME_OPS[12],
    bytes_set: &RUNTIME_OPS[13],
    bytes_slice: &RUNTIME_OPS[14],
    drop: &RUNTIME_OPS[15],
    dup: &RUNTIME_OPS[16],
    get_bool: &RUNTIME_OPS[17],
    get_float: &RUNTIME_OPS[18],
    get_int: &RUNTIME_OPS[19],
    live_objects: &RUNTIME_OPS[20],
    map_alloc: &RUNTIME_OPS[21],
    map_empty: &RUNTIME_OPS[22],
    map_insert: &RUNTIME_OPS[23],
    map_iter: &RUNTIME_OPS[24],
    map_iter_key: &RUNTIME_OPS[25],
    map_iter_next: &RUNTIME_OPS[26],
    map_iter_val: &RUNTIME_OPS[27],
    map_key: &RUNTIME_OPS[28],
    map_len: &RUNTIME_OPS[29],
    map_lookup: &RUNTIME_OPS[30],
    map_remove: &RUNTIME_OPS[31],
    map_set: &RUNTIME_OPS[32],
    map_size: &RUNTIME_OPS[33],
    map_val: &RUNTIME_OPS[34],
    reset: &RUNTIME_OPS[35],
    set_contains: &RUNTIME_OPS[36],
    set_difference: &RUNTIME_OPS[37],
    set_empty: &RUNTIME_OPS[38],
    set_insert: &RUNTIME_OPS[39],
    set_intersection: &RUNTIME_OPS[40],
    set_iter: &RUNTIME_OPS[41],
    set_iter_elem: &RUNTIME_OPS[42],
    set_iter_next: &RUNTIME_OPS[43],
    set_remove: &RUNTIME_OPS[44],
    set_size: &RUNTIME_OPS[45],
    set_union: &RUNTIME_OPS[46],
    str_get: &RUNTIME_OPS[47],
    str_new: &RUNTIME_OPS[48],
    sum_disc: &RUNTIME_OPS[49],
    sum_new: &RUNTIME_OPS[50],
    sum_new_reuse: &RUNTIME_OPS[51],
    sum_payload: &RUNTIME_OPS[52],
    vec_concat: &RUNTIME_OPS[53],
    vec_empty: &RUNTIME_OPS[54],
    vec_get: &RUNTIME_OPS[55],
    vec_len: &RUNTIME_OPS[56],
    vec_push: &RUNTIME_OPS[57],
    vec_split: &RUNTIME_OPS[58],
    vec_update: &RUNTIME_OPS[59],
};
