//! @generated by `cargo xtask codegen` from cdz-runtime/wit/runtime.wit — DO NOT hand-edit.
//!
//! The value-heap runtime's ABI as STRUCTURED data: each op's name + core signature, a typed
//! `OPS` accessor, the interface name, and the runtime's content hash. The wasm backend builds a
//! program's per-program import section from this (importing only the ops it uses) — no opaque
//! envelope blob, no baked-in op index (imports resolve by name). Regenerate with `cargo xtask
//! codegen`; `cargo xtask codegen --check` (a hard gate in `xtask check`) fails if it drifts from
//! the runtime WIT or the built runtime's bytes. Plain data — no dependency, so it ships.

/// The LOGICAL value type of a runtime op's param/result, as the WIT declares it (the
/// runtime interface uses only these four). Kept logical, NOT collapsed to a core valtype,
/// because the two envelope surfaces need different projections that are not recoverable from
/// each other: a core `i32` is the lowering of `u32`, `bool` AND `s32` alike, so the COMPONENT
/// import instance-type (which must structurally match the runtime's exported type) cannot be
/// rebuilt from the core byte. `core_byte` is the core-module import functype's valtype;
/// `comp_byte` is the component instance-type's primitive valtype. Both are wasm-spec
/// constants (a TARGET concern) so they live here in the backend, not in the generated data.
/// The runtime interface itself uses only `U32`/`S64`/`Bool`/`F64`/`F32`; the remaining
/// variants (the narrower aliased int widths `S8`/`U8`/`S16`/`U16`/`S32`/`U64`, and `Char`)
/// are used by the HOST-op boundary (`host::abi_val_type`), where a delegated effect operation
/// may carry any aliased scalar as a parameter or result — each crosses as its faithful
/// component-model primitive, lowered to the core i32/i64/f32/f64 slot the canonical ABI uses.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum AbiValType {
    U32,
    S64,
    Bool,
    F64,
    F32,
    S8,
    U8,
    S16,
    U16,
    S32,
    U64,
    Char,
}
impl AbiValType {
    /// The CORE wasm valtype byte a lowered scalar occupies (i32=0x7F, i64=0x7E, f64=0x7C,
    /// f32=0x7D). A `u32` handle / `bool` / `char` / every aliased int of width ≤32 lowers to
    /// core i32 (the canonical ABI sign/zero-extends a narrow value into the i32 slot); a 64-bit
    /// int is i64.
    pub fn core_byte(self) -> u8 {
        match self {
            AbiValType::U32
            | AbiValType::Bool
            | AbiValType::S8
            | AbiValType::U8
            | AbiValType::S16
            | AbiValType::U16
            | AbiValType::S32
            | AbiValType::Char => 0x7F,
            AbiValType::S64 | AbiValType::U64 => 0x7E,
            AbiValType::F64 => 0x7C,
            AbiValType::F32 => 0x7D,
        }
    }
    /// The COMPONENT-model primitive valtype byte — the faithful boundary type the import
    /// instance-type declares (wasm-spec constants: bool=0x7F, s8=0x7E, u8=0x7D, s16=0x7C,
    /// u16=0x7B, s32=0x7A, u32=0x79, s64=0x78, u64=0x77, f32=0x76, f64=0x75, char=0x74).
    pub fn comp_byte(self) -> u8 {
        match self {
            AbiValType::Bool => 0x7F,
            AbiValType::S8 => 0x7E,
            AbiValType::U8 => 0x7D,
            AbiValType::S16 => 0x7C,
            AbiValType::U16 => 0x7B,
            AbiValType::S32 => 0x7A,
            AbiValType::U32 => 0x79,
            AbiValType::S64 => 0x78,
            AbiValType::U64 => 0x77,
            AbiValType::F32 => 0x76,
            AbiValType::F64 => 0x75,
            AbiValType::Char => 0x74,
        }
    }
}
/// One value-heap runtime op the compiler may import: its WIT name and logical signature. A
/// non-`lowerable` op carries a non-scalar WIT type (string/tuple) the bare-core envelope
/// cannot import; it is listed for completeness but never selected.
pub struct RtOp {
    pub name: &'static str,
    pub params: &'static [AbiValType],
    pub result: Option<AbiValType>,
    pub lowerable: bool,
}
/// The runtime interface a program imports — the fixed ABI identity, prefix of the
/// versioned `<iface>@…+<hash>` import name (`component-abi.md` §The Value-Heap Runtime
/// Crosses By A Well-Known Import). The content-address suffix is `REQUIRED_RUNTIME_HASH`.
pub const RUNTIME_IFACE: &str = "cadenza:runtime/heap";
/// The three runtime CONTENT-HASH consts (`REQUIRED_RUNTIME_HASH` / `DEBUG_RUNTIME_HASH` /
/// `REQUIRED_NFC_HASH`) live in `cadenza-compile-abi::runtime_hash` (generated by the same
/// `cargo xtask codegen`) so the thin `!standalone` `cdz` dispatcher reads them WITHOUT linking
/// `rcdzc`; re-exported here so every `rcdzc::backend::wasm::runtime_abi::REQUIRED_RUNTIME_HASH`
/// reference (incl. the compiler's own runtime-stamp path) stays byte-stable.
pub use cadenza_compile_abi::runtime_hash::{
    DEBUG_RUNTIME_HASH, REQUIRED_NFC_HASH, REQUIRED_RUNTIME_HASH,
};
/// The NFC-normalization interface — the plain WIT name the value-heap RUNTIME imports for
/// Unicode Normalization Form C. FINDING#23 (operator ruling d): NFC lives in a SEPARATE
/// component (the heavy `unicode-normalization` tables); the runtime's WIT `world` declares
/// `import cadenza:nfc/normalize` (a runtime-world dep under this PLAIN iface name — NOT a
/// program-emitted versioned `@…+<hash>` import), and the host composes the NFC component into
/// the runtime by content hash. The compiler emits NO program-side NFC import; this const is
/// the interface name the host matches when composing (see cdz-run compose_nfc_into_runtime_linker).
pub const NFC_IFACE: &str = "cadenza:nfc/normalize";
/// The runtime's INLINE-UNIT handle — the value `arr-alloc(0)` returns (a compile-time-known
/// handle carrying the empty tuple/unit, no heap node). DERIVED from the runtime's `cdz-abi`
/// custom section (read at codegen, then stripped), so the compiler can push it as a constant
/// for a unit payload (a nullary sum variant, an empty tuple/record/list) instead of emitting
/// a runtime `arr-alloc(0)` CALL. Guarded by the content hash — never hand-transcribed.
pub const IMM_UNIT: u32 = 2u32;
/// Every op the runtime `heap` interface declares, as structured signature data (sorted).
pub const RUNTIME_OPS: &[RtOp] = &[
    RtOp {
        name: "arr-alloc",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "arr-alloc-reuse",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "arr-get",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "arr-len",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "arr-set",
        params: &[AbiValType::U32, AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "ast-decode",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "ast-encode",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "ast-print",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "bigint-add",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "bigint-cmp",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::S64),
        lowerable: true,
    },
    RtOp {
        name: "bigint-div",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "bigint-mul",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "bigint-of-bytes",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "bigint-of-i64",
        params: &[AbiValType::S64],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "bigint-rem",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "bigint-sub",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "bigint-to-i64-checked",
        params: &[AbiValType::U32],
        result: Some(AbiValType::S64),
        lowerable: true,
    },
    RtOp {
        name: "box-bool",
        params: &[AbiValType::Bool],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "box-float",
        params: &[AbiValType::F64],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "box-float32",
        params: &[AbiValType::F32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "box-int",
        params: &[AbiValType::S64],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "bytes-alloc",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "bytes-compact",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "bytes-concat",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "bytes-get",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "bytes-len",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "bytes-scalar-at",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "bytes-set",
        params: &[AbiValType::U32, AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "bytes-slice",
        params: &[AbiValType::U32, AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "drop",
        params: &[AbiValType::U32],
        result: None,
        lowerable: true,
    },
    RtOp {
        name: "dup",
        params: &[AbiValType::U32],
        result: None,
        lowerable: true,
    },
    RtOp {
        name: "get-bool",
        params: &[AbiValType::U32],
        result: Some(AbiValType::Bool),
        lowerable: true,
    },
    RtOp {
        name: "get-float",
        params: &[AbiValType::U32],
        result: Some(AbiValType::F64),
        lowerable: true,
    },
    RtOp {
        name: "get-float32",
        params: &[AbiValType::U32],
        result: Some(AbiValType::F32),
        lowerable: true,
    },
    RtOp {
        name: "get-int",
        params: &[AbiValType::U32],
        result: Some(AbiValType::S64),
        lowerable: true,
    },
    RtOp {
        name: "hash-blake3",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "live-objects",
        params: &[],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-alloc",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-empty",
        params: &[],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-insert",
        params: &[AbiValType::U32, AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-iter",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-iter-key",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-iter-next",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-iter-val",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-key",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-len",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-lookup",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-merge",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-remove",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-set",
        params: &[
            AbiValType::U32,
            AbiValType::U32,
            AbiValType::U32,
            AbiValType::U32,
        ],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-size",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-to-list",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "map-val",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "mark-immortal",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "mark-immortal-deep",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "rational-add",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "rational-cmp",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::S64),
        lowerable: true,
    },
    RtOp {
        name: "rational-den",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "rational-div",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "rational-mul",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "rational-num",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "rational-of",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "rational-sub",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "reset",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "set-contains",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::Bool),
        lowerable: true,
    },
    RtOp {
        name: "set-difference",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "set-empty",
        params: &[],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "set-insert",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "set-intersection",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "set-iter",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "set-iter-elem",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "set-iter-next",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "set-remove",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "set-size",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "set-to-list",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "set-union",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "str-from-bytes",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "str-get",
        params: &[AbiValType::U32],
        result: None,
        lowerable: false,
    },
    RtOp {
        name: "str-new",
        params: &[],
        result: Some(AbiValType::U32),
        lowerable: false,
    },
    RtOp {
        name: "str-nfc-normalize",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "sum-disc",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "sum-new",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "sum-new-reuse",
        params: &[AbiValType::U32, AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "sum-payload",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "value-canonicalize",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "value-cmp",
        params: &[AbiValType::U32, AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::S32),
        lowerable: true,
    },
    RtOp {
        name: "value-decode",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "value-encode",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "value-eq",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::Bool),
        lowerable: true,
    },
    RtOp {
        name: "value-eq-shaped",
        params: &[AbiValType::U32, AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::Bool),
        lowerable: true,
    },
    RtOp {
        name: "vec-concat",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "vec-drop",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "vec-empty",
        params: &[],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "vec-get",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "vec-len",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "vec-of-arr",
        params: &[AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "vec-prepend",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "vec-push",
        params: &[AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
    RtOp {
        name: "vec-split",
        params: &[AbiValType::U32, AbiValType::U32],
        result: None,
        lowerable: false,
    },
    RtOp {
        name: "vec-update",
        params: &[AbiValType::U32, AbiValType::U32, AbiValType::U32],
        result: Some(AbiValType::U32),
        lowerable: true,
    },
];
/// Typed access to each runtime op by name — `OPS.arr_get` borrows `&RUNTIME_OPS[i]`. A
/// field per op (kebab-case WIT name → snake_case field), so a rename in the WIT is a
/// compile error at every use rather than a silent stringly-typed miss.
pub struct RuntimeOps {
    pub arr_alloc: &'static RtOp,
    pub arr_alloc_reuse: &'static RtOp,
    pub arr_get: &'static RtOp,
    pub arr_len: &'static RtOp,
    pub arr_set: &'static RtOp,
    pub ast_decode: &'static RtOp,
    pub ast_encode: &'static RtOp,
    pub ast_print: &'static RtOp,
    pub bigint_add: &'static RtOp,
    pub bigint_cmp: &'static RtOp,
    pub bigint_div: &'static RtOp,
    pub bigint_mul: &'static RtOp,
    pub bigint_of_bytes: &'static RtOp,
    pub bigint_of_i64: &'static RtOp,
    pub bigint_rem: &'static RtOp,
    pub bigint_sub: &'static RtOp,
    pub bigint_to_i64_checked: &'static RtOp,
    pub box_bool: &'static RtOp,
    pub box_float: &'static RtOp,
    pub box_float32: &'static RtOp,
    pub box_int: &'static RtOp,
    pub bytes_alloc: &'static RtOp,
    pub bytes_compact: &'static RtOp,
    pub bytes_concat: &'static RtOp,
    pub bytes_get: &'static RtOp,
    pub bytes_len: &'static RtOp,
    pub bytes_scalar_at: &'static RtOp,
    pub bytes_set: &'static RtOp,
    pub bytes_slice: &'static RtOp,
    pub drop: &'static RtOp,
    pub dup: &'static RtOp,
    pub get_bool: &'static RtOp,
    pub get_float: &'static RtOp,
    pub get_float32: &'static RtOp,
    pub get_int: &'static RtOp,
    pub hash_blake3: &'static RtOp,
    pub live_objects: &'static RtOp,
    pub map_alloc: &'static RtOp,
    pub map_empty: &'static RtOp,
    pub map_insert: &'static RtOp,
    pub map_iter: &'static RtOp,
    pub map_iter_key: &'static RtOp,
    pub map_iter_next: &'static RtOp,
    pub map_iter_val: &'static RtOp,
    pub map_key: &'static RtOp,
    pub map_len: &'static RtOp,
    pub map_lookup: &'static RtOp,
    pub map_merge: &'static RtOp,
    pub map_remove: &'static RtOp,
    pub map_set: &'static RtOp,
    pub map_size: &'static RtOp,
    pub map_to_list: &'static RtOp,
    pub map_val: &'static RtOp,
    pub mark_immortal: &'static RtOp,
    pub mark_immortal_deep: &'static RtOp,
    pub rational_add: &'static RtOp,
    pub rational_cmp: &'static RtOp,
    pub rational_den: &'static RtOp,
    pub rational_div: &'static RtOp,
    pub rational_mul: &'static RtOp,
    pub rational_num: &'static RtOp,
    pub rational_of: &'static RtOp,
    pub rational_sub: &'static RtOp,
    pub reset: &'static RtOp,
    pub set_contains: &'static RtOp,
    pub set_difference: &'static RtOp,
    pub set_empty: &'static RtOp,
    pub set_insert: &'static RtOp,
    pub set_intersection: &'static RtOp,
    pub set_iter: &'static RtOp,
    pub set_iter_elem: &'static RtOp,
    pub set_iter_next: &'static RtOp,
    pub set_remove: &'static RtOp,
    pub set_size: &'static RtOp,
    pub set_to_list: &'static RtOp,
    pub set_union: &'static RtOp,
    pub str_from_bytes: &'static RtOp,
    pub str_get: &'static RtOp,
    pub str_new: &'static RtOp,
    pub str_nfc_normalize: &'static RtOp,
    pub sum_disc: &'static RtOp,
    pub sum_new: &'static RtOp,
    pub sum_new_reuse: &'static RtOp,
    pub sum_payload: &'static RtOp,
    pub value_canonicalize: &'static RtOp,
    pub value_cmp: &'static RtOp,
    pub value_decode: &'static RtOp,
    pub value_encode: &'static RtOp,
    pub value_eq: &'static RtOp,
    pub value_eq_shaped: &'static RtOp,
    pub vec_concat: &'static RtOp,
    pub vec_drop: &'static RtOp,
    pub vec_empty: &'static RtOp,
    pub vec_get: &'static RtOp,
    pub vec_len: &'static RtOp,
    pub vec_of_arr: &'static RtOp,
    pub vec_prepend: &'static RtOp,
    pub vec_push: &'static RtOp,
    pub vec_split: &'static RtOp,
    pub vec_update: &'static RtOp,
}
/// The one `RuntimeOps` value — each field borrows its entry in `RUNTIME_OPS` by offset.
pub const OPS: RuntimeOps = RuntimeOps {
    arr_alloc: &RUNTIME_OPS[0],
    arr_alloc_reuse: &RUNTIME_OPS[1],
    arr_get: &RUNTIME_OPS[2],
    arr_len: &RUNTIME_OPS[3],
    arr_set: &RUNTIME_OPS[4],
    ast_decode: &RUNTIME_OPS[5],
    ast_encode: &RUNTIME_OPS[6],
    ast_print: &RUNTIME_OPS[7],
    bigint_add: &RUNTIME_OPS[8],
    bigint_cmp: &RUNTIME_OPS[9],
    bigint_div: &RUNTIME_OPS[10],
    bigint_mul: &RUNTIME_OPS[11],
    bigint_of_bytes: &RUNTIME_OPS[12],
    bigint_of_i64: &RUNTIME_OPS[13],
    bigint_rem: &RUNTIME_OPS[14],
    bigint_sub: &RUNTIME_OPS[15],
    bigint_to_i64_checked: &RUNTIME_OPS[16],
    box_bool: &RUNTIME_OPS[17],
    box_float: &RUNTIME_OPS[18],
    box_float32: &RUNTIME_OPS[19],
    box_int: &RUNTIME_OPS[20],
    bytes_alloc: &RUNTIME_OPS[21],
    bytes_compact: &RUNTIME_OPS[22],
    bytes_concat: &RUNTIME_OPS[23],
    bytes_get: &RUNTIME_OPS[24],
    bytes_len: &RUNTIME_OPS[25],
    bytes_scalar_at: &RUNTIME_OPS[26],
    bytes_set: &RUNTIME_OPS[27],
    bytes_slice: &RUNTIME_OPS[28],
    drop: &RUNTIME_OPS[29],
    dup: &RUNTIME_OPS[30],
    get_bool: &RUNTIME_OPS[31],
    get_float: &RUNTIME_OPS[32],
    get_float32: &RUNTIME_OPS[33],
    get_int: &RUNTIME_OPS[34],
    hash_blake3: &RUNTIME_OPS[35],
    live_objects: &RUNTIME_OPS[36],
    map_alloc: &RUNTIME_OPS[37],
    map_empty: &RUNTIME_OPS[38],
    map_insert: &RUNTIME_OPS[39],
    map_iter: &RUNTIME_OPS[40],
    map_iter_key: &RUNTIME_OPS[41],
    map_iter_next: &RUNTIME_OPS[42],
    map_iter_val: &RUNTIME_OPS[43],
    map_key: &RUNTIME_OPS[44],
    map_len: &RUNTIME_OPS[45],
    map_lookup: &RUNTIME_OPS[46],
    map_merge: &RUNTIME_OPS[47],
    map_remove: &RUNTIME_OPS[48],
    map_set: &RUNTIME_OPS[49],
    map_size: &RUNTIME_OPS[50],
    map_to_list: &RUNTIME_OPS[51],
    map_val: &RUNTIME_OPS[52],
    mark_immortal: &RUNTIME_OPS[53],
    mark_immortal_deep: &RUNTIME_OPS[54],
    rational_add: &RUNTIME_OPS[55],
    rational_cmp: &RUNTIME_OPS[56],
    rational_den: &RUNTIME_OPS[57],
    rational_div: &RUNTIME_OPS[58],
    rational_mul: &RUNTIME_OPS[59],
    rational_num: &RUNTIME_OPS[60],
    rational_of: &RUNTIME_OPS[61],
    rational_sub: &RUNTIME_OPS[62],
    reset: &RUNTIME_OPS[63],
    set_contains: &RUNTIME_OPS[64],
    set_difference: &RUNTIME_OPS[65],
    set_empty: &RUNTIME_OPS[66],
    set_insert: &RUNTIME_OPS[67],
    set_intersection: &RUNTIME_OPS[68],
    set_iter: &RUNTIME_OPS[69],
    set_iter_elem: &RUNTIME_OPS[70],
    set_iter_next: &RUNTIME_OPS[71],
    set_remove: &RUNTIME_OPS[72],
    set_size: &RUNTIME_OPS[73],
    set_to_list: &RUNTIME_OPS[74],
    set_union: &RUNTIME_OPS[75],
    str_from_bytes: &RUNTIME_OPS[76],
    str_get: &RUNTIME_OPS[77],
    str_new: &RUNTIME_OPS[78],
    str_nfc_normalize: &RUNTIME_OPS[79],
    sum_disc: &RUNTIME_OPS[80],
    sum_new: &RUNTIME_OPS[81],
    sum_new_reuse: &RUNTIME_OPS[82],
    sum_payload: &RUNTIME_OPS[83],
    value_canonicalize: &RUNTIME_OPS[84],
    value_cmp: &RUNTIME_OPS[85],
    value_decode: &RUNTIME_OPS[86],
    value_encode: &RUNTIME_OPS[87],
    value_eq: &RUNTIME_OPS[88],
    value_eq_shaped: &RUNTIME_OPS[89],
    vec_concat: &RUNTIME_OPS[90],
    vec_drop: &RUNTIME_OPS[91],
    vec_empty: &RUNTIME_OPS[92],
    vec_get: &RUNTIME_OPS[93],
    vec_len: &RUNTIME_OPS[94],
    vec_of_arr: &RUNTIME_OPS[95],
    vec_prepend: &RUNTIME_OPS[96],
    vec_push: &RUNTIME_OPS[97],
    vec_split: &RUNTIME_OPS[98],
    vec_update: &RUNTIME_OPS[99],
};
