//! @generated by `cargo xtask codegen` from the `wasm-encoder` crate — DO NOT hand-edit.
//!
//! Every wasm / component-model byte the backend emits, EXTRACTED from `wasm-encoder` (the spec
//! byte encoder): the core opcode table, core + component valtype bytes, core + component section
//! ids, the two magic headers, and the functype form bytes. `codegen` encodes a one-off value
//! with `wasm-encoder` and reads the byte back, so nothing here is hand-transcribed. Regenerate
//! with `cargo xtask codegen`; `cargo xtask codegen --check` (a hard gate in `xtask check`) fails
//! if it drifts from the encoder. Plain data — no dependency, so it ships in the portable
//! compiler (the `wasm-encoder` oracle stays in xtask). The backend's serializer reads these
//! rather than baking a raw byte into the emit path.

/// The core-wasm opcode bytes the serializer emits — one `pub const` per Lir
/// instruction, the byte `wasm-encoder` encodes that instruction to. A one-byte opcode
/// each (its operands follow, emitted by the serializer); the extraction asserts that.
pub mod op {
    pub const I32_CONST: u8 = 0x41;
    pub const I64_CONST: u8 = 0x42;
    pub const IF: u8 = 0x04;
    pub const ELSE: u8 = 0x05;
    pub const END: u8 = 0x0b;
    pub const LOCAL_GET: u8 = 0x20;
    pub const LOCAL_SET: u8 = 0x21;
    pub const CALL: u8 = 0x10;
    pub const UNREACHABLE: u8 = 0x00;
    pub const I32_ADD: u8 = 0x6a;
    pub const I32_SUB: u8 = 0x6b;
    pub const I32_MUL: u8 = 0x6c;
    pub const I32_DIV_S: u8 = 0x6d;
    pub const I32_DIV_U: u8 = 0x6e;
    pub const I32_REM_S: u8 = 0x6f;
    pub const I32_REM_U: u8 = 0x70;
    pub const I32_AND: u8 = 0x71;
    pub const I32_OR: u8 = 0x72;
    pub const I32_XOR: u8 = 0x73;
    pub const I32_SHL: u8 = 0x74;
    pub const I32_SHR_S: u8 = 0x75;
    pub const I32_SHR_U: u8 = 0x76;
    pub const I32_EQ: u8 = 0x46;
    pub const I32_NE: u8 = 0x47;
    pub const I32_LT_S: u8 = 0x48;
    pub const I32_LT_U: u8 = 0x49;
    pub const I32_GT_S: u8 = 0x4a;
    pub const I32_GT_U: u8 = 0x4b;
    pub const I32_LE_S: u8 = 0x4c;
    pub const I32_LE_U: u8 = 0x4d;
    pub const I32_GE_S: u8 = 0x4e;
    pub const I32_GE_U: u8 = 0x4f;
    pub const I64_ADD: u8 = 0x7c;
    pub const I64_SUB: u8 = 0x7d;
    pub const I64_MUL: u8 = 0x7e;
    pub const I64_DIV_S: u8 = 0x7f;
    pub const I64_DIV_U: u8 = 0x80;
    pub const I64_REM_S: u8 = 0x81;
    pub const I64_REM_U: u8 = 0x82;
    pub const I64_AND: u8 = 0x83;
    pub const I64_OR: u8 = 0x84;
    pub const I64_XOR: u8 = 0x85;
    pub const I64_SHL: u8 = 0x86;
    pub const I64_SHR_S: u8 = 0x87;
    pub const I64_SHR_U: u8 = 0x88;
    pub const I64_EQ: u8 = 0x51;
    pub const I64_NE: u8 = 0x52;
    pub const I64_LT_S: u8 = 0x53;
    pub const I64_LT_U: u8 = 0x54;
    pub const I64_GT_S: u8 = 0x55;
    pub const I64_GT_U: u8 = 0x56;
    pub const I64_LE_S: u8 = 0x57;
    pub const I64_LE_U: u8 = 0x58;
    pub const I64_GE_S: u8 = 0x59;
    pub const I64_GE_U: u8 = 0x5a;
    pub const I32_WRAP_I64: u8 = 0xa7;
    pub const I64_EXTEND_I32_S: u8 = 0xac;
    pub const I64_EXTEND_I32_U: u8 = 0xad;
}
/// core valtype `i32` — a ≤32-bit scalar's machine slot.
pub const CORE_I32: u8 = 0x7f;
/// core valtype `i64` — a 64-bit scalar's machine slot.
pub const CORE_I64: u8 = 0x7e;
/// core valtype `f32`.
pub const CORE_F32: u8 = 0x7d;
/// core valtype `f64`.
pub const CORE_F64: u8 = 0x7c;
/// empty block type — a structured block (`if`/`block`) that leaves no value.
pub const BLOCK_EMPTY: u8 = 0x40;
/// component `bool`.
pub const COMP_BOOL: u8 = 0x7f;
/// component `s8`.
pub const COMP_S8: u8 = 0x7e;
/// component `u8`.
pub const COMP_U8: u8 = 0x7d;
/// component `s16`.
pub const COMP_S16: u8 = 0x7c;
/// component `u16`.
pub const COMP_U16: u8 = 0x7b;
/// component `s32`.
pub const COMP_S32: u8 = 0x7a;
/// component `u32`.
pub const COMP_U32: u8 = 0x79;
/// component `s64`.
pub const COMP_S64: u8 = 0x78;
/// component `u64`.
pub const COMP_U64: u8 = 0x77;
/// component `f32`.
pub const COMP_F32: u8 = 0x76;
/// component `f64`.
pub const COMP_F64: u8 = 0x75;
/// core TYPE section id.
pub const CORE_SEC_TYPE: u8 = 0x01;
/// core FUNCTION section id.
pub const CORE_SEC_FUNCTION: u8 = 0x03;
/// core EXPORT section id.
pub const CORE_SEC_EXPORT: u8 = 0x07;
/// core CODE section id.
pub const CORE_SEC_CODE: u8 = 0x0a;
/// component CORE-MODULE section id.
pub const COMP_SEC_CORE_MODULE: u8 = 0x01;
/// component CORE-INSTANCE section id.
pub const COMP_SEC_CORE_INSTANCE: u8 = 0x02;
/// component ALIAS section id.
pub const COMP_SEC_ALIAS: u8 = 0x06;
/// component TYPE section id.
pub const COMP_SEC_TYPE: u8 = 0x07;
/// component CANONICAL-FUNCTION section id.
pub const COMP_SEC_CANONICAL: u8 = 0x08;
/// component EXPORT section id.
pub const COMP_SEC_EXPORT: u8 = 0x0b;
/// core export kind `func` — the export-descriptor byte for a function export.
pub const EXPORT_KIND_FUNC: u8 = 0x00;
/// core functype form tag — opens a core `func` type before its param/result vecs.
pub const CORE_FUNCTYPE_FORM: u8 = 0x60;
/// component functype form tag — opens a component function type.
pub const COMP_FUNCTYPE_FORM: u8 = 0x40;
/// the `\0asm` version-1 core-module preamble.
pub const CORE_MAGIC: &[u8] = &[0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00];
/// the `\0asm` component-layer preamble (component-model version).
pub const COMPONENT_MAGIC: &[u8] = &[0x00, 0x61, 0x73, 0x6d, 0x0d, 0x00, 0x01, 0x00];
