(case "pyi5 a BRANCH-ROUTED ABORT — the first draw answer picks whether to stop immediately or draw again first, both paths end in the aborting op at different depths, and the seeds abort from different states" (input (do
  (effect E (op tick (-> Int64)) (op stop (-> Int64)))
  (def (main (: n Int64))
    (handle E (% n 3)
      ((tick () s (resume (+ (* s 10) 1) (+ s 1)))
       (stop () s (+ 9000 (* s 10))))
      (if (> (E.tick) 15)
          (E.stop)
          (+ (* 10 (E.tick)) (E.stop)))))
  (export main)))
  (call   main (: 10 Int64)) (output (: 9030 Int64))
  (call   main (: 0 Int64)) (output (: 9020 Int64)))
