(case "pyfb3-nextstate-binder: a let-bound nullary FOREIGN perform read by the threaded next-state under multi-dispatch now FOLDS once-per-dispatch (freeze-once, was the triangular extra-perform miscompile) — the B counter fires exactly N times for N A-dispatches, read back via a non-incrementing total"
  (input (do
  (effect A (op tick (-> Int64)))
  (effect B (op beat (-> Int64)) (op total (-> Int64)))
  (def (main (: n Int64))
    (handle B (: 0 Int64)
      ((beat () bs (resume bs (+ bs 1)))
       (total () bs (resume bs bs)))
      (+ (handle A (% n 3)
           ((tick () s (let ((k (B.beat))) (resume (+ s 1) (+ s k)))))
           (+ (A.tick) (A.tick)))
         (* 10000 (B.total)))))
  (export main)))
  (call   main (: 10 Int64)) (output (: 20004 Int64))
  (call   main (: 0 Int64)) (output (: 20002 Int64)))
