(case "pyfb2-discarded: A's arm performs B (value DISCARDED by do) then resumes purely; witnesses the foreign effect runs EXACTLY ONCE per dispatch even when its value is dropped, and the pure A-body value is preserved (correct = N beats)"
  (input (do
  (effect A (op tick (-> Int64)))
  (effect B (op beat (-> Int64)) (op total (-> Int64)))
  (def (main (: n Int64))
    (handle B (: 0 Int64)
      ((beat () bs (resume bs (+ bs 1)))
       (total () bs (resume bs bs)))
      (+ (handle A (% n 3)
           ((tick () s (do (B.beat) (resume (+ s 1) (+ s 1)))))
           (+ (A.tick) (A.tick)))
         (* 10000 (B.total)))))
  (export main)))
  (call   main (: 10 Int64)) (output (: 20005 Int64))
  (call   main (: 0 Int64)) (output (: 20003 Int64)))
