(case "rlm1 a SLIDING-WINDOW rate limiter — allow prunes expired timestamps then admits only under the cap of two per ten ticks; the seeded third request either bounces inside the window or lands beyond it and steals a later slot"
  (input  (do
            (effect S (op allow (-> Int64 Int64)))
            (def (prune (: xs (List Int64)) (: cutoff Int64) (: i Int64) (: acc (List Int64)))
              (match (List.at xs i)
                ((Some x) (prune xs cutoff (+ i 1) (if (> x cutoff) (List.push acc x) acc)))
                ((None u) acc)))
            (def (main (: n Int64))
              (handle S (: (list) (List Int64))
                ((allow (t) w
                  (let ((w2 (prune w (- t 10) 0 (: (list) (List Int64)))))
                    (if (< (List.len w2) 2)
                        (resume 1 (List.push w2 t))
                        (resume 0 w2)))))
                (let ((a (S.allow 10)))
                  (let ((b (S.allow 11)))
                    (let ((c (S.allow n)))
                      (let ((d (S.allow 25)))
                        (let ((e (S.allow 26)))
                          (+ (* 10 (+ (* 10 (+ (* 10 (+ (* 10 (+ a 1)) (+ b 1))) (+ c 1))) (+ d 1))) (+ e 1)))))))))
            (export main)))
  (call   main (: 13 Int64)) (output (: 22122 Int64))
  (call   main (: 22 Int64)) (output (: 22221 Int64)))
