(case "grd1 a 2D GRID state — set rebuilds one CELL via List.update-within-List.update (row carved out, cell replaced, row reinstalled), the answer re-sums the whole grid and reads bound-check both levels"
  (input  (do
            (effect S
              (op setc (-> Int64 Int64 Int64 Int64))
              (op getc (-> Int64 Int64 Int64)))
            (def (row-sum (: xs (List Int64)) (: i Int64) (: acc Int64))
              (match (List.at xs i)
                ((Some v) (row-sum xs (+ i 1) (+ acc v)))
                ((None u) acc)))
            (def (grid-sum (: g (List (List Int64))) (: r Int64) (: acc Int64))
              (match (List.at g r)
                ((Some row) (grid-sum g (+ r 1) (+ acc (row-sum row 0 0))))
                ((None u) acc)))
            (def (main (: n Int64))
              (handle S (list (list 1 2) (list 3 4))
                ((setc (r c v) g
                  (let ((g2 (match (List.at g r)
                              ((Some row) (List.update g r (List.update row c v)))
                              ((None u) g))))
                    (resume (grid-sum g2 0 0) g2)))
                 (getc (r c) g
                  (resume (match (List.at g r)
                            ((Some row) (match (List.at row c) ((Some v) v) ((None u) -1)))
                            ((None u) -1))
                          g)))
                (let ((a (S.setc 0 1 n)))
                  (let ((b (S.getc 0 1)))
                    (let ((c (S.setc 1 0 (+ n 5))))
                      (let ((d (S.getc 1 0)))
                        (let ((e (S.getc 9 9)))
                          (+ (* 10 (+ (* 100 (+ (* 100 (+ (* 100 a) b)) c)) d)) (+ e 2)))))))))
            (export main)))
  (call   main (: 7 Int64)) (output (: 150724121 Int64))
  (call   main (: 0 Int64)) (output (: 80010051 Int64)))
