(case "pq1 a PRIORITY-POP protocol — pushes append unsorted (priority,value) pairs, popmin scans for the strict minimum priority (first-of-equals wins) answers its value and removes it by filtered rebuild"
  (input  (do
            (effect S
              (op push (-> Int64 Int64 Int64))
              (op popmin (-> Int64)))
            (def (find-min (: q (List (Tuple Int64 Int64))) (: i Int64) (: bi Int64) (: bp Int64))
              (match (List.at q i)
                ((Some p) (match p
                            ((tuple pri _v)
                              (if (< pri bp)
                                  (find-min q (+ i 1) i pri)
                                  (find-min q (+ i 1) bi bp)))))
                ((None u) bi)))
            (def (drop-at (: q (List (Tuple Int64 Int64))) (: i Int64) (: k Int64) (: acc (List (Tuple Int64 Int64))))
              (match (List.at q i)
                ((Some p) (drop-at q (+ i 1) k (if (= i k) acc (List.push acc p))))
                ((None u) acc)))
            (def (main (: n Int64))
              (handle S (: (list) (List (Tuple Int64 Int64)))
                ((push (pri v) q
                  (let ((q2 (List.push q (tuple pri v))))
                    (resume (List.len q2) q2)))
                 (popmin () q
                  (if (= (List.len q) 0)
                      (resume -1 q)
                      (let ((k (find-min q 0 0 1000000)))
                        (let ((val (match (List.at q k)
                                     ((Some p) (match p ((tuple _pri v) v)))
                                     ((None u) -1))))
                          (resume val (drop-at q 0 k (: (list) (List (Tuple Int64 Int64))))))))))
                (let ((a (S.push 5 10)))
                  (let ((b (S.push n 20)))
                    (let ((c (S.push 7 30)))
                      (let ((d (S.popmin)))
                        (let ((e (S.popmin)))
                          (+ (* 100 (+ (* 100 (+ (* 10 (+ (* 10 a) b)) c)) d)) e))))))))
            (export main)))
  (call   main (: 2 Int64)) (output (: 1232010 Int64))
  (call   main (: 9 Int64)) (output (: 1231030 Int64)))
