(case "pyad1 probe: ABORTING arm (no resume) whose answer DISPATCHES a distinct effect F, after a resuming tick threads state"
  (input (do
  (effect E (op tick (-> Int64)) (op stop (-> Int64)))
  (effect F (op aux (-> Int64)))
  (def (main (: n Int64))
    (handle F (: 0 Int64)
      ((aux () fs (resume (: 100 Int64) fs)))
      (handle E (% n 3)
        ((tick () s (resume (+ s 1) (+ s 10)))
         (stop () s (+ (* s 1000) (F.aux))))
        (let ((a (E.tick)))
          (+ a (E.stop))))))
  (export main)))
  (call   main (: 10 Int64)) (output (: 11100 Int64))
  (call   main (: 0 Int64)) (output (: 10100 Int64)))
