(case "closure as a list element via List.at" (doc "isolate: closure stored in a list, extracted by List.at, applied. wasm vs rust.")
  (input (do
    (def (adder n) (fn (x) (+ x n)))
    (def (main)
      (let ((fs (list (adder 1) (adder 2))))
        (match (List.at fs 0) ((Some f) (f 10)) ((None u) -1))))
    (export main)))
  (output (: 11 Int64)))
(case "closure as a tuple element (control — tuples often differ from lists)" (doc "closure in a tuple, extracted, applied")
  (input (do
    (def (adder n) (fn (x) (+ x n)))
    (def (main)
      (let (((tuple f g) (tuple (adder 1) (adder 2)))) (+ (f 10) (g 10))))
    (export main)))
  (output (: 23 Int64)))
