(case "w7 w6 plus the length-compare branch returning a STRING from both arms"
  (input (do
        (def (digit-str (: v Int64))
          (Option.expect (String.at "0123456789" v) "d"))
        (def (comp-go (: s String) (: i Int64) (: len Int64) (: cur String) (: cnt Int64) (: acc String))
          (if (>= i len)
              (String.concat acc (String.concat cur (digit-str cnt)))
              (match (String.at s i)
                ((Some c)
                  (if (= c cur)
                      (comp-go s (+ i 1) len cur (+ cnt 1) acc)
                      (comp-go s (+ i 1) len c 1 (String.concat acc (String.concat cur (digit-str cnt))))))
                ((None _u) acc))))
        (def (main (: mode Int64))
          (do
            (def s (if (= mode 1) "aabcccccaaa" "abc"))
            (match (String.at s 0)
              ((Some c0)
                (do
                  (def out (comp-go s 1 (String.byte-len s) c0 1 ""))
                  (String.byte-len (if (< (String.byte-len out) (String.byte-len s)) out s))))
              ((None _u) -1))))
        (export main)))
  (call main (: 1 Int64)) (output (: 8 Int64))
  (call main (: 2 Int64)) (output (: 3 Int64)))
