(do
  (type Instant (Instant UInt64))
  (def (inst-ns (: t Instant)) (match t ((Instant.Instant n) n)))
  (type KBox (KBox (-> Unit Unit)))
  (type PQ PQNil (PQCons (Tuple Instant KBox PQ)))
  (def (pop-apply (: q PQ))
    (match q
      ((PQ.PQNil _) unit)
      ((PQ.PQCons (tuple wake kb rest)) (match kb ((KBox.KBox k) (k unit))))))
  (effect Sim (op sleep (-> Instant Unit)) (op now (-> Unit Instant)))
  (def (main)
    (handle Sim (Instant.Instant 0)
      ( (now (u) s (resume s s))
        (sleep (wake) s (pop-apply (PQ.PQCons (tuple wake (KBox.KBox (fn (_u) (resume unit wake))) (PQ.PQNil ()))))) )
      (do (Sim.sleep (Instant.Instant 5000000000)) (inst-ns (Sim.now)))))
  (export main))
