(do
  (type Instant (Instant UInt64))
  (def (inst-ns (: t Instant)) (match t ((Instant.Instant n) n)))
  (def (before? (: a Instant) (: b Instant)) (< (inst-ns a) (inst-ns b)))
  ; the timer pqueue stores (Instant, payload) — payload will be Cont at step-3; use Int64 to type-check shape now
  (type PQ PQNil (PQCons (Tuple Instant Int64 PQ)))
  (def (pq-insert (: q PQ) (: t Instant) (: v Int64))
    (match q
      ((PQ.PQNil _) (PQ.PQCons (tuple t v (PQ.PQNil ()))))
      ((PQ.PQCons (tuple ht hv rest))
        (if (before? t ht)
            (PQ.PQCons (tuple t v (PQ.PQCons (tuple ht hv rest))))
            (PQ.PQCons (tuple ht hv (pq-insert rest t v)))))))
  ; SchedState record: clock + timer pqueue + primary-count
  (type Sched (Sched (Tuple Instant PQ UInt64)))
  (def (clock-of (: s Sched)) (match s ((Sched.Sched (tuple c _ _)) c)))
  (def (timers-of (: s Sched)) (match s ((Sched.Sched (tuple _ pq _)) pq)))
  (def (prims-of (: s Sched)) (match s ((Sched.Sched (tuple _ _ p)) p)))
  ; a scheduler-step skeleton: pop-min from timers, set clock, decrement... (apply-k is the step-3 hole)
  (def (advance-clock (: s Sched) (: to Instant))
    (Sched.Sched (tuple to (timers-of s) (prims-of s))))
  (def (main)
    (let ((s0 (Sched.Sched (tuple (Instant.Instant 0) (PQ.PQNil ()) 1)))
          (s1 (advance-clock s0 (Instant.Instant 5000000000))))
      (inst-ns (clock-of s1))))
  (export main))
