(case "frm1 a LENGTH-PREFIXED frame protocol over a Bytes state — writers append [len,payload..] frames, the reader pops exactly one frame by its prefix and the drained read answers a sentinel"
  (input  (do
            (effect S
              (op frame2 (-> Int64 Int64 Int64))
              (op frame1 (-> Int64 Int64))
              (op popf (-> Int64)))
            (def (bat (: b Bytes) (: i Int64))
              (match (Bytes.at b i) ((Some v) v) ((None u) 0)))
            (def (sum-body (: b Bytes) (: i Int64) (: end Int64) (: acc Int64))
              (if (< i end) (sum-body b (+ i 1) end (+ acc (bat b i))) acc))
            (def (main (: n Int64))
              (handle S (Bytes.of (list))
                ((frame2 (x y) bs
                  (let ((b2 (Bytes.concat bs (Bytes.of (list (UInt8.wrap 2) (UInt8.wrap x) (UInt8.wrap y))))))
                    (resume (Bytes.len b2) b2)))
                 (frame1 (x) bs
                  (let ((b2 (Bytes.concat bs (Bytes.of (list (UInt8.wrap 1) (UInt8.wrap x))))))
                    (resume (Bytes.len b2) b2)))
                 (popf () bs
                  (if (= (Bytes.len bs) 0)
                      (resume -1 bs)
                      (let ((ln (bat bs 0)))
                        (let ((body-sum (sum-body bs 1 (+ 1 ln) 0)))
                          (let ((rest (match (Bytes.slice bs (+ 1 ln) (- (Bytes.len bs) (+ 1 ln)))
                                        ((Some r) r)
                                        ((None u) (Bytes.of (list))))))
                            (resume (+ (* 10 body-sum) ln) rest)))))))
                (let ((a (S.frame2 n 4)))
                  (let ((b (S.frame1 9)))
                    (let ((c (S.popf)))
                      (let ((d (S.popf)))
                        (let ((e (S.popf)))
                          (+ (* 10 (+ (* 100 (+ (* 100 (+ (* 10 a) b)) c)) d)) (+ e 2)))))))))
            (export main)))
  (call   main (: 3 Int64)) (output (: 3572911 Int64))
  (call   main (: 30 Int64)) (output (: 3842911 Int64)))
