(case "fe4 float comparisons route an integer match — the sign of the second draw picks the arm, exact identities verify inside"
  (input  (do
            (effect F (op next (-> Float64)))
            (def (main (: n Int64))
              (handle F (Float64.of-int n)
                ((next () s (resume s (- s 1.5))))
                (let ((a (F.next)))
                  (let ((b (F.next)))
                    (match (if (< b 0.0) 0 1)
                      (0 (if (= (- a b) 1.5) 11 12))
                      (_o (if (= (+ a b) (- (* 2.0 (Float64.of-int n)) 1.5)) 21 22)))))))
            (export main)))
  (call   main (: 5 Int64)) (output (: 21 Int64))
  (call   main (: 1 Int64)) (output (: 11 Int64))
  (call   main (: 0 Int64)) (output (: 11 Int64)))
