(case "prn1 a PAREN-DEPTH validator — open and close chars move the depth, an underflow flips the STICKY invalid flag whose every later answer is the sentinel, and the seed picks a balanced or underflowing stream"
  (input  (do
            (effect S (op feed (-> String Int64)))
            (def (main (: n Int64))
              (handle S (tuple 0 0)
                ((feed (c) st
                  (match st
                    ((tuple depth bad)
                      (if (= bad 1)
                          (resume -9 st)
                          (let ((d2 (+ depth (if (= c "(") 1 (if (= c ")") -1 0)))))
                            (if (< d2 0)
                                (resume -9 (tuple d2 1))
                                (resume d2 (tuple d2 0)))))))))
                (let ((s1 (if (= n 0) "(" "(")))
                  (let ((s2 (if (= n 0) "(" ")")))
                    (let ((s3 (if (= n 0) ")" ")")))
                      (let ((a (S.feed s1)))
                        (let ((b (S.feed s2)))
                          (let ((c (S.feed s3)))
                            (let ((d (S.feed "(")))
                              (+ (* 100 (+ (* 100 (+ (* 100 (+ a 10)) (+ b 10))) (+ c 10))) (+ d 10)))))))))))
            (export main)))
  (call   main (: 0 Int64)) (output (: 11121112 Int64))
  (call   main (: 1 Int64)) (output (: 11100101 Int64)))
