(case "lt1 the arm SWAPS its list state's ends per dispatch — the head alternates between the original ends"
  (input  (do
            (effect L (op spin (-> Int64)))
            (def (main (: n Int64))
              (handle L (list n 2 9)
                ((spin () s (resume (match (List.at s 0) ((Some h) h) ((None) -1))
                                    (match (List.at s 0)
                                      ((Some h) (match (List.at s 2)
                                                  ((Some t) (List.update (List.update s 0 t) 2 h))
                                                  ((None) s)))
                                      ((None) s)))))
                (+ (L.spin) (+ (* 10 (L.spin)) (* 100 (L.spin))))))
            (export main)))
  (call   main (: 5 Int64)) (output (: 595 Int64))
  (call   main (: 0 Int64)) (output (: 90 Int64)))
