(case "pymu1 probe: a two-op effect where bump answers UNIT (advances state only, no meaningful value) and peek answers (* s 100) reading the state — interleaved via let/do as peek,bump,peek,bump,peek; the UNIT-answering op threads (+ s 3) while the reader leaves state unchanged, testing a Unit resume-answer alongside a value-answer in one shared-state tail fold"
  (input (do
  (effect E (op bump (-> Unit Unit)) (op peek (-> Int64)))
  (def (main (: n Int64))
    (handle E (% n 3)
      ((bump (u) s (resume unit (+ s 3)))
       (peek () s (resume (* s 100) s)))
      (let ((x (E.peek)))
        (do (E.bump)
            (let ((y (E.peek)))
              (do (E.bump)
                  (+ (* 1000 x) (+ y (E.peek)))))))))
  (export main)))
  (call   main (: 10 Int64)) (output (: 101100 Int64))
  (call   main (: 0 Int64)) (output (: 900 Int64)))
