/// The tour's chapter registry — the ordered list that drives the sidebar, routing, and prev/next.
///
/// Each chapter is a lazily-loaded TSX module (so it can embed <Runnable> examples). The order here
/// is the reading order; front-loads Cadenza's differentiators (effects, the value model) after the
/// fundamentals, per the guide's information architecture.
///
/// The CHAPTERS[] array below is @GENERATED by the xtask `xtask-codegen-guide --registry` (`npm run
/// codegen:registry`): reading ORDER comes from `chapter-order.txt` (the editorial lever) and every
/// per-chapter field (title/blurb/pillar/section/exercises) is DERIVED from that chapter's `.sexp`. Do NOT
/// hand-edit the generated region — edit the `.sexp` (metadata) or `chapter-order.txt` (order). Everything
/// else in this file is hand-written.

import type { ComponentType } from "react";
import { lazy } from "react";

/// The site's two top-level pillars (operator-directed, 2026-08-01): "Cadenza the Language" (the
/// interactive language tour) and "Cadenza the Platform" (the agent-kernel design concepts). A chapter
/// belongs to exactly one pillar; `section` groups chapters WITHIN a pillar. The sidebar renders a pillar
/// header only when more than one pillar is present, so a single-pillar site looks unchanged.
export type Pillar = "language" | "platform";

/// Human-readable pillar labels, in reading order (language first). Drives the sidebar pillar headers.
export const PILLARS: { id: Pillar; label: string }[] = [
  { id: "language", label: "Cadenza the Language" },
  { id: "platform", label: "Cadenza the Platform" },
];

export interface Chapter {
  slug: string;
  title: string;
  /** One-line blurb shown in the sidebar / cards. */
  blurb: string;
  /** Which top-level pillar this chapter lives under. Defaults to "language" (see `pillarOf`). */
  pillar?: Pillar;
  /** Section grouping for the sidebar, WITHIN a pillar. */
  section: string;
  /** Number of graded exercises in the chapter (drives the sidebar progress badge). Default 0. */
  exercises?: number;
  Component: ComponentType;
}

/// A chapter's pillar, defaulting to "language" so the existing tour needs no per-entry churn.
export function pillarOf(c: Chapter): Pillar {
  return c.pillar ?? "language";
}

/// Sections whose chapters are NOT "teaching" chapters — they wrap up or showcase rather than introduce a
/// concept, so the teaching-chapter invariants (opener.test's <Lede>/<Runnable>, tenets.test's <Why> box)
/// deliberately exempt them. SINGLE SOURCE OF TRUTH: both test files import this — a copy in each would let
/// a newly-added non-teaching section be exempted by one gate but not the other, silently mis-scoping it.
/// (Language-pillar section names; the platform pillar is exempted separately by `pillarOf`.)
export const NON_TEACHING_SECTIONS: ReadonlySet<string> = new Set(["Wrapping up", "Example applications"]);

export const CHAPTERS: Chapter[] = [
  // <generated:chapters> — DO NOT EDIT; regenerated by `xtask-codegen-guide --registry` (from chapter-order.txt + each chapter's .sexp)
  {
    slug: "welcome",
    title: "Welcome",
    blurb: "What Cadenza is, and how this interactive guide works.",
    section: "Getting started",
    Component: lazy(() => import("./chapters/Welcome.tsx")),
  },
  {
    slug: "philosophy",
    title: "Why Cadenza is the way it is",
    blurb: "The core tenets underneath the language.",
    section: "Getting started",
    Component: lazy(() => import("./chapters/Philosophy.tsx")),
  },
  {
    slug: "basics",
    title: "Values & functions",
    blurb: "Literals, bindings, functions, and type inference.",
    section: "Fundamentals",
    exercises: 2,
    Component: lazy(() => import("./chapters/Basics.tsx")),
  },
  {
    slug: "functions",
    title: "Composing functions",
    blurb: "Pipelines, composition, and applying one argument at a time.",
    section: "Fundamentals",
    exercises: 2,
    Component: lazy(() => import("./chapters/Functions.tsx")),
  },
  {
    slug: "control-flow",
    title: "Control flow",
    blurb: "if / then / else, sequencing, and short-circuit logic.",
    section: "Fundamentals",
    exercises: 2,
    Component: lazy(() => import("./chapters/ControlFlow.tsx")),
  },
  {
    slug: "ordering",
    title: "Comparison & ordering",
    blurb: "Comparisons, and the three-way shape of a total order.",
    section: "Fundamentals",
    exercises: 2,
    Component: lazy(() => import("./chapters/Ordering.tsx")),
  },
  {
    slug: "data",
    title: "Tuples & records",
    blurb: "Bundling values together, by position or by name.",
    section: "Fundamentals",
    exercises: 2,
    Component: lazy(() => import("./chapters/Data.tsx")),
  },
  {
    slug: "records-tuples",
    title: "Working with records & tuples",
    blurb: "Passing structured data around and reaching into it.",
    section: "Fundamentals",
    exercises: 3,
    Component: lazy(() => import("./chapters/RecordsTuples.tsx")),
  },
  {
    slug: "pattern-matching",
    title: "Pattern matching",
    blurb: "Deciding by shape; sum types and exhaustiveness.",
    section: "Fundamentals",
    exercises: 2,
    Component: lazy(() => import("./chapters/PatternMatching.tsx")),
  },
  {
    slug: "irrefutable-patterns",
    title: "Irrefutable patterns",
    blurb: "Destructuring that always matches, in a let and in arguments.",
    section: "Fundamentals",
    exercises: 2,
    Component: lazy(() => import("./chapters/IrrefutablePatterns.tsx")),
  },
  {
    slug: "iteration",
    title: "Iteration without loops",
    blurb: "Cadenza has no for or while; you repeat work with recursion and the fold family. Here's how, and why.",
    section: "Fundamentals",
    Component: lazy(() => import("./chapters/Iteration.tsx")),
  },
  {
    slug: "lists",
    title: "Lists",
    blurb: "Ordered, immutable sequences of values.",
    section: "Fundamentals",
    exercises: 4,
    Component: lazy(() => import("./chapters/Lists.tsx")),
  },
  {
    slug: "iterators",
    title: "Iterators & ranges",
    blurb: "Lazy pull sequences: describe an endless range, produce only the elements you use.",
    section: "Fundamentals",
    exercises: 2,
    Component: lazy(() => import("./chapters/Iterators.tsx")),
  },
  {
    slug: "maps-sets",
    title: "Maps & sets",
    blurb: "Membership and key→value association, without duplicates.",
    section: "Fundamentals",
    exercises: 2,
    Component: lazy(() => import("./chapters/MapsSets.tsx")),
  },
  {
    slug: "strings",
    title: "Strings & text",
    blurb: "Unicode text, joining, and character vs byte length.",
    section: "Fundamentals",
    exercises: 3,
    Component: lazy(() => import("./chapters/Strings.tsx")),
  },
  {
    slug: "bytes",
    title: "Bytes",
    blurb: "Raw octet sequences, and the bridge from text.",
    section: "Fundamentals",
    exercises: 2,
    Component: lazy(() => import("./chapters/Bytes.tsx")),
  },
  {
    slug: "binary-matching",
    title: "Binary matching",
    blurb: "Describe a byte layout as typed segments; the (bin …) form builds and destructures Bytes.",
    section: "Fundamentals",
    exercises: 2,
    Component: lazy(() => import("./chapters/BinaryMatching.tsx")),
  },
  {
    slug: "symbols",
    title: "Symbols",
    blurb: "Interned names, compared by identity.",
    section: "Fundamentals",
    exercises: 2,
    Component: lazy(() => import("./chapters/Symbols.tsx")),
  },
  {
    slug: "numbers",
    title: "The numeric model",
    blurb: "Checked integers and no silent promotion.",
    section: "Fundamentals",
    exercises: 2,
    Component: lazy(() => import("./chapters/Numbers.tsx")),
  },
  {
    slug: "sized-integers",
    title: "Sized integers",
    blurb: "Fixed-width integers that never convert silently.",
    section: "Fundamentals",
    exercises: 2,
    Component: lazy(() => import("./chapters/SizedIntegers.tsx")),
  },
  {
    slug: "floats",
    title: "Floating-point numbers",
    blurb: "Real-valued arithmetic with its own operators.",
    section: "Fundamentals",
    exercises: 2,
    Component: lazy(() => import("./chapters/Floats.tsx")),
  },
  {
    slug: "rationals",
    title: "Exact fractions",
    blurb: "Rationals: exact ratios, always in lowest terms, so where floats round, these don't.",
    section: "Fundamentals",
    exercises: 3,
    Component: lazy(() => import("./chapters/Rationals.tsx")),
  },
  {
    slug: "errors",
    title: "Errors & absence",
    blurb: "Option, Result, safe indexing, and checked arithmetic.",
    section: "Fundamentals",
    exercises: 2,
    Component: lazy(() => import("./chapters/Errors.tsx")),
  },
  {
    slug: "effects",
    title: "Effects & handlers",
    blurb: "Perform an operation; a handler decides what it means.",
    section: "What makes Cadenza different",
    exercises: 3,
    Component: lazy(() => import("./chapters/Effects.tsx")),
  },
  {
    slug: "contracts",
    title: "Design by contract",
    blurb: "@requires and @ensures turn an assumption into an enforced check at the function boundary.",
    section: "What makes Cadenza different",
    Component: lazy(() => import("./chapters/DesignByContract.tsx")),
  },
  {
    slug: "modules",
    title: "Modules",
    blurb: "Grouping definitions under a name; a module is a record of its exports.",
    section: "What makes Cadenza different",
    exercises: 2,
    Component: lazy(() => import("./chapters/Modules.tsx")),
  },
  {
    slug: "opaque-types",
    title: "Opaque types",
    blurb: "Export a type's name but keep its constructor private: values flow only through the module's functions, so an invariant can't be broken.",
    section: "What makes Cadenza different",
    exercises: 2,
    Component: lazy(() => import("./chapters/OpaqueTypes.tsx")),
  },
  {
    slug: "units",
    title: "Units of measure",
    blurb: "Carry a unit with a value; mix dimensions and it won't compile.",
    section: "What makes Cadenza different",
    exercises: 5,
    Component: lazy(() => import("./chapters/Units.tsx")),
  },
  {
    slug: "types-as-values",
    title: "Types as values",
    blurb: "A type is an ordinary value: reflect it, compare it, branch on it, all at compile time.",
    section: "What makes Cadenza different",
    exercises: 2,
    Component: lazy(() => import("./chapters/TypesAsValues.tsx")),
  },
  {
    slug: "const-parameters",
    title: "Const parameters",
    blurb: "Arguments known at compile time, inlined into a specialized copy and erased: a constant, a type, or a dictionary of behaviour.",
    section: "What makes Cadenza different",
    exercises: 2,
    Component: lazy(() => import("./chapters/ConstParameters.tsx")),
  },
  {
    slug: "ad-hoc-polymorphism",
    title: "Ad-hoc polymorphism",
    blurb: "One name, a per-type meaning: operators dispatch on operand type, generics specialize per type, all at compile time.",
    section: "What makes Cadenza different",
    exercises: 2,
    Component: lazy(() => import("./chapters/AdHocPolymorphism.tsx")),
  },
  {
    slug: "metaprogramming",
    title: "Metaprogramming",
    blurb: "Code is data: quote a program to an AST value, take it apart, build it up, eval it.",
    section: "What makes Cadenza different",
    exercises: 3,
    Component: lazy(() => import("./chapters/Metaprogramming.tsx")),
  },
  {
    slug: "property-testing",
    title: "Testing & properties",
    blurb: "@test marks a function as a test; give it parameters and the runner generates inputs and shrinks failures.",
    section: "What makes Cadenza different",
    exercises: 2,
    Component: lazy(() => import("./chapters/PropertyTesting.tsx")),
  },
  {
    slug: "example-apps",
    title: "Example applications",
    blurb: "Full interactive apps built in Cadenza, the differentiators running for real: playground, calculator, CAD, notebook.",
    section: "Example applications",
    Component: lazy(() => import("./chapters/ExampleApps.tsx")),
  },
  {
    slug: "using-the-playground",
    title: "The playground",
    blurb: "The full editor: a REPL, compiled-output views, and shareable links.",
    section: "Wrapping up",
    Component: lazy(() => import("./chapters/Playground.tsx")),
  },
  {
    slug: "cdz-toolchain",
    title: "The cdz toolchain",
    blurb: "The same compiler as one binary on your PATH: compile, run, a cargo-style project workflow, and code queries for humans and agents.",
    section: "Wrapping up",
    Component: lazy(() => import("./chapters/CdzToolchain.tsx")),
  },
  {
    slug: "whats-next",
    title: "Where to go next",
    blurb: "A recap, one last program, and how to keep exploring.",
    section: "Wrapping up",
    Component: lazy(() => import("./chapters/WhatsNext.tsx")),
  },
  {
    slug: "platform-overview",
    title: "Cadenza the Platform",
    blurb: "The agent kernel: a generic runtime where an agent's state is a pure fold over an event log, and the language is what flows through it.",
    pillar: "platform",
    section: "The kernel model",
    Component: lazy(() => import("./chapters/PlatformOverview.tsx")),
  },
  {
    slug: "platform-state",
    title: "Events & state",
    blurb: "How the pure-fold model stays practical: a reducer stateless between events, a persistent-map KV that snapshots for free, and one rule for reading immutable-by-hash vs. mutable-now.",
    pillar: "platform",
    section: "Events & state",
    Component: lazy(() => import("./chapters/PlatformState.tsx")),
  },
  {
    slug: "platform-safety",
    title: "Doing things safely",
    blurb: "Capabilities and authorization: every reach outward is an effect through one gate, the effect row is the permission list, and dangerous power is attenuated behind safe components.",
    pillar: "platform",
    section: "Doing things safely",
    Component: lazy(() => import("./chapters/PlatformSafety.tsx")),
  },
  {
    slug: "platform-execution",
    title: "The execution model",
    blurb: "One kernel, many agents: sessions multiplexed concurrently, an append wakes the reducer (nothing polls, nothing gets stuck), and determinism lives in the log, not the scheduler.",
    pillar: "platform",
    section: "The execution model",
    Component: lazy(() => import("./chapters/PlatformExecution.tsx")),
  },
  {
    slug: "writing-a-reducer",
    title: "Writing a reducer",
    blurb: "The capstone: author a real agent-harness reducer in Cadenza, a pure apply that folds events to effect-requests, with host state reached through effect-and-binding, compiled to a component the kernel loads.",
    pillar: "platform",
    section: "Writing a reducer",
    Component: lazy(() => import("./chapters/WritingAReducer.tsx")),
  },
  // </generated:chapters>
];

export function chapterAt(slug: string): { chapter: Chapter; index: number } | null {
  const index = CHAPTERS.findIndex((c) => c.slug === slug);
  if (index < 0) return null;
  return { chapter: CHAPTERS[index], index };
}
