/// The guide's reading ORDER — the sole editorial order source for the @generated chapter registry.
/// chapters.ts CHAPTERS[] is derived from THIS list (order) + each chapter's .sexp metadata. To
/// reorder the guide, reorder these file stems. (Bootstrapped from the pre-derivation chapters.ts.)
export const CHAPTER_ORDER = [
  "Welcome",
  "Philosophy",
  "Basics",
  "Functions",
  "ControlFlow",
  "Ordering",
  "Data",
  "RecordsTuples",
  "PatternMatching",
  "IrrefutablePatterns",
  "Iteration",
  "Lists",
  "Iterators",
  "MapsSets",
  "Strings",
  "Bytes",
  "BinaryMatching",
  "Symbols",
  "Numbers",
  "SizedIntegers",
  "Floats",
  "Rationals",
  "Errors",
  "Effects",
  "DesignByContract",
  "Modules",
  "OpaqueTypes",
  "Units",
  "TypesAsValues",
  "ConstParameters",
  "AdHocPolymorphism",
  "Metaprogramming",
  "PropertyTesting",
  "ExampleApps",
  "Playground",
  "CdzToolchain",
  "WhatsNext",
  "PlatformOverview",
  "PlatformState",
  "PlatformSafety",
  "PlatformExecution",
  "WritingAReducer",
];
