(case "pysh5 probe: the outer arm's RESUME ANSWER contains a nested closed handle of a DISTINCT effect F — tick answers (+ (* s 100) <handle F 7 ...>) threading (+ s 1), where the inner handle F is closed (ff answers t*2, threads t+1, body (F.ff)+(F.ff) = 14+16 = 30); the closed distinct-effect handle in the answer position reduces to 30 and adds to each outer dispatch, testing a nested closed handle in the answer hole (pyre6 axis) driven per-dispatch by the outer fold"
  (input (do
  (effect E (op tick (-> Int64)))
  (effect F (op ff (-> Int64)))
  (def (main (: n Int64))
    (handle E (% n 3)
      ((tick () s (resume (+ (* s 100)
                             (handle F (: 7 Int64)
                               ((ff () t (resume (* t 2) (+ t 1))))
                               (+ (F.ff) (F.ff))))
                          (+ s 1))))
      (+ (E.tick) (E.tick))))
  (export main)))
  (call   main (: 10 Int64)) (output (: 360 Int64))
  (call   main (: 0 Int64)) (output (: 160 Int64)))
