(case "py3n1 probe: a THREE-LEVEL handler nest (A over B over C) where the innermost body draws from ALL THREE effects — each op resumes a distinct transform of its own handler's state, so the three independent state threads (A doubles, B adds five, C adds nine hundred) route to their correct handlers and pack into separate digit ranges"
  (input (do
  (effect A (op a (-> Int64)))
  (effect B (op b (-> Int64)))
  (effect C (op c (-> Int64)))
  (def (main (: n Int64))
    (handle A (+ (% n 3) (: 100 Int64))
      ((a () s (resume (* s 2) (+ s 1))))
      (handle B (: 20 Int64)
        ((b () s (resume (+ s 5) (+ s 1))))
        (handle C (: 3 Int64)
          ((c () s (resume (+ s 900) (+ s 1))))
          (+ (A.a) (+ (* 10 (B.b)) (* 100 (C.c))))))))
  (export main)))
  (call   main (: 10 Int64)) (output (: 90752 Int64))
  (call   main (: 0 Int64)) (output (: 90750 Int64)))
