(case "tp4 readers and a SPIN writer share one tuple state — sum flows into slot a while old a shifts to b"
  (input  (do
            (effect E (op geta (-> Int64)) (op getb (-> Int64)) (op spin (-> Int64)))
            (def (main (: n Int64))
              (handle E (tuple n 100)
                ((geta () s (match s ((tuple a b) (resume a s))))
                 (getb () s (match s ((tuple a b) (resume b s))))
                 (spin () s (match s ((tuple a b) (resume (+ a b) (tuple (+ a b) a))))))
                (let ((r1 (E.geta)))
                  (let ((r2 (E.getb)))
                    (do (E.spin)
                        (+ r1 (+ (* 10 r2) (+ (* 100 (E.geta)) (* 1000 (E.getb))))))))))
            (export main)))
  (call   main (: 3 Int64)) (output (: 14303 Int64))
  (call   main (: 0 Int64)) (output (: 11000 Int64))
  (call   main (: -5 Int64)) (output (: 5495 Int64)))
