(case "mml1 a MULTIMAP handler state — (Map Int64 (List Int64)) buckets grow per-key across dispatches; put answers the new bucket length and total sums a bucket later"
  (input  (do
            (effect S
              (op put (-> Int64 Int64 Int64))
              (op total (-> Int64 Int64)))
            (def (sum-list (: xs (List Int64)) (: i Int64) (: acc Int64))
              (match (List.at xs i)
                ((Some v) (sum-list xs (+ i 1) (+ acc v)))
                ((None u) acc)))
            (def (append-at (: m (Map Int64 (List Int64))) (: k Int64) (: v Int64))
              (match (Map.lookup m k)
                ((Some xs) (Map.insert m k (List.push xs v)))
                ((None u) (Map.insert m k (list v)))))
            (def (bucket-len (: m (Map Int64 (List Int64))) (: k Int64))
              (match (Map.lookup m k) ((Some xs) (List.len xs)) ((None u) 0)))
            (def (bucket-sum (: m (Map Int64 (List Int64))) (: k Int64))
              (match (Map.lookup m k) ((Some xs) (sum-list xs 0 0)) ((None u) 0)))
            (def (main (: n Int64))
              (handle S Map.empty
                ((put (k v) m (let ((m2 (append-at m k v))) (resume (bucket-len m2 k) m2)))
                 (total (k) m (resume (bucket-sum m k) m)))
                (let ((a (S.put n n)))
                  (let ((b (S.put (+ n 1) (* 2 n))))
                    (let ((c (S.put n (+ n 10))))
                      (let ((d (S.total n)))
                        (let ((e (S.total (+ n 1))))
                          (let ((f (S.total 99)))
                            (+ (* 10 (+ (* 100 (+ (* 100 (+ (* 10 (+ (* 10 a) b)) c)) d)) e)) f)))))))))
            (export main)))
  (call   main (: 3 Int64)) (output (: 11216060 Int64))
  (call   main (: 7 Int64)) (output (: 11224140 Int64)))
