(case "fzk1 a FIZZBUZZ classifier with a seed-shaped first modulus — feed answers fifteen for both divisors, three for the first, five for the second, else the value itself (specials counted), and shrinking the first modulus from three to two RECLASSIFIES two of the five feeds including promoting a five-row to a fifteen-row"
  (input  (do
            (effect F
              (op feed (-> Int64 Int64))
              (op cnt (-> Int64)))
            (def (main (: n Int64))
              (handle F (: 0 Int64)
                ((feed (v) specials
                  (if (= (% v (+ (% n 3) 2)) 0)
                      (if (= (% v 5) 0)
                          (resume 15 (+ specials 1))
                          (resume 3 (+ specials 1)))
                      (if (= (% v 5) 0)
                          (resume 5 (+ specials 1))
                          (resume v specials))))
                 (cnt () specials (resume specials specials)))
                (let ((a (F.feed 6)))
                  (let ((b (F.feed 10)))
                    (let ((c (F.feed 7)))
                      (let ((d (F.feed 30)))
                        (let ((e (F.feed 4)))
                          (let ((f (F.cnt)))
                            (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 a) b)) c)) d)) e)) f)))))))))
            (export main)))
  (call   main (: 10 Int64)) (output (: 30507150403 Int64))
  (call   main (: 0 Int64)) (output (: 31507150304 Int64)))
