(case "tok1 a TOKENIZER protocol — next-tok skips leading spaces, answers the token's byte-len, and threads the REST of the string; the drained stream answers zero forever"
  (input  (do
            (effect S (op tok (-> Int64)))
            (def (skip (: s String) (: i Int64))
              (match (String.at s i)
                ((Some c) (if (= c " ") (skip s (+ i 1)) i))
                ((None u) i)))
            (def (scan (: s String) (: j Int64))
              (match (String.at s j)
                ((Some c) (if (= c " ") j (scan s (+ j 1))))
                ((None u) j)))
            (def (main (: n Int64))
              (handle S (if (= n 0) "ab cde  f" "x  yz w")
                ((tok () s
                  (let ((i (skip s 0)))
                    (let ((j (scan s i)))
                      (let ((rest (match (String.slice s j (String.byte-len s))
                                    ((Some r) r)
                                    ((None u) ""))))
                        (resume (- j i) rest))))))
                (let ((a (S.tok)))
                  (let ((b (S.tok)))
                    (let ((c (S.tok)))
                      (let ((d (S.tok)))
                        (+ (* 10 (+ (* 10 (+ (* 10 (+ a 1)) (+ b 1))) (+ c 1))) (+ d 1))))))))
            (export main)))
  (call   main (: 0 Int64)) (output (: 3421 Int64))
  (call   main (: 1 Int64)) (output (: 2321 Int64)))
