(case "ns4 a record payload whose FIELD is itself a sum-wrapped record — projections traverse two wrap layers built from one dispatch"
  (input  (do
            (type Box (Wrap (Record (x Int64) (y Int64))))
            (type Big (Node (Record (tag Int64) (inner Box))))
            (effect E (op make (-> Big)) (op probe (-> Int64)))
            (def (main (: n Int64))
              (handle E n
                ((make () s (resume (Big.Node (record (tag (+ s 4))
                                               (inner (Box.Wrap (record (x s) (y (+ s 2)))))))
                                    (+ s 6)))
                 (probe () s (resume s s)))
                (match (E.make)
                  ((Big.Node outer)
                    (match (. outer inner)
                      ((Box.Wrap r)
                        (+ (* 100 (. outer tag))
                           (+ (* 10 (. r x))
                              (+ (. r y) (* 1000 (- (E.probe) n)))))))))))
            (export main)))
  (call   main (: 3 Int64)) (output (: 6735 Int64))
  (call   main (: 0 Int64)) (output (: 6402 Int64))
  (call   main (: -4 Int64)) (output (: 5958 Int64)))
