(case "ns4 a record payload whose FIELD is itself a sum-wrapped record — helper unboxers traverse two wrap layers built from one dispatch"
  (input  (do
            (type Box (Wrap (Record (: x Int64) (: y Int64))))
            (type Big (Node (Record (: tag Int64) (: inner Box))))
            (effect E (op make (-> Big)) (op probe (-> Int64)))
            (def (unnode (: g Big)) (match g ((Big.Node o) o)))
            (def (unwrap (: b Box)) (match b ((Box.Wrap r) r)))
            (def (main (: n Int64))
              (handle E n
                ((make () s (resume (Big.Node (record (tag (+ s 4))
                                               (inner (Box.Wrap (record (x s) (y (+ s 2)))))))
                                    (+ s 6)))
                 (probe () s (resume s s)))
                (let ((outer (unnode (E.make))))
                  (let ((r (unwrap (. outer inner))))
                    (+ (* 100 (. outer tag))
                       (+ (* 10 (. r x))
                          (+ (. r y) (* 1000 (- (E.probe) n)))))))))
            (export main)))
  (call   main (: 3 Int64)) (output (: 6735 Int64))
  (call   main (: 0 Int64)) (output (: 6402 Int64))
  (call   main (: -4 Int64)) (output (: 5958 Int64)))
