(case "twn1 TWO structurally IDENTICAL effect declarations (same op name, same signature, different effect names) nested as a tower — interleaved draws must dispatch to the CORRECT handler by effect identity alone, the sharpest post-schema-hash identity probe: same-shape effects with different seeds thread independently"
  (input  (do
            (effect A (op bump (-> Int64 Int64)))
            (effect B (op bump (-> Int64 Int64)))
            (def (main (: n Int64))
              (handle A (: n Int64)
                ((bump (v) s (resume (+ s v) (+ s v))))
                (handle B (: 100 Int64)
                  ((bump (v) s (resume (+ s v) (+ s v))))
                  (let ((a (A.bump 3)))
                    (let ((b (B.bump 3)))
                      (let ((c (A.bump 5)))
                        (let ((d (B.bump 5)))
                          (let ((e (A.bump 1)))
                            (+ (* 1000 (+ (* 1000 (+ (* 1000 (+ (* 1000 a) b)) c)) d)) e)))))))))
            (export main)))
  (call   main (: 10 Int64)) (output (: 13103018108019 Int64))
  (call   main (: 0 Int64)) (output (: 3103008108009 Int64)))
