(case "lru1 a CAPACITY-2 LRU cache — put inserts as most-recent and answers the evicted key or 0, get answers the value refreshing recency or -1 on miss, and the SEED collides the computed key with a literal so one run UPDATES where the other EVICTS"
  (input  (do
            (effect C
              (op put (-> Int64 Int64 Int64))
              (op get (-> Int64 Int64)))
            (def (without (: xs (List Int64)) (: k Int64) (: i Int64) (: acc (List Int64)))
              (if (< i (List.len xs))
                  (without xs k (+ i 1)
                    (match (List.at xs i)
                      ((Some v) (if (= v k) acc (List.push acc v)))
                      ((None u) acc)))
                  acc))
            (def (headof (: xs (List Int64)))
              (match (List.at xs 0) ((Some v) v) ((None u) 0)))
            (def (tailof (: xs (List Int64)) (: i Int64) (: acc (List Int64)))
              (if (< i (List.len xs))
                  (tailof xs (+ i 1) (List.push acc (match (List.at xs i) ((Some v) v) ((None u) 0))))
                  acc))
            (def (main (: n Int64))
              (handle C (tuple (: (list) (List Int64)) (: (map) (Map Int64 Int64)))
                ((put (k v) st
                  (match st
                    ((tuple rec m)
                      (match (List.push (without rec k 0 (: (list) (List Int64))) k)
                        (rec2
                          (if (< 2 (List.len rec2))
                              (resume (headof rec2)
                                      (tuple (tailof rec2 1 (: (list) (List Int64)))
                                             (Map.remove (Map.insert m k v) (headof rec2))))
                              (resume 0 (tuple rec2 (Map.insert m k v)))))))))
                 (get (k) st
                  (match st
                    ((tuple rec m)
                      (match (Map.lookup m k)
                        ((Some v) (resume v (tuple (List.push (without rec k 0 (: (list) (List Int64))) k) m)))
                        ((None) (resume -1 st)))))))
                (let ((a (C.put (+ n 1) 5)))
                  (let ((b (C.put 1 6)))
                    (let ((c (C.get (+ n 1))))
                      (let ((d (C.put 3 7)))
                        (let ((e (C.get 1)))
                          (let ((f (C.get (+ n 1))))
                            (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 a) b)) c)) d)) e)) f)))))))))
            (export main)))
  (call   main (: 10 Int64)) (output (: 5009905 Int64))
  (call   main (: 0 Int64)) (output (: 6000606 Int64)))
