(case "rle2 a RUN-LENGTH ENCODER state — equal-to-last feeds bump the tail pair's count via List.update at len-1, fresh values push a new pair; the n=5 seed merges the middle literal into one long run"
  (input  (do
            (effect S (op feed (-> Int64 Int64)))
            (def (main (: n Int64))
              (handle S (: (list) (List (Tuple Int64 Int64)))
                ((feed (v) enc
                  (let ((k (List.len enc)))
                    (let ((enc2 (if (= k 0)
                                    (List.push enc (tuple v 1))
                                    (match (List.at enc (- k 1))
                                      ((Some p)
                                        (match p
                                          ((tuple lv lc)
                                            (if (= lv v)
                                                (List.update enc (- k 1) (tuple v (+ lc 1)))
                                                (List.push enc (tuple v 1))))))
                                      ((None u) enc)))))
                      (let ((k2 (List.len enc2)))
                        (resume (+ (* 10 k2)
                                   (match (List.at enc2 (- k2 1))
                                     ((Some p) (match p ((tuple _lv lc) lc)))
                                     ((None u) 0)))
                                enc2))))))
                (let ((a (S.feed n)))
                  (let ((b (S.feed n)))
                    (let ((c (S.feed 5)))
                      (let ((d (S.feed n)))
                        (let ((e (S.feed n)))
                          (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 a) b)) c)) d)) e))))))))
            (export main)))
  (call   main (: 3 Int64)) (output (: 1112213132 Int64))
  (call   main (: 5 Int64)) (output (: 1112131415 Int64)))
