(effect S (op add (-> Int64 Int64)))
(def (walk (: k Int64) (: acc Int64))
  (if (= k 0) acc (walk (- k 1) (+ acc (S.add k)))))
(def (main (: n Int64))
  (handle S (Map.insert Map.empty 0 0)
    ((add (v) m
      (let ((kk (Map.len m)))
        (let ((prev (match (Map.lookup m (- kk 1)) ((Some x) x) ((None _u) 0))))
          (let ((t (+ prev v)))
            (resume (% t 10) (Map.insert m kk t)))))))
    (walk 7 0)))
(export main)