(effect S (op add (-> Int64 Int64)))
(def (main (: n Int64))
  (handle S (Map.insert Map.empty 0 0)
    ((add (v) m
      (let ((kk (Map.len m)))
        (let ((prev (match (Map.lookup m (- kk 1)) ((Some x) x) ((None _u) 0))))
          (let ((t (+ prev v)))
            (resume (% t 10) (Map.insert m kk t)))))))
    (let ((a (S.add 3))) (let ((b (S.add 4))) (let ((c (S.add 9))) (let ((d (S.add 1))) (let ((e (S.add 6))) (let ((f (S.add 2))) (+ (* 100000 a) (+ (* 10000 b) (+ (* 1000 c) (+ (* 100 d) (+ (* 10 e) (* 1 f))))))))))))))
(export main)