(case "pfxM finding-23 sibling: MAP state — computed-key read + insert across seven dispatches (CHAMP growth)"
  (input  (do
            (effect S (op add (-> Int64 Int64)))
            (def (main (: n Int64))
              (handle S (Map.insert Map.empty 0 0)
                ((add (v) m
                  (let ((k (Map.len m)))
                    (let ((prev (match (Map.lookup m (- k 1)) ((Some x) x) ((None u) 0))))
                      (let ((t (+ prev v)))
                        (resume (% t 10) (Map.insert m k t)))))))
                (let ((a (S.add n)))
                  (let ((b (S.add 4)))
                    (let ((c (S.add 9)))
                      (let ((d (S.add 1)))
                        (let ((e (S.add 6)))
                          (let ((f (S.add 2)))
                            (let ((g (S.add 8)))
                              (+ (* 1000000 a) (+ (* 100000 b) (+ (* 10000 c) (+ (* 1000 d) (+ (* 100 e) (+ (* 10 f) g)))))))))))))))
            (export main)))
  (call   main (: 3 Int64)) (output (: 3767353 Int64))
  (call   main (: 7 Int64)) (output (: 7101797 Int64)))
