(case "ml1 a Map whose VALUES are tuples — a draw-keyed insert of a drawn pair, lookups destructure both hit and neighbor"
  (input  (do
            (effect E (op next (-> Int64)))
            (def (get2 (: m (Map Int64 (Tuple Int64 Int64))) (: k Int64))
              (match (Map.lookup m k)
                ((Some p) p)
                ((None) (tuple -1 -1))))
            (def (main (: n Int64))
              (handle E n
                ((next () s (resume s (+ s 2))))
                (let ((k (+ (% (E.next) 3) 1)))
                  (let ((v1 (E.next)))
                    (let ((m (Map.insert (Map.insert (Map.insert (Map.insert (map) 1 (tuple 10 20)) 2 (tuple 30 40)) 3 (tuple 50 60)) k (tuple v1 (* 2 v1)))))
                      (match (get2 m k)
                        ((tuple a b)
                          (match (get2 m (if (= k 1) 2 1))
                            ((tuple c d) (+ a (+ b (+ c d))))))))))))
            (export main)))
  (call   main (: 2 Int64)) (output (: 42 Int64))
  (call   main (: 0 Int64)) (output (: 76 Int64))
  (call   main (: 4 Int64)) (output (: 48 Int64)))
