(case "pyn1 POST-RESUME TOLLS AT BOTH NESTING LEVELS — the outer levy adds a thousandfold toll around a body whose second summand is a WHOLE INNER HANDLE running two hundredfold-tolled ticks, the inner pyramid unwinds completely inside the outer frame's replay before the outer toll settles, and the seed moves only the outer answer and toll leaving the inner arithmetic fixed"
  (input  (do
            (effect T (op levy (-> Int64)))
            (effect E (op tick (-> Int64)))
            (def (main (: n Int64))
              (handle T (% n 3)
                ((levy () t (+ (resume t (+ t 1)) (* 1000 (+ t 1)))))
                (+ (T.levy)
                   (handle E (: 1 Int64)
                     ((tick () s (+ (resume s (+ s 1)) (* 100 s))))
                     (let ((a (E.tick)))
                       (let ((b (E.tick)))
                         (+ a (* 10 b))))))))
            (export main)))
  (call   main (: 10 Int64)) (output (: 2322 Int64))
  (call   main (: 0 Int64)) (output (: 1321 Int64)))
