(case "sw2 a SLIDING WINDOW of the last two payloads — the arm keeps a bounded list state and resumes the window sum"
  (input  (do
            (effect E (op feed (-> Int64 Int64)))
            (def (sum-at (: xs (List Int64)) (: i Int64) (: acc Int64))
              (match (List.at xs i)
                ((Some v) (sum-at xs (+ i 1) (+ acc v)))
                ((None) acc)))
            (def (sum2 (: xs (List Int64))) (sum-at xs 0 0))
            (def (main (: n Int64))
              (handle E (list)
                ((feed (v) win
                  (let ((grown (List.push win v)))
                    (let ((kept (if (> (List.len grown) 2)
                                    (match (List.at grown 1)
                                      ((Some a) (match (List.at grown 2)
                                                  ((Some b) (list a b))
                                                  ((None) grown)))
                                      ((None) grown))
                                    grown)))
                      (resume (sum2 kept) kept)))))
                (+ (* 100 (E.feed n)) (+ (* 10 (E.feed 7)) (E.feed (+ n 1))))))
            (export main)))
  (call   main (: 5 Int64)) (output (: 633 Int64))
  (call   main (: 0 Int64)) (output (: 78 Int64))
  (call   main (: -3 Int64)) (output (: -255 Int64)))
