(case "sw3 the window CAPACITY is itself state — a grow op resizes the window mid-stream, windowed MAX tracked across the resize"
  (input  (do
            (effect E (op feed (-> Int64 Int64)) (op grow (-> Int64)))
            (def (max-at (: xs (List Int64)) (: i Int64) (: best Int64))
              (match (List.at xs i)
                ((Some v) (max-at xs (+ i 1) (if (> v best) v best)))
                ((None) best)))
            (def (drop-to (: xs (List Int64)) (: cap Int64))
              (if (> (List.len xs) cap)
                  (match (List.at xs (- (List.len xs) cap))
                    ((Some h)
                     (match (List.at xs (- (List.len xs) 1))
                       ((Some t) (if (= cap 2) (list h t)
                                     (match (List.at xs (- (List.len xs) 2))
                                       ((Some m) (list h m t))
                                       ((None) xs))))
                       ((None) xs)))
                    ((None) xs))
                  xs))
            (def (main (: n Int64))
              (handle E (tuple (list) 2)
                ((feed (v) st (match st
                                ((tuple win cap)
                                 (let ((kept (drop-to (List.push win v) cap)))
                                   (resume (max-at kept 0 -1000000) (tuple kept cap))))))
                 (grow () st (match st
                               ((tuple win cap) (resume cap (tuple win 3))))))
                (let ((r1 (E.feed n)))
                  (let ((r2 (E.feed 7)))
                    (do (E.grow)
                        (let ((r3 (E.feed (+ n 9))))
                          (let ((r4 (E.feed 1)))
                            (+ r1 (+ (* 2 r2) (+ (* 3 r3) (* 4 r4)))))))))))
            (export main)))
  (call   main (: 5 Int64)) (output (: 117 Int64))
  (call   main (: 0 Int64)) (output (: 77 Int64))
  (call   main (: -8 Int64)) (output (: 55 Int64)))
