(case "sw4 windowed AVERAGE with the truncating divide — window sum over live length, a negative window exercises toward-zero"
  (input  (do
            (effect E (op feed (-> Int64 Int64)))
            (def (sum-at (: xs (List Int64)) (: i Int64) (: acc Int64))
              (match (List.at xs i)
                ((Some v) (sum-at xs (+ i 1) (+ acc v)))
                ((None) acc)))
            (def (tail3 (: xs (List Int64)))
              (if (> (List.len xs) 3)
                  (match (List.at xs (- (List.len xs) 3))
                    ((Some a) (match (List.at xs (- (List.len xs) 2))
                                ((Some b) (match (List.at xs (- (List.len xs) 1))
                                            ((Some c) (list a b c))
                                            ((None) xs)))
                                ((None) xs)))
                    ((None) xs))
                  xs))
            (def (main (: n Int64))
              (handle E (list)
                ((feed (v) win
                  (let ((kept (tail3 (List.push win v))))
                    (resume (/ (sum-at kept 0 0) (List.len kept)) kept))))
                (let ((r1 (E.feed n)))
                  (let ((r2 (E.feed 7)))
                    (let ((r3 (E.feed (+ n 2))))
                      (let ((r4 (E.feed -5)))
                        (+ r1 (+ (* 2 r2) (+ (* 3 r3) (* 4 r4))))))))))
            (export main)))
  (call   main (: 5 Int64)) (output (: 47 Int64))
  (call   main (: 0 Int64)) (output (: 19 Int64))
  (call   main (: -6 Int64)) (output (: -9 Int64)))
