(case "sw5 DISTINCT-count over the window — a Set built per dispatch from the last-3 list measures dedupe, n=7 collides with the constant feed"
  (input  (do
            (effect E (op feed (-> Int64 Int64)))
            (def (tail3 (: xs (List Int64)))
              (if (> (List.len xs) 3)
                  (match (List.at xs (- (List.len xs) 3))
                    ((Some a) (match (List.at xs (- (List.len xs) 2))
                                ((Some b) (match (List.at xs (- (List.len xs) 1))
                                            ((Some c) (list a b c))
                                            ((None) xs)))
                                ((None) xs)))
                    ((None) xs))
                  xs))
            (def (distinct-at (: xs (List Int64)) (: i Int64) (: seen (Set Int64)))
              (match (List.at xs i)
                ((Some v) (distinct-at xs (+ i 1) (Set.insert seen v)))
                ((None) (Set.len seen))))
            (def (main (: n Int64))
              (handle E (list)
                ((feed (v) win
                  (let ((kept (tail3 (List.push win v))))
                    (resume (distinct-at kept 0 (Set.of (list))) kept))))
                (let ((r1 (E.feed n)))
                  (let ((r2 (E.feed n)))
                    (let ((r3 (E.feed 7)))
                      (let ((r4 (E.feed n)))
                        (+ (* 1000 r1) (+ (* 100 r2) (+ (* 10 r3) r4)))))))))
            (export main)))
  (call   main (: 5 Int64)) (output (: 1122 Int64))
  (call   main (: 7 Int64)) (output (: 1111 Int64))
  (call   main (: 0 Int64)) (output (: 1122 Int64)))
