(case "ms2 match ARMS themselves draw after the performing scrutinee advanced the state — arm-selected continuation of the same thread"
  (input  (do
            (type Mode (A) (B Int64) (C Int64 Int64))
            (effect E (op mode (-> Mode)) (op next (-> Int64)))
            (def (main (: n Int64))
              (handle E n
                ((mode () s (resume (match (% s 3)
                                      (0 (A))
                                      (1 (B s))
                                      (_ (C s s)))
                                    (+ s 1)))
                 (next () s (resume s (+ s 1))))
                (+ (* 100 (match (E.mode)
                            ((A) (E.next))
                            ((B x) (+ x (E.next)))
                            ((C x y) (+ x y))))
                   (E.next))))
            (export main)))
  (call   main (: 0 Int64)) (output (: 102 Int64))
  (call   main (: 1 Int64)) (output (: 303 Int64))
  (call   main (: 2 Int64)) (output (: 403 Int64))
  (call   main (: 6 Int64)) (output (: 708 Int64)))
