(case "ms4 the C arm RE-MATCHES its own payload's parity — a nested pure match inside an arm of the performing-scrutinee match"
  (input  (do
            (type Mode (A) (B Int64) (C Int64 Int64))
            (effect E (op mode (-> Mode)) (op next (-> Int64)))
            (def (main (: n Int64))
              (handle E n
                ((mode () s (resume (match (% s 3)
                                      (0 (A))
                                      (1 (B s))
                                      (_ (C s s)))
                                    (+ s 1)))
                 (next () s (resume s (+ s 1))))
                (+ (* 10 (match (E.mode)
                           ((A) 7)
                           ((B x) x)
                           ((C x y) (match (% x 2)
                                      (0 (+ 1000 y))
                                      (_ (+ 2000 y))))))
                   (E.next))))
            (export main)))
  (call   main (: 2 Int64)) (output (: 10023 Int64))
  (call   main (: 5 Int64)) (output (: 20056 Int64))
  (call   main (: 0 Int64)) (output (: 71 Int64))
  (call   main (: 1 Int64)) (output (: 12 Int64)))
