(case "rr1 a concat-built RELAXED RRB list indexes correctly across every seam"
  (input  (do
            (def (build (: n Int64) (: acc (List Int64)))
              (if (> n 0) (build (- n 1) (List.push acc n)) acc))
            (def (main (: k Int64))
              (let ((a (build 37 (list)))
                    (b (build 45 (list)))
                    (c (build 29 (list))))
                (let ((joined (List.concat (List.concat a b) c)))
                  (+ (* 1000 (List.len joined))
                     (+ (* 100 (match (List.at joined 36) ((Some v) v) ((None _u) -1)))
                        (+ (* 10 (match (List.at joined 37) ((Some v) v) ((None _u) -1)))
                           (match (List.at joined (+ 81 k)) ((Some v) v) ((None _u) -1))))))))
            (export main)))
  (call   main (: 0 Int64)) (output (: 111551 Int64)))
