//! Integration test: the agent-harness embedder drives a real compiled Cadenza agent-loop consumer,
//! answering its `Model.converse` call with the MOCK backend (no network, no creds — CI-safe).
//!
//! The consumer fixture (`tests/fixtures/model-consumer.wasm`) is a compiled Cadenza program that binds
//! `Model : String -> String` to `cadenza:model/api`, converses on the literal prompt "hi", and returns
//! the completion's byte-len (a scalar entrypoint — the peer-result-escape ABI is a separate slice). The
//! mock converse uppercases: "hi" -> "HI" (still 2 bytes), so `main()` returns 2.
//!
//! The fixture records the value-heap runtime it needs BY CONTENT ADDRESS; the runtime is a build
//! artifact (`cargo xtask build` writes `target/cadenza-store/<hash>.wasm`). We resolve it from the
//! store and SKIP if it is absent OR its hash no longer matches the fixture (a runtime change re-hashes
//! it — the fixture is regenerated by a maintainer via `cdz compile`; a mismatch means "stale fixture,
//! not a bug"), so the test never false-fails on an out-of-band runtime bump.

use std::path::PathBuf;

/// Walk up from the crate dir to find the repo's content-addressed runtime store, returning the bytes of
/// `<store>/<hash>.wasm` for the required `hash`, or None if no store on any ancestor holds it.
fn find_runtime(hash: &str) -> Option<Vec<u8>> {
    let mut dir: PathBuf = env!("CARGO_MANIFEST_DIR").into();
    loop {
        let candidate = dir
            .join("target/cadenza-store")
            .join(format!("{hash}.wasm"));
        if let Ok(bytes) = std::fs::read(&candidate) {
            return Some(bytes);
        }
        if !dir.pop() {
            return None;
        }
    }
}

#[test]
fn the_embedder_drives_a_cadenza_loop_with_the_mock_model() {
    let consumer = include_bytes!("fixtures/model-consumer.wasm");

    // The runtime the fixture requires (by content address). If the fixture declares none, that is a
    // broken fixture — but a String-consuming loop always imports the value-heap runtime.
    let req = cdz_run::required_runtime(consumer)
        .expect("read the fixture's runtime requirement")
        .expect("the model-consumer fixture imports the value-heap runtime (a String is a rope)");

    let Some(runtime) = find_runtime(&req.hash) else {
        eprintln!(
            "[cdz-agent] runtime {} not in any ancestor store (run `cargo xtask build`), \
             or the fixture is stale vs the current runtime hash; skipping",
            req.hash
        );
        return;
    };

    let opts = cdz_run::RunOpts {
        export: Some("main".to_string()),
        args: Vec::new(),
        runtime: Some(runtime),
        runtime_cache_dir: None,
        host_responses: Vec::new(),
    };

    // Drive the loop: `Model.converse("hi")` is answered by the mock (uppercase -> "HI"), whose byte-len
    // is 2. A String crossed OUT to the host closure and the completion crossed back IN, both as
    // shared-runtime rope handles the embedder marshalled via str-get/str-new.
    match cdz_agent::run_agent_loop(consumer, &opts, cdz_agent::mock_converse) {
        Ok(cdz_run::Outcome::Value(s)) => assert_eq!(
            s, "2",
            "the mock completion's byte-len proves the String round-tripped through the embedder"
        ),
        Ok(cdz_run::Outcome::Trap(t)) => panic!("embedder run trapped: {t}"),
        Err(e) => panic!("embedder run errored: {e}"),
    }
}

#[test]
fn mock_converse_uppercases() {
    // A pure unit check of the mock backend (no runtime needed) — pins the stand-in the loop test relies
    // on so a mock change that would silently alter the loop test's expected value is caught here too.
    assert_eq!(cdz_agent::mock_converse("hello".to_string()), "HELLO");
}
