//! Integration test: the agent-harness embedder drives a real compiled Cadenza agent-loop consumer,
//! answering its `Model.converse` call with the MOCK backend (no network, no creds — CI-safe).
//!
//! The consumer fixture (`tests/fixtures/model-consumer.wasm`) is a compiled Cadenza program that binds
//! `Model : String -> String` to `cadenza:model/api`, converses on the literal prompt "hi", and returns
//! the completion's byte-len (a scalar entrypoint — the peer-result-escape ABI is a separate slice). The
//! mock converse uppercases: "hi" -> "HI" (still 2 bytes), so `main()` returns 2.
//!
//! The fixture records the value-heap runtime it needs BY CONTENT ADDRESS; the runtime is a build
//! artifact (`cargo xtask build` writes `target/cadenza-store/<hash>.wasm`). We resolve it from the
//! store and SKIP if it is absent OR its hash no longer matches the fixture (a runtime change re-hashes
//! it — the fixture is regenerated by a maintainer via `cdz compile`; a mismatch means "stale fixture,
//! not a bug"), so the test never false-fails on an out-of-band runtime bump.

use std::path::PathBuf;

/// Walk up from the crate dir to find the repo's content-addressed runtime store, returning the bytes of
/// `<store>/<hash>.wasm` for the required `hash`, or None if no store on any ancestor holds it.
fn find_runtime(hash: &str) -> Option<Vec<u8>> {
    let mut dir: PathBuf = env!("CARGO_MANIFEST_DIR").into();
    loop {
        let candidate = dir
            .join("target/cadenza-store")
            .join(format!("{hash}.wasm"));
        if let Ok(bytes) = std::fs::read(&candidate) {
            return Some(bytes);
        }
        if !dir.pop() {
            return None;
        }
    }
}

#[test]
fn the_embedder_drives_a_cadenza_loop_with_the_mock_model() {
    let consumer = include_bytes!("fixtures/model-consumer.wasm");

    // The runtime the fixture requires (by content address). If the fixture declares none, that is a
    // broken fixture — but a String-consuming loop always imports the value-heap runtime.
    let req = cdz_run::required_runtime(consumer)
        .expect("read the fixture's runtime requirement")
        .expect("the model-consumer fixture imports the value-heap runtime (a String is a rope)");

    let Some(runtime) = find_runtime(&req.hash) else {
        eprintln!(
            "[cdz-agent] runtime {} not in any ancestor store (run `cargo xtask build`), \
             or the fixture is stale vs the current runtime hash; skipping",
            req.hash
        );
        return;
    };

    let opts = cdz_run::RunOpts {
        export: Some("main".to_string()),
        args: Vec::new(),
        runtime: Some(runtime),
        runtime_cache_dir: None,
        host_responses: Vec::new(),
    };

    // Drive the loop: `Model.converse("hi")` is answered by the mock (uppercase -> "HI"), whose byte-len
    // is 2. A String crossed OUT to the host closure and the completion crossed back IN, both as
    // shared-runtime rope handles the embedder marshalled via str-get/str-new.
    match cdz_agent::run_agent_loop(consumer, &opts, cdz_agent::mock_converse) {
        Ok(cdz_run::Outcome::Value(s)) => assert_eq!(
            s, "2",
            "the mock completion's byte-len proves the String round-tripped through the embedder"
        ),
        Ok(cdz_run::Outcome::Trap(t)) => panic!("embedder run trapped: {t}"),
        Err(e) => panic!("embedder run errored: {e}"),
    }
}

#[test]
fn mock_converse_uppercases() {
    // A pure unit check of the mock backend (no runtime needed) — pins the stand-in the loop test relies
    // on so a mock change that would silently alter the loop test's expected value is caught here too.
    assert_eq!(cdz_agent::mock_converse("hello".to_string()), "HELLO");
}

#[test]
fn the_embedder_gates_the_loop_on_a_real_cedar_policy() {
    // The FULL authorized-agent shape (Inc-3 end-to-end): a Cadenza loop that performs
    // Cedar.authorize("tool:chat") and, ONLY on allow, Model.converse("hi") — returning the completion's
    // byte-len (2), else 0. The embedder answers `converse` with the mock model and `authorize` with the
    // REAL cedar-policy engine (`cedar_authorizer`). So the whole chain runs: Cadenza loop → authz effect
    // → cedar-policy decision → (allow) model effect → mock → byte-len, all over the shared runtime.
    let consumer = include_bytes!("fixtures/authz-model-consumer.wasm");
    let req = cdz_run::required_runtime(consumer)
        .expect("read the fixture's runtime requirement")
        .expect("the authz-model-consumer fixture imports the value-heap runtime");
    let Some(runtime) = find_runtime(&req.hash) else {
        eprintln!(
            "[cdz-agent] runtime {} not in any ancestor store (run `cargo xtask build`) or stale fixture; skipping",
            req.hash
        );
        return;
    };
    let opts = cdz_run::RunOpts {
        export: Some("main".to_string()),
        args: Vec::new(),
        runtime: Some(runtime),
        runtime_cache_dir: None,
        host_responses: Vec::new(),
    };

    // ALLOW policy: permit the chat tool. The loop authorizes "tool:chat" → allow → converse("hi") →
    // "HI" → byte-len 2. The action string the loop performs is a bare tag; the authorizer maps it to a
    // Cedar action UID (`Action::"<action>"`) — here the policy permits exactly that.
    let allow = cdz_agent::cedar_authorizer(
        r#"permit(principal, action == Action::"tool:chat", resource);"#.to_string(),
        r#"Agent::"agent:harness""#.to_string(),
        r#"Tool::"chat""#.to_string(),
        "{}".to_string(),
    );
    match cdz_agent::run_authorized_agent_loop(consumer, &opts, cdz_agent::mock_converse, allow) {
        Ok(cdz_run::Outcome::Value(s)) => assert_eq!(
            s, "2",
            "allowed: authorize→1 gates the model call → 'HI' byte-len 2"
        ),
        Ok(cdz_run::Outcome::Trap(t)) => panic!("authorized-loop run trapped: {t}"),
        Err(e) => panic!("authorized-loop run errored: {e}"),
    }

    // DENY policy: permit only a DIFFERENT action, so "tool:chat" has no permit → deny → the model call
    // is never made → the loop returns 0. This proves the gate is load-bearing e2e through the real
    // Cedar engine (not just that the allow path runs).
    let deny = cdz_agent::cedar_authorizer(
        r#"permit(principal, action == Action::"tool:other", resource);"#.to_string(),
        r#"Agent::"agent:harness""#.to_string(),
        r#"Tool::"chat""#.to_string(),
        "{}".to_string(),
    );
    match cdz_agent::run_authorized_agent_loop(consumer, &opts, cdz_agent::mock_converse, deny) {
        Ok(cdz_run::Outcome::Value(s)) => assert_eq!(
            s, "0",
            "denied: authorize→0 blocks the model call → 0 (the gate is load-bearing)"
        ),
        Ok(cdz_run::Outcome::Trap(t)) => panic!("authorized-loop deny run trapped: {t}"),
        Err(e) => panic!("authorized-loop deny run errored: {e}"),
    }
}

#[test]
fn cedar_authorizer_maps_decision_to_gate_value_fail_closed() {
    // The authorizer bridge: allow → 1, deny → 0, AND a malformed policy → 0 (fail-closed, never a
    // silent allow). No runtime needed — a pure check of the closure the loop's authorize op calls.
    let allow = cdz_agent::cedar_authorizer(
        r#"permit(principal, action == Action::"tool:chat", resource);"#.to_string(),
        r#"Agent::"a""#.to_string(),
        r#"Tool::"t""#.to_string(),
        "{}".to_string(),
    );
    // The loop passes a BARE tag; the authorizer wraps it into `Action::"<tag>"`.
    assert_eq!(allow("tool:chat".to_string()), 1, "permitted action → 1");
    assert_eq!(allow("tool:nope".to_string()), 0, "unpermitted action → 0");
    let broken = cdz_agent::cedar_authorizer(
        "not a policy".to_string(),
        r#"Agent::"a""#.to_string(),
        r#"Tool::"t""#.to_string(),
        "{}".to_string(),
    );
    assert_eq!(
        broken("tool:chat".to_string()),
        0,
        "a malformed policy must FAIL CLOSED (deny), never silently allow"
    );
}

#[test]
fn the_embedder_gates_the_loop_on_an_on_behalf_of_delegation() {
    // ON-BEHALF-OF end-to-end: an agent acting for a user is gated by the INTERSECTION of its own
    // policies AND the user's delegation grant (the narrower bound wins, DESIGN §4.2). Same authz-model
    // consumer (authorizes "tool:chat" then converses → byte-len 2 on allow, else 0), but the authorizer
    // is a DELEGATED one. This is the operator's explicit ask: "grant an agent to work on behalf of a
    // user, scoped by policy."
    let consumer = include_bytes!("fixtures/authz-model-consumer.wasm");
    let req = cdz_run::required_runtime(consumer)
        .expect("read runtime requirement")
        .expect("fixture imports the runtime");
    let Some(runtime) = find_runtime(&req.hash) else {
        eprintln!(
            "[cdz-agent] runtime {} absent or stale fixture; skipping",
            req.hash
        );
        return;
    };
    let opts = cdz_run::RunOpts {
        export: Some("main".to_string()),
        args: Vec::new(),
        runtime: Some(runtime),
        runtime_cache_dir: None,
        host_responses: Vec::new(),
    };
    let principal = r#"Agent::"agent:harness""#;
    let resource = r#"Tool::"chat""#;
    let on_behalf = r#"{"on_behalf_of":"user:cameron"}"#;

    // (a) BOTH allow: the agent may chat, and the user delegated chat (when acting for that user) →
    // allow → converse → byte-len 2.
    let both = cdz_agent::cedar_delegated_authorizer(
        r#"permit(principal, action, resource);"#.to_string(), // agent: anything
        r#"permit(principal, action == Action::"tool:chat", resource) when { context.on_behalf_of == "user:cameron" };"#.to_string(),
        principal.to_string(),
        resource.to_string(),
        on_behalf.to_string(),
    );
    match cdz_agent::run_authorized_agent_loop(consumer, &opts, cdz_agent::mock_converse, both) {
        Ok(cdz_run::Outcome::Value(s)) => {
            assert_eq!(
                s, "2",
                "agent allows AND delegation allows (for this user) → allow"
            )
        }
        Ok(cdz_run::Outcome::Trap(t)) => panic!("delegated allow trapped: {t}"),
        Err(e) => panic!("delegated allow errored: {e}"),
    }

    // (b) The DELEGATION does not cover chat (grants a different tool) → intersection denies → 0, even
    // though the agent itself could. The narrower bound (the delegation) wins.
    let narrow_delegation = cdz_agent::cedar_delegated_authorizer(
        r#"permit(principal, action, resource);"#.to_string(), // agent: anything
        r#"permit(principal, action == Action::"tool:other", resource) when { context.on_behalf_of == "user:cameron" };"#.to_string(),
        principal.to_string(),
        resource.to_string(),
        on_behalf.to_string(),
    );
    match cdz_agent::run_authorized_agent_loop(
        consumer,
        &opts,
        cdz_agent::mock_converse,
        narrow_delegation,
    ) {
        Ok(cdz_run::Outcome::Value(s)) => assert_eq!(
            s, "0",
            "a delegation that doesn't cover the action denies even a broad agent (narrower wins)"
        ),
        Ok(cdz_run::Outcome::Trap(t)) => panic!("delegated deny trapped: {t}"),
        Err(e) => panic!("delegated deny errored: {e}"),
    }
}
