(case "dl1 TEN chained lets each drawing once — position weights 1..10 pin every binder to its draw"
  (input  (do
            (effect E (op next (-> Int64)) (op probe (-> Int64)))
            (def (main (: n Int64))
              (handle E n
                ((next () s (resume s (+ s 1)))
                 (probe () s (resume s s)))
                (let ((v1 (E.next)))
                  (let ((v2 (E.next)))
                    (let ((v3 (E.next)))
                      (let ((v4 (E.next)))
                        (let ((v5 (E.next)))
                          (let ((v6 (E.next)))
                            (let ((v7 (E.next)))
                              (let ((v8 (E.next)))
                                (let ((v9 (E.next)))
                                  (let ((v10 (E.next)))
                                    (+ (* 10 (+ (* 1 v1) (+ (* 2 v2) (+ (* 3 v3) (+ (* 4 v4) (+ (* 5 v5) (+ (* 6 v6) (+ (* 7 v7) (+ (* 8 v8) (+ (* 9 v9) (* 10 v10)))))))))))
                                       (- (E.probe) n))))))))))))))
            (export main)))
  (call   main (: 5 Int64)) (output (: 6060 Int64))
  (call   main (: 0 Int64)) (output (: 3310 Int64))
  (call   main (: -7 Int64)) (output (: -540 Int64)))
