(case "bor1 a TWO-LIMB borrow decrement — subtracting from the low limb borrows from the high one when it underflows, and a borrow with no high limb left SATURATES both to zero"
  (input  (do
            (effect S (op dec (-> Int64 Int64)))
            (def (main (: n Int64))
              (handle S (tuple n 1)
                ((dec (k) st
                  (match st
                    ((tuple lo hi)
                      (let ((nl (- lo k)))
                        (if (>= nl 0)
                            (resume (+ (* hi 1000) nl) (tuple nl hi))
                            (let ((nh (- hi 1)))
                              (if (< nh 0)
                                  (resume 0 (tuple 0 0))
                                  (let ((l2 (+ nl 100)))
                                    (if (< l2 0)
                                        (resume 0 (tuple 0 0))
                                        (resume (+ (* nh 1000) l2) (tuple l2 nh))))))))))))
                (let ((a (S.dec 5)))
                  (let ((b (S.dec 98)))
                    (let ((c (S.dec 50)))
                      (+ (* 10000 (+ (* 10000 a) b)) c))))))
            (export main)))
  (call   main (: 3 Int64)) (output (: 9800000000 Int64))
  (call   main (: 50 Int64)) (output (: 104500470000 Int64)))
