(do
  (def (getat (: xs (List Int64)) (: i Int64))
    (match (List.at xs i) ((Some v) v) ((None u) 0)))
  (def (smallest (: xs (List Int64)) (: i Int64))
    (if (< (+ (* 2 i) 1) (List.len xs))
        (if (< (getat xs (+ (* 2 i) 1)) (getat xs i))
            (if (< (+ (* 2 i) 2) (List.len xs))
                (if (< (getat xs (+ (* 2 i) 2)) (getat xs (+ (* 2 i) 1))) (+ (* 2 i) 2) (+ (* 2 i) 1))
                (+ (* 2 i) 1))
            (if (< (+ (* 2 i) 2) (List.len xs))
                (if (< (getat xs (+ (* 2 i) 2)) (getat xs i)) (+ (* 2 i) 2) i)
                i))
        i))
  (def (siftdn (: xs (List Int64)) (: i Int64))
    (if (= (smallest xs i) i)
        xs
        (siftdn (List.update (List.update xs (smallest xs i) (getat xs i)) i (getat xs (smallest xs i))) (smallest xs i))))
  (def (main (: n Int64))
    (getat (siftdn (List.push (List.push (List.push (List.push (: (list) (List Int64)) (+ n 2)) 4) 7) (- n 3)) 0) 0))
  (export main))
