(do
  (effect H (op push (-> Int64 Int64)) (op popmin (-> Int64)))
  (def (getat (: xs (List Int64)) (: i Int64)) (match (List.at xs i) ((Some v) v) ((None u) 0)))
  (def (siftup (: xs (List Int64)) (: i Int64)) (if (= i 0) xs (if (< (getat xs i) (getat xs (/ (- i 1) 2))) (siftup (List.update (List.update xs (/ (- i 1) 2) (getat xs i)) i (getat xs (/ (- i 1) 2))) (/ (- i 1) 2)) xs)))
  (def (smallest (: xs (List Int64)) (: i Int64)) (if (< (+ (* 2 i) 1) (List.len xs)) (if (< (getat xs (+ (* 2 i) 1)) (getat xs i)) (if (< (+ (* 2 i) 2) (List.len xs)) (if (< (getat xs (+ (* 2 i) 2)) (getat xs (+ (* 2 i) 1))) (+ (* 2 i) 2) (+ (* 2 i) 1)) (+ (* 2 i) 1)) (if (< (+ (* 2 i) 2) (List.len xs)) (if (< (getat xs (+ (* 2 i) 2)) (getat xs i)) (+ (* 2 i) 2) i) i)) i))
  (def (siftdn (: xs (List Int64)) (: i Int64)) (if (= (smallest xs i) i) xs (siftdn (List.update (List.update xs (smallest xs i) (getat xs i)) i (getat xs (smallest xs i))) (smallest xs i))))
  (def (dropl (: xs (List Int64)) (: i Int64) (: keep Int64) (: acc (List Int64))) (if (< i keep) (dropl xs (+ i 1) keep (List.push acc (getat xs i))) acc))
  (def (main (: n Int64))
    (handle H (: (list) (List Int64))
      ((push (v) st (let ((h2 (siftup (List.push st v) (- (List.len (List.push st v)) 1)))) (resume (getat h2 0) h2)))
       (popmin () st (if (= (List.len st) 0) (resume -99 st) (if (= (List.len st) 1) (resume (getat st 0) (: (list) (List Int64))) (let ((h2 (siftdn (List.update (dropl st 0 (- (List.len st) 1) (: (list) (List Int64))) 0 (getat st (- (List.len st) 1))) 0))) (resume (getat st 0) h2))))))
      (let ((a (H.push (+ n 2)))) (let ((b (H.push 4))) (let ((c (H.push 7))) (let ((d (H.popmin))) (let ((e (H.push (- n 3)))) (let ((f (H.popmin))) (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 (+ (* 100 a) b)) c)) d)) e)) f)))))))))
  (export main))
