(case "sftB shrink — popmin only (siftdn with computed-index double List.update + smallest scan)"
  (input  (do
            (effect H (op popmin (-> Int64)))
            (def (getat (: xs (List Int64)) (: i Int64))
              (match (List.at xs i) ((Some v) v) ((None u) 0)))
            (def (smallest (: xs (List Int64)) (: i Int64))
              (if (< (+ (* 2 i) 1) (List.len xs))
                  (if (< (getat xs (+ (* 2 i) 1)) (getat xs i))
                      (if (< (+ (* 2 i) 2) (List.len xs))
                          (if (< (getat xs (+ (* 2 i) 2)) (getat xs (+ (* 2 i) 1))) (+ (* 2 i) 2) (+ (* 2 i) 1))
                          (+ (* 2 i) 1))
                      (if (< (+ (* 2 i) 2) (List.len xs))
                          (if (< (getat xs (+ (* 2 i) 2)) (getat xs i)) (+ (* 2 i) 2) i)
                          i))
                  i))
            (def (siftdn (: xs (List Int64)) (: i Int64))
              (if (= (smallest xs i) i)
                  xs
                  (siftdn (List.update (List.update xs (smallest xs i) (getat xs i)) i (getat xs (smallest xs i))) (smallest xs i))))
            (def (dropl (: xs (List Int64)) (: i Int64) (: keep Int64) (: acc (List Int64)))
              (if (< i keep)
                  (dropl xs (+ i 1) keep (List.push acc (getat xs i)))
                  acc))
            (def (main (: n Int64))
              (handle H (: (list 9 n 7) (List Int64))
                ((popmin () st
                  (if (= (List.len st) 0)
                      (resume -99 st)
                      (if (= (List.len st) 1)
                          (resume (getat st 0) (: (list) (List Int64)))
                          (match (siftdn (List.update (dropl st 0 (- (List.len st) 1) (: (list) (List Int64))) 0 (getat st (- (List.len st) 1))) 0)
                            (h2 (resume (getat st 0) h2)))))))
                (H.popmin)))
            (export main)))
  (call   main (: 10 Int64)) (output (: 9 Int64))
  (call   main (: 0 Int64)) (output (: 9 Int64)))
