(case "pysh7 probe: THREE-level SAME-EFFECT nested shadowing — three handle E for one effect E, seeds n%3 / 5 / 20, answers (* s 1000) / (* s 100) / (* s 10) all threading (+ s 1); the body performs an outer tick, then a mid tick, then two innermost ticks, so each nested handle E shadows the ones outside it only within its own body and each level threads its own state independently"
  (input (do
  (effect E (op tick (-> Int64)))
  (def (main (: n Int64))
    (handle E (% n 3)
      ((tick () s (resume (* s 1000) (+ s 1))))
      (+ (E.tick)
         (handle E (: 5 Int64)
           ((tick () s (resume (* s 100) (+ s 1))))
           (+ (E.tick)
              (handle E (: 20 Int64)
                ((tick () s (resume (* s 10) (+ s 1))))
                (+ (E.tick) (E.tick))))))))
  (export main)))
  (call   main (: 10 Int64)) (output (: 1910 Int64))
  (call   main (: 0 Int64)) (output (: 910 Int64)))
