(case "bas1 a BASE-7 codec state — encode peels a value's digits MSB-first onto the list (recursive prepend-peel), decode folds the WHOLE accumulated digit run back and clears; concatenated encodes decode as positional composition"
  (input  (do
            (effect S
              (op enc (-> Int64 Int64))
              (op dec (-> Int64)))
            (def (peel (: x Int64) (: acc (List Int64)))
              (if (= x 0) acc (peel (/ x 7) (List.prepend acc (% x 7)))))
            (def (fold7 (: ds (List Int64)) (: i Int64) (: acc Int64))
              (match (List.at ds i)
                ((Some d) (fold7 ds (+ i 1) (+ (* acc 7) d)))
                ((None u) acc)))
            (def (cat (: a (List Int64)) (: b (List Int64)) (: i Int64))
              (match (List.at b i)
                ((Some v) (cat (List.push a v) b (+ i 1)))
                ((None u) a)))
            (def (main (: n Int64))
              (handle S (: (list) (List Int64))
                ((enc (v) digs
                  (let ((ds (if (= v 0) (list 0) (peel v (: (list) (List Int64))))))
                    (let ((d2 (cat digs ds 0)))
                      (resume (List.len d2) d2))))
                 (dec () digs
                  (resume (fold7 digs 0 0) (: (list) (List Int64)))))
                (let ((a (S.enc n)))
                  (let ((b (S.enc 3)))
                    (let ((c (S.dec)))
                      (let ((d (S.enc 50)))
                        (let ((e (S.dec)))
                          (+ (* 1000 (+ (* 10 (+ (* 1000 (+ (* 10 a) b)) c)) d)) e))))))))
            (export main)))
  (call   main (: 10 Int64)) (output (: 230733050 Int64))
  (call   main (: 48 Int64)) (output (: 233393050 Int64)))
