(case "lstB the lstD twin with a BRANCH around the dual-use let — a capacity check answers negated length when full, else grows through the bound list"
  (input  (do
            (effect L (op grow (-> Int64)))
            (def (lastv (: xs (List Int64)))
              (match (List.at xs (- (List.len xs) 1)) ((Some v) v) ((None u) 0)))
            (def (main (: n Int64))
              (handle L (: (list n 7) (List Int64))
                ((grow () st
                  (if (< 4 (List.len st))
                      (resume (- 0 (List.len st)) st)
                      (let ((r (List.push st (+ (lastv st) 1))))
                        (resume (+ (List.len r) (lastv r)) r)))))
                (let ((a (L.grow)))
                  (let ((b (L.grow)))
                    (let ((c (L.grow)))
                      (let ((d (L.grow)))
                        (+ (* 100 (+ (* 100 (+ (* 100 a) b)) c)) d)))))))
            (export main)))
  (call   main (: 10 Int64)) (output (: 11131495 Int64))
  (call   main (: 0 Int64)) (output (: 11131495 Int64)))
