(case "lstS the tsq4 kernel isolated — the let-bound list feeds the resume value AND a SECOND recursive call (prefix-drop) in the state slot, four straight-line dispatches"
  (input  (do
            (effect L (op popl (-> Int64)))
            (def (lastv (: xs (List Int64)))
              (match (List.at xs (- (List.len xs) 1)) ((Some v) v) ((None u) 0)))
            (def (dropl (: xs (List Int64)) (: i Int64) (: keep Int64) (: acc (List Int64)))
              (if (< i keep)
                  (dropl xs (+ i 1) keep (List.push acc (match (List.at xs i) ((Some v) v) ((None u) 0))))
                  acc))
            (def (main (: n Int64))
              (handle L (: (list n 7 (+ n 2)) (List Int64))
                ((popl () st
                  (if (= (List.len st) 0)
                      (resume -99 st)
                      (let ((r st))
                        (resume (lastv r) (dropl r 0 (- (List.len r) 1) (: (list) (List Int64))))))))
                (let ((a (L.popl)))
                  (let ((b (L.popl)))
                    (let ((c (L.popl)))
                      (let ((d (L.popl)))
                        (+ (* 100 (+ (* 100 (+ (* 100 a) b)) c)) d)))))))
            (export main)))
  (call   main (: 10 Int64)) (output (: 12070901 Int64))
  (call   main (: 0 Int64)) (output (: 2069901 Int64)))
