(case "lstY the lstR arm in a MIXED-op region — the recursive copyapp-built dual-use let interleaves with a llen reader"
  (input  (do
            (effect L (op grow (-> Int64)) (op llen (-> Int64)))
            (def (lastv (: xs (List Int64)))
              (match (List.at xs (- (List.len xs) 1)) ((Some v) v) ((None u) 0)))
            (def (copyapp (: xs (List Int64)) (: i Int64) (: v Int64) (: acc (List Int64)))
              (if (< i (List.len xs))
                  (copyapp xs (+ i 1) v (List.push acc (match (List.at xs i) ((Some w) w) ((None u) 0))))
                  (List.push acc v)))
            (def (main (: n Int64))
              (handle L (: (list n 7) (List Int64))
                ((grow () st
                  (if (< 4 (List.len st))
                      (resume (- 0 (List.len st)) st)
                      (let ((r (copyapp st 0 (+ (lastv st) 1) (: (list) (List Int64)))))
                        (resume (+ (List.len r) (lastv r)) r))))
                 (llen () st (resume (List.len st) st)))
                (let ((a (L.grow)))
                  (let ((b (L.llen)))
                    (let ((c (L.grow)))
                      (let ((d (L.llen)))
                        (+ (* 100 (+ (* 100 (+ (* 100 a) b)) c)) d)))))))
            (export main)))
  (call   main (: 10 Int64)) (output (: 11031304 Int64))
  (call   main (: 0 Int64)) (output (: 11031304 Int64)))
