//! @generated by `xtask-codegen-wasm-abi --crate-lib` from `data/wasm-abi.sexp` — DO NOT hand-edit.
//!
//! The backend's wasm / component-model byte table as a standalone crate: the core opcode table,
//! core + component valtype bytes, section ids, magic headers, and functype form bytes. Projected
//! from the AUTHORITATIVE, hand-authored `data/wasm-abi.sexp` (the language-independent source of
//! truth); `rcdzc` depends on this crate for the constants, so the compiler carries no `wasm-encoder`
//! dependency. A `#[cfg(test)]` oracle module (each byte asserted against the `wasm-encoder` spec
//! encoder, isolated to this crate's dev-dependencies) guards the authored table against a
//! transcription typo.

/// The core-wasm opcode bytes the serializer emits — one `pub const` per Lir
/// instruction, the byte `wasm-encoder` encodes that instruction to. A one-byte opcode
/// each (its operands follow, emitted by the serializer); the extraction asserts that.
pub mod op {
    pub const I32_CONST: u8 = 0x41;
    pub const I64_CONST: u8 = 0x42;
    pub const F64_CONST: u8 = 0x44;
    pub const F32_CONST: u8 = 0x43;
    pub const F64_ADD: u8 = 0xa0;
    pub const F64_SUB: u8 = 0xa1;
    pub const F64_MUL: u8 = 0xa2;
    pub const F64_DIV: u8 = 0xa3;
    pub const F32_ADD: u8 = 0x92;
    pub const F32_SUB: u8 = 0x93;
    pub const F32_MUL: u8 = 0x94;
    pub const F32_DIV: u8 = 0x95;
    pub const F64_EQ: u8 = 0x61;
    pub const F64_NE: u8 = 0x62;
    pub const F32_EQ: u8 = 0x5b;
    pub const F32_NE: u8 = 0x5c;
    pub const F64_LT: u8 = 0x63;
    pub const F64_GT: u8 = 0x64;
    pub const F64_LE: u8 = 0x65;
    pub const F64_GE: u8 = 0x66;
    pub const F32_LT: u8 = 0x5d;
    pub const F32_GT: u8 = 0x5e;
    pub const F32_LE: u8 = 0x5f;
    pub const F32_GE: u8 = 0x60;
    pub const F32_DEMOTE_F64: u8 = 0xb6;
    pub const F64_PROMOTE_F32: u8 = 0xbb;
    pub const F64_CONVERT_I64_S: u8 = 0xb9;
    pub const F32_CONVERT_I64_S: u8 = 0xb4;
    pub const I32_REINTERPRET_F32: u8 = 0xbc;
    pub const I64_REINTERPRET_F64: u8 = 0xbd;
    pub const IF: u8 = 0x04;
    pub const ELSE: u8 = 0x05;
    pub const END: u8 = 0x0b;
    pub const SELECT: u8 = 0x1b;
    pub const DROP: u8 = 0x1a;
    pub const BLOCK: u8 = 0x02;
    pub const LOOP: u8 = 0x03;
    pub const BR: u8 = 0x0c;
    pub const BR_IF: u8 = 0x0d;
    pub const BR_TABLE: u8 = 0x0e;
    pub const LOCAL_GET: u8 = 0x20;
    pub const LOCAL_SET: u8 = 0x21;
    pub const LOCAL_TEE: u8 = 0x22;
    pub const GLOBAL_GET: u8 = 0x23;
    pub const GLOBAL_SET: u8 = 0x24;
    pub const CALL: u8 = 0x10;
    pub const CALL_INDIRECT: u8 = 0x11;
    pub const RETURN_CALL: u8 = 0x12;
    pub const RETURN: u8 = 0x0f;
    pub const UNREACHABLE: u8 = 0x00;
    pub const I32_ADD: u8 = 0x6a;
    pub const I32_SUB: u8 = 0x6b;
    pub const I32_MUL: u8 = 0x6c;
    pub const I32_DIV_S: u8 = 0x6d;
    pub const I32_DIV_U: u8 = 0x6e;
    pub const I32_REM_S: u8 = 0x6f;
    pub const I32_REM_U: u8 = 0x70;
    pub const I32_AND: u8 = 0x71;
    pub const I32_OR: u8 = 0x72;
    pub const I32_XOR: u8 = 0x73;
    pub const I32_SHL: u8 = 0x74;
    pub const I32_SHR_S: u8 = 0x75;
    pub const I32_SHR_U: u8 = 0x76;
    pub const I32_EQ: u8 = 0x46;
    pub const I32_EQZ: u8 = 0x45;
    pub const I32_NE: u8 = 0x47;
    pub const I32_LT_S: u8 = 0x48;
    pub const I32_LT_U: u8 = 0x49;
    pub const I32_GT_S: u8 = 0x4a;
    pub const I32_GT_U: u8 = 0x4b;
    pub const I32_LE_S: u8 = 0x4c;
    pub const I32_LE_U: u8 = 0x4d;
    pub const I32_GE_S: u8 = 0x4e;
    pub const I32_GE_U: u8 = 0x4f;
    pub const I64_ADD: u8 = 0x7c;
    pub const I64_SUB: u8 = 0x7d;
    pub const I64_MUL: u8 = 0x7e;
    pub const I64_DIV_S: u8 = 0x7f;
    pub const I64_DIV_U: u8 = 0x80;
    pub const I64_REM_S: u8 = 0x81;
    pub const I64_REM_U: u8 = 0x82;
    pub const I64_AND: u8 = 0x83;
    pub const I64_OR: u8 = 0x84;
    pub const I64_XOR: u8 = 0x85;
    pub const I64_SHL: u8 = 0x86;
    pub const I64_SHR_S: u8 = 0x87;
    pub const I64_SHR_U: u8 = 0x88;
    pub const I64_EQ: u8 = 0x51;
    pub const I64_EQZ: u8 = 0x50;
    pub const I64_NE: u8 = 0x52;
    pub const I64_LT_S: u8 = 0x53;
    pub const I64_LT_U: u8 = 0x54;
    pub const I64_GT_S: u8 = 0x55;
    pub const I64_GT_U: u8 = 0x56;
    pub const I64_LE_S: u8 = 0x57;
    pub const I64_LE_U: u8 = 0x58;
    pub const I64_GE_S: u8 = 0x59;
    pub const I64_GE_U: u8 = 0x5a;
    pub const I32_WRAP_I64: u8 = 0xa7;
    pub const I64_EXTEND_I32_S: u8 = 0xac;
    pub const I64_EXTEND_I32_U: u8 = 0xad;
    pub const I32_STORE: u8 = 0x36;
    pub const I32_STORE8: u8 = 0x3a;
    pub const I64_STORE: u8 = 0x37;
    pub const F32_STORE: u8 = 0x38;
    pub const F64_STORE: u8 = 0x39;
    pub const I32_STORE16: u8 = 0x3b;
    pub const I32_LOAD: u8 = 0x28;
    pub const I32_LOAD8_U: u8 = 0x2d;
    pub const I64_LOAD: u8 = 0x29;
    pub const F32_LOAD: u8 = 0x2a;
    pub const F64_LOAD: u8 = 0x2b;
    pub const I32_LOAD8_S: u8 = 0x2c;
    pub const I32_LOAD16_S: u8 = 0x2e;
    pub const I32_LOAD16_U: u8 = 0x2f;
}
/// core valtype `i32` — a ≤32-bit scalar's machine slot.
pub const CORE_I32: u8 = 0x7f;
/// core valtype `i64` — a 64-bit scalar's machine slot.
pub const CORE_I64: u8 = 0x7e;
/// core valtype `f32`.
pub const CORE_F32: u8 = 0x7d;
/// core valtype `f64`.
pub const CORE_F64: u8 = 0x7c;
/// empty block type — a structured block (`if`/`block`) that leaves no value.
pub const BLOCK_EMPTY: u8 = 0x40;
/// component `bool`.
pub const COMP_BOOL: u8 = 0x7f;
/// component `s8`.
pub const COMP_S8: u8 = 0x7e;
/// component `u8`.
pub const COMP_U8: u8 = 0x7d;
/// component `s16`.
pub const COMP_S16: u8 = 0x7c;
/// component `u16`.
pub const COMP_U16: u8 = 0x7b;
/// component `s32`.
pub const COMP_S32: u8 = 0x7a;
/// component `u32`.
pub const COMP_U32: u8 = 0x79;
/// component `s64`.
pub const COMP_S64: u8 = 0x78;
/// component `u64`.
pub const COMP_U64: u8 = 0x77;
/// component `f32`.
pub const COMP_F32: u8 = 0x76;
/// component `f64`.
pub const COMP_F64: u8 = 0x75;
/// component `string`.
pub const COMP_STRING: u8 = 0x73;
/// core TYPE section id.
pub const CORE_SEC_TYPE: u8 = 0x01;
/// core FUNCTION section id.
pub const CORE_SEC_FUNCTION: u8 = 0x03;
/// core TABLE section id (the funcref table a closure's `call_indirect` dispatches through — one entry per lambda-lifted closure function).
pub const CORE_SEC_TABLE: u8 = 0x04;
/// core ELEMENT section id (the active segment filling the funcref table with the lifted closure functions' indices, so a closure's stored table slot names its code).
pub const CORE_SEC_ELEMENT: u8 = 0x09;
/// core MEMORY section id (the linear memory a `list<u8>`/`string` return lifts through).
pub const CORE_SEC_MEMORY: u8 = 0x05;
/// core GLOBAL section id (a build-once static compound's handle global; the bump-allocator cursor).
pub const CORE_SEC_GLOBAL: u8 = 0x06;
/// core EXPORT section id.
pub const CORE_SEC_EXPORT: u8 = 0x07;
/// core START section id (the init function that builds each static compound once).
pub const CORE_SEC_START: u8 = 0x08;
/// core CODE section id.
pub const CORE_SEC_CODE: u8 = 0x0a;
/// core DATA section id (an active segment initializing linear memory — the constant value form + return area of a resource escape).
pub const CORE_SEC_DATA: u8 = 0x0b;
/// component CORE-MODULE section id.
pub const COMP_SEC_CORE_MODULE: u8 = 0x01;
/// component CORE-INSTANCE section id.
pub const COMP_SEC_CORE_INSTANCE: u8 = 0x02;
/// component ALIAS section id.
pub const COMP_SEC_ALIAS: u8 = 0x06;
/// component TYPE section id.
pub const COMP_SEC_TYPE: u8 = 0x07;
/// component CANONICAL-FUNCTION section id.
pub const COMP_SEC_CANONICAL: u8 = 0x08;
/// component IMPORT section id.
pub const COMP_SEC_IMPORT: u8 = 0x0a;
/// component EXPORT section id.
pub const COMP_SEC_EXPORT: u8 = 0x0b;
/// component COMPONENT section id (a nested component definition).
pub const COMP_SEC_COMPONENT: u8 = 0x04;
/// component INSTANCE section id (instantiate a component).
pub const COMP_SEC_INSTANCE: u8 = 0x05;
/// core export kind `func` — the export-descriptor byte for a function export.
pub const EXPORT_KIND_FUNC: u8 = 0x00;
/// core export kind `memory` — the export-descriptor byte for a memory export (the resource escape's `memory`).
pub const EXPORT_KIND_MEMORY: u8 = 0x02;
/// core functype form tag — opens a core `func` type before its param/result vecs.
pub const CORE_FUNCTYPE_FORM: u8 = 0x60;
/// component functype form tag — opens a component function type.
pub const COMP_FUNCTYPE_FORM: u8 = 0x40;
/// the `\0asm` version-1 core-module preamble.
pub const CORE_MAGIC: &[u8] = &[0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00];
/// the `\0asm` component-layer preamble (component-model version).
pub const COMPONENT_MAGIC: &[u8] = &[0x00, 0x61, 0x73, 0x6d, 0x0d, 0x00, 0x01, 0x00];

#[cfg(test)]
mod oracle {
    //! @generated — the operator's inverted guarantee: every constant above matches the `wasm-encoder` spec
    //! oracle. A hand-edit to `wasm-abi.sexp` that transcribes a wrong byte fails these tests. `wasm-encoder`
    //! is a DEV-dependency of this crate ONLY (its consumers do not carry it).
    #![allow(unused_imports)]
    use wasm_encoder::{
        BlockType, Component, ComponentSectionId, Encode, ExportKind, Instruction, Module,
        PrimitiveValType, SectionId, ValType,
    };

    /// The first byte `wasm-encoder` emits for a value — the opcode / tag byte the backend constant should equal.
    fn byte0<E: Encode>(v: E) -> u8 {
        let mut b = Vec::new();
        v.encode(&mut b);
        assert!(!b.is_empty(), "wasm-encoder emitted no bytes");
        b[0]
    }

    #[test]
    fn opcodes_match_wasm_encoder() {
        assert_eq!(
            super::op::I32_CONST,
            byte0(Instruction::I32Const(0)),
            "I32_CONST"
        );
        assert_eq!(
            super::op::I64_CONST,
            byte0(Instruction::I64Const(0)),
            "I64_CONST"
        );
        assert_eq!(
            super::op::F64_CONST,
            byte0(Instruction::F64Const(0.0f64.into())),
            "F64_CONST"
        );
        assert_eq!(
            super::op::F32_CONST,
            byte0(Instruction::F32Const(0.0f32.into())),
            "F32_CONST"
        );
        assert_eq!(super::op::F64_ADD, byte0(Instruction::F64Add), "F64_ADD");
        assert_eq!(super::op::F64_SUB, byte0(Instruction::F64Sub), "F64_SUB");
        assert_eq!(super::op::F64_MUL, byte0(Instruction::F64Mul), "F64_MUL");
        assert_eq!(super::op::F64_DIV, byte0(Instruction::F64Div), "F64_DIV");
        assert_eq!(super::op::F32_ADD, byte0(Instruction::F32Add), "F32_ADD");
        assert_eq!(super::op::F32_SUB, byte0(Instruction::F32Sub), "F32_SUB");
        assert_eq!(super::op::F32_MUL, byte0(Instruction::F32Mul), "F32_MUL");
        assert_eq!(super::op::F32_DIV, byte0(Instruction::F32Div), "F32_DIV");
        assert_eq!(super::op::F64_EQ, byte0(Instruction::F64Eq), "F64_EQ");
        assert_eq!(super::op::F64_NE, byte0(Instruction::F64Ne), "F64_NE");
        assert_eq!(super::op::F32_EQ, byte0(Instruction::F32Eq), "F32_EQ");
        assert_eq!(super::op::F32_NE, byte0(Instruction::F32Ne), "F32_NE");
        assert_eq!(super::op::F64_LT, byte0(Instruction::F64Lt), "F64_LT");
        assert_eq!(super::op::F64_GT, byte0(Instruction::F64Gt), "F64_GT");
        assert_eq!(super::op::F64_LE, byte0(Instruction::F64Le), "F64_LE");
        assert_eq!(super::op::F64_GE, byte0(Instruction::F64Ge), "F64_GE");
        assert_eq!(super::op::F32_LT, byte0(Instruction::F32Lt), "F32_LT");
        assert_eq!(super::op::F32_GT, byte0(Instruction::F32Gt), "F32_GT");
        assert_eq!(super::op::F32_LE, byte0(Instruction::F32Le), "F32_LE");
        assert_eq!(super::op::F32_GE, byte0(Instruction::F32Ge), "F32_GE");
        assert_eq!(
            super::op::F32_DEMOTE_F64,
            byte0(Instruction::F32DemoteF64),
            "F32_DEMOTE_F64"
        );
        assert_eq!(
            super::op::F64_PROMOTE_F32,
            byte0(Instruction::F64PromoteF32),
            "F64_PROMOTE_F32"
        );
        assert_eq!(
            super::op::F64_CONVERT_I64_S,
            byte0(Instruction::F64ConvertI64S),
            "F64_CONVERT_I64_S"
        );
        assert_eq!(
            super::op::F32_CONVERT_I64_S,
            byte0(Instruction::F32ConvertI64S),
            "F32_CONVERT_I64_S"
        );
        assert_eq!(
            super::op::I32_REINTERPRET_F32,
            byte0(Instruction::I32ReinterpretF32),
            "I32_REINTERPRET_F32"
        );
        assert_eq!(
            super::op::I64_REINTERPRET_F64,
            byte0(Instruction::I64ReinterpretF64),
            "I64_REINTERPRET_F64"
        );
        assert_eq!(
            super::op::IF,
            byte0(Instruction::If(wasm_encoder::BlockType::Empty)),
            "IF"
        );
        assert_eq!(super::op::ELSE, byte0(Instruction::Else), "ELSE");
        assert_eq!(super::op::END, byte0(Instruction::End), "END");
        assert_eq!(super::op::SELECT, byte0(Instruction::Select), "SELECT");
        assert_eq!(super::op::DROP, byte0(Instruction::Drop), "DROP");
        assert_eq!(
            super::op::BLOCK,
            byte0(Instruction::Block(wasm_encoder::BlockType::Empty)),
            "BLOCK"
        );
        assert_eq!(
            super::op::LOOP,
            byte0(Instruction::Loop(wasm_encoder::BlockType::Empty)),
            "LOOP"
        );
        assert_eq!(super::op::BR, byte0(Instruction::Br(0)), "BR");
        assert_eq!(super::op::BR_IF, byte0(Instruction::BrIf(0)), "BR_IF");
        assert_eq!(
            super::op::BR_TABLE,
            byte0(Instruction::BrTable(std::borrow::Cow::Borrowed(&[]), 0)),
            "BR_TABLE"
        );
        assert_eq!(
            super::op::LOCAL_GET,
            byte0(Instruction::LocalGet(0)),
            "LOCAL_GET"
        );
        assert_eq!(
            super::op::LOCAL_SET,
            byte0(Instruction::LocalSet(0)),
            "LOCAL_SET"
        );
        assert_eq!(
            super::op::LOCAL_TEE,
            byte0(Instruction::LocalTee(0)),
            "LOCAL_TEE"
        );
        assert_eq!(
            super::op::GLOBAL_GET,
            byte0(Instruction::GlobalGet(0)),
            "GLOBAL_GET"
        );
        assert_eq!(
            super::op::GLOBAL_SET,
            byte0(Instruction::GlobalSet(0)),
            "GLOBAL_SET"
        );
        assert_eq!(super::op::CALL, byte0(Instruction::Call(0)), "CALL");
        assert_eq!(
            super::op::CALL_INDIRECT,
            byte0(Instruction::CallIndirect {
                type_index: 0,
                table_index: 0,
            }),
            "CALL_INDIRECT"
        );
        assert_eq!(
            super::op::RETURN_CALL,
            byte0(Instruction::ReturnCall(0)),
            "RETURN_CALL"
        );
        assert_eq!(super::op::RETURN, byte0(Instruction::Return), "RETURN");
        assert_eq!(
            super::op::UNREACHABLE,
            byte0(Instruction::Unreachable),
            "UNREACHABLE"
        );
        assert_eq!(super::op::I32_ADD, byte0(Instruction::I32Add), "I32_ADD");
        assert_eq!(super::op::I32_SUB, byte0(Instruction::I32Sub), "I32_SUB");
        assert_eq!(super::op::I32_MUL, byte0(Instruction::I32Mul), "I32_MUL");
        assert_eq!(
            super::op::I32_DIV_S,
            byte0(Instruction::I32DivS),
            "I32_DIV_S"
        );
        assert_eq!(
            super::op::I32_DIV_U,
            byte0(Instruction::I32DivU),
            "I32_DIV_U"
        );
        assert_eq!(
            super::op::I32_REM_S,
            byte0(Instruction::I32RemS),
            "I32_REM_S"
        );
        assert_eq!(
            super::op::I32_REM_U,
            byte0(Instruction::I32RemU),
            "I32_REM_U"
        );
        assert_eq!(super::op::I32_AND, byte0(Instruction::I32And), "I32_AND");
        assert_eq!(super::op::I32_OR, byte0(Instruction::I32Or), "I32_OR");
        assert_eq!(super::op::I32_XOR, byte0(Instruction::I32Xor), "I32_XOR");
        assert_eq!(super::op::I32_SHL, byte0(Instruction::I32Shl), "I32_SHL");
        assert_eq!(
            super::op::I32_SHR_S,
            byte0(Instruction::I32ShrS),
            "I32_SHR_S"
        );
        assert_eq!(
            super::op::I32_SHR_U,
            byte0(Instruction::I32ShrU),
            "I32_SHR_U"
        );
        assert_eq!(super::op::I32_EQ, byte0(Instruction::I32Eq), "I32_EQ");
        assert_eq!(super::op::I32_EQZ, byte0(Instruction::I32Eqz), "I32_EQZ");
        assert_eq!(super::op::I32_NE, byte0(Instruction::I32Ne), "I32_NE");
        assert_eq!(super::op::I32_LT_S, byte0(Instruction::I32LtS), "I32_LT_S");
        assert_eq!(super::op::I32_LT_U, byte0(Instruction::I32LtU), "I32_LT_U");
        assert_eq!(super::op::I32_GT_S, byte0(Instruction::I32GtS), "I32_GT_S");
        assert_eq!(super::op::I32_GT_U, byte0(Instruction::I32GtU), "I32_GT_U");
        assert_eq!(super::op::I32_LE_S, byte0(Instruction::I32LeS), "I32_LE_S");
        assert_eq!(super::op::I32_LE_U, byte0(Instruction::I32LeU), "I32_LE_U");
        assert_eq!(super::op::I32_GE_S, byte0(Instruction::I32GeS), "I32_GE_S");
        assert_eq!(super::op::I32_GE_U, byte0(Instruction::I32GeU), "I32_GE_U");
        assert_eq!(super::op::I64_ADD, byte0(Instruction::I64Add), "I64_ADD");
        assert_eq!(super::op::I64_SUB, byte0(Instruction::I64Sub), "I64_SUB");
        assert_eq!(super::op::I64_MUL, byte0(Instruction::I64Mul), "I64_MUL");
        assert_eq!(
            super::op::I64_DIV_S,
            byte0(Instruction::I64DivS),
            "I64_DIV_S"
        );
        assert_eq!(
            super::op::I64_DIV_U,
            byte0(Instruction::I64DivU),
            "I64_DIV_U"
        );
        assert_eq!(
            super::op::I64_REM_S,
            byte0(Instruction::I64RemS),
            "I64_REM_S"
        );
        assert_eq!(
            super::op::I64_REM_U,
            byte0(Instruction::I64RemU),
            "I64_REM_U"
        );
        assert_eq!(super::op::I64_AND, byte0(Instruction::I64And), "I64_AND");
        assert_eq!(super::op::I64_OR, byte0(Instruction::I64Or), "I64_OR");
        assert_eq!(super::op::I64_XOR, byte0(Instruction::I64Xor), "I64_XOR");
        assert_eq!(super::op::I64_SHL, byte0(Instruction::I64Shl), "I64_SHL");
        assert_eq!(
            super::op::I64_SHR_S,
            byte0(Instruction::I64ShrS),
            "I64_SHR_S"
        );
        assert_eq!(
            super::op::I64_SHR_U,
            byte0(Instruction::I64ShrU),
            "I64_SHR_U"
        );
        assert_eq!(super::op::I64_EQ, byte0(Instruction::I64Eq), "I64_EQ");
        assert_eq!(super::op::I64_EQZ, byte0(Instruction::I64Eqz), "I64_EQZ");
        assert_eq!(super::op::I64_NE, byte0(Instruction::I64Ne), "I64_NE");
        assert_eq!(super::op::I64_LT_S, byte0(Instruction::I64LtS), "I64_LT_S");
        assert_eq!(super::op::I64_LT_U, byte0(Instruction::I64LtU), "I64_LT_U");
        assert_eq!(super::op::I64_GT_S, byte0(Instruction::I64GtS), "I64_GT_S");
        assert_eq!(super::op::I64_GT_U, byte0(Instruction::I64GtU), "I64_GT_U");
        assert_eq!(super::op::I64_LE_S, byte0(Instruction::I64LeS), "I64_LE_S");
        assert_eq!(super::op::I64_LE_U, byte0(Instruction::I64LeU), "I64_LE_U");
        assert_eq!(super::op::I64_GE_S, byte0(Instruction::I64GeS), "I64_GE_S");
        assert_eq!(super::op::I64_GE_U, byte0(Instruction::I64GeU), "I64_GE_U");
        assert_eq!(
            super::op::I32_WRAP_I64,
            byte0(Instruction::I32WrapI64),
            "I32_WRAP_I64"
        );
        assert_eq!(
            super::op::I64_EXTEND_I32_S,
            byte0(Instruction::I64ExtendI32S),
            "I64_EXTEND_I32_S"
        );
        assert_eq!(
            super::op::I64_EXTEND_I32_U,
            byte0(Instruction::I64ExtendI32U),
            "I64_EXTEND_I32_U"
        );
        assert_eq!(
            super::op::I32_STORE,
            byte0(Instruction::I32Store(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            })),
            "I32_STORE"
        );
        assert_eq!(
            super::op::I32_STORE8,
            byte0(Instruction::I32Store8(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            })),
            "I32_STORE8"
        );
        assert_eq!(
            super::op::I64_STORE,
            byte0(Instruction::I64Store(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            })),
            "I64_STORE"
        );
        assert_eq!(
            super::op::F32_STORE,
            byte0(Instruction::F32Store(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            })),
            "F32_STORE"
        );
        assert_eq!(
            super::op::F64_STORE,
            byte0(Instruction::F64Store(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            })),
            "F64_STORE"
        );
        assert_eq!(
            super::op::I32_STORE16,
            byte0(Instruction::I32Store16(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            })),
            "I32_STORE16"
        );
        assert_eq!(
            super::op::I32_LOAD,
            byte0(Instruction::I32Load(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            })),
            "I32_LOAD"
        );
        assert_eq!(
            super::op::I32_LOAD8_U,
            byte0(Instruction::I32Load8U(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            })),
            "I32_LOAD8_U"
        );
        assert_eq!(
            super::op::I64_LOAD,
            byte0(Instruction::I64Load(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            })),
            "I64_LOAD"
        );
        assert_eq!(
            super::op::F32_LOAD,
            byte0(Instruction::F32Load(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            })),
            "F32_LOAD"
        );
        assert_eq!(
            super::op::F64_LOAD,
            byte0(Instruction::F64Load(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            })),
            "F64_LOAD"
        );
        assert_eq!(
            super::op::I32_LOAD8_S,
            byte0(Instruction::I32Load8S(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            })),
            "I32_LOAD8_S"
        );
        assert_eq!(
            super::op::I32_LOAD16_S,
            byte0(Instruction::I32Load16S(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            })),
            "I32_LOAD16_S"
        );
        assert_eq!(
            super::op::I32_LOAD16_U,
            byte0(Instruction::I32Load16U(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            })),
            "I32_LOAD16_U"
        );
    }

    #[test]
    fn singles_match_wasm_encoder() {
        assert_eq!(super::CORE_I32, byte0(ValType::I32), "CORE_I32");
        assert_eq!(super::CORE_I64, byte0(ValType::I64), "CORE_I64");
        assert_eq!(super::CORE_F32, byte0(ValType::F32), "CORE_F32");
        assert_eq!(super::CORE_F64, byte0(ValType::F64), "CORE_F64");
        assert_eq!(
            super::BLOCK_EMPTY,
            byte0(wasm_encoder::BlockType::Empty),
            "BLOCK_EMPTY"
        );
        assert_eq!(super::COMP_BOOL, byte0(PrimitiveValType::Bool), "COMP_BOOL");
        assert_eq!(super::COMP_S8, byte0(PrimitiveValType::S8), "COMP_S8");
        assert_eq!(super::COMP_U8, byte0(PrimitiveValType::U8), "COMP_U8");
        assert_eq!(super::COMP_S16, byte0(PrimitiveValType::S16), "COMP_S16");
        assert_eq!(super::COMP_U16, byte0(PrimitiveValType::U16), "COMP_U16");
        assert_eq!(super::COMP_S32, byte0(PrimitiveValType::S32), "COMP_S32");
        assert_eq!(super::COMP_U32, byte0(PrimitiveValType::U32), "COMP_U32");
        assert_eq!(super::COMP_S64, byte0(PrimitiveValType::S64), "COMP_S64");
        assert_eq!(super::COMP_U64, byte0(PrimitiveValType::U64), "COMP_U64");
        assert_eq!(super::COMP_F32, byte0(PrimitiveValType::F32), "COMP_F32");
        assert_eq!(super::COMP_F64, byte0(PrimitiveValType::F64), "COMP_F64");
        assert_eq!(
            super::COMP_STRING,
            byte0(PrimitiveValType::String),
            "COMP_STRING"
        );
        assert_eq!(
            super::CORE_SEC_TYPE,
            u8::from(SectionId::Type),
            "CORE_SEC_TYPE"
        );
        assert_eq!(
            super::CORE_SEC_FUNCTION,
            u8::from(SectionId::Function),
            "CORE_SEC_FUNCTION"
        );
        assert_eq!(
            super::CORE_SEC_TABLE,
            u8::from(SectionId::Table),
            "CORE_SEC_TABLE"
        );
        assert_eq!(
            super::CORE_SEC_ELEMENT,
            u8::from(SectionId::Element),
            "CORE_SEC_ELEMENT"
        );
        assert_eq!(
            super::CORE_SEC_MEMORY,
            u8::from(SectionId::Memory),
            "CORE_SEC_MEMORY"
        );
        assert_eq!(
            super::CORE_SEC_GLOBAL,
            u8::from(SectionId::Global),
            "CORE_SEC_GLOBAL"
        );
        assert_eq!(
            super::CORE_SEC_EXPORT,
            u8::from(SectionId::Export),
            "CORE_SEC_EXPORT"
        );
        assert_eq!(
            super::CORE_SEC_START,
            u8::from(SectionId::Start),
            "CORE_SEC_START"
        );
        assert_eq!(
            super::CORE_SEC_CODE,
            u8::from(SectionId::Code),
            "CORE_SEC_CODE"
        );
        assert_eq!(
            super::CORE_SEC_DATA,
            u8::from(SectionId::Data),
            "CORE_SEC_DATA"
        );
        assert_eq!(
            super::COMP_SEC_CORE_MODULE,
            u8::from(ComponentSectionId::CoreModule),
            "COMP_SEC_CORE_MODULE"
        );
        assert_eq!(
            super::COMP_SEC_CORE_INSTANCE,
            u8::from(ComponentSectionId::CoreInstance),
            "COMP_SEC_CORE_INSTANCE"
        );
        assert_eq!(
            super::COMP_SEC_ALIAS,
            u8::from(ComponentSectionId::Alias),
            "COMP_SEC_ALIAS"
        );
        assert_eq!(
            super::COMP_SEC_TYPE,
            u8::from(ComponentSectionId::Type),
            "COMP_SEC_TYPE"
        );
        assert_eq!(
            super::COMP_SEC_CANONICAL,
            u8::from(ComponentSectionId::CanonicalFunction),
            "COMP_SEC_CANONICAL"
        );
        assert_eq!(
            super::COMP_SEC_IMPORT,
            u8::from(ComponentSectionId::Import),
            "COMP_SEC_IMPORT"
        );
        assert_eq!(
            super::COMP_SEC_EXPORT,
            u8::from(ComponentSectionId::Export),
            "COMP_SEC_EXPORT"
        );
        assert_eq!(
            super::COMP_SEC_COMPONENT,
            u8::from(ComponentSectionId::Component),
            "COMP_SEC_COMPONENT"
        );
        assert_eq!(
            super::COMP_SEC_INSTANCE,
            u8::from(ComponentSectionId::Instance),
            "COMP_SEC_INSTANCE"
        );
        assert_eq!(
            super::EXPORT_KIND_FUNC,
            byte0(wasm_encoder::ExportKind::Func),
            "EXPORT_KIND_FUNC"
        );
        assert_eq!(
            super::EXPORT_KIND_MEMORY,
            byte0(wasm_encoder::ExportKind::Memory),
            "EXPORT_KIND_MEMORY"
        );
    }

    #[test]
    fn magics_match_wasm_encoder() {
        assert_eq!(super::CORE_MAGIC, &Module::HEADER, "CORE_MAGIC");
        assert_eq!(
            super::COMPONENT_MAGIC,
            &Component::HEADER,
            "COMPONENT_MAGIC"
        );
    }
}
