on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: k-framework

jobs:
  k-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: camshaft
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build Cadenza CLI
        run: nix develop --accept-flake-config --command cargo build --bin cadenza

      - name: Compile K definition
        run: nix develop --accept-flake-config --command cargo xtask k kompile

      - name: Run K framework tests
        run: nix develop --accept-flake-config --command cargo xtask k test
