//! @generated by `cargo xtask codegen` from cdz-platform/contracts/check.cdz — DO NOT hand-edit.
//!
//! The `check` contract's schema as Cadenza-AST builder calls: `schema(b)` reconstructs the
//! contract's named type declarations, which the platform hands to `Contract::new`. The source is
//! real Cadenza that `cargo xtask codegen` validates + runs the conformance tests of (via the
//! `cdz` binary) before generating this file, so the schema is provably valid Cadenza and a
//! marshalled value type-ascribes against it. Edit the schema in `check.cdz`, then regenerate
//! with `cargo xtask codegen`; `cargo xtask codegen --check` (a hard gate in `xtask check`) fails
//! if this file is stale. Plain builder calls — no dependency on the compiler, so it ships in
//! `cdz-platform`.

#![allow(dead_code)]
#[allow(unused_imports)]
use crate::contract_value as v;
use cadenza_ast::ast::{Arenas, Builder, StructId};
/// The `check` contract's schema: its named Cadenza type declarations, in source order, ready
/// to hand to `Contract::new`. Generated from the contract's Cadenza source, which `cdz`
/// typechecks and runs the conformance tests of at codegen time, so this is provably a
/// valid Cadenza schema.
pub fn schema(b: &mut Builder) -> Vec<StructId> {
    let v0 = b.name("type");
    let v1 = b.name("Envelope");
    let v2 = b.name("Check");
    let v3 = b.name("Record");
    let v4 = b.name(":");
    let v5 = b.name("log");
    let v6 = b.name("Bytes");
    let v7 = b.list(vec![v4, v5, v6]);
    let v8 = b.name(":");
    let v9 = b.name("verdict");
    let v10 = b.name("Bytes");
    let v11 = b.list(vec![v8, v9, v10]);
    let v12 = b.list(vec![v3, v7, v11]);
    let v13 = b.list(vec![v2, v12]);
    let v14 = b.list(vec![v0, v1, v13]);
    let v15 = b.name("type");
    let v16 = b.name("Ack");
    let v17 = b.name("Ack");
    let v18 = b.list(vec![v15, v16, v17]);
    vec![v14, v18]
}
/// The contract this module declares — built from its `@!contract` / `@!input` /
/// `@!output` pragmas and its schema. The one place the contract's name and input/output
/// type references live is the `.cdz` source; `*_contract()` calls this.
pub fn contract() -> crate::Contract {
    crate::Contract::new(
        crate::Str::from_static("cdz-platform.check"),
        schema,
        "Envelope",
        "Ack",
    )
}
/// The fields of a `Envelope.Check` value — each a built value occurrence.
pub struct EnvelopeCheck {
    pub log: StructId,
    pub verdict: StructId,
}
/// Build a canonical `Envelope.Check` value.
pub fn envelope_check(b: &mut Builder, fields: EnvelopeCheck) -> StructId {
    v::record(b, vec![("log", fields.log), ("verdict", fields.verdict)])
}
/// Read a `Envelope.Check` value's fields by name, or `None`.
pub fn as_envelope_check(arenas: &Arenas, id: StructId) -> Option<EnvelopeCheck> {
    let rec = id;
    Some(EnvelopeCheck {
        log: v::record_field(arenas, rec, "log")?,
        verdict: v::record_field(arenas, rec, "verdict")?,
    })
}
/// Build a canonical `Ack.Ack` value.
pub fn ack_ack(b: &mut Builder) -> StructId {
    v::unit(b)
}
/// Whether `id` is a `Ack.Ack` value.
pub fn is_ack_ack(arenas: &Arenas, id: StructId) -> bool {
    v::is_unit(arenas, id)
}
