//! @generated by `cargo xtask codegen` from cdz-platform/contracts/check.cdz — DO NOT hand-edit.
//!
//! The `check` contract's schema as Cadenza-AST builder calls: `schema(b)` reconstructs the
//! contract's named type declarations, which the platform hands to `Contract::new`. The source is
//! real Cadenza that `cargo xtask codegen` validates + runs the conformance tests of (via the
//! `cdz` binary) before generating this file, so the schema is provably valid Cadenza and a
//! marshalled value type-ascribes against it. Edit the schema in `check.cdz`, then regenerate
//! with `cargo xtask codegen`; `cargo xtask codegen --check` (a hard gate in `xtask check`) fails
//! if this file is stale. Plain builder calls — no dependency on the compiler, so it ships in
//! `cdz-platform`.

#![allow(dead_code)]
use crate::contract_value as v;
use cadenza_ast::ast::{Arenas, Builder, StructId};
/// The `check` contract's schema: its named Cadenza type declarations, in source order, ready
/// to hand to `Contract::new`. Generated from the contract's Cadenza source, which `cdz`
/// typechecks and runs the conformance tests of at codegen time, so this is provably a
/// valid Cadenza schema.
pub fn schema(b: &mut Builder) -> Vec<StructId> {
    let v0 = b.name("type");
    let v1 = b.name("Envelope");
    let v2 = b.name("Check");
    let v3 = b.name("Bytes");
    let v4 = b.list(vec![v2, v3]);
    let v5 = b.list(vec![v0, v1, v4]);
    let v6 = b.name("type");
    let v7 = b.name("Ack");
    let v8 = b.name("Ack");
    let v9 = b.list(vec![v6, v7, v8]);
    vec![v5, v9]
}
/// The contract this module declares — built from its `@!contract` / `@!input` /
/// `@!output` pragmas and its schema. The one place the contract's name and input/output
/// type references live is the `.cdz` source; `*_contract()` calls this.
pub fn contract() -> crate::Contract {
    crate::Contract::new(
        crate::Str::from_static("cdz-platform.check"),
        schema,
        "Envelope",
        "Ack",
    )
}
/// Build a canonical `Envelope.Check` value.
pub fn envelope_check(b: &mut Builder, x: StructId) -> StructId {
    v::qctor(b, "Envelope", "Check", vec![x])
}
/// Read the payload of a `Envelope.Check` value, or `None`.
pub fn as_envelope_check(arenas: &Arenas, id: StructId) -> Option<StructId> {
    let t = v::as_qctor(arenas, id, "Envelope", "Check")?;
    let [x] = <[StructId; 1]>::try_from(t).ok()?;
    Some(x)
}
/// Build a canonical `Ack.Ack` value.
pub fn ack_ack(b: &mut Builder) -> StructId {
    v::qctor(b, "Ack", "Ack", vec![])
}
/// Whether `id` is a `Ack.Ack` value.
pub fn is_ack_ack(arenas: &Arenas, id: StructId) -> bool {
    v::as_qctor(arenas, id, "Ack", "Ack").is_some_and(|t| t.is_empty())
}
