//! @generated by `cargo xtask codegen` from cdz-platform/contracts/deliver.cdz — DO NOT hand-edit.
//!
//! The `deliver` contract's schema as Cadenza-AST builder calls: `schema(b)` reconstructs the
//! contract's named type declarations, which the platform hands to `Contract::new`. The source is
//! real Cadenza that `cargo xtask codegen` validates + runs the conformance tests of (via the
//! `cdz` binary) before generating this file, so the schema is provably valid Cadenza and a
//! marshalled value type-ascribes against it. Edit the schema in `deliver.cdz`, then regenerate
//! with `cargo xtask codegen`; `cargo xtask codegen --check` (a hard gate in `xtask check`) fails
//! if this file is stale. Plain builder calls — no dependency on the compiler, so it ships in
//! `cdz-platform`.

#![allow(dead_code)]
use crate::contract_value as v;
use cadenza_ast::ast::{Arenas, Builder, StructId};
/// The `deliver` contract's schema: its named Cadenza type declarations, in source order, ready
/// to hand to `Contract::new`. Generated from the contract's Cadenza source, which `cdz`
/// typechecks and runs the conformance tests of at codegen time, so this is provably a
/// valid Cadenza schema.
pub fn schema(b: &mut Builder) -> Vec<StructId> {
    let v0 = b.name("type");
    let v1 = b.name("Error");
    let v2 = b.name("Timeout");
    let v3 = b.name("MissingHandler");
    let v4 = b.list(vec![v0, v1, v2, v3]);
    let v5 = b.name("type");
    let v6 = b.name("Event");
    let v7 = b.name("Message");
    let v8 = b.name("Record");
    let v9 = b.name(":");
    let v10 = b.name("id");
    let v11 = b.name("Bytes");
    let v12 = b.list(vec![v9, v10, v11]);
    let v13 = b.name(":");
    let v14 = b.name("reducer");
    let v15 = b.name("Bytes");
    let v16 = b.list(vec![v13, v14, v15]);
    let v17 = b.name(":");
    let v18 = b.name("host");
    let v19 = b.name("Bytes");
    let v20 = b.list(vec![v17, v18, v19]);
    let v21 = b.name(":");
    let v22 = b.name("payload");
    let v23 = b.name("Bytes");
    let v24 = b.list(vec![v21, v22, v23]);
    let v25 = b.name(":");
    let v26 = b.name("token");
    let v27 = b.name("Bytes");
    let v28 = b.list(vec![v25, v26, v27]);
    let v29 = b.list(vec![v8, v12, v16, v20, v24, v28]);
    let v30 = b.list(vec![v7, v29]);
    let v31 = b.name("Response");
    let v32 = b.name("Record");
    let v33 = b.name(":");
    let v34 = b.name("id");
    let v35 = b.name("Bytes");
    let v36 = b.list(vec![v33, v34, v35]);
    let v37 = b.name(":");
    let v38 = b.name("token");
    let v39 = b.name("Bytes");
    let v40 = b.list(vec![v37, v38, v39]);
    let v41 = b.name(":");
    let v42 = b.name("result");
    let v43 = b.name("Result");
    let v44 = b.name("Bytes");
    let v45 = b.name("Error");
    let v46 = b.list(vec![v43, v44, v45]);
    let v47 = b.list(vec![v41, v42, v46]);
    let v48 = b.list(vec![v32, v36, v40, v47]);
    let v49 = b.list(vec![v31, v48]);
    let v50 = b.name("Notification");
    let v51 = b.name("Record");
    let v52 = b.name(":");
    let v53 = b.name("id");
    let v54 = b.name("Bytes");
    let v55 = b.list(vec![v52, v53, v54]);
    let v56 = b.name(":");
    let v57 = b.name("payload");
    let v58 = b.name("Bytes");
    let v59 = b.list(vec![v56, v57, v58]);
    let v60 = b.list(vec![v51, v55, v59]);
    let v61 = b.list(vec![v50, v60]);
    let v62 = b.list(vec![v5, v6, v30, v49, v61]);
    let v63 = b.name("type");
    let v64 = b.name("Envelope");
    let v65 = b.name("Deliver");
    let v66 = b.name("Record");
    let v67 = b.name(":");
    let v68 = b.name("target");
    let v69 = b.name("Bytes");
    let v70 = b.list(vec![v67, v68, v69]);
    let v71 = b.name(":");
    let v72 = b.name("event");
    let v73 = b.name("Event");
    let v74 = b.list(vec![v71, v72, v73]);
    let v75 = b.list(vec![v66, v70, v74]);
    let v76 = b.list(vec![v65, v75]);
    let v77 = b.list(vec![v63, v64, v76]);
    let v78 = b.name("type");
    let v79 = b.name("Outcome");
    let v80 = b.name("Delivered");
    let v81 = b.name("Failed");
    let v82 = b.name("Bytes");
    let v83 = b.list(vec![v81, v82]);
    let v84 = b.list(vec![v78, v79, v80, v83]);
    vec![v4, v62, v77, v84]
}
/// Build a canonical `Error.Timeout` value.
pub fn error_timeout(b: &mut Builder) -> StructId {
    v::qctor(b, "Error", "Timeout", vec![])
}
/// Whether `id` is a `Error.Timeout` value.
pub fn is_error_timeout(arenas: &Arenas, id: StructId) -> bool {
    v::as_qctor(arenas, id, "Error", "Timeout").is_some_and(|t| t.is_empty())
}
/// Build a canonical `Error.MissingHandler` value.
pub fn error_missing_handler(b: &mut Builder) -> StructId {
    v::qctor(b, "Error", "MissingHandler", vec![])
}
/// Whether `id` is a `Error.MissingHandler` value.
pub fn is_error_missing_handler(arenas: &Arenas, id: StructId) -> bool {
    v::as_qctor(arenas, id, "Error", "MissingHandler").is_some_and(|t| t.is_empty())
}
/// Build a canonical `Event.Message` value.
pub fn event_message(
    b: &mut Builder,
    id: StructId,
    reducer: StructId,
    host: StructId,
    payload: StructId,
    token: StructId,
) -> StructId {
    let rec = v::record(
        b,
        vec![
            ("id", id),
            ("reducer", reducer),
            ("host", host),
            ("payload", payload),
            ("token", token),
        ],
    );
    v::qctor(b, "Event", "Message", vec![rec])
}
/// Read the 5 field(s) of a `Event.Message` value, in declared order, or `None`.
pub fn as_event_message(arenas: &Arenas, id: StructId) -> Option<[StructId; 5usize]> {
    let t = v::as_qctor(arenas, id, "Event", "Message")?;
    let [rec] = <[StructId; 1]>::try_from(t).ok()?;
    Some([
        v::record_field(arenas, rec, "id")?,
        v::record_field(arenas, rec, "reducer")?,
        v::record_field(arenas, rec, "host")?,
        v::record_field(arenas, rec, "payload")?,
        v::record_field(arenas, rec, "token")?,
    ])
}
/// Build a canonical `Event.Response` value.
pub fn event_response(
    b: &mut Builder,
    id: StructId,
    token: StructId,
    result: StructId,
) -> StructId {
    let rec = v::record(b, vec![("id", id), ("token", token), ("result", result)]);
    v::qctor(b, "Event", "Response", vec![rec])
}
/// Read the 3 field(s) of a `Event.Response` value, in declared order, or `None`.
pub fn as_event_response(arenas: &Arenas, id: StructId) -> Option<[StructId; 3usize]> {
    let t = v::as_qctor(arenas, id, "Event", "Response")?;
    let [rec] = <[StructId; 1]>::try_from(t).ok()?;
    Some([
        v::record_field(arenas, rec, "id")?,
        v::record_field(arenas, rec, "token")?,
        v::record_field(arenas, rec, "result")?,
    ])
}
/// Build a canonical `Event.Notification` value.
pub fn event_notification(b: &mut Builder, id: StructId, payload: StructId) -> StructId {
    let rec = v::record(b, vec![("id", id), ("payload", payload)]);
    v::qctor(b, "Event", "Notification", vec![rec])
}
/// Read the 2 field(s) of a `Event.Notification` value, in declared order, or `None`.
pub fn as_event_notification(arenas: &Arenas, id: StructId) -> Option<[StructId; 2usize]> {
    let t = v::as_qctor(arenas, id, "Event", "Notification")?;
    let [rec] = <[StructId; 1]>::try_from(t).ok()?;
    Some([
        v::record_field(arenas, rec, "id")?,
        v::record_field(arenas, rec, "payload")?,
    ])
}
/// Build a canonical `Envelope.Deliver` value.
pub fn envelope_deliver(b: &mut Builder, target: StructId, event: StructId) -> StructId {
    let rec = v::record(b, vec![("target", target), ("event", event)]);
    v::qctor(b, "Envelope", "Deliver", vec![rec])
}
/// Read the 2 field(s) of a `Envelope.Deliver` value, in declared order, or `None`.
pub fn as_envelope_deliver(arenas: &Arenas, id: StructId) -> Option<[StructId; 2usize]> {
    let t = v::as_qctor(arenas, id, "Envelope", "Deliver")?;
    let [rec] = <[StructId; 1]>::try_from(t).ok()?;
    Some([
        v::record_field(arenas, rec, "target")?,
        v::record_field(arenas, rec, "event")?,
    ])
}
/// Build a canonical `Outcome.Delivered` value.
pub fn outcome_delivered(b: &mut Builder) -> StructId {
    v::qctor(b, "Outcome", "Delivered", vec![])
}
/// Whether `id` is a `Outcome.Delivered` value.
pub fn is_outcome_delivered(arenas: &Arenas, id: StructId) -> bool {
    v::as_qctor(arenas, id, "Outcome", "Delivered").is_some_and(|t| t.is_empty())
}
/// Build a canonical `Outcome.Failed` value.
pub fn outcome_failed(b: &mut Builder, x: StructId) -> StructId {
    v::qctor(b, "Outcome", "Failed", vec![x])
}
/// Read the payload of a `Outcome.Failed` value, or `None`.
pub fn as_outcome_failed(arenas: &Arenas, id: StructId) -> Option<StructId> {
    let t = v::as_qctor(arenas, id, "Outcome", "Failed")?;
    let [x] = <[StructId; 1]>::try_from(t).ok()?;
    Some(x)
}
