//! @generated by `cargo xtask codegen` from cdz-platform/contracts/deliver.cdz — DO NOT hand-edit.
//!
//! The `deliver` contract's schema as Cadenza-AST builder calls: `schema(b)` reconstructs the
//! contract's named type declarations, which the platform hands to `Contract::new`. The source is
//! real Cadenza that `cargo xtask codegen` validates + runs the conformance tests of (via the
//! `cdz` binary) before generating this file, so the schema is provably valid Cadenza and a
//! marshalled value type-ascribes against it. Edit the schema in `deliver.cdz`, then regenerate
//! with `cargo xtask codegen`; `cargo xtask codegen --check` (a hard gate in `xtask check`) fails
//! if this file is stale. Plain builder calls — no dependency on the compiler, so it ships in
//! `cdz-platform`.

#![allow(dead_code)]
#[allow(unused_imports)]
use crate::contract_value as v;
use cadenza_ast::ast::{Arenas, Builder, StructId};
/// The `deliver` contract's schema: its named Cadenza type declarations, in source order, ready
/// to hand to `Contract::new`. Generated from the contract's Cadenza source, which `cdz`
/// typechecks and runs the conformance tests of at codegen time, so this is provably a
/// valid Cadenza schema.
pub fn schema(b: &mut Builder) -> Vec<StructId> {
    let v0 = b.name("type");
    let v1 = b.name("Error");
    let v2 = b.name("Timeout");
    let v3 = b.name("MissingHandler");
    let v4 = b.name("SchemaViolation");
    let v5 = b.name("Faulted");
    let v6 = b.list(vec![v0, v1, v2, v3, v4, v5]);
    let v7 = b.name("type");
    let v8 = b.name("Event");
    let v9 = b.name("Message");
    let v10 = b.name("Record");
    let v11 = b.name(":");
    let v12 = b.name("id");
    let v13 = b.name("Bytes");
    let v14 = b.list(vec![v11, v12, v13]);
    let v15 = b.name(":");
    let v16 = b.name("reducer");
    let v17 = b.name("Bytes");
    let v18 = b.list(vec![v15, v16, v17]);
    let v19 = b.name(":");
    let v20 = b.name("host");
    let v21 = b.name("Bytes");
    let v22 = b.list(vec![v19, v20, v21]);
    let v23 = b.name(":");
    let v24 = b.name("payload");
    let v25 = b.name("Bytes");
    let v26 = b.list(vec![v23, v24, v25]);
    let v27 = b.name(":");
    let v28 = b.name("token");
    let v29 = b.name("Bytes");
    let v30 = b.list(vec![v27, v28, v29]);
    let v31 = b.list(vec![v10, v14, v18, v22, v26, v30]);
    let v32 = b.list(vec![v9, v31]);
    let v33 = b.name("Response");
    let v34 = b.name("Record");
    let v35 = b.name(":");
    let v36 = b.name("id");
    let v37 = b.name("Bytes");
    let v38 = b.list(vec![v35, v36, v37]);
    let v39 = b.name(":");
    let v40 = b.name("token");
    let v41 = b.name("Bytes");
    let v42 = b.list(vec![v39, v40, v41]);
    let v43 = b.name(":");
    let v44 = b.name("result");
    let v45 = b.name("Result");
    let v46 = b.name("Bytes");
    let v47 = b.name("Error");
    let v48 = b.list(vec![v45, v46, v47]);
    let v49 = b.list(vec![v43, v44, v48]);
    let v50 = b.list(vec![v34, v38, v42, v49]);
    let v51 = b.list(vec![v33, v50]);
    let v52 = b.name("Notification");
    let v53 = b.name("Record");
    let v54 = b.name(":");
    let v55 = b.name("id");
    let v56 = b.name("Bytes");
    let v57 = b.list(vec![v54, v55, v56]);
    let v58 = b.name(":");
    let v59 = b.name("payload");
    let v60 = b.name("Bytes");
    let v61 = b.list(vec![v58, v59, v60]);
    let v62 = b.list(vec![v53, v57, v61]);
    let v63 = b.list(vec![v52, v62]);
    let v64 = b.list(vec![v7, v8, v32, v51, v63]);
    let v65 = b.name("type");
    let v66 = b.name("Envelope");
    let v67 = b.name("Deliver");
    let v68 = b.name("Record");
    let v69 = b.name(":");
    let v70 = b.name("target");
    let v71 = b.name("Bytes");
    let v72 = b.list(vec![v69, v70, v71]);
    let v73 = b.name(":");
    let v74 = b.name("event");
    let v75 = b.name("Event");
    let v76 = b.list(vec![v73, v74, v75]);
    let v77 = b.list(vec![v68, v72, v76]);
    let v78 = b.list(vec![v67, v77]);
    let v79 = b.list(vec![v65, v66, v78]);
    let v80 = b.name("type");
    let v81 = b.name("Outcome");
    let v82 = b.name("Delivered");
    let v83 = b.name("Failed");
    let v84 = b.name("Bytes");
    let v85 = b.list(vec![v83, v84]);
    let v86 = b.list(vec![v80, v81, v82, v85]);
    vec![v6, v64, v79, v86]
}
/// The contract this module declares — built from its `@!contract` / `@!input` /
/// `@!output` pragmas and its schema. The one place the contract's name and input/output
/// type references live is the `.cdz` source; `*_contract()` calls this.
pub fn contract() -> crate::Contract {
    crate::Contract::new(
        crate::Str::from_static("cdz-platform.deliver"),
        schema,
        "Envelope",
        "Outcome",
    )
}
/// Build a canonical `Error.Timeout` value.
pub fn error_timeout(b: &mut Builder) -> StructId {
    v::qctor(b, "Error", "Timeout", vec![])
}
/// Whether `id` is a `Error.Timeout` value.
pub fn is_error_timeout(arenas: &Arenas, id: StructId) -> bool {
    v::as_qctor(arenas, id, "Error", "Timeout").is_some_and(|t| t.is_empty())
}
/// Build a canonical `Error.MissingHandler` value.
pub fn error_missing_handler(b: &mut Builder) -> StructId {
    v::qctor(b, "Error", "MissingHandler", vec![])
}
/// Whether `id` is a `Error.MissingHandler` value.
pub fn is_error_missing_handler(arenas: &Arenas, id: StructId) -> bool {
    v::as_qctor(arenas, id, "Error", "MissingHandler").is_some_and(|t| t.is_empty())
}
/// Build a canonical `Error.SchemaViolation` value.
pub fn error_schema_violation(b: &mut Builder) -> StructId {
    v::qctor(b, "Error", "SchemaViolation", vec![])
}
/// Whether `id` is a `Error.SchemaViolation` value.
pub fn is_error_schema_violation(arenas: &Arenas, id: StructId) -> bool {
    v::as_qctor(arenas, id, "Error", "SchemaViolation").is_some_and(|t| t.is_empty())
}
/// Build a canonical `Error.Faulted` value.
pub fn error_faulted(b: &mut Builder) -> StructId {
    v::qctor(b, "Error", "Faulted", vec![])
}
/// Whether `id` is a `Error.Faulted` value.
pub fn is_error_faulted(arenas: &Arenas, id: StructId) -> bool {
    v::as_qctor(arenas, id, "Error", "Faulted").is_some_and(|t| t.is_empty())
}
/// The fields of a `Event.Message` value — each a built value occurrence.
pub struct EventMessage {
    pub id: StructId,
    pub reducer: StructId,
    pub host: StructId,
    pub payload: StructId,
    pub token: StructId,
}
/// Build a canonical `Event.Message` value.
pub fn event_message(b: &mut Builder, fields: EventMessage) -> StructId {
    let rec = v::record(
        b,
        vec![
            ("id", fields.id),
            ("reducer", fields.reducer),
            ("host", fields.host),
            ("payload", fields.payload),
            ("token", fields.token),
        ],
    );
    v::qctor(b, "Event", "Message", vec![rec])
}
/// Read a `Event.Message` value's fields by name, or `None`.
pub fn as_event_message(arenas: &Arenas, id: StructId) -> Option<EventMessage> {
    let t = v::as_qctor(arenas, id, "Event", "Message")?;
    let [rec] = <[StructId; 1]>::try_from(t).ok()?;
    Some(EventMessage {
        id: v::record_field(arenas, rec, "id")?,
        reducer: v::record_field(arenas, rec, "reducer")?,
        host: v::record_field(arenas, rec, "host")?,
        payload: v::record_field(arenas, rec, "payload")?,
        token: v::record_field(arenas, rec, "token")?,
    })
}
/// The fields of a `Event.Response` value — each a built value occurrence.
pub struct EventResponse {
    pub id: StructId,
    pub token: StructId,
    pub result: StructId,
}
/// Build a canonical `Event.Response` value.
pub fn event_response(b: &mut Builder, fields: EventResponse) -> StructId {
    let rec = v::record(
        b,
        vec![
            ("id", fields.id),
            ("token", fields.token),
            ("result", fields.result),
        ],
    );
    v::qctor(b, "Event", "Response", vec![rec])
}
/// Read a `Event.Response` value's fields by name, or `None`.
pub fn as_event_response(arenas: &Arenas, id: StructId) -> Option<EventResponse> {
    let t = v::as_qctor(arenas, id, "Event", "Response")?;
    let [rec] = <[StructId; 1]>::try_from(t).ok()?;
    Some(EventResponse {
        id: v::record_field(arenas, rec, "id")?,
        token: v::record_field(arenas, rec, "token")?,
        result: v::record_field(arenas, rec, "result")?,
    })
}
/// The fields of a `Event.Notification` value — each a built value occurrence.
pub struct EventNotification {
    pub id: StructId,
    pub payload: StructId,
}
/// Build a canonical `Event.Notification` value.
pub fn event_notification(b: &mut Builder, fields: EventNotification) -> StructId {
    let rec = v::record(b, vec![("id", fields.id), ("payload", fields.payload)]);
    v::qctor(b, "Event", "Notification", vec![rec])
}
/// Read a `Event.Notification` value's fields by name, or `None`.
pub fn as_event_notification(arenas: &Arenas, id: StructId) -> Option<EventNotification> {
    let t = v::as_qctor(arenas, id, "Event", "Notification")?;
    let [rec] = <[StructId; 1]>::try_from(t).ok()?;
    Some(EventNotification {
        id: v::record_field(arenas, rec, "id")?,
        payload: v::record_field(arenas, rec, "payload")?,
    })
}
/// The fields of a `Envelope.Deliver` value — each a built value occurrence.
pub struct EnvelopeDeliver {
    pub target: StructId,
    pub event: StructId,
}
/// Build a canonical `Envelope.Deliver` value.
pub fn envelope_deliver(b: &mut Builder, fields: EnvelopeDeliver) -> StructId {
    v::record(b, vec![("target", fields.target), ("event", fields.event)])
}
/// Read a `Envelope.Deliver` value's fields by name, or `None`.
pub fn as_envelope_deliver(arenas: &Arenas, id: StructId) -> Option<EnvelopeDeliver> {
    let rec = id;
    Some(EnvelopeDeliver {
        target: v::record_field(arenas, rec, "target")?,
        event: v::record_field(arenas, rec, "event")?,
    })
}
/// Build a canonical `Outcome.Delivered` value.
pub fn outcome_delivered(b: &mut Builder) -> StructId {
    v::qctor(b, "Outcome", "Delivered", vec![])
}
/// Whether `id` is a `Outcome.Delivered` value.
pub fn is_outcome_delivered(arenas: &Arenas, id: StructId) -> bool {
    v::as_qctor(arenas, id, "Outcome", "Delivered").is_some_and(|t| t.is_empty())
}
/// Build a canonical `Outcome.Failed` value.
pub fn outcome_failed(b: &mut Builder, x: StructId) -> StructId {
    v::qctor(b, "Outcome", "Failed", vec![x])
}
/// Read the payload of a `Outcome.Failed` value, or `None`.
pub fn as_outcome_failed(arenas: &Arenas, id: StructId) -> Option<StructId> {
    let t = v::as_qctor(arenas, id, "Outcome", "Failed")?;
    let [x] = <[StructId; 1]>::try_from(t).ok()?;
    Some(x)
}
