//! @generated by `cargo xtask codegen` from cdz-platform/contracts/fire_after.cdz — DO NOT hand-edit.
//!
//! The `fire_after` contract's schema as Cadenza-AST builder calls: `schema(b)` reconstructs the
//! contract's named type declarations, which the platform hands to `Contract::new`. The source is
//! real Cadenza that `cargo xtask codegen` validates + runs the conformance tests of (via the
//! `cdz` binary) before generating this file, so the schema is provably valid Cadenza and a
//! marshalled value type-ascribes against it. Edit the schema in `fire_after.cdz`, then regenerate
//! with `cargo xtask codegen`; `cargo xtask codegen --check` (a hard gate in `xtask check`) fails
//! if this file is stale. Plain builder calls — no dependency on the compiler, so it ships in
//! `cdz-platform`.

#![allow(dead_code)]
use crate::contract_value as v;
use cadenza_ast::ast::{Arenas, Builder, StructId};
/// The `fire_after` contract's schema: its named Cadenza type declarations, in source order, ready
/// to hand to `Contract::new`. Generated from the contract's Cadenza source, which `cdz`
/// typechecks and runs the conformance tests of at codegen time, so this is provably a
/// valid Cadenza schema.
pub fn schema(b: &mut Builder) -> Vec<StructId> {
    let v0 = b.name("type");
    let v1 = b.name("Arm");
    let v2 = b.name("Arm");
    let v3 = b.name("Record");
    let v4 = b.name(":");
    let v5 = b.name("millis");
    let v6 = b.name("Bytes");
    let v7 = b.list(vec![v4, v5, v6]);
    let v8 = b.name(":");
    let v9 = b.name("token");
    let v10 = b.name("Bytes");
    let v11 = b.list(vec![v8, v9, v10]);
    let v12 = b.list(vec![v3, v7, v11]);
    let v13 = b.list(vec![v2, v12]);
    let v14 = b.list(vec![v0, v1, v13]);
    let v15 = b.name("type");
    let v16 = b.name("Fired");
    let v17 = b.name("Fired");
    let v18 = b.name("Record");
    let v19 = b.name(":");
    let v20 = b.name("token");
    let v21 = b.name("Bytes");
    let v22 = b.list(vec![v19, v20, v21]);
    let v23 = b.list(vec![v18, v22]);
    let v24 = b.list(vec![v17, v23]);
    let v25 = b.list(vec![v15, v16, v24]);
    let v26 = b.name("type");
    let v27 = b.name("Ack");
    let v28 = b.name("Ack");
    let v29 = b.list(vec![v26, v27, v28]);
    vec![v14, v25, v29]
}
/// The fields of a `Arm.Arm` value — each a built value occurrence.
pub struct ArmArm {
    pub millis: StructId,
    pub token: StructId,
}
/// Build a canonical `Arm.Arm` value.
pub fn arm_arm(b: &mut Builder, fields: ArmArm) -> StructId {
    let rec = v::record(b, vec![("millis", fields.millis), ("token", fields.token)]);
    v::qctor(b, "Arm", "Arm", vec![rec])
}
/// Read a `Arm.Arm` value's fields by name, or `None`.
pub fn as_arm_arm(arenas: &Arenas, id: StructId) -> Option<ArmArm> {
    let t = v::as_qctor(arenas, id, "Arm", "Arm")?;
    let [rec] = <[StructId; 1]>::try_from(t).ok()?;
    Some(ArmArm {
        millis: v::record_field(arenas, rec, "millis")?,
        token: v::record_field(arenas, rec, "token")?,
    })
}
/// The fields of a `Fired.Fired` value — each a built value occurrence.
pub struct FiredFired {
    pub token: StructId,
}
/// Build a canonical `Fired.Fired` value.
pub fn fired_fired(b: &mut Builder, fields: FiredFired) -> StructId {
    let rec = v::record(b, vec![("token", fields.token)]);
    v::qctor(b, "Fired", "Fired", vec![rec])
}
/// Read a `Fired.Fired` value's fields by name, or `None`.
pub fn as_fired_fired(arenas: &Arenas, id: StructId) -> Option<FiredFired> {
    let t = v::as_qctor(arenas, id, "Fired", "Fired")?;
    let [rec] = <[StructId; 1]>::try_from(t).ok()?;
    Some(FiredFired {
        token: v::record_field(arenas, rec, "token")?,
    })
}
/// Build a canonical `Ack.Ack` value.
pub fn ack_ack(b: &mut Builder) -> StructId {
    v::qctor(b, "Ack", "Ack", vec![])
}
/// Whether `id` is a `Ack.Ack` value.
pub fn is_ack_ack(arenas: &Arenas, id: StructId) -> bool {
    v::as_qctor(arenas, id, "Ack", "Ack").is_some_and(|t| t.is_empty())
}
