//! @generated by `cargo xtask codegen` from cdz-platform/contracts/forward.cdz — DO NOT hand-edit.
//!
//! The `forward` contract's schema as Cadenza-AST builder calls: `schema(b)` reconstructs the
//! contract's named type declarations, which the platform hands to `Contract::new`. The source is
//! real Cadenza that `cargo xtask codegen` validates + runs the conformance tests of (via the
//! `cdz` binary) before generating this file, so the schema is provably valid Cadenza and a
//! marshalled value type-ascribes against it. Edit the schema in `forward.cdz`, then regenerate
//! with `cargo xtask codegen`; `cargo xtask codegen --check` (a hard gate in `xtask check`) fails
//! if this file is stale. Plain builder calls — no dependency on the compiler, so it ships in
//! `cdz-platform`.

#![allow(dead_code)]
use crate::contract_value as v;
use cadenza_ast::ast::{Arenas, Builder, StructId};
/// The `forward` contract's schema: its named Cadenza type declarations, in source order, ready
/// to hand to `Contract::new`. Generated from the contract's Cadenza source, which `cdz`
/// typechecks and runs the conformance tests of at codegen time, so this is provably a
/// valid Cadenza schema.
pub fn schema(b: &mut Builder) -> Vec<StructId> {
    let v0 = b.name("type");
    let v1 = b.name("Envelope");
    let v2 = b.name("Forward");
    let v3 = b.name("Record");
    let v4 = b.name(":");
    let v5 = b.name("token");
    let v6 = b.name("Bytes");
    let v7 = b.list(vec![v4, v5, v6]);
    let v8 = b.name(":");
    let v9 = b.name("contract");
    let v10 = b.name("Bytes");
    let v11 = b.list(vec![v8, v9, v10]);
    let v12 = b.name(":");
    let v13 = b.name("payload");
    let v14 = b.name("Bytes");
    let v15 = b.list(vec![v12, v13, v14]);
    let v16 = b.list(vec![v3, v7, v11, v15]);
    let v17 = b.list(vec![v2, v16]);
    let v18 = b.list(vec![v0, v1, v17]);
    let v19 = b.name("type");
    let v20 = b.name("Outcome");
    let v21 = b.name("Accepted");
    let v22 = b.name("Failed");
    let v23 = b.name("Bytes");
    let v24 = b.list(vec![v22, v23]);
    let v25 = b.list(vec![v19, v20, v21, v24]);
    vec![v18, v25]
}
/// The contract this module declares — built from its `@!contract` / `@!input` /
/// `@!output` pragmas and its schema. The one place the contract's name and input/output
/// type references live is the `.cdz` source; `*_contract()` calls this.
pub fn contract() -> crate::Contract {
    crate::Contract::new(
        crate::Str::from_static("cdz-platform.forward"),
        schema,
        "Envelope",
        "Outcome",
    )
}
/// The fields of a `Envelope.Forward` value — each a built value occurrence.
pub struct EnvelopeForward {
    pub token: StructId,
    pub contract: StructId,
    pub payload: StructId,
}
/// Build a canonical `Envelope.Forward` value.
pub fn envelope_forward(b: &mut Builder, fields: EnvelopeForward) -> StructId {
    let rec = v::record(
        b,
        vec![
            ("token", fields.token),
            ("contract", fields.contract),
            ("payload", fields.payload),
        ],
    );
    v::qctor(b, "Envelope", "Forward", vec![rec])
}
/// Read a `Envelope.Forward` value's fields by name, or `None`.
pub fn as_envelope_forward(arenas: &Arenas, id: StructId) -> Option<EnvelopeForward> {
    let t = v::as_qctor(arenas, id, "Envelope", "Forward")?;
    let [rec] = <[StructId; 1]>::try_from(t).ok()?;
    Some(EnvelopeForward {
        token: v::record_field(arenas, rec, "token")?,
        contract: v::record_field(arenas, rec, "contract")?,
        payload: v::record_field(arenas, rec, "payload")?,
    })
}
/// Build a canonical `Outcome.Accepted` value.
pub fn outcome_accepted(b: &mut Builder) -> StructId {
    v::qctor(b, "Outcome", "Accepted", vec![])
}
/// Whether `id` is a `Outcome.Accepted` value.
pub fn is_outcome_accepted(arenas: &Arenas, id: StructId) -> bool {
    v::as_qctor(arenas, id, "Outcome", "Accepted").is_some_and(|t| t.is_empty())
}
/// Build a canonical `Outcome.Failed` value.
pub fn outcome_failed(b: &mut Builder, x: StructId) -> StructId {
    v::qctor(b, "Outcome", "Failed", vec![x])
}
/// Read the payload of a `Outcome.Failed` value, or `None`.
pub fn as_outcome_failed(arenas: &Arenas, id: StructId) -> Option<StructId> {
    let t = v::as_qctor(arenas, id, "Outcome", "Failed")?;
    let [x] = <[StructId; 1]>::try_from(t).ok()?;
    Some(x)
}
