//! @generated by `cargo xtask codegen` from cdz-platform/contracts/lifecycle.cdz — DO NOT hand-edit.
//!
//! The `lifecycle` contract's schema as Cadenza-AST builder calls: `schema(b)` reconstructs the
//! contract's named type declarations, which the platform hands to `Contract::new`. The source is
//! real Cadenza that `cargo xtask codegen` validates + runs the conformance tests of (via the
//! `cdz` binary) before generating this file, so the schema is provably valid Cadenza and a
//! marshalled value type-ascribes against it. Edit the schema in `lifecycle.cdz`, then regenerate
//! with `cargo xtask codegen`; `cargo xtask codegen --check` (a hard gate in `xtask check`) fails
//! if this file is stale. Plain builder calls — no dependency on the compiler, so it ships in
//! `cdz-platform`.

#![allow(dead_code)]
#[allow(unused_imports)]
use crate::contract_value as v;
use cadenza_ast::ast::{Arenas, Builder, StructId};
/// The `lifecycle` contract's schema: its named Cadenza type declarations, in source order, ready
/// to hand to `Contract::new`. Generated from the contract's Cadenza source, which `cdz`
/// typechecks and runs the conformance tests of at codegen time, so this is provably a
/// valid Cadenza schema.
pub fn schema(b: &mut Builder) -> Vec<StructId> {
    let v0 = b.name("type");
    let v1 = b.name("Event");
    let v2 = b.name("Exited");
    let v3 = b.name("Record");
    let v4 = b.name(":");
    let v5 = b.name("reducer");
    let v6 = b.name("Bytes");
    let v7 = b.list(vec![v4, v5, v6]);
    let v8 = b.name(":");
    let v9 = b.name("schema");
    let v10 = b.name("Bytes");
    let v11 = b.list(vec![v8, v9, v10]);
    let v12 = b.name(":");
    let v13 = b.name("reason");
    let v14 = b.name("Bytes");
    let v15 = b.list(vec![v12, v13, v14]);
    let v16 = b.list(vec![v3, v7, v11, v15]);
    let v17 = b.list(vec![v2, v16]);
    let v18 = b.name("Crashed");
    let v19 = b.name("Record");
    let v20 = b.name(":");
    let v21 = b.name("reducer");
    let v22 = b.name("Bytes");
    let v23 = b.list(vec![v20, v21, v22]);
    let v24 = b.list(vec![v19, v23]);
    let v25 = b.list(vec![v18, v24]);
    let v26 = b.list(vec![v0, v1, v17, v25]);
    let v27 = b.name("type");
    let v28 = b.name("Ack");
    let v29 = b.name("Ack");
    let v30 = b.list(vec![v27, v28, v29]);
    vec![v26, v30]
}
/// The contract this module declares — built from its `@!contract` / `@!input` /
/// `@!output` pragmas and its schema. The one place the contract's name and input/output
/// type references live is the `.cdz` source; `*_contract()` calls this.
pub fn contract() -> crate::Contract {
    crate::Contract::new(
        crate::Str::from_static("cdz-platform.lifecycle"),
        schema,
        "Event",
        "Ack",
    )
}
/// The fields of a `Event.Exited` value — each a built value occurrence.
pub struct EventExited {
    pub reducer: StructId,
    pub schema: StructId,
    pub reason: StructId,
}
/// Build a canonical `Event.Exited` value.
pub fn event_exited(b: &mut Builder, fields: EventExited) -> StructId {
    let rec = v::record(
        b,
        vec![
            ("reducer", fields.reducer),
            ("schema", fields.schema),
            ("reason", fields.reason),
        ],
    );
    v::qctor(b, "Event", "Exited", vec![rec])
}
/// Read a `Event.Exited` value's fields by name, or `None`.
pub fn as_event_exited(arenas: &Arenas, id: StructId) -> Option<EventExited> {
    let t = v::as_qctor(arenas, id, "Event", "Exited")?;
    let [rec] = <[StructId; 1]>::try_from(t).ok()?;
    Some(EventExited {
        reducer: v::record_field(arenas, rec, "reducer")?,
        schema: v::record_field(arenas, rec, "schema")?,
        reason: v::record_field(arenas, rec, "reason")?,
    })
}
/// The fields of a `Event.Crashed` value — each a built value occurrence.
pub struct EventCrashed {
    pub reducer: StructId,
}
/// Build a canonical `Event.Crashed` value.
pub fn event_crashed(b: &mut Builder, fields: EventCrashed) -> StructId {
    let rec = v::record(b, vec![("reducer", fields.reducer)]);
    v::qctor(b, "Event", "Crashed", vec![rec])
}
/// Read a `Event.Crashed` value's fields by name, or `None`.
pub fn as_event_crashed(arenas: &Arenas, id: StructId) -> Option<EventCrashed> {
    let t = v::as_qctor(arenas, id, "Event", "Crashed")?;
    let [rec] = <[StructId; 1]>::try_from(t).ok()?;
    Some(EventCrashed {
        reducer: v::record_field(arenas, rec, "reducer")?,
    })
}
/// Build a canonical `Ack.Ack` value.
pub fn ack_ack(b: &mut Builder) -> StructId {
    v::unit(b)
}
/// Whether `id` is a `Ack.Ack` value.
pub fn is_ack_ack(arenas: &Arenas, id: StructId) -> bool {
    v::is_unit(arenas, id)
}
