//! @generated by `cargo xtask codegen` from cdz-platform/contracts/respond.cdz — DO NOT hand-edit.
//!
//! The `respond` contract's schema as Cadenza-AST builder calls: `schema(b)` reconstructs the
//! contract's named type declarations, which the platform hands to `Contract::new`. The source is
//! real Cadenza that `cargo xtask codegen` validates + runs the conformance tests of (via the
//! `cdz` binary) before generating this file, so the schema is provably valid Cadenza and a
//! marshalled value type-ascribes against it. Edit the schema in `respond.cdz`, then regenerate
//! with `cargo xtask codegen`; `cargo xtask codegen --check` (a hard gate in `xtask check`) fails
//! if this file is stale. Plain builder calls — no dependency on the compiler, so it ships in
//! `cdz-platform`.

#![allow(dead_code)]
use crate::contract_value as v;
use cadenza_ast::ast::{Arenas, Builder, StructId};
/// The `respond` contract's schema: its named Cadenza type declarations, in source order, ready
/// to hand to `Contract::new`. Generated from the contract's Cadenza source, which `cdz`
/// typechecks and runs the conformance tests of at codegen time, so this is provably a
/// valid Cadenza schema.
pub fn schema(b: &mut Builder) -> Vec<StructId> {
    let v0 = b.name("type");
    let v1 = b.name("Error");
    let v2 = b.name("Timeout");
    let v3 = b.name("MissingHandler");
    let v4 = b.name("SchemaViolation");
    let v5 = b.name("Faulted");
    let v6 = b.list(vec![v0, v1, v2, v3, v4, v5]);
    let v7 = b.name("type");
    let v8 = b.name("Envelope");
    let v9 = b.name("Respond");
    let v10 = b.name("Record");
    let v11 = b.name(":");
    let v12 = b.name("token");
    let v13 = b.name("Bytes");
    let v14 = b.list(vec![v11, v12, v13]);
    let v15 = b.name(":");
    let v16 = b.name("answer");
    let v17 = b.name("Result");
    let v18 = b.name("Bytes");
    let v19 = b.name("Error");
    let v20 = b.list(vec![v17, v18, v19]);
    let v21 = b.list(vec![v15, v16, v20]);
    let v22 = b.list(vec![v10, v14, v21]);
    let v23 = b.list(vec![v9, v22]);
    let v24 = b.list(vec![v7, v8, v23]);
    let v25 = b.name("type");
    let v26 = b.name("Outcome");
    let v27 = b.name("Accepted");
    let v28 = b.name("Failed");
    let v29 = b.name("Bytes");
    let v30 = b.list(vec![v28, v29]);
    let v31 = b.list(vec![v25, v26, v27, v30]);
    vec![v6, v24, v31]
}
/// The contract this module declares — built from its `@!contract` / `@!input` /
/// `@!output` pragmas and its schema. The one place the contract's name and input/output
/// type references live is the `.cdz` source; `*_contract()` calls this.
pub fn contract() -> crate::Contract {
    crate::Contract::new(
        crate::Str::from_static("cdz-platform.respond"),
        schema,
        "Envelope",
        "Outcome",
    )
}
/// Build a canonical `Error.Timeout` value.
pub fn error_timeout(b: &mut Builder) -> StructId {
    v::qctor(b, "Error", "Timeout", vec![])
}
/// Whether `id` is a `Error.Timeout` value.
pub fn is_error_timeout(arenas: &Arenas, id: StructId) -> bool {
    v::as_qctor(arenas, id, "Error", "Timeout").is_some_and(|t| t.is_empty())
}
/// Build a canonical `Error.MissingHandler` value.
pub fn error_missing_handler(b: &mut Builder) -> StructId {
    v::qctor(b, "Error", "MissingHandler", vec![])
}
/// Whether `id` is a `Error.MissingHandler` value.
pub fn is_error_missing_handler(arenas: &Arenas, id: StructId) -> bool {
    v::as_qctor(arenas, id, "Error", "MissingHandler").is_some_and(|t| t.is_empty())
}
/// Build a canonical `Error.SchemaViolation` value.
pub fn error_schema_violation(b: &mut Builder) -> StructId {
    v::qctor(b, "Error", "SchemaViolation", vec![])
}
/// Whether `id` is a `Error.SchemaViolation` value.
pub fn is_error_schema_violation(arenas: &Arenas, id: StructId) -> bool {
    v::as_qctor(arenas, id, "Error", "SchemaViolation").is_some_and(|t| t.is_empty())
}
/// Build a canonical `Error.Faulted` value.
pub fn error_faulted(b: &mut Builder) -> StructId {
    v::qctor(b, "Error", "Faulted", vec![])
}
/// Whether `id` is a `Error.Faulted` value.
pub fn is_error_faulted(arenas: &Arenas, id: StructId) -> bool {
    v::as_qctor(arenas, id, "Error", "Faulted").is_some_and(|t| t.is_empty())
}
/// The fields of a `Envelope.Respond` value — each a built value occurrence.
pub struct EnvelopeRespond {
    pub token: StructId,
    pub answer: StructId,
}
/// Build a canonical `Envelope.Respond` value.
pub fn envelope_respond(b: &mut Builder, fields: EnvelopeRespond) -> StructId {
    let rec = v::record(b, vec![("token", fields.token), ("answer", fields.answer)]);
    v::qctor(b, "Envelope", "Respond", vec![rec])
}
/// Read a `Envelope.Respond` value's fields by name, or `None`.
pub fn as_envelope_respond(arenas: &Arenas, id: StructId) -> Option<EnvelopeRespond> {
    let t = v::as_qctor(arenas, id, "Envelope", "Respond")?;
    let [rec] = <[StructId; 1]>::try_from(t).ok()?;
    Some(EnvelopeRespond {
        token: v::record_field(arenas, rec, "token")?,
        answer: v::record_field(arenas, rec, "answer")?,
    })
}
/// Build a canonical `Outcome.Accepted` value.
pub fn outcome_accepted(b: &mut Builder) -> StructId {
    v::qctor(b, "Outcome", "Accepted", vec![])
}
/// Whether `id` is a `Outcome.Accepted` value.
pub fn is_outcome_accepted(arenas: &Arenas, id: StructId) -> bool {
    v::as_qctor(arenas, id, "Outcome", "Accepted").is_some_and(|t| t.is_empty())
}
/// Build a canonical `Outcome.Failed` value.
pub fn outcome_failed(b: &mut Builder, x: StructId) -> StructId {
    v::qctor(b, "Outcome", "Failed", vec![x])
}
/// Read the payload of a `Outcome.Failed` value, or `None`.
pub fn as_outcome_failed(arenas: &Arenas, id: StructId) -> Option<StructId> {
    let t = v::as_qctor(arenas, id, "Outcome", "Failed")?;
    let [x] = <[StructId; 1]>::try_from(t).ok()?;
    Some(x)
}
