//! @generated by `cargo xtask codegen` from cdz-platform/contracts/run.cdz — DO NOT hand-edit.
//!
//! The `run` contract's schema as Cadenza-AST builder calls: `schema(b)` reconstructs the
//! contract's named type declarations, which the platform hands to `Contract::new`. The source is
//! real Cadenza that `cargo xtask codegen` validates + runs the conformance tests of (via the
//! `cdz` binary) before generating this file, so the schema is provably valid Cadenza and a
//! marshalled value type-ascribes against it. Edit the schema in `run.cdz`, then regenerate
//! with `cargo xtask codegen`; `cargo xtask codegen --check` (a hard gate in `xtask check`) fails
//! if this file is stale. Plain builder calls — no dependency on the compiler, so it ships in
//! `cdz-platform`.

#![allow(dead_code)]
use crate::contract_value as v;
use cadenza_ast::ast::{Arenas, Builder, StructId};
/// The `run` contract's schema: its named Cadenza type declarations, in source order, ready
/// to hand to `Contract::new`. Generated from the contract's Cadenza source, which `cdz`
/// typechecks and runs the conformance tests of at codegen time, so this is provably a
/// valid Cadenza schema.
pub fn schema(b: &mut Builder) -> Vec<StructId> {
    let v0 = b.name("type");
    let v1 = b.name("Request");
    let v2 = b.name("Run");
    let v3 = b.name("Record");
    let v4 = b.name(":");
    let v5 = b.name("program");
    let v6 = b.name("Bytes");
    let v7 = b.list(vec![v4, v5, v6]);
    let v8 = b.name(":");
    let v9 = b.name("contract");
    let v10 = b.name("Bytes");
    let v11 = b.list(vec![v8, v9, v10]);
    let v12 = b.name(":");
    let v13 = b.name("input");
    let v14 = b.name("Bytes");
    let v15 = b.list(vec![v12, v13, v14]);
    let v16 = b.list(vec![v3, v7, v11, v15]);
    let v17 = b.list(vec![v2, v16]);
    let v18 = b.list(vec![v0, v1, v17]);
    let v19 = b.name("type");
    let v20 = b.name("Output");
    let v21 = b.name("Output");
    let v22 = b.name("Bytes");
    let v23 = b.list(vec![v21, v22]);
    let v24 = b.list(vec![v19, v20, v23]);
    vec![v18, v24]
}
/// The contract this module declares — built from its `@!contract` / `@!input` /
/// `@!output` pragmas and its schema. The one place the contract's name and input/output
/// type references live is the `.cdz` source; `*_contract()` calls this.
pub fn contract() -> crate::Contract {
    crate::Contract::new(
        crate::Str::from_static("cdz-platform.run"),
        schema,
        "Request",
        "Output",
    )
}
/// The fields of a `Request.Run` value — each a built value occurrence.
pub struct RequestRun {
    pub program: StructId,
    pub contract: StructId,
    pub input: StructId,
}
/// Build a canonical `Request.Run` value.
pub fn request_run(b: &mut Builder, fields: RequestRun) -> StructId {
    let rec = v::record(
        b,
        vec![
            ("program", fields.program),
            ("contract", fields.contract),
            ("input", fields.input),
        ],
    );
    v::qctor(b, "Request", "Run", vec![rec])
}
/// Read a `Request.Run` value's fields by name, or `None`.
pub fn as_request_run(arenas: &Arenas, id: StructId) -> Option<RequestRun> {
    let t = v::as_qctor(arenas, id, "Request", "Run")?;
    let [rec] = <[StructId; 1]>::try_from(t).ok()?;
    Some(RequestRun {
        program: v::record_field(arenas, rec, "program")?,
        contract: v::record_field(arenas, rec, "contract")?,
        input: v::record_field(arenas, rec, "input")?,
    })
}
/// Build a canonical `Output.Output` value.
pub fn output_output(b: &mut Builder, x: StructId) -> StructId {
    v::qctor(b, "Output", "Output", vec![x])
}
/// Read the payload of a `Output.Output` value, or `None`.
pub fn as_output_output(arenas: &Arenas, id: StructId) -> Option<StructId> {
    let t = v::as_qctor(arenas, id, "Output", "Output")?;
    let [x] = <[StructId; 1]>::try_from(t).ok()?;
    Some(x)
}
