//! @generated by `cargo xtask codegen` from cdz-platform/contracts/spawned.cdz — DO NOT hand-edit.
//!
//! The `spawned` contract's schema as Cadenza-AST builder calls: `schema(b)` reconstructs the
//! contract's named type declarations, which the platform hands to `Contract::new`. The source is
//! real Cadenza that `cargo xtask codegen` validates + runs the conformance tests of (via the
//! `cdz` binary) before generating this file, so the schema is provably valid Cadenza and a
//! marshalled value type-ascribes against it. Edit the schema in `spawned.cdz`, then regenerate
//! with `cargo xtask codegen`; `cargo xtask codegen --check` (a hard gate in `xtask check`) fails
//! if this file is stale. Plain builder calls — no dependency on the compiler, so it ships in
//! `cdz-platform`.

#![allow(dead_code)]
#[allow(unused_imports)]
use crate::contract_value as v;
use cadenza_ast::ast::{Arenas, Builder, StructId};
/// The `spawned` contract's schema: its named Cadenza type declarations, in source order, ready
/// to hand to `Contract::new`. Generated from the contract's Cadenza source, which `cdz`
/// typechecks and runs the conformance tests of at codegen time, so this is provably a
/// valid Cadenza schema.
pub fn schema(b: &mut Builder) -> Vec<StructId> {
    let v0 = b.name("type");
    let v1 = b.name("Event");
    let v2 = b.name("Spawned");
    let v3 = b.name("Record");
    let v4 = b.name(":");
    let v5 = b.name("id");
    let v6 = b.name("Bytes");
    let v7 = b.list(vec![v4, v5, v6]);
    let v8 = b.name(":");
    let v9 = b.name("parent");
    let v10 = b.name("Bytes");
    let v11 = b.list(vec![v8, v9, v10]);
    let v12 = b.list(vec![v3, v7, v11]);
    let v13 = b.list(vec![v2, v12]);
    let v14 = b.list(vec![v0, v1, v13]);
    let v15 = b.name("type");
    let v16 = b.name("Ack");
    let v17 = b.name("Ack");
    let v18 = b.list(vec![v15, v16, v17]);
    vec![v14, v18]
}
/// The contract this module declares — built from its `@!contract` / `@!input` /
/// `@!output` pragmas and its schema. The one place the contract's name and input/output
/// type references live is the `.cdz` source; `*_contract()` calls this.
pub fn contract() -> crate::Contract {
    crate::Contract::new(
        crate::Str::from_static("cdz-platform.spawned"),
        schema,
        "Event",
        "Ack",
    )
}
/// The fields of a `Event.Spawned` value — each a built value occurrence.
pub struct EventSpawned {
    pub id: StructId,
    pub parent: StructId,
}
/// Build a canonical `Event.Spawned` value.
pub fn event_spawned(b: &mut Builder, fields: EventSpawned) -> StructId {
    v::record(b, vec![("id", fields.id), ("parent", fields.parent)])
}
/// Read a `Event.Spawned` value's fields by name, or `None`.
pub fn as_event_spawned(arenas: &Arenas, id: StructId) -> Option<EventSpawned> {
    let rec = id;
    Some(EventSpawned {
        id: v::record_field(arenas, rec, "id")?,
        parent: v::record_field(arenas, rec, "parent")?,
    })
}
/// Build a canonical `Ack.Ack` value.
pub fn ack_ack(b: &mut Builder) -> StructId {
    v::qctor(b, "Ack", "Ack", vec![])
}
/// Whether `id` is a `Ack.Ack` value.
pub fn is_ack_ack(arenas: &Arenas, id: StructId) -> bool {
    v::as_qctor(arenas, id, "Ack", "Ack").is_some_and(|t| t.is_empty())
}
