//! The compile-boundary contract types — the vocabulary the build tool speaks across the compiler
//! seam, shared by the compiler that produces them (`rcdzc`) and the thin front-door that delegates to
//! it (`cdz`). See the crate manifest for the extraction rationale (the compile-boundary analogue of
//! `cadenza-ast`'s AST-wire crate).
//!
//! So far the crate holds the pure-data boundary enums — the requested [`Target`], the [`OptLevel`],
//! and the sidecar [`Request`]/[`Query`] request vocabulary — plus the [`sidecar::encode`]/[`decode`]
//! codec that serializes a request list to/from the canonical binary AST (the one `cadenza-ast` dep),
//! and the source [`spans`] side-table (`SpanData`/`LineStarts` + its codec, a debug compile's kinded
//! input). A later slice moves the kinded `Artifact` list + the `{artifacts, diagnostics}` result. The
//! compiler IMPLEMENTATIONS behind the boundary (query eval over a live `Db`, `compile`, the backends)
//! stay in `rcdzc`.

pub mod abi;
pub mod closure_hash_wire;
pub mod diagnostics_wire;
pub mod doc_wire;
pub mod effect_bind_wire;
pub mod export_types_wire;
pub mod exports_wire;
pub mod func_layout_wire;
mod graft;
pub mod highlight_wire;
pub mod instantiations_wire;
pub mod link_map;
pub mod name_wire;
pub mod opt;
pub mod overflow;
pub mod param_manifest_wire;
pub mod resolve_wire;
pub mod result_types_wire;
// @generated by `cargo xtask codegen` — the relocated home of the three runtime CONTENT-HASH consts
// (`REQUIRED_RUNTIME_HASH` / `DEBUG_RUNTIME_HASH` / `REQUIRED_NFC_HASH`), read by the thin `!standalone`
// `cdz` (doctor) without linking `rcdzc`; `rcdzc::backend::wasm::runtime_abi` re-exports them.
pub mod runtime_hash;
pub mod scope_wire;
pub mod sidecar;
pub mod spans;
pub mod symbols_wire;
pub mod target;
pub mod type_at_wire;
pub mod type_info_wire;
pub mod uses_wire;

pub use abi::{
    Artifact, CompileOutput, Diagnostic, DiagnosticFix, FixKind, KIND_COMPONENT_NAME, KIND_ENTRY,
    Severity, WRAP_HOLE, component_name_artifact, entry_artifact, wrap_prefix_suffix,
};
pub use closure_hash_wire::{decode_closure_hash, encode_closure_hash};
pub use diagnostics_wire::{decode_diagnostics, encode_diagnostics};
pub use doc_wire::{DocAnswer, decode_doc, encode_doc};
pub use export_types_wire::{
    decode_export_types, decode_export_types_checked, encode_export_types,
};
pub use exports_wire::{ExportEntry, decode_exports, encode_exports};
pub use highlight_wire::{decode_highlight, encode_highlight};
pub use link_map::{FileSpan, KIND_LINK_MAP, decode_link_map, encode_link_map};
pub use name_wire::{decode_name, encode_name};
pub use opt::OptLevel;
pub use overflow::{OverflowMode, OverflowSpec};
pub use resolve_wire::{decode_resolve, encode_resolve};
pub use result_types_wire::{
    decode_result_types, decode_result_types_checked, encode_result_types,
};
pub use scope_wire::{ScopeBinding, decode_scope, encode_scope};
pub use sidecar::{Query, Request, decode, encode};
pub use symbols_wire::{decode_symbols, encode_symbols};
pub use target::Target;
pub use type_at_wire::{TypeAt, decode_type_at, encode_type_at};
pub use type_info_wire::{TypeInfo, decode_type_info, encode_type_info};
pub use uses_wire::{decode_uses, encode_uses};
