//! @generated by `cargo xtask codegen` from the built runtime/nfc component bytes — DO NOT hand-edit.
//!
//! The three runtime CONTENT-HASH consts (`REQUIRED_RUNTIME_HASH` / `DEBUG_RUNTIME_HASH` /
//! `REQUIRED_NFC_HASH`), regenerated from the built component bytes so they track a runtime/nfc-code
//! change automatically. They live HERE in `cadenza-compile-abi` (a boundary crate in both the `rcdzc`
//! and the thin `!standalone` `cdz` closures) so `cdz doctor` reads them WITHOUT linking `rcdzc`;
//! `rcdzc::backend::wasm::runtime_abi` `pub use`s them for byte-stability. Each is a compile-time
//! `CDZ_*_HASH` env override with the committed literal as the default (a nix build bakes the hash of
//! the component it built in the same closure). Regenerate with `cargo xtask codegen`; `--check` gates it.

/// The BLAKE3 content address of the value-heap runtime component this compiler was generated
/// against — the runtime a program built with this compiler requires. Regenerated from the
/// built runtime bytes, so it tracks a runtime-code change automatically. Overridable at
/// COMPILE TIME via the `CDZ_RUNTIME_HASH` env: a nix build bakes the hash of the runtime it
/// built in the SAME closure (so the compiler and its runtime stay self-consistent per host,
/// with no cross-host byte-reproducibility requirement); absent, the committed default is used.
pub const REQUIRED_RUNTIME_HASH: &str = match option_env!("CDZ_RUNTIME_HASH") {
    Some(h) => h,
    None => "05VEBnefTxbYiaPmrpRlIO1KExNaAxvmc0e5CO3GTWghF",
};
/// The BLAKE3 content address of the DEBUG-COUNTERS runtime build — the same runtime code
/// with the `live-objects` leak counter compiled in (`--features debug-counters`). A shipped
/// program pins `REQUIRED_RUNTIME_HASH` (the release build); a Perceus leak-check harness
/// composes THIS build to assert `live-objects == 0` after a run. Recorded here so the harness
/// locates the debug runtime by content address (from the store), never by rebuilding it.
/// Overridable at compile time via the `CDZ_DEBUG_RUNTIME_HASH` env (see `REQUIRED_RUNTIME_HASH`).
pub const DEBUG_RUNTIME_HASH: &str = match option_env!("CDZ_DEBUG_RUNTIME_HASH") {
    Some(h) => h,
    None => "05mGWQDAZ3zfXn0FrKvwKhSmXn7Z3EzZdX9u3jI6u0gPv",
};
/// The BLAKE3 content address of the NFC component (`cdz-nfc`) the RUNTIME imports. Regenerated
/// from the built NFC-component bytes like `REQUIRED_RUNTIME_HASH`, so it tracks an NFC-code
/// change automatically. The host resolves + composes the NFC component from the CAS by this hash
/// (the store records `nfc = "<hash>"`; cdz-run/main.rs verify the loaded bytes against it). The
/// NFC dep lives on the RUNTIME's world, so the NFC-code hash feeds `REQUIRED_RUNTIME_HASH`
/// (the runtime that imports NFC hashes differently); it is not a separate program-import hash.
/// Overridable at compile time via the `CDZ_NFC_HASH` env (see `REQUIRED_RUNTIME_HASH`).
pub const REQUIRED_NFC_HASH: &str = match option_env!("CDZ_NFC_HASH") {
    Some(h) => h,
    None => "05Zt7vNrKO3xBrZ9EhMG0dIl2XV53G218sS5kz7OoofIT",
};
